### ISSUE TITLE
Availability of HG002 partially phased assemblies

### ISSUE THREAD

**Issue by GuillaumeHolley** [chhylp123/hifiasm#109]
Hi,

I was wondering whether the two partially phased assemblies of HG002 as assembled by Hifiasm v0.15 (HG002.asm.bp.hap?.p_ctg.gfa) were available somewhere?

Thank you!

Guillaume

**Comment by chhylp123** [comment]
We have several HG002 datasets with different folds of coverage. Which one do you need?

**Comment by GuillaumeHolley** [comment]
Good question. Something like 30-40x and the best coverage you have?

**Comment by chhylp123** [comment]
Sure. Let me see how to share it.

**Comment by chhylp123** [comment]
It's here (generated by hifiasm r334 with 34x HiFi reads): 
>
https://drive.google.com/file/d/1MM09a2DVqd9Kr3934GfjX83Ubmk1h2pr/view?usp=sharing
https://drive.google.com/file/d/1Ae7Q82GfK_vfG6Qgz-WwRubI2KeOMdq-/view?usp=sharing

**Comment by GuillaumeHolley** [comment]
This will be super useful. Thanks for taking the time to upload the data, I appreciate it!
