### ISSUE TITLE
Can hifiasm take CLR and ccs.bam?

### ISSUE THREAD

**Issue by ardy20** [chhylp123/hifiasm#112]
Hi

Can hifiasm take CLR and ccs.bam (from HiFi)? And Is there any benefit using ccs.bam over subreads.fasta?

Regards

**Comment by chhylp123** [comment]
Unfortunately, it cannot take CLR for now.

**Comment by ctxchris** [comment]
Any experience with using error corrected CLR reads with hifiasm?

**Comment by lh3** [comment]
No, corrected CLR reads won't work.

**Comment by ardy20** [comment]
What about ccs.bam files? Can HoFiasm take ccs.bam file

**Comment by chhylp123** [comment]
No, you should covert ccs.bam to fastq first.

**Comment by ardy20** [comment]
Is PacBio's bam2fastq good?

**Comment by chhylp123** [comment]
Yean, it's OK.
