### ISSUE TITLE
Clarification: content of "--write-ec" fasta

### ISSUE THREAD

**Issue by ptrebert** [chhylp123/hifiasm#117]
Hi,

I am a bit puzzled about the contents of the error-corrected reads FASTA dumped via setting `--write-ec`. For hifiasm v0.15.1 and the test data set (chr11-2M.fa.gz), it looks like the ec FASTA contains all error-corrected reads twice (in the same orientation). What am I missing? I couldn't spot any info related to this in issues #12 and #53, sorry if I missed something there. Thanks for clarifying.

Best,
Peter

**Comment by chhylp123** [comment]
Sorry where can I find `chr11-2M.fa.gz`?

**Comment by ptrebert** [comment]
thanks for the quick reply - here's the link from the readme:
`https://github.com/chhylp123/hifiasm/releases/download/v0.7/chr11-2M.fa.gz`
