### ISSUE TITLE
get corrected reads in fasta format

### ISSUE THREAD

**Issue by HenrivdGeest** [chhylp123/hifiasm#12]
In earlier versions hifiasm stored the corrected reads in a fasta file, now it seems it stores them in a binary file. Is there any way to retrieve them back into a fasta format? For downstream analysis, its a very nice feuture to have these corrected reads.

**Comment by chhylp123** [comment]
Hi Henri,

You can have a try with "--write-ec" using the binary files.

Best,
Haoyu

**Comment by HenrivdGeest** [comment]
Hi thanks! Could you explain how to use exactly? 
I tried both "~/bin/hifiasm/hifiasm-0.7/hifiasm  -write-ec hifi.fasta "and  "~/bin/hifiasm/hifiasm-0.7/hifiasm  -write-ec hifi.bin", although I think the first one is correct, it gives me an error:
```
[M::ha_opt_update_cov] updated max_n_chain to 180
hifiasm: sketch.cpp:47: void ha_sketch(const char*, int, int, int, uint32_t, int, ha_mz1_v*, const void*): Assertion `len > 0 && len < 1<<27 && rid < 1<<28 && (w > 0 && w < 256) && (k > 0 && k <= 63)' failed.
Aborted (core dumped)

```

**Comment by chhylp123** [comment]
It should be run like this (just like rerun the hifiasm with bin files):

hifiasm -o hifiasm.asm --write-ec input.fq

The corrected will be extracted from the bin files. No need to rerun the whole hifiasm, so that it should be quite fast.

**Comment by sjin09** [comment]
Hello, is it possible to generate error-corrected reads without generating the contigs?

**Comment by chhylp123** [comment]
Just curious why do you don't like contigs?

**Comment by sjin09** [comment]
Hello @chhylp123, I am in the Darwin Tree of Life project at the Wellcome Sanger Institute. I am, however, not working in the assembly team and I just want to use the error-corrected reads for other purposes. I wish I could share the reasons, but github is a public domain! :(

**Comment by chhylp123** [comment]
I see. Actually the error correction step is the most time-consuming part in hifiasm (~90% in the whole workflow). So I guess generating the contigs shouldn't take too much time for Darwin Tree of Life project? But I can add an option to disable the assembly step in hifiasm if you want.

**Comment by sjin09** [comment]
That will be fantastic.

**Comment by sjin09** [comment]
I was also wondering whether fastq sequences can be returned with quality scores instead of fasta sequences in the future.

**Comment by chhylp123** [comment]
I have exposed '-e' to make users perform correction only. It's tricky to return fastq for corrected reads. Actually I have no idea what's the usage of HiFi read's quality... Could you please give me some examples about its practical usage?

**Comment by HenrivdGeest** [comment]
Export works like a charm. Thanks!

**Comment by chhylp123** [comment]
: )
