### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kushalsuryamohan** [chhylp123/hifiasm#120]
Hello,
I am trying to assemble a ~1.5 Gb genome using HiFi data (~25 Gb of CCS data from 2 SMRT cells) and am encountering a segmentation fault.
I am running hifiasm with the following script to submit to a SLURM SGE:

```#!/bin/sh
#SBATCH -n 50
#SBATCH -J hifiasm_ssvp 
#SBATCH -e hifiasm_ssvp.err
#SBATCH -o hifiasm_ssvp.out
#SBATCH --time=180:00:00

source ~/.bashrc

hifiasm -o SSVP_hifiasm -t 32 ./SSVP-Liver_HiFi-Cell1/m64022e_210429_212358.reads.fastq.gz SSVP_Liver_HiFI_3rd-Cell1/m64022e_210507_223631.reads.fastq.gz 
```

I'm also attaching the log file for this. Any help would be appreciated.

FYI, HiCanu was able to generate an assembly although I am not too impressed with the contig NG50 (780kb) so want to compare with hifiasm.

Thanks!

[hifiasm_ssvp.log](https://github.com/chhylp123/hifiasm/files/6475373/hifiasm_ssvp.log)

**Comment by chhylp123** [comment]
Well, is it possible that you can share the fastq files with us? From the log I cannot see what happened...

**Comment by kushalsuryamohan** [comment]
I'm sorry but the data cannot be shared at the moment. Is there another way to troubleshoot this? Could this be a memory-related issue?

**Comment by chhylp123** [comment]
Hifiasm takes more memory than HiCanu, so could you check if it is caused by RAM limitation of your cluster?

**Comment by kushalsuryamohan** [comment]
Got it thanks. Can I limit the memory for hifiasm? Is there a flag for this? Thanks!

**Comment by chhylp123** [comment]
Wait... why hifiasm took such huge memory for this sample... is it highly repetitive?

**Comment by kushalsuryamohan** [comment]
The genome is about 40-45% repetitive.

**Comment by chhylp123** [comment]
Probably you can use less CPUs like '-t8'...However I'm confused why it took such huge memory...

**Comment by chhylp123** [comment]
By the way, last time we have seen similar issues when users tried to assemble CLR reads by hifiasm. Since the N50 of HiCanu assembly is also not good, have you checked if your data has contaminations?

**Comment by kushalsuryamohan** [comment]
Thank you for the suggestion - how do I check for contamination? Is there a tool that can expedite this?

**Comment by kushalsuryamohan** [comment]
Update, it was a memory issue. Thanks for your prompt responses.
