### ISSUE TITLE
run hifiasm with --n-hap=1 generate two haplotype result

### ISSUE THREAD

**Issue by PengJia6** [chhylp123/hifiasm#128]
Hi, 

I want to use hifiasm (0.15.1-r334) to assemble a genome with very low heterozygosity rate. 

my script is : 

```
hifiasm -o prefix --n-hap 1 -t 40  input.ccs.fq.gz
```
and I got  output file:
```               
prefix.bp.hap1.p_ctg.gfa        
prefix.bp.hap1.p_ctg.lowQ.bed   
prefix.bp.hap1.p_ctg.noseq.gfa  
prefix.bp.hap2.p_ctg.gfa        
prefix.bp.hap2.p_ctg.lowQ.bed   
prefix.bp.hap2.p_ctg.noseq.gfa  
prefix.bp.p_ctg.gfa             
prefix.bp.p_ctg.lowQ.bed        
prefix.bp.p_ctg.noseq.gfa
prefix.bp.p_utg.gfa
prefix.bp.p_utg.lowQ.bed
prefix.bp.p_utg.noseq.gfa
prefix.bp.r_utg.gfa
prefix.bp.r_utg.lowQ.bed
prefix.bp.r_utg.noseq.gfa
prefix.ec.bin
prefix.ovlp.reverse.bin
prefix.ovlp.source.bin

```
I have two questions:

1. Can hifiasm assemble genome with low heterozygosity rate like [CHM13](https://sites.google.com/ucsc.edu/t2tworkinggroup/chm13-cell-line) in [T2T](https://sites.google.com/ucsc.edu/t2tworkinggroup) project？
2. I think the option -n-hap=1 will generate only one haplotype assembly, but I got two, is it correct? 

BTW, I get **0.15.1-r334** with 
```
hifiasm -v 
```
But there is no such verision tag in hifiasm [release page](https://github.com/chhylp123/hifiasm/releases/tag/0.15.2) 

Thx,
Peng Jia

**Comment by chhylp123** [comment]
You should use '-l0' for homozygous sample. And 0.15.1-r334 is 0.15.2-r334, sorry for the typo.

**Comment by PengJia6** [comment]
Thank you for your prompt reply! 

I should use the following script for homozygous sample , am I right? 

```
hifiasm -o prefix --n-hap 1 -l0 -t 40  input.ccs.fq.gz
```

**Comment by chhylp123** [comment]
Probably just: 
```
hifiasm -o prefix -l0 -t 40  input.ccs.fq.gz
```

**Comment by PengJia6** [comment]
Thanks for your clarification！
