### ISSUE TITLE
cannot find output files

### ISSUE THREAD

**Issue by dagi34** [chhylp123/hifiasm#13]
Hi
I am running HIfiasm on a dataset of _D.melanogaster_ HiFi reads that was downloaded from NCBI.
I am using the command line;
time hifiasm -o <path of output file>  -t 36  <path of input file>
It has the intention of creating a folder in home directory and placing the generated files in it. However, after hrs of working I get 
'writing reads to disk ....
Segmentation fault (core dumped)'

There is no new folder created and I cannot find the specified output files.
What am I doing wrong? I am rather new to assembling these genomes

**Comment by HenrivdGeest** [comment]
Hi, 

I think this is because you did not enter any output file. If you forget -o as a whole, you get the same segmen. Error. I think you should give it a try with a valid -o argument ( its a prequel, so  myassembly would give a few files starting with this text)

**Comment by dagi34** [comment]
Dear HenrivdGeest
Thanks a lot for your comment. The message got presented wrongly. In the command line after -o I did type in the path of ~/foldername/filename. I expected it to create a folder with the files in the home directory. But I cannot find the files or folder there.

**Comment by chhylp123** [comment]
Thanks Henri.

Hi dagi34, could you please share the exact commands you have used? Thank you so much.

**Comment by dagi34** [comment]
Thank you for offering to help. This is the exact command:
time ./hifiasm -o ~/HiFiasm/DmelhifiasmPacbio.asm -t 36 ~/Flye-2.3.3/DmelPacBio/SRR10188371.fastq
The actual folder HiFiasm does not exist in the home directory, but I expect it to create and the files should have the prefix DmelhifiasmPacbio.

**Comment by lh3** [comment]
> I expect it to create and the files should have the prefix DmelhifiasmPacbio.

Most tools don't create new directories for you.

That said, hifiasm should report an error in this case, instead of segfault.

**Comment by chhylp123** [comment]
I agree with Heng. I guess you should check if ~/HiFiasm/DmelhifiasmPacbio.asm is available. '-o' specifies the prefix of output files, instead of directory.
