### ISSUE TITLE
Don't we need Hi-C any more for haplotype-resolved assemblies?

### ISSUE THREAD

**Issue by ke-shi** [chhylp123/hifiasm#135]
Nice to know v0.15 can produce hap1 and hap2 contigs in addition to primary without Hi-C data. 
As mentioned, I am worrying about "haplotype switch" errors. I assume Hi-C data is still required to gain high accurate haplotype-resolved assemblies. Or not any more?

**Comment by lh3** [comment]
For many species, it is impossible to do phasing without Hi-C.
