### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MartinPippel** [chhylp123/hifiasm#136]
Hi, 

I have used hifiasm 0.15.3-r339 to assemble a large genome but it crashed with a segfault. We tested it on different machines but the result was the same. Here is the log file: 
[slurm-17204452.txt](https://github.com/chhylp123/hifiasm/files/6661203/slurm-17204452.txt)

When we did a test assembly with 12x CCS (i.e. 6X haploid) read coverage with hifiasm v0.14.2. the assembly finished without any errors and the assembly stats were surprisingly good. 

Any further guidance would be much appreciated.

Best,
Martin

**Comment by chhylp123** [comment]
Looks like the bin files have already been generated. V0.14.2 and v0.15.3 share the same bin files so could you please run v0.14.2 on the new bin files? I just want make sure if it is the specific issue of v0.14.2. I personally guess another possibility is no enough memory.

**Comment by MartinPippel** [comment]
thx for your fast reply. I ran v0.14.2 as well and it crashed at the same point. For the assembly I reserved 5Tb RAM and according to slurm the peak Mem was "only" 1.4Tb. I just submitted it again with 40Tb on the bigmem machine. Is there any option to run hifiasm in debug mode to provide you with some more details?

**Comment by chhylp123** [comment]
I see. Probably it is a hifiasm issue. It is hard to figure out what happened. May I ask what's the size of bin files?

**Comment by MartinPippel** [comment]
418G   ec.bin
190G   ovlp.source.bin
55G     ovlp.reverse.bin

**Comment by chhylp123** [comment]
Thanks a lot. I wonder if you can share the bin files with us, so that we can figure out what happened. I'm also pretty curious if it is a bug of hifiasm.

**Comment by MartinPippel** [comment]
Its confidential data so I have to ask the owner first. I will keep you in the loop.

**Comment by chhylp123** [comment]
Thanks a lot. Could you please send the bin file to hcheng@jimmy.harvard.edu ?

**Comment by chhylp123** [comment]
Solved by version 0.15.4-r347.
