### ISSUE TITLE
Error in genome consensus

### ISSUE THREAD

**Issue by tbrown91** [chhylp123/hifiasm#140]
Hello,

We have a collaborator who is working on gene annotation and loss and found a number of genes which were falsely annotated as lost or mutated as the output of hifiasm. Mapping the ccs reads back to the assembly, we see that these are often single bp insertions in homopolymer runs, which are only supported by a small number of reads. I ran hifiasm is hic mode, so have both haplotypes and was version  0.15.1-r331. 

I have attached two examples with single errors which are present in both haplotypes, and a third location where there are a number of insertions in one haplotype and not the other. 

Is there way to improve the consensus calling using hifiasm's built-in arguments?

First location hap1:
![image](https://user-images.githubusercontent.com/11500978/122759427-358a8880-d29a-11eb-9b8d-3ad061220383.png)
hap2:
![image](https://user-images.githubusercontent.com/11500978/122759537-56eb7480-d29a-11eb-86d4-ea644c6b028a.png)

Second location hap1:
![image](https://user-images.githubusercontent.com/11500978/122759852-b6e21b00-d29a-11eb-9d90-3149b4a70648.png)
hap2:
![image](https://user-images.githubusercontent.com/11500978/122759896-c6f9fa80-d29a-11eb-9546-efc6cd906c0b.png)

Finally an example of where there are a number of single bp insertions in the reference, this time only present in hap1. Hap2 looks to have the correct consensus sequence.
hap1:
![image](https://user-images.githubusercontent.com/11500978/122760177-1dffcf80-d29b-11eb-9899-d6c35c84b084.png)
hap2:
![image](https://user-images.githubusercontent.com/11500978/122760209-29eb9180-d29b-11eb-8364-f3eb1c6fd17b.png)

Any advice would be much appreciated.

Many thanks,

Tom

**Comment by chhylp123** [comment]
Just make sure: do you mean here is a consensus error, and the assembly has base 'G'?
![image](https://user-images.githubusercontent.com/11708053/122768069-3ce96c00-d271-11eb-92d5-9056d19506c0.png)

**Comment by tbrown91** [comment]
Yes, so in the assembly there is an extra G inserted in this position, which is only supported by a few reads

**Comment by chhylp123** [comment]
Just curious: why non-G is right and G is wrong?

**Comment by tbrown91** [comment]
If we are to believe pacbio, then the remaining sequencing errors are mostly those in homopolymer stretches. In this case we have 28 reads with 7 G's and 5 reads with 8 G's, which is why we believe the assembly should have 7. On a biological level, this created a gene mutation, which was not present in an illumina assembly.

**Comment by chhylp123** [comment]
I see, thanks a lot. It looks like a somatic mutation? Hifiasm is haplotype-aware and this mutation is supported by enough reads. In this case hifiasm thinks 7 G's is one haplotype and 8 G's is another. So I guess it is not a consensus error. Could please show the corresponding subgraph of these reads in p_utg or r_utg?

**Comment by tbrown91** [comment]
I guess it looks pretty clean in the graphs

p_utg:
![image](https://user-images.githubusercontent.com/11500978/122775292-44793700-d2aa-11eb-95bf-baf4d847b2ea.png)

r_utg:
![image](https://user-images.githubusercontent.com/11500978/122775538-8609e200-d2aa-11eb-9591-5c1f5416254f.png)

**Comment by lh3** [comment]
These look like consensus errors but that is the best the current version of hifiasm can do. We will try to improve but it will take time. For now, you may consider to use Illumina to only fix long homopolyers in easy regions in theory. In practice, this can be very tricky.

**Comment by tbrown91** [comment]
Thank you for the update. We will go forward with polishing to try and remove these errors. We will report back if these errors go away in future releases. Thank you for the tool and hard work!
