### ISSUE TITLE
haplotype-resolved assemblies by Hic

### ISSUE THREAD

**Issue by yilunhuangyue** [chhylp123/hifiasm#144]
Hi, thank you for developimg this toos. I am very glad to see the Hic mode was added. I want to performed haplotype-resoved assembly and I noticed another software DipAsm. I wonder which one id better for genome phasing by Hic. Thanks very much for you reply.

**Comment by lh3** [comment]
Hifiasm is preferred.

**Comment by yilunhuangyue** [comment]
Thanks for your reply!
