### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by charlesdavid** [chhylp123/hifiasm#145]
Hello, where is the user manual for the program? Also, where in the outputs are the standard assembly statistics? Thanks.

**Comment by chhylp123** [comment]
Please see `man ./hifiasm.1`. In addition, the `-h` option of hifiasm provides brief description of options. `man ./hifiasm.1` also provides description of different type of outputs.

**Comment by charlesdavid** [comment]
Thanks for your reply. I had already looked at those.
My question why doesn't this program output any standard assembly statistics?
Were is the N50? The largest contig? The N90? The mean coverage??? Etc... These are conspicuous by their absence.

**Comment by lh3** [comment]
Users will anyway run their favorite tools or scripts to compute assembly size, N50 etc. I don't see an assembler needs to output those. That said, we are thinking to add more information for debugging purposes.
