### ISSUE TITLE
ERROR6 in log file

### ISSUE THREAD

**Issue by charlesfeigin** [chhylp123/hifiasm#153]
Hi, I am trying to assemble a ~3Gb mammalian genomewith ~20x coverage of hifi data. In my initial run, I used default settings. The run finishes (though unfortunately with fairly poor results, N50 of ~1.5Mb). However, I noticed near the end of the log file two instances of "ERROR6". I can't find this in previous issues or in forums. Do you have a sense of what this might mean? Thank you!

Here is the end of the log file:

Writing reads to disk...
Reads has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
bin files have been written.
[M::purge_dups] purge duplication coverage threshold: 22
ERROR6
Writing raw unitig GFA to disk...
Writing processed unitig GFA to disk...
ERROR6
[M::purge_dups] purge duplication coverage threshold: 22
[M::mc_solve_core::1.084] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [14, infinity]
Writing eq_hifiasm_defs_test1.bp.p_ctg.gfa to disk...
Writing eq_hifiasm_defs_test1.bp.hap1.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [14, infinity]
Writing eq_hifiasm_defs_test1.bp.hap2.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [14, infinity]
Inconsistency threshold for low-quality regions in BED files: 70%
[M::main] Version: 0.15.4-r347
[M::main] CMD: /home/cfeigin/src/hifiasm/hifiasm -t 72 -o eq_hifiasm_defs_test1 XDOVE_20210528_S64018_PL100178519-1_A01.ccs.fastq XDOVE_20210528_S64018_PL100178519-1_B01.ccs.fastq XDOVE_20210528_S64018_PL100178519-1_C01.ccs.fastq
[M::main] Real time: 15396.332 sec; CPU: 502032.734 sec; Peak RSS: 64.581 GB

**Comment by chhylp123** [comment]
It's a warning so please just ignore it

**Comment by charlesfeigin** [comment]
Thanks!
