### ISSUE TITLE
hifiasm HiC partition for tetraploid 

### ISSUE THREAD

**Issue by XuanlinWu** [chhylp123/hifiasm#161]
With the latest version of hifiasm, is it possible for hifiasm to run HiC partition on tetraploid like this:

hifiasm -o tetraploid.asm -t16 --n-weight 5 --h1 read1_1.fq.gz, read1_2.fq.gz --h2 read2_1.fq.gz, read 2_2.fq.gz total.ccs.fastq.gz

Or hifiasm HiC partition works only for diploid for now?

**Comment by chhylp123** [comment]
No, for now hifiasm only support diploid Hi-C phasing. We do 't have polyploid samples for testing.

**Comment by XuanlinWu** [comment]
Thanks for answering.

**Comment by jinxin112233** [comment]
> No, for now hifiasm only supports diploid Hi-C phasing. We don't have polyploid samples for testing.

Could you tell us what is the main difficulty of phasing polyploids at present？

**Comment by chhylp123** [comment]
Well, we do not have time to dig into polyploid genomes right now...
