### ISSUE TITLE
Is there redundancy among assembly contig ?

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#163]
i got primary contig fa files,Is there redundancy among assembly contig ? or is there   containment relationship between some contings ？

**Comment by zhoudreames** [comment]
@chhylp123 could you help  me ? thanks~

**Comment by chhylp123** [comment]
There might be a few overlaps between contigs but these overlaps should be very short. So you can ignore them.

**Comment by zhoudreames** [comment]
> There might be a few overlaps between contigs but these overlaps should be very short. So you can ignore them.

Can I understand that all contings are approximately unique and do not need to make ir de redundant ？

**Comment by chhylp123** [comment]
Yes, I think so.

**Comment by zhoudreames** [comment]
thanks~
