### ISSUE TITLE
How to combine both HiC reads and mother-son reads information to phase assembly?

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#164]
Hi, we got illumina short reads, HIFI reads and HiC reads for both mother and son, How to simultaneously take advantage bothe Hic data and one parent specific kmer to phase assembly the genome?

**Comment by zhoudreames** [comment]
@chhylp123 I am so sorry again disturb you ，i have one problem i want to ask，thank for  your help~

**Comment by chhylp123** [comment]
Do you mean you have short reads, Hi-C and HiFi for mother, father and child?

**Comment by zhoudreames** [comment]
> Do you mean you have short reads, Hi-C and HiFi for mother, father and child?

i only have short reads, Hi-C and HiFi for mother and child,but lack of the father data.

**Comment by zhoudreames** [comment]
> Do you mean you have short reads, Hi-C and HiFi for mother, father and child?

i only have short reads, Hi-C and HiFi for mother and child,but lack of the father data.

**Comment by zhoudreames** [comment]
@chhylp123 Hi

**Comment by chhylp123** [comment]
Right now hifiasm requires both father and mother for trio-binning, so probably you can only only do Hi-C phased assembly. However, if you can bin HiFi reads by your self, the binning results can be feed to hifiasm using the option `-3` and `-4`.

**Comment by zhoudreames** [comment]
i gain the bin hifi reads by using mother and son data,but I want to add HIC information to hifiasm for assembly at the same time. Can I use the following code to achieve it ，or do you have any other way to recommend me to complete it？thanks~
hifiasm -o asm   -3 mohap.readnames  -4 Fahap.readnames   --h1 read1.fq.gz --h2 read2.fq.gz HG002-HiFi.fq.gz

**Comment by chhylp123** [comment]
No, it won't work. Actually it is easy to integrate Hi-C and trio but we haven't done that. If the bin results are reliable, `-3/-4` should be better than Hi-C phased assembly.
