### ISSUE TITLE
Can WES data be used in trio binning mode of hifiasm?

### ISSUE THREAD

**Issue by Jesson-mark** [chhylp123/hifiasm#167]
Hi, I have a question about the data used in trio binning mode of hifiasm. 
The trio binning mode of hifiasm requires parental short reads, which is WGS data. 
But does that mode works with parental WES data? If so, is there any difference of haplotype-resolved assemblies generated by using WGS and WES data?
Thanks.

**Comment by chhylp123** [comment]
I guess WES cannot cover whole genome, so the uncovered regions cannot be phased correctly. You can run it but I have no idea about the results.

**Comment by Jesson-mark** [comment]
I know that. Thank you.

**Comment by chhylp123** [comment]
Maybe hifiasm itself can directly phase those regions if the genes are not too long.

**Comment by Jesson-mark** [comment]
Ok. Thanks a lot.
