### ISSUE TITLE
Only have some of the final result

### ISSUE THREAD

**Issue by ld9866** [chhylp123/hifiasm#168]
Hello! Now l have 100G HIFI and 300G HIC, and l am trying to use this command "hifiasm -o  bamei -t32 --h1 read1.fq.gz --h2 read2.fq.gz HiFi-reads.fq.gz 2>bamei.log".

However, the log file showed that:
[M::ha_hist_line]  rest: ********************* 559871
[M::ha_analyze_count] left: count[20] = 1703842
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 42; peak_het: 20
[M::ha_pt_gen::54046.182*43.31] ==> indexed 2807518370 positions
[M::ha_assemble::55647.550*43.44@159.190GB] ==> found overlaps for the final round
[M::ha_print_ovlp_stat] # overlaps: 461002264
[M::ha_print_ovlp_stat] # strong overlaps: 168296383
[M::ha_print_ovlp_stat] # weak overlaps: 292705881
[M::ha_print_ovlp_stat] # exact overlaps: 449747493
[M::ha_print_ovlp_stat] # inexact overlaps: 11254771
[M::ha_print_ovlp_stat] # overlaps without large indels: 460468813
[M::ha_print_ovlp_stat] # reverse overlaps: 173895460
Writing reads to disk...
Reads has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
bin files have been written.
[M::purge_dups] homozygous read coverage threshold: 41
[M::purge_dups] purge duplication coverage threshold: 52
Writing raw unitig GFA to disk...
Writing processed unitig GFA to disk...
[M::purge_dups] homozygous read coverage threshold: 41
[M::purge_dups] purge duplication coverage threshold: 52
[M::mc_solve_core::0.220] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [34, infinity]
Writing bamei.hic.p_ctg.gfa to disk...

The result only have these some of the final result:
bamei.ec.bin
bamei.hic.p_ctg.gfa
bamei.hic.p_ctg.lowQ.bed
bamei.hic.p_ctg.noseq.gfa
bamei.hic.p_utg.gfa
bamei.hic.p_utg.lowQ.bed
bamei.hic.p_utg.noseq.gfa
bamei.hic.r_utg.gfa
bamei.hic.r_utg.lowQ.bed
bamei.hic.r_utg.noseq.gfa
bamei.log
bamei.ovlp.reverse.bin
bamei.ovlp.source.bin

l want to ask how to solv this problem? My computer has 64cores and 256G memory.
Thank you!

**Comment by ld9866** [comment]
I am very glad to receive your reply. 
The assembled genome is somewhat larger, which is about 2.5G, but now the size is 2.7g.
In addition, the haplotype genome did not appear in our result files. What is described above is all our result files.

**Comment by chhylp123** [comment]
Sorry I was wrong... It seems hifiasm has not completed Hi-C part. Could you please rerun it again? As bin files have been generated, rerunning hifiasm should be pretty fast. But it should be better to why the log file was truncated.

**Comment by ld9866** [comment]
well! I will try again to see if there will be new results. As you said, I used the screen command to run this task, and the result of the command line is the same as this, which is really confusing.

**Comment by ld9866** [comment]
Hello! l have listened to your advice and rerun it again. The final part log file showed that, is that OK?
and now l have all the files we need! But l do not sure whether the results are right?
Thank you!

 26G bamei.ec.bin
2.1G bamei.hic.hap1.p_ctg.gfa
1.8M bamei.hic.hap1.p_ctg.lowQ.bed
 31M bamei.hic.hap1.p_ctg.noseq.gfa
2.3G bamei.hic.hap2.p_ctg.gfa
1.9M bamei.hic.hap2.p_ctg.lowQ.bed
 35M bamei.hic.hap2.p_ctg.noseq.gfa
 13G bamei.hic.lk.bin
2.6G bamei.hic.p_ctg.gfa
2.0M bamei.hic.p_ctg.lowQ.bed
 39M bamei.hic.p_ctg.noseq.gfa
4.1G bamei.hic.p_utg.gfa
4.5M bamei.hic.p_utg.lowQ.bed
 58M bamei.hic.p_utg.noseq.gfa
4.1G bamei.hic.r_utg.gfa
4.5M bamei.hic.r_utg.lowQ.bed
 59M bamei.hic.r_utg.noseq.gfa
 78G bamei.hic.tlb.bin
 34K bamei.log
6.9G bamei.ovlp.reverse.bin
 19G bamei.ovlp.source.bin


[M::mc_solve_core::0.215] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [34, infinity]
Writing bamei.hic.p_ctg.gfa to disk...
[M::build_unitig_index::223.144] ==> Counting
[M::build_unitig_index::91.192] ==> Memory allocating
[M::build_unitig_index::281.207] ==> Filling pos
[M::build_unitig_index::5.545] ==> Sorting pos
[M::build_unitig_index::601.121] ==> HiC index has been built
[M::write_hc_pt_index] Index has been written.
[M::alignment_worker_pipeline::8207.739] ==> Qualification
[M::dedup_hits::55.375] ==> Dedup
[M::adjust_weight_kv_u_trans_advance::163.045]
[M::mb_solve_core::275.460] ==> Partition
[M::mc_solve_core::235.807] ==> Partition
[M::adjust_weight_kv_u_trans_advance::173.001]
[M::mb_solve_core::271.993] ==> Partition
[M::mc_solve_core::234.158] ==> Partition
[M::adjust_weight_kv_u_trans_advance::173.097]
[M::mb_solve_core::276.999] ==> Partition
[M::mc_solve_core::245.742] ==> Partition
[M::stat] # heterozygous bases: 3115571011; # homozygous bases: 1121412498
[M::reduce_hamming_error::3.390] # inserted edges: 20516, # fixed bubbles: 292
[M::adjust_utg_by_trio] primary contig coverage range: [34, infinity]
Writing bamei.hic.hap1.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [34, infinity]
Writing bamei.hic.hap2.p_ctg.gfa to disk...
Inconsistency threshold for low-quality regions in BED files: 70%
[M::main] Version: 0.15.5-r350
[M::main] CMD: hifiasm -o bamei -t 10 --h1 Bamei_1.q30.clean.fq.gz --h2 Bamei_2.q30.clean.fq.gz bamei.fastq.gz
[M::main] Real time: 16761.755 sec; CPU: 98700.135 sec; Peak RSS: 158.144 GB

**Comment by ld9866** [comment]
The genome size is a little bigger than we estimated. We think 2.5G is more proper!

**Comment by chhylp123** [comment]
How do you estimate genome size?

**Comment by ld9866** [comment]
As we know, the genome size of pigs is about 2.5G, no more than 2.5G.

**Comment by chhylp123** [comment]
Could you show the sizes of two haplotypes generated by hifiasm?

**Comment by ld9866** [comment]
Hello! the sizes of the result are shown below:
2.1G hic.hap1.p_ctg.gfa
2.3G hic.hap2.p_ctg.gfa
2.6G hic.p_ctg.gfa
I have another question. Will the genome size become larger or smaller after the HIC data is mounted?

**Comment by chhylp123** [comment]
Could you show the genome size instead of file size?

**Comment by ld9866** [comment]
Is that true?
This is the PIg genome calculated by quast.
Duroc  pig Total length 2501912388
Our result:
hic.p_ctg.fa Total length 2687790201
hic.hap1.p_ctg.fa Total length 2158975521
hic.hap2.p_ctg.fa Total length 2431392695

**Comment by ld9866** [comment]
If this is not true. could you tell me how to show the genome size?
Thank you!

**Comment by chhylp123** [comment]
Thanks. I found the genome size of pig is around 2.7Gb (see: https://www.sanger.ac.uk/resources/downloads/othervertebrates/pig.html), so probably it is right? And the unbalanced size of hap1 and hap2 might be caused by sex chromosomes. Hifiasm will put both chrX and chrY into one haplotype.

**Comment by ld9866** [comment]
Thank you very much for your reply! Next, I try to mount the HIC data with juicer, and then see if the file size is roughly consistent with our current results.
I also want to ask an additional question, how can I get the size of the genome?

**Comment by ld9866** [comment]
This newest paper showed that the pig genome size is about 2.5G.
https://onlinelibrary.wiley.com/doi/abs/10.1111/1755-0998.13396

**Comment by chhylp123** [comment]
It is PacBio CLR assembly generated by FALCON. CLR assembly is usually smaller than the real genome as CLR assembly may collapse many repeats.

**Comment by chhylp123** [comment]
You can use k-mer to estimate genome size but the estimated genome size is often smaller. I guess 2.7Gb autosomes + chrX + chrY should be right.

**Comment by ld9866** [comment]
Thank you！l will do the next step.



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 12, 2021 11:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chhylp123/hifiasm] Only have some of the final result (#168)




 
You can use k-mer to estimate genome size but the estimated genome size is often smaller. I guess 2.7Gb autosomes + chrX + chrY should be right.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
