### ISSUE TITLE
Got different ContigN50 with different versions of hifiasm

### ISSUE THREAD

**Issue by PengJia6** [chhylp123/hifiasm#169]
Hi, 

I want to assemble a human genome with hifiasm by 50X HiFi reads.  I used 0.14, 0.14.2, 0.15.4 to do this work, but I got different contig N50 of these draft genomes (see following table). 

|  version   | contig N50 (M) |
|  ----  | ----  |
|0.14|47 |
|0.14.2 |48 |
|0.15.4| 31 |

I am confused which version should I use?  Are there any evaluation of different versions of hifiasm in terms of misassembly, compleness, and so on? Could you please offer some advice? 

Thanks!

**Comment by chhylp123** [comment]
Could you give the sizes of different assemblies?

**Comment by PengJia6** [comment]
Please see the following table! 

|  version   | contig N50 (M) |draft size(bp)|
|  ----  | ----  | ----- |
|0.14|47 | 3,045,933,325 |
|0.14.2 |48 | 3,037,576,472  |
|0.15.4| 31 | 3,091,691,032  |

**Comment by philge** [comment]
Hi,

I also find fewer number of contigs from hifiasm version 0.15 compared to version 0.13. What could be the reason?

Thanks

**Comment by chhylp123** [comment]
> Please see the following table!
> 
> version	contig N50 (M)	draft size(bp)
> 0.14	47	3,045,933,325
> 0.14.2	48	3,037,576,472
> 0.15.4	31	3,091,691,032

I personally think 0.15.4 is better as it is larger, meaning it keeps more segdups. The higher N50 of old version should be caused by misjoined segdups. You can also have a try with current github HEAD, which should produce assembly with similar N50 as v0.14 and comparable segdup resolution as v0.15.4.

**Comment by chhylp123** [comment]
> Please see the following table!
> 
> version	contig N50 (M)	draft size(bp)
> 0.14	47	3,045,933,325
> 0.14.2	48	3,037,576,472
> 0.15.4	31	3,091,691,032

You can use `paftools asmgene` in minimap2 to evaluate completeness for human genome.

**Comment by chhylp123** [comment]
> Hi,
> 
> I also find fewer number of contigs from hifiasm version 0.15 compared to version 0.13. What could be the reason?
> 
> Thanks

Fewer contigs are better, right?

**Comment by PengJia6** [comment]
> > Please see the following table!
> > version	contig N50 (M)	draft size(bp)
> > 0.14	47	3,045,933,325
> > 0.14.2	48	3,037,576,472
> > 0.15.4	31	3,091,691,032
> 
> I personally think 0.15.4 is better as it is larger, meaning it keeps more segdups. The higher N50 of old version should be caused by misjoined segdups. You can also have a try with current github HEAD, which should produce assembly with similar N50 as v0.14 and comparable segdup resolution as v0.15.4.

Thanks for your advice！
BTW, is there any recommended tool to detect mis-assembly ?

**Comment by chhylp123** [comment]
I have no idea... traditional tools like quast might be not useful for now. By the way, if you want to have a try with current github HEAD, you should rerun it from from scratch. The github HEAD has improved error correction part so that the bin files are different.

**Comment by PengJia6** [comment]
> I have no idea... traditional tools like quast might be not useful for now. By the way, if you want to have a try with current github HEAD, you should rerun it from from scratch. The github HEAD has improved error correction part so that the bin files are different.

Thanks a lot! I will try the lastet version of hifiasm.

**Comment by philge** [comment]
> > Hi,
> > I also find fewer number of contigs from hifiasm version 0.15 compared to version 0.13. What could be the reason?
> > Thanks
> 
> Fewer contigs are better, right?

Yes true. But I got 491 contigs using version 0.13 and 252 contigs using version 0.15. This large difference is worrying me. How can I confirm the 0.15 result is better. Genome size I got is 3,048,009,938 using version 0.13 and 2,962,231,703 using version 0.15.

**Comment by philge** [comment]
> > > Hi,
> > > I also find fewer number of contigs from hifiasm version 0.15 compared to version 0.13. What could be the reason?
> > > Thanks
> > 
> > 
> > Fewer contigs are better, right?
> 
> Yes true. But I got 491 contigs using version 0.13 and 252 contigs using version 0.15. This large difference is worrying me. How can I confirm the 0.15 result is better. Genome size I got is 3,048,009,938 using version 0.13 and 2,962,231,703 using version 0.15.

Hi, any thoughts regarding this observation. Thanks.

**Comment by chhylp123** [comment]
Do you have BUSCO scores for these two versions?

**Comment by philge** [comment]
> Do you have BUSCO scores for these two versions?

No, I need to calculate

**Comment by chhylp123** [comment]
I guess for your sample, the heterozygosity rate should be high. Since v0.14, hifiasm significantly improves the purge_dups so that the smaller assembly generated by v0.15 should be better. But it would be good to double check with BUSCO scores.
