### ISSUE TITLE
many fragment sequence in the p_ctg

### ISSUE THREAD

**Issue by libenping** [chhylp123/hifiasm#17]
Hi Haoyu/Heng Li,
     Thanks for the fantastic software for assembling HiFi reads!  Recently I am following hifiasm(0.8-r279)  for our plant genome assembly(~350M), and the p_ctg is as follows:
     Total_length 460M, Max_length 51M, N50_length 33M, Total_number 2646.
  The contiguity is higher than any other  assemblers  I have used , however I also notice that 2542 contigs length are less than 50kb, about 96% of total contigs number.
     I wonder why there are so many  fragment contigs and can I remove these contigs from  p_ctg?
Thank you.

**Comment by chhylp123** [comment]
Did you run hifiasm on a dataset with very high coverage? Sometimes high coverage may introduce weird things.

**Comment by kevfengler227** [comment]
many of the small contigs in plant genome assemblies represent variants of telomeric/knob repeats. I typically set the min contig length to 60kb. Even with that, after hybrid scaffolding with BioNano, almost all of the unscaffolded leftovers will be telomeric/knob repeats.

**Comment by libenping** [comment]
@chhylp123 @kevfengler227 Thank you for the reply! Yeah, the coverage is about 77X, and I will try to assemble with lower coverage (maybe 30-40x) ,Thank you .
