### ISSUE TITLE
what's the difference beween -l 2 and -l 3 

### ISSUE THREAD

**Issue by yywyaoyaowu** [chhylp123/hifiasm#171]
Hi 
Have you compare the ddifference between -l 2 and  -l 3?  based on the mannual, it says "Purge-dups:
    -l INT       purge level. 0: no purging; 1: light; 2/3: aggressive [0 for trio; 3 for unzip]"
What's the different between 2 and 3?  I'm not quite understand "3 for unzip".

Thanks very much!

**Comment by chhylp123** [comment]
`-l3` is always prefer. `-l1` and `-l2` were required since the purging step of hifiasm old versions cannot handle samples with different heterozygosity. Currently hifiasm is stable in purging so that you can directly use `-l3`. Probably we should remove `-l1` and `-l2` in the next release.

**Comment by chhylp123** [comment]
Either is OK. If you can make sure `-l0` assembly does not contain false duplications, probably it is better. `-l3` may collapse some segdups.
