### ISSUE TITLE
correspondence relationship between hap1 and hap2 contigs

### ISSUE THREAD

**Issue by cyr2017** [chhylp123/hifiasm#173]
Hi,

I have run hifiasm with HiFi reads and Hi-C reads. Hifiasm outputted both hap1 assembly and hap2 assembly, which works fantastic. 

I want to find out correspondence relationship between hap1 and hap2 contigs.  I'm doing whole genome sequence comparison between hap1 and hap2 assemblies and trying to get this info from syntenic alignments. However, it would much better and more efficient if I there is a way to extract this info from existing hifiasm outpout files.
 Is there a way to  do it ?a
Thanks

**Comment by chhylp123** [comment]
The internal contig alignment is not as accurate as minimap2 or unimap, so I till recommend you to use minimap2 or unimap. But hifiasm has an additional information for homologous reads. There should be some homologous reads shared in both haplotypes. So you can get those reads and then infer the coordinates of homologous regions.
