### ISSUE TITLE
how to set -D and -N paraments

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#174]
I want to resolve some repeat region by raising the value of -D and - N paraments,know But I don't know how much to set those values，Do you have a better recommendation ？

**Comment by zhoudreames** [comment]
@chhylp123 i am so sorry disturb you,could you help me ? thanks~

**Comment by chhylp123** [comment]
Could you wait me a few days? We will make a new release soon, which should significantly improve the segdup resolution.

**Comment by zhoudreames** [comment]
> Could you wait me a few days? We will make a new release soon, which should significantly improve the segdup resolution.

thanks~, will this new release help resolve repeat? or will better completetment string graph than now version ？  because there are many fragment string graph in my p-utg files，especially chorosome Y.

**Comment by chhylp123** [comment]
It should improve all of them. For CHM13, new release can generate assembly with >90Mb N50, while current release generates assembly with around 80Mb N50.

**Comment by zhoudreames** [comment]
thanks~

**Comment by chhylp123** [comment]
We have made new release (see: https://github.com/chhylp123/hifiasm/releases/tag/0.16.0). Hopefully this will help.

**Comment by zhoudreames** [comment]
> We have made a new release (see: https://github.com/chhylp123/hifiasm/releases/tag/0.16.0). Hopefully this will help.

thanks for your help

**Comment by zhoudreames** [comment]
> @zhoudreames Just curious: have you observed that hifiasm 0.16.1 can resolve more segdups on non-human samples? For CHM13, its N50 is 112Mb with 0.16.1 vs 80Mb with 0.15.

the result  was better,and have resolved two Acrocentric chromosomes ，but The Y chromosome remains the same result.

**Comment by chhylp123** [comment]
That's great, thank you a lot.
