### ISSUE TITLE
Printing contained reads

### ISSUE THREAD

**Issue by cjain7** [chhylp123/hifiasm#175]
Dear hifiasm developers,

Can you suggest a way to print out the read ids that get removed from overlap graph when they are contained in a longer read?

Thanks!

**Comment by chhylp123** [comment]
``--write-paf`` is able to print all overlaps in PAF format. Could you please get contained reads from the PAF file? I guess it is not so hard.

**Comment by cjain7** [comment]
Thanks, given a PAF record of the following format:
```
READ1  LEN   0   LEN  +/-  READ2 ...
```
should imply that READ1 is contained. This way, I can parse all lines and label each read. Hope that's exactly what you meant.

**Comment by chhylp123** [comment]
Yes, it should work in most cases.

**Comment by cjain7** [comment]
:|
I now wonder when would this not work? You said `most` cases?

**Comment by chhylp123** [comment]
Oh sorry I mean sometimes the all-to-all overlaps produced by hifiasm are incorrect, so this way we may lose or misidentify some contained reads.

**Comment by cjain7** [comment]
Thanks for the response.
