### ISSUE TITLE
After getting the following initial assembly files, which one should be selected as the file for subsequent anchoring chromosomes？

### ISSUE THREAD

**Issue by xiaobaiymq** [chhylp123/hifiasm#177]
After getting the following initial assembly files, which one should be selected as the file for subsequent anchoring chromosomes？

`prefix`.hic.p_ctg.gfa: assembly graph of primary contigs.
`prefix`.hic.hap1.p_ctg.gfa: fully phased contig graph of haplotype1 where each contig is fully phased.
`prefix`.hic.hap2.p_ctg.gfa: fully phased contig graph of haplotype2 where each contig is fully phased.

**Comment by ptranvan** [comment]
Hi @chhylp123, I have a releated question.

I use to use the older version with "p_ctg" as primary contigs and "a_ctg" as haplotigs. 

1 ) With the new version, I am not sure what represent `prefix.hic.p_ctg.gfa`: is it still a haploid assembly at the end and if yes where are the haplotigs ?

2) What is  `prefix.hic.p_ctg.noseq.gfa`

3) If have a triploid genome and I have` prefix.hic.hap1.p_ctg.gfa ` and `prefix.hic.hap2.p_ctg.gfa`. It's likely wrong no ? therefore should I use `prefix.hic.p_ctg.gfa` ?

**Comment by chhylp123** [comment]
1) Yes. But if you want to use `p_ctg` and `a_ctg`, you should use the option `--primary`. See [https://hifiasm.readthedocs.io/en/latest/interpreting-output.html]. For triploid genome, you should also set `--n-hap 3`. 
2) `*.noseq.gfa` is a simplified version for corresponding `*.gfa` without sequence. It might be useful for visualization by Bandage.
3) I guess it should be incorrect for triploid genome.
