### ISSUE TITLE
Function for combined use of hifi and ONT reads is needed.

### ISSUE THREAD

**Issue by biozhangzhou** [chhylp123/hifiasm#178]
Hello:
      Can hifiasm deal with hifi and ont ultralong reads ? Since the N50 result from hifi only is not good, Ont ultalong reads must be useful.  But how should we use it ?

**Comment by chhylp123** [comment]
Hifiasm doesn't support UL integration for now. Some tools are able to integrate different assemblies. Probably you can generate assemblies with ultralong reads and then integrate it with HiFi assembly.

**Comment by yangxiaofeill** [comment]
Hi,
      In your opinion, which integration tool is the best one?

Best

**Comment by chhylp123** [comment]
We haven't tried that, but here is an example: https://www.biorxiv.org/content/10.1101/2021.08.30.456472v1
