### ISSUE TITLE
filtering based on coverage?

### ISSUE THREAD

**Issue by kevfengler227** [chhylp123/hifiasm#18]
Is there an easy way to extract the coverage for each unitig/contig? I have a 5 Gb plant genome that ballooned to a 21 Gb assembly from soil contamination.  Hoping I don't have to align the reads to the assembly to get the coverage and find the ~30x contigs. I am assuming the gfa files only list the reads from the tiling path. Is that right? I am assuming that -n only applies to tiling path reads??

Thanks,
KF

**Comment by chhylp123** [comment]
It is not hard to output coverage, just don't know which is the best way to do that. Do you have any suggestion?

**Comment by kevfengler227** [comment]
a tiginfo file like canu generates would be good

#tigID  tigLen  coverage        tigClass        sugRept sugBubb sugCirc numChildren
1       18807238        26.20   contig  no      no      no      29732
3       39575   17.58   contig  no      yes     no      41
4       38016   10.49   contig  no      yes     no      24
6       33996   7.27    contig  no      yes     no      15
7       25754   1.98    contig  no      yes     no      3
8       26839   3.92    contig  no      yes     no      7
11      37370   7.11    contig  no      yes     no      15
14      41010   12.45   contig  no      yes     no      31
15      33639   14.61   contig  no      yes     no      30

**Comment by chhylp123** [comment]
Thanks. Please wait a few days.

**Comment by chhylp123** [comment]
@kevfengler227  We have updated 0.8-dirty-r280. It outputs coverage at 'rd:i:' in S-line of gfa. Here is an example:
> S       atg000001l      *       LN:i:119418     rd:i:19
The coverage of atg000001l is 19.

**Comment by kevfengler227** [comment]
awesome. thanks!. I will give this a try and let you know how it goes.

KF

**Comment by kevfengler227** [comment]
this is very helpful. thanks!

KF
