### ISSUE TITLE
Can hifiasm output assembly reads coverage for each utg？ 

### ISSUE THREAD

**Issue by 865699871** [chhylp123/hifiasm#180]
Can hifiasm output assembly reads coverage for each utg？ like   
![1630829021(1)](https://user-images.githubusercontent.com/13797223/132119990-a927818b-c790-43c7-b231-f3bbfbd4635c.png)

**Comment by chhylp123** [comment]
`rd:i:` is the coverage. See https://hifiasm.readthedocs.io/en/latest/interpreting-output.html#output-file-formats .

**Comment by 865699871** [comment]
Thank you for your answer. We found the rd:i of some utg are 0. 
![1630916346(1)](https://user-images.githubusercontent.com/13797223/132184425-89d483ab-b3af-45ef-93c6-b5c74c7adab3.png)

What strategy used for hifiasm to assign read coverage？Why zero occur？

**Comment by chhylp123** [comment]
It is calculated by the reads coming from the same contig/unitig. `rd:i:X` indicates coverage of `X+1`.
