### ISSUE TITLE
ERROR: this implementation supports no more than 268435456 reads

### ISSUE THREAD

**Issue by iamnotaNL** [chhylp123/hifiasm#182]
Hi,
I am using hifiasm version 0.16.0-r369 at HIC mode, but it stops with this error. Please help me check it.
Thanks.

**Comment by chhylp123** [comment]
Do you have more than 268435456 reads for assembly?

**Comment by iamnotaNL** [comment]
I have 4.7 million hifi reads and 385161126 HIC read pairs (770322252 HIC reads). The problem also occurs in version 0.15.5-r350.

**Comment by chhylp123** [comment]
Could you please check if there are some errors in HiFi fastq file? This problem only reported by hifiasm when there are >= 268435456 HiFi reads. I have seen it before when the HiFi fastq files are truncated un correctly.

**Comment by iamnotaNL** [comment]
I check the md5 of the HIC fq.gz files again and confirm they are correct.
I remember that I did not have the question (version may be 0.15.1-r334) when using the same HIC data several months ago, but that time I only had 2.0 million hifi reads.

**Comment by iamnotaNL** [comment]
I found V 0.15.5 had the same problem. I will try using 0.15.1-r334 to find if the same problem happens.

**Comment by chhylp123** [comment]
Could you count how many HiFi reads by seqtk or seqkit? Could you please show the whole log file? And could you please do assembly without Hi-C?

**Comment by iamnotaNL** [comment]
V0.16.0-r369 can work well only with hifi reads; when using HIC mode, the log file only contains one sentence "ERROR: this implementation supports no more than 268435456 reads". No other out files were produced. The TRIO mode is running, but seems ok as no errors are reported till now.

**Comment by chhylp123** [comment]
Thanks... Could you please show the exact commands with and without Hi-C?

**Comment by iamnotaNL** [comment]
I just checked the original reads from the company and found the HIC reads files may be damaged when I copyed them to another disk. I think this is the reason for the strange problem. I will use the original reads tomorrow and hope the problem is resolved. Thanks for your quick reply.

**Comment by iamnotaNL** [comment]
All are OK now! Thanks.
