### ISSUE TITLE
Phasing

### ISSUE THREAD

**Issue by m-jahani** [chhylp123/hifiasm#183]
Hi,
If a long-running time was okay, what  --n-weight, --n-perturb, and --f-perturb would you recommend for the best phasing results?
What is the best way to check phasing quality?

**Comment by chhylp123** [comment]
If you have trio, you can use trio as ground truth for evaluation. If not, probably you can just use Hi-C heatmap...

As for `--n-weight`, `--n-perturb` and `--f-perturb`, the default value is Ok if your `p_utg.gfa` has <100k unitigs. It is hard to say if larger values can make the results better. If your `p_utg.gfa` has too many unitigs, I guess larger values for these options should be helpful.

**Comment by m-jahani** [comment]
Thanks for your quick answer. My `p_utg.gfa` has ~10K unitigs. I think I should be okay with the default values.
