### ISSUE TITLE
adding extra data to hifiasm

### ISSUE THREAD

**Issue by hoppo** [chhylp123/hifiasm#19]
Hi,

Thanks for the great software - it's fantastic to have an assembly tool which we can run in a modest amount of time. 

I have a question (rather than an issue).

We are working on a diploid plant species (genome size 950Mbp) which is relatively heterozygous (1.5% at the base level). 
We want to see just how far we can push hifi data to generate an assembly without any additional technology. 

I currently have around 89Gbp of data (~88x coverage) data with Hifi data. 
This gives us a pretty good assembly N50 - 37,230,366
To estimate if adding data would improve our assembly further, I downsampled the data which gave us the following N50 values

90% - 32,307,688
80% - 27,353,633
70% - 21,585,766

This would appear to indicate that adding more data would improve the N50.
I do also see an increase in the number of total contigs (which is not unexpected) as the coverage increases. 

Unfortunately I do not have a good reference for this species so I am relying on comparing it to a closely related species. 
I can see in some cases that a single contig spans a complete chromosome (on the closely related species). 

You mentioned in a previous post that hifiasm works best at ~40x coverage and if coverage is too high - 'high coverage may introduce weird things'. Do you think that hifiasm could actually continue to improve our assembly if we were to add more data, or do you think it may start to do some of these 'weird things'. 
Or would it be a better strategy to do more stringent filtering on the input data to maintain the same coverage. We currently are using the default Q20 cutoff.

**Comment by lh3** [comment]
Interesting experiment. In theory, given very high coverage, some sequencing errors may reoccur and deceive hifiasm into thinking them as real haplotype differences. This potentially leads to fragmented assembly downstream. For short reads and noisy long reads, excessively high coverage usually hurts assembly. Quite a few assemblers automatically downsample.

However, we haven't carefully evaluated the effect of high coverage (>50X). I honestly don't know how hifiasm reacts to very high coverage for complex genomes.

> We want to see just how far we can push hifi data to generate an assembly without any additional technology.

We have seen sporadic coverage drops if you sequence from one library. If you have enough DNA, I suspect having two+ ligations/libraries is better. Also, the Canu group has observed that HiFi reads can't reliably go through (GA)n repeats. Nanopore can be useful in this case, though we don't know how to integrate nanopore with HiFi.

**Comment by kevfengler227** [comment]
Indeed most of the gaps in my HiFi plant genome assemblies are due to (GA)n repeats. So adding more HiFi data does not help. PacBio CLR performs better in these regions.

**Comment by hoppo** [comment]
Thanks for the replies. 
@kevfengler227 - what level of coverage did you use for your plant genomes such that the majority of the gaps were just (GA)n repeats? 

One of my concerns is indeed that sequencing errors (or minor contamination) receive enough coverage to be mistaken for actual sequences and thus becomes incorporated into the finished assembly.
If this were to be the case, how would this manifest itself in the finished assembly stats? 
A greater proportion of phasing (albeit incorrectly)? 
A larger number of (smaller) contigs? 

Could this be driving the improvements I see in the N50?

**Comment by kevfengler227** [comment]
From my from experience, for inbred crop plant genomes, 30-40x HiFi is all you need to get just a handful of contigs per chromosome. In your case, if the assembly size is close the expected size, then heterozygosity is not a major concern that would necessitate additional coverage. The best way to answer your questions about the assembly, characterize the gaps, assess the heterozygosity and to create a reference is to add a BioNano map. Then, for example you'd see that most of the gaps are very small  (<5 kb) and associated with coverage dropouts in the HiFi data (GA)n. Also, you may see a few more mis-assemblies in your higher coverage assemblies getting cut during hybrid scaffolding with BioNano.
