### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by KaiqiangLiu** [chhylp123/hifiasm#20]
Hi,
    Thanks for the great software. 
     When I run hifiasm (0.7/0.8) to assemble one huge genome, more than 40Gb with 1.4Tb CCS data on a 4Tb node.
     Suppose 4Tb node is enough given 35.6 Gb redwood genome only needs 699Gb memory.
     Unfortunately, I failed to complete the jobs after the index step, the error is 'Segmentation fault (core dumped)',   any ideas to help me out. 
     Thanks.

**Comment by chhylp123** [comment]
Could you please share the log information? Thanks.

**Comment by KaiqiangLiu** [comment]
Thanks for your quick reply. 
The log file is below.
```
[M::ha_analyze_count] lowest: count[379] = 287425
[M::ha_analyze_count] highest: count[4095] = 9819891
[M::ha_hist_line]     2: ******************************************************************************************
[M::ha_hist_line]     3: ******************************************************************************************
[M::ha_hist_line]     4: ****************************************************************************************** 
...
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 192; peak_het: -1
[M::ha_pt_gen::182655.618*30.61] ==> indexed 31527383716 positions
work.sh: line 2: 28147 Segmentation fault      (core dumped)  hifiasm-0.7/hifiasm -o asm -t 300 $fa
```

**Comment by chhylp123** [comment]
Could you share the whole log? Thanks again.

**Comment by KaiqiangLiu** [comment]
The log file is more than 200kb.
Could you please offer me an email address?  I would like to send you an email with the whole log file. 
Thanks.

**Comment by chhylp123** [comment]
Here is my email: hcheng@jimmy.harvard.edu. Thanks.

**Comment by KaiqiangLiu** [comment]
I send you one email, please check. Thanks.

**Comment by chhylp123** [comment]
The k-mer histogram is quite weird. Which type if sample are you assembling, diploid or polyploidy? And what's the coverage of this sample?

**Comment by KaiqiangLiu** [comment]
The genome is diploid, the data is about 28X.

**Comment by HenrivdGeest** [comment]
Could we look along with the kmer distribution?  Could help others for
future debugging:)
Ontopic; you could try to subsample the data to a quarter, which should
already assemble into something close to your expected genome size.

**Comment by lh3** [comment]
@KaiqiangLiu based on the k-mer spectrum, it seems that you are using subreads prior to the CCS step.

**Comment by KaiqiangLiu** [comment]
@lh3  The above description of the data is not clear enough.  
Half of my data is CCS reads, the other half is the corrected CLR one(accuracy > 98% ).
Given the high accuracy of corrected CLR reads and the proper input format (FASTA), I feed both CCS reads and corrected CLR one to the Hifiasm. 
On your side, the data I feed in could cause something weird?  
Is there any workaround to assemble the genome with my data? 
Thanks.

**Comment by lh3** [comment]
With homopolymers compressed, HiFi reads have >99.9% accuracy. Corrected CLR data are not good enough. Try on HiFi reads only.

**Comment by chhylp123** [comment]
BTW, I highly recommend you to use the latest version (v0.9) since it is able to avoid misassemblies. If you have the bin files generated by v0.8, you can just quickly rerun hifiasm v0.9 with v0.8 bin files.

**Comment by KaiqiangLiu** [comment]
@HenrivdGeest  @lh3  @chhylp123  Thanks. I will try the latest version with HiFi reads.

**Comment by KaiqiangLiu** [comment]
This time I only used 750G HIFI data to assemble the genome by hifiasm v0.9,  but It is quite weird that the memory consumption is more than 3.2Tb, moreover, it seems that the memory still grows.

**Comment by lh3** [comment]
What does the k-mer histogram look like?

**Comment by KaiqiangLiu** [comment]
Please check out the whole log I send you.

**Comment by lh3** [comment]
Your k-mer spectrum still looks unusual: it has no peaks. You are supposed to see one or two peaks around the estimated coverage.

**Comment by chhylp123** [comment]
For diploid samples, a typical k-mer histogram likes (https://github.com/chhylp123/hifiasm/issues/10):
![image](https://user-images.githubusercontent.com/2330901/79697364-a5f6dd80-8282-11ea-9d21-abf6e9748b3c.png)

There should be two peaks, one is the homozygous peak, while another is the heterozygous peak.

Another possibility is that hifiasm print wrong k-mer histogram, although I think it is almost impossible. To double check it, you can run Jellyfish and then passing the histogram of reads through GenomeScope (http://qb.cshl.edu/genomescope/).

**Comment by KaiqiangLiu** [comment]
I checked the k-mer histogram by Jellyfish and GenomeScope,  it turned out same as hifiasm.

**Comment by chhylp123** [comment]
Then it is very likely that your reads have some problems. We haven't observed any diploid sample with such k-mer histogram.
