### ISSUE TITLE
hifiasm with -l0 still apparently merging different segmental duplications

### ISSUE THREAD

**Issue by dabitz** [chhylp123/hifiasm#21]
Hi, thanks a lot for the great assembler.

I am trying to assemble a homozygous plant genome with 1.6gb with 40X CCS reads. Interestingly, this plant seems to have accumulated large segmental duplications that share a high similarity. In some cases over 95%. We have tried hifiasm with and without the purging option (-l0). The assembly looks much better without the purging step (N50 20Mb) in comparison with the purging step (N50 12 Mb). However, it seems that even without purging some regions after mapping seems to contain collapsed segmental duplications as checked by mapping the reads. Some regions seem to have double coverage. 

![igv_snapshot](https://user-images.githubusercontent.com/25509795/88920123-99fcbd80-d26c-11ea-8650-0162954ec188.png)

Any parameter suggestion to improve the assembly?

Thanks!
André

**Comment by chhylp123** [comment]
May I ask which version are you using? Thanks.

**Comment by chhylp123** [comment]
From the the unitig name, I guess you are using v0.7. I strong recommend you to reassemble with v0.9. For v0.9, you can adjust the following options:
>purge-cov
>pri-range

And what's the size of p_ctg.gfa and a_ctg.gfa? We have also tested a repetitive maize genome and the result looks fine.

**Comment by dabitz** [comment]
Yes, indeed this was done with version 0.7, I will now run with the new version with the suggested parameters. Any suggestion to use with 40X coverage?

p_ctg.gfa has 1.66Gb and a_ctg.gfa has 102Mb

Thanks!

**Comment by dabitz** [comment]
these are -l0 numbers. Do you think -l1 would help?

I will try the different approaches... Thanks for the support!

**Comment by chhylp123** [comment]
Maybe not... There is still room for improvement on segdups, we are constantly working on that.

**Comment by lh3** [comment]
Hifiasm is not perfect and may produce misassemblies. Some of the peaks should be misassemblies. Nonetheless, a unitig represent multiple exact copies of a repeat/segdup. Most of such unitigs can't be resolved unless you add longer nanopore reads. These are remaining ambiguity in the assembly but are not really counted as misassemblies. For a homozygous genome, a typical misassembly has doubled coverage AND is enriched with heterozygous "SNPs".

**Comment by dabitz** [comment]
Thank you guys for the support. Now I have merged the p_ctg and a_ctg fast files and I got I pretty nice mapping uniformity... Only one contig keeps showing half of the coverage. What could it be?

![best-assembly-igv_snapshot](https://user-images.githubusercontent.com/25509795/89499049-a8445f80-d7bf-11ea-8f1a-2363b361b1e6.png)

**Comment by lh3** [comment]
A good try on merging p_ctg and a_ctg. Now I wonder if these a_ctg should really be p_ctg...

> Only one contig keeps showing half of the coverage. What could it be?

You said your sample is homozygous, which implies it is not haploid. In that case, there could be a heterozygous deletion on one haplotype. Another possibility is that hifiasm assembles one homozygous region into two, but I think this is unlikely. I don't know.

**Comment by chhylp123** [comment]
I agree with Heng. Another way is to check the corresponding regions at r_utg.gfa. We can have a look together if you upload the subgraph of r_utg.gfa here.

**Comment by dabitz** [comment]
Hi, here are the graphs for the p_ctg.gfa file, the contig with half coverage is highlightened, how should I send you the r_utg.gfa? is a 1.8gb file!

Looking at the circular shape of this contig graph, would it be possible that hifiasm assembled the same sequence twice and did not collapsed?

![TestrPuberaCCS p_ctg](https://user-images.githubusercontent.com/25509795/89629813-bb7a2c80-d89e-11ea-8858-4ed4bca670ce.jpg)

**Comment by dabitz** [comment]
Indeed! But why?

![utg003791l](https://user-images.githubusercontent.com/25509795/89631991-d26e4e00-d8a1-11ea-8184-aafbd20fc239.png)

**Comment by dabitz** [comment]
is it possible to set assembly with even higher read accuracy?

**Comment by lh3** [comment]
Are the two copies exactly the same? If not, hifiasm will separate them.

**Comment by dabitz** [comment]
They are 99,99% similar

**Comment by lh3** [comment]
You can send us the r_utg.noseq.gfa first without sequences. That should be much smaller. You can also give us a few read names on that questionable contig such that we can pinpoint the unitig inthe r_utg graph.

Based on the information so far, my current guess is that this is a real heterozygous region. However, hifiasm somehow misassembles the two haplotypes into one contig.

**Comment by dabitz** [comment]
Here are the links to download the r_utg.noseq.gfa and a list with read names

https://www.dropbox.com/s/aif2ldq3nqfhc27/TestRpuberaCCS.r_utg.noseq.gfa?dl=0

https://www.dropbox.com/s/aif2ldq3nqfhc27/TestRpuberaCCS.r_utg.noseq.gfa?dl=0

I can also send the bam file only for this particular contig...

**Comment by dabitz** [comment]
any news on this issue?

**Comment by chhylp123** [comment]
I'm so sorry for the late reply. I just checked your r_utg.gfa, which is a little bit weird. For example, m64078_200405_044943/109644221/ccs and m64078_200427_080658/85131714/ccs are at utg003791l, but they are not at r_utg.gfa. Can you please check where does utg003791l come from? It shouldn't come from p_ctg.gfa since the prefix of contig name at p_ctg.gfa is 'ptg'.

**Comment by zhaotao1987** [comment]
> Hi, here are the graphs for the p_ctg.gfa file, the contig with half coverage is highlightened, how should I send you the r_utg.gfa? is a 1.8gb file!
> 
> Looking at the circular shape of this contig graph, would it be possible that hifiasm assembled the same sequence twice and did not collapsed?
> 
> ![TestrPuberaCCS p_ctg](https://user-images.githubusercontent.com/25509795/89629813-bb7a2c80-d89e-11ea-8858-4ed4bca670ce.jpg)

I wondered how can you generate such graphs, looks great. Thanks!

**Comment by dabitz** [comment]
https://rrwick.github.io/Bandage/

**Comment by zhaotao1987** [comment]
> https://rrwick.github.io/Bandage/

Cool, thanks! @dabitz

**Comment by B10inform** [comment]
Hi all,

With hifiasm (p.ctg.gfa) and bandage, i get this graph.
![image](https://user-images.githubusercontent.com/66449329/99846712-b8443d00-2b2b-11eb-8910-d09b680bbb02.png)

Is this a correct output,  unlike #dabitz's graph the lines are one color  (major larges ones). Any help to interpret would be great.

Best

**Comment by chhylp123** [comment]
> Hi all,
> 
> With hifiasm (p.ctg.gfa) and bandage, i get this graph.
> ![image](https://user-images.githubusercontent.com/66449329/99846712-b8443d00-2b2b-11eb-8910-d09b680bbb02.png)
> 
> Is this a correct output, unlike #dabitz's graph the lines are one color (major larges ones). Any help to interpret would be great.
> 
> Best

Looks like the graph is not bad? The color of each contig is determined by Bandage.
