### ISSUE TITLE
hififasm generates unexpected alternate content for haploids

### ISSUE THREAD

**Issue by klabutti** [chhylp123/hifiasm#210]
Hello,

I've recently assessed a variety of diploid-aware assemblers for assembly of fungal PacBio Sequel IIe HiFi.   44 HiFi data sets (17 diploid) were used in the experiment.   hifiasm performed quite well with respect to basic assembly statistics and genome completeness measures (cegma, busco, EST capture) but results for haploids exhibit an unexpected amount of alternate contigs.  Assembly consensus was reformatted as suggested in the docs:

awk '/^S/{print ">"$2"\n"$3}' hifiasm.bp.hap*.p_ctg.gfa   # combines primary and alternate

Below is a plot showing boxplots for assembly/completeness statistics per assembler/ploidy.   The concerning amount of alternate output, presented as percent of duplicated BUSCO, is circled.

![image](https://user-images.githubusercontent.com/1903026/142225824-c93c2d1c-594c-414c-bc23-3c5301e9b1a8.png)

For the above reasons I'm hesitant to use hifiasm for (haploid) fungal assembly since we don't always know what the expected ploidy is beforehand and the current output does not seem representative of the haploid genome.

Do you have any suggestions for haploid assembly with hifiasm?

Best regards,
Kurt

**Comment by chhylp123** [comment]
For haploid, do you mean the sample itself is haploid, instead of the sample is diploid but you want to get a primary assembly? And if you want to combine primary assembly and the alternate assembly, you should merge 'bp.p_ctg.gfa' and 'bp.a_ctg.gfa', rather than 'bp.hap1.p_ctg.gfa' and 'bp.hap2.p_ctg.gfa'. 'bp.hap*.p_ctg.gfa' will double the homozygous regions so it will introduce false duplications.

**Comment by klabutti** [comment]
Hello,

Yes the sample itself is haploid or diploid/dikaryon.  In either case I
would like the most representative assembly for each.   Are you suggesting
combining different outputs based on expected ploidy?   This isn't possible
unless we can accurately estimate ploidy given the HiFi k31 profile.
Another estimation of ploidy we use is how much of the resulting assembly
is duplicated, especially with respect to markers like BUSCO or CEGMA.  I'm
curious why there is such significant 'alternate' content for haploid
samples, as you can see the other assemblers in the experiment did not
identify alternate content.



Best regards,
Kurt

**Comment by chhylp123** [comment]
What if you just use primary assembly (bp.p_ctg.gfa), or (bp.p_ctg.gfa+bp.a_ctg.gfa)? You shouldn't combine 'bp.hap1.p_ctg.gfa' and 'bp.hap2.p_ctg.gfa', which will double the homozygous regions.

**Comment by klabutti** [comment]
Yes, I can reassess with your suggestion,  but I'm curious why there is
alternate content to begin with given a haploid.

Best,
Kurt

**Comment by chhylp123** [comment]
Could you please show the size of p_ctg and a_ctg?

**Comment by klabutti** [comment]
Yes, though our HPC is undergoing routine maintenance today so I won't have
access to the data until tomorrow.

Best,
Kurt

**Comment by lh3** [comment]
> combines primary and alternate

`*.bp.hap?.p_ctg.gfa` are not the primary/alternate assembly pair. They are the so-called "dual" assembly unique to hifiasm. Generating them assumes the sample is diploid. For a direct comparison to other assemblers, you should look at `*.bp.p_ctg.gfa` and `*.bp.a_ctg.gfa` instead. If the heterozygosity is low, you will find the dual assembly to be much more useful for pangenome analysis.

**Comment by klabutti** [comment]
Thank you Heng, I will assess the primary/alternate output to see how it
compares.  My concern is still if ploidy isn't available beforehand how
does one know which files to use?,  or is it a matter of comparing the
primary/associate vs hap1/hap2?

Best,
Kurt

**Comment by lh3** [comment]
> My concern is still if ploidy isn't available beforehand how does one know which files to use?

You can tell based on the size of alternate contigs.

**Comment by klabutti** [comment]
Ah, yes of course.  Thank you.

**Comment by klabutti** [comment]
Our compute is back online and checked my output.  Thank you for your patience with my misunderstanding.

I ran hifiasm 3 different ways for each dataset (default, -n-hap1 , -l0) and can confirm the primary/alternate contig output from -l0 (or --primary) is as expected for haploids vs diploids, below.

![image](https://user-images.githubusercontent.com/1903026/142447800-61b3d151-170c-46a4-a23a-48dc6596ee30.png)

Best regards,
Kurt

**Comment by klabutti** [comment]
I agree adding to the FAQ may help guide those assembling a variety of conditions.    As a follow up here are the fraction of alternate bases assembled by hifiasm for 48 fungal data sets.   (contaminated data sets were labeled as ploidy=3 for convenience)

![image](https://user-images.githubusercontent.com/1903026/142656418-ef506683-0986-467d-9ff8-b07345e7b001.png)

**Comment by chhylp123** [comment]
Thanks!
