### ISSUE TITLE
Using error corrected sequal data as input for hifiasm 

### ISSUE THREAD

**Issue by hmdfirst** [chhylp123/hifiasm#212]
Hi,

The question might be a bit strange but wanted to check this with the developers. Some of us have still RS II or Sequel data (not hifi). I was wondering if such data after error correction using canu, falcon, etc. can be fed into hifiasm to assemble a genome.

I have data from sequal for a diploid highly heterozygous genome and want to give it a try since I got very good results using hifiasm on hifi data and both haplotypes phased perfectly for another diploid genome. Please let me know if it might work or not, and if I need to use specific parameters to enhance the outcome.

Thanks in advance,

**Comment by chhylp123** [comment]
You can have a try, but it might do not work in most cases.

**Comment by hmdfirst** [comment]
Thanks and sorry for my question if too basic. May I ask what might be different? the error corrected reads have quite a similar error rate and length compared to the HIFI reads.  Is it the coverage or there is something else in hifi reads that is required and not available in error-corrected reads?
thanks in advance

**Comment by lh3** [comment]
Error correction kills phasing which is critical for hifiasm to function.
