### ISSUE TITLE
HiC integrated output fastq

### ISSUE THREAD

**Issue by B10inform** [chhylp123/hifiasm#215]
Hi chhylp123,

Can the hiC integrated hifiasm output hap1, hap2 separated raw .fastq files too?

Best

**Comment by chhylp123** [comment]
In GFA file, the A-lines with `HG:A:p`, `HG:A:m` and `HG:A:a` indicate reads coming from hap1, hap2 and ambiguous, respectively.

**Comment by B10inform** [comment]
Thank you chhylp123,

Does the GFA file has information of HiC reads too?

Thanks

**Comment by chhylp123** [comment]
No, it doesn't have Hi-C reads.

**Comment by B10inform** [comment]
Is there anyway the HiC reads can be extracted too? (hifiasm hiC integerated)

Thanks

**Comment by lh3** [comment]
Unfortunately, no.

**Comment by B10inform** [comment]
Do you think the Hap 1 (HG:A:p) reads and Hap2 (HG:A:m) reads extracted from GFA file, if used to pull read sequences from the raw HiFi data (original .fastq files) are good enough to use again for hifiasm assembly. 
Would these reads give same results as the original Hifiasm assembly?
When i check the Hap 1 (HG:A:p) GFA file there are only ~110390 reads the original .fastq has ~1415000.

Thanks

**Comment by lh3** [comment]
> Would these reads give same results as the original Hifiasm assembly?

No.

**Comment by B10inform** [comment]
Hi, 

When i assemble the Hap 1 (HG:A:p) reads .fastq I get the phased assembly. 
hifiasm -o HAP1.asm -t32 HAP1.fq
It gives me HAP1.gfa and HAP2.gfa file. Is it common?

Same goes with Hap2 (HG:A:m.

Thanks

**Comment by lh3** [comment]
> Is it common?

Yes. Again, hifiasm is not designed to be used this way.
