### ISSUE TITLE
Selecting homozygous peak (--hom-cov)

### ISSUE THREAD

**Issue by pjm43** [chhylp123/hifiasm#223]
I'm running hifiasm with HiC data using the defaults (0.16.1-r375) on a photosynthetic flagellate (eukaryote).  The question I have is with regards to picking the correct homozygous peak.  I have a single peak in the kmer analysis at 26X coverage
([hifiasm_asm.txt](https://github.com/chhylp123/hifiasm/files/7729048/hifiasm_asm.txt)).  It appears, however, that hifiasm picked a homozygous read coverage of 52 ([M::purge_dups] homozygous read coverage threshold: 52), yet in other parts of the output it indicates that the peak is at 26 (e.g., [M::ha_pt_gen] peak_hom: 26; peak_het: -1).  Since my hap1 and hap2 gfa files are not balanced I'm trying to figure out what approach I should take to get them balanced.  Is 52 the correct homozygous peak call? Or should I set --hom-cov to 26 and rerun?  

Thanks in advance for your help!

**Comment by chhylp123** [comment]
Yes, set `--hom-cov 26` and rerun with the existing bin files. There is one line in log file:
>[M::stat] # heterozygous bases: 2740819595; # homozygous bases: 625497658

It means hifiasm thought 20% of bases are homozygous, which is totally wrong. It is pretty tricky to get a right coverage peaks, so sometimes we may need to manually adjust it. Probably you may also need to tune `-s` if the heterozygosity rate is too high. Here are some FAQs about Hi-C: https://hifiasm.readthedocs.io/en/latest/faq.html#why-one-hi-c-integrated-assembly-is-larger-than-another-one  and https://hifiasm.readthedocs.io/en/latest/faq.html#how-can-i-tweak-parameters-to-improve-hi-c-integrated-assembly .

**Comment by pjm43** [comment]
Thanks for the quick response!
