### ISSUE TITLE
Rescuing contained reads 

### ISSUE THREAD

**Issue by cjain7** [chhylp123/hifiasm#227]
Hello,

From the Hifiasm-meta pre-print, I learnt about a heuristic available in Hifiasm to rescue contained reads when they are needed.
I believe the logic for this is implemented in function [rescue_contained_reads_aggressive()](https://github.com/chhylp123/hifiasm/blob/ab80851b946ee2897b0ff0583b164fc11362ef42/Overlaps.cpp#L26494).
Can you please suggest if it is trivial to edit the function and print out read ids of all the reads which are rescued? If so, how?

**Comment by chhylp123** [comment]
Well, I guess the simplest way might be disabling it and getting a graph. Then if we compare the graph without contained reads with the default graph including contained reads, we would know which reads are rescued. In most cases, it should work. I can also add a function printing read id if necessary.

**Comment by cjain7** [comment]
Thanks for the quick response. 

Is there is a command line option to disable this feature, or do you recommend editing the code?
Also, when you say "most cases", when would the above route not work?

**Comment by cjain7** [comment]
Thanks. The way I did it was to extract all read ids from `r_utg.gfa` file obtained after Hifiasm run and intersect it with contained read ids. I think this should work.

**Comment by chhylp123** [comment]
I see, your solution might be better. As for the "most cases", I mean hifiasm do graph cleaning iteratively so some changes in upstream steps may affect the downstream steps. But I guess it won't affect a  lot.
