### ISSUE TITLE
Too many contigs and lager genome size compared with ONT seqenceing 

### ISSUE THREAD

**Issue by Aannaw** [chhylp123/hifiasm#229]
Hello, professor
I am new to hifiasm. I am using Hifiasm 0.16.1-r375 to generate a assembly from three HiFi CCS  reads. My command is: `hifiasm -o A -t 30 A.1.fasta A.2.fasta A.3.fasta > A.hifiasm.log. The A.1.fasta、A.2.fasta and A.3.fasta` are the conversion from CCS.bam to fasta using "`samtools view A.1.ccs.bam | awk '{print ">"$1"\n"$10}' > A.1.fasta`". However, after converting the  primary assembly "A.p_utg.gfa" to the "A.p_utg.fasta" with the command "`awk '/^S/{print ">"$2;print $3}'`", I got the  primary assembly of with 2530 contigs. After using juicer+3ddna to scaffold the contig assembly with hic data, only 114 contigs are anchored 32  chromosomes and the anchoring rate is low about 74%. Genome size is 3,210,343,700. And in my output directory, I can not find the  two sets of partially phased contigs A.hap*.p_ctg.gfa as described by the  tutorial . Is it normal?
Also, We sequenced several other sepecies of the same genus with ONT and  assembled by nexdenovo, but the genome size is all about  2.5G. It about decreased by 500M compared with hifiasm assembly. I am not sure the the difference of two way of sequencing and assembly is due to  the sequence platform or species difference? Maybe should I set the parameters to decrease the contig number of A.p_utg.fasta? 
The following is my log.
[A.hifiasm.log](https://github.com/chhylp123/hifiasm/files/7820272/A.hifiasm.log)
Looking forward with your reply.
Best wishes!

**Comment by chhylp123** [comment]
From your log file, you are using version 0.14-r312 instead of v0.16.1. I strongly recommend you to rerun assembly with v0.16.1.

**Comment by lh3** [comment]
In addition, 1) use p_ctg, not p_utg and 2) nextdenovo is known to produce smaller-than-expected assemblies.

**Comment by Aannaw** [comment]
Hello,professor
Thanks for your reply.
I will rerun assembly with v0.16.1. Maybe the version will produce the assembly with less contigs?  And do I need to combine three  CCS fasta by` cat A.1.fasta、A.2.fasta and A.3.fasta > A.fasta ` and then rerun?
Thanks again for your reply!

**Comment by Aannaw** [comment]
Hello,Professor
I have rerun assembly  with v0.16.1 and the *.bp.p_ctg.fasta has 832 contigs. However, there is a " ERROR-purge" in the log file just like the following picture. Then I checked the kmer plot in the log and the homozygous coverage peak is 26 or 27. In the log file,  hifiasm prints the following information "[M::purge_dups] homozygous read coverage threshold: 26". It seems that the homozygous read coverage is correct. But there seems to be a heterozygous peak on the kmer plot.  Is it the reason of "ERROR-purge"? I would appreciate with you if you could give me any suggestions?
Looking forward with your reply!
Best wishes!
![4e61bdacd9a8ade1f18885f0109c9d1](https://user-images.githubusercontent.com/82857778/148906408-5130855c-31c7-4450-b5bf-0ad6265feb9f.png)


[log.log](https://github.com/chhylp123/hifiasm/files/7844829/log.log)

**Comment by chhylp123** [comment]
You can ignore `ERROR-purge`, which is just a warning. From the log file, it seems your assembly is pretty good.

**Comment by Aannaw** [comment]
Hello,professor
Thanks very much for your reply!
May I have ask for another two questions? 
Firstly, does the kmer plot in the log indicates the heterozygous peak  before the major homozygous peak? Should I run purge_dups?
Secondly, shold I polish the hifiasm assembly using pilon or racon?
Looking forward with your reply！
Best wishes!

**Comment by chhylp123** [comment]
>1. Firstly, does the kmer plot in the log indicates the heterozygous peak before the major homozygous peak? Should I run purge_dups?

Yes, it is the heterozygous peak. Running purge_dups or not depends on your applications. For example, if you want to get haplotype-resolved assemblies, the assemblies should not be purged. 

>2. Secondly, shold I polish the hifiasm assembly using pilon or racon?

No, it is likely to be overcorrection at some repetitive regions.

**Comment by Aannaw** [comment]
Hello, professor
I am confused if I should run` purge_dups`. Maybe it is a fool question, but I really can not understand "`haplotype-resolved assemblies`". Now I generated `the primary assembly (Ma6.bp.p_ctg.fasta) `and `two sets of Partially phased assembly (Ma6.bp.hap1.p_ctg.gfa, Ma6.bp.hap2.p_ctg.fasta)`. I have checked the The concepts of different types of assemblies  referring 
the link [https://lh3.github.io/2021/04/17/concepts-in-phased-assemblies](url). It seems that primary  assembly and partially phased assembly both have long stretches of phased blocks, but I haven't found the differences between them.  As you said "`haplotype-resolved assemblies`" above,  does it indicates "`primary assembly`" or " `Partially phased assembly` "?

**Comment by Aannaw** [comment]
Hello,Professor
If I want to use primary assembly to downstream analysis, should I run purge_dup ?

**Comment by chhylp123** [comment]
`Primary assembly` is contiguous but `alternative assembly` is highly fragmented. If you are assembling a diploid genome, hifiasm will output two `partially phased assemblies`, each of which is as contiguous as the primary assembly. This is the main difference between `primary assembly/alternative assembly` and `partially phased assemblies`.

As for purge_dups, it depends on how does your primary assembly looks like. You could run BUSCO or get k-mer plot to see if there are false duplications. If there are large numbers of false duplications, probably you should run purge_dups.

**Comment by Aannaw** [comment]
The "get k-mer plot " you said above refers to calculating kmers with hifi reads or assembly fasta?

**Comment by lh3** [comment]
The assembly looks ok. No need to run purge_dups.

**Comment by Aannaw** [comment]
Hello,Professor
Thanks for your prompt reply. It helps a lot for me. 
Best wishes!

**Comment by studyliu123** [comment]
> 您好，教授 感谢您的回复。我将使用 v0.16.1 重新运行程序集。也许该版本将生成具有较少重叠群的程序集？我是否需要将三个 CCS fasta 组合在一起，然后重新运行？另外，我是否需要添加到参数中设置，如自述文件中显示的鼠标或其他参数？我的物种是Spalacidae。期待您的回复。愿你安好！`cat A.1.fasta、A.2.fasta and A.3.fasta > A.fasta``-l0``"no purging"``"-D -N"`

hello,I am  also

**Comment by studyliu123** [comment]
> Hello,professor Thanks for your reply. I will rerun assembly with v0.16.1. Maybe the version will produce the assembly with less contigs? And do I need to combine three CCS fasta by`cat A.1.fasta、A.2.fasta and A.3.fasta > A.fasta` and then rerun? Also, do I need to add to the parameter `-l0` to set `"no purging"` like the mouse displayed in the readme or other parameters like`"-D -N"`? My species is Spalacidae. Looking forward with your reply. Best Wishes!

hello , I am new to assembly .I have the same problem as you. Can you share your code? Looking forward with your reply！
Best wishes!

**Comment by Aannaw** [comment]
Hello,
I just use default parameters with `hifiasm -o Ma6 -t 48 Ma6-1.fasta  Ma6-2.fasta Ma6-3.fasta 2> Ma6.log` . However I surprisingly found the assembly with `v0.16.1` have  `the same numbers of contig` ,  `N50 and even busco score` as the assembly by` 0.14-r312 `with `l3 `parameter before. I am actually confused. Maybe professors could give us some suggestions. @chhylp123 @lh3

**Comment by chhylp123** [comment]
Are you running v0.16.1 on top of v0.14 bin files?

**Comment by Aannaw** [comment]
Hello,Professor
It seems that I am not running v0.16.1 on top of v0.14 bin files. As said above, I run  v0.16.1 with command "hifiasm -o Ma6 -t 48 Ma6-1.fasta Ma6-2.fasta Ma6-3.fasta 2> Ma6.log". The fasta file is generated by Pacbio  toolkit bam2fastx from ccs bam file.

**Comment by chhylp123** [comment]
> Hello,Professor It seems that I am not running `v0.16.1` on top of `v0.14` bin files. As said above, I run `v0.16.1` with command "`hifiasm -o Ma6 -t 48 Ma6-1.fasta Ma6-2.fasta Ma6-3.fasta 2> Ma6.log`". The fasta file is generated by Pacbio toolkit `bam2fastx` from` ccs bam` file.

Your assembly is pretty good, so probably no need to worry about that. But it is weird for me that two versions produced the same assemblies. I have no idea about this.
