### ISSUE TITLE
read correction in polyploïd genomes

### ISSUE THREAD

**Issue by chklopp** [chhylp123/hifiasm#231]
We are assembling a tetraploïd genomes harboring parts issuing from an ancient duplication which make it look octoploïd in some locations. How many rounds of read correction should we use. Is there a risk to over-correct the reads? If only 1/8 of the reads present a variation, lets say 4 out of 32 will hifiasm replace the alternative allele with the majority allele?

**Comment by chhylp123** [comment]
Hifiasm does not have a diploid assumption, so probably no need to worry about that. You can have a try a version that might be a little bit better in terms of overcorrection (https://github.com/chhylp123/hifiasm/tree/hifiasm_dev_debug). But I guess the results won't be changed a lot.

**Comment by chklopp** [comment]
Thank you.
