### ISSUE TITLE
ERROR: this implementation supports no more than 268435456 reads

### ISSUE THREAD

**Issue by junya11235** [chhylp123/hifiasm#237]
Hi, would you let me know how to assemble more than 268,435,456 reads?
I have 1600M reads.

**Comment by lh3** [comment]
Is it HiFi? 268M reads of ~15kb can sequence a 100Gb genome 40 times.

**Comment by junya11235** [comment]
It was my misunderstanding.
I supposed to use illumina short reads.
Sorry for disturbing you.

**Comment by junya11235** [comment]
It was my misunderstanding.
I supposed to use illumina short reads.
Sorry for disturbing you.

**Comment by Ahahaha3** [comment]
I still don't quite understand what is causing this, can you please clarify? thanks @junya11235 @lh3
