### ISSUE TITLE
How high is “high heterozygosity”?

### ISSUE THREAD

**Issue by jelber2** [chhylp123/hifiasm#24]
Curious if there is a recommendation on what level of heterozygosity to use the “--high-het“ option?

**Comment by chhylp123** [comment]
Actually I don't know the exactly number, I guess it is unnecessary to use “--high-het“ for samples with <1.5% heterozygosity rate. Probably I'm wrong. 
For now this option is not stable and will increase running time. Probably running hifiasm without “--high-het“ and postprocessing with Sanger Purge_dups is still a stable way. We really appreciate if you're interested to test it.

**Comment by jelber2** [comment]
I am afraid that my only contributions would be through simulated data and not real data at this point as I only have PacBio CLR reads (~14x coverage) corrected with GraphAligner to an average quality value of Q27 (not quite expected Q30 of HiFi reads). Also the raw reads of the mentioned real data have a very truncated N50 of only about 3 Kbp (not > 10 Kbp).

**Comment by chhylp123** [comment]
I don't know either. But corrected CLR data might not work well.

**Comment by jelber2** [comment]
Thanks for the suggestions on het rates.
