### ISSUE TITLE
PAF formatted overlaps

### ISSUE THREAD

**Issue by cjain7** [chhylp123/hifiasm#241]
I'm trying to understand the PAF overlap information available from Hifiasm. I'm seeing records of the following type:

```
read=1,reverse,position=65187724-65244826,length=57102	57102	53458	56708	-	read=3663,forward,position=65188118-65191368,length=3250	3250	0	3250	1	3250	255
```
Based on PAF format specification, column 10 should contain the "Number of residue matches". However, this information is not available in the above record. Can you please give details about whether Hifiasm follows the PAF convention or not (especially in columns 10 and 11)?

**Comment by chhylp123** [comment]
We initially used these overlaps for debugging so they do not strictly follow the standard PAF format. Columns 1-9 and 12 are organized as PAF format specification, but column 10 indicate if this read has informative sites (0/1) and column 11 is equal to column 7, which is the target sequence length.

**Comment by cjain7** [comment]
Got it. Thanks!

**Comment by cjain7** [comment]
A follow up question:
Would 0 in column 10 occur if and only if the overlap is exact (100% identical)? Just trying to see if value in column 10 can be useful to predict overlap identity.

**Comment by chhylp123** [comment]
No, 0 in column 10 indicates there are informative sites. Probably a quick solution is to check if the query overlap length and the target overlap length are equal.

**Comment by cjain7** [comment]
Alright. Thanks again for quick response.
