### ISSUE TITLE
het_peak -1

### ISSUE THREAD

**Issue by genmor** [chhylp123/hifiasm#245]
Hiya, I'm rather new to the field, so please bear with me if this is an uninformed question. I ran hifiasm, and the output seems sensible to me (and my advisor). What gives me pause is that hifiasm places peak_het at -1.  I would like to know what this means, and whether this is an error of some sort (and if so, how can it be remedied?).  I've pasted the output below, in case it will help to diagnose any issues.  Thanks.

[M::ha_analyze_count] lowest: count[6] = 8172160
[M::ha_analyze_count] highest: count[16] = 82030387
[M::ha_hist_line]     2: ****************************************************************************************************> 321145406
[M::ha_hist_line]     3: ****************************************************************************************************> 90910784
[M::ha_hist_line]     4: ************************************ 29609582
[M::ha_hist_line]     5: ************** 11702905
[M::ha_hist_line]     6: ********** 8172160
[M::ha_hist_line]     7: ************ 9716668
[M::ha_hist_line]     8: ****************** 14550334
[M::ha_hist_line]     9: *************************** 22255587
[M::ha_hist_line]    10: **************************************** 32520388
[M::ha_hist_line]    11: ****************************************************** 44243006
[M::ha_hist_line]    12: ********************************************************************* 56566469
[M::ha_hist_line]    13: *********************************************************************************** 67996039
[M::ha_hist_line]    14: ********************************************************************************************* 76639176
[M::ha_hist_line]    15: **************************************************************************************************** 81650490
[M::ha_hist_line]    16: **************************************************************************************************** 82030387
[M::ha_hist_line]    17: ************************************************************************************************ 78519038
[M::ha_hist_line]    18: **************************************************************************************** 71841182
[M::ha_hist_line]    19: ***************************************************************************** 62845160
[M::ha_hist_line]    20: **************************************************************** 52805125
[M::ha_hist_line]    21: **************************************************** 42827933
[M::ha_hist_line]    22: ***************************************** 33880252
[M::ha_hist_line]    23: ******************************** 26288968
[M::ha_hist_line]    24: ************************* 20641304
[M::ha_hist_line]    25: ******************** 16556285
[M::ha_hist_line]    26: ***************** 13913931
[M::ha_hist_line]    27: *************** 12533038
[M::ha_hist_line]    28: ************** 11839771
[M::ha_hist_line]    29: ************** 11530672
[M::ha_hist_line]    30: ************** 11573873
[M::ha_hist_line]    31: ************** 11554786
[M::ha_hist_line]    32: ************** 11515436
[M::ha_hist_line]    33: ************** 11278994
[M::ha_hist_line]    34: ************* 10894043
[M::ha_hist_line]    35: ************* 10341461
[M::ha_hist_line]    36: ************ 9567265
[M::ha_hist_line]    37: *********** 8695235
[M::ha_hist_line]    38: ********** 7795634
[M::ha_hist_line]    39: ******** 6852468
[M::ha_hist_line]    40: ******* 5949327
[M::ha_hist_line]    41: ****** 5033021
[M::ha_hist_line]    42: ***** 4257624
[M::ha_hist_line]    43: **** 3601734
[M::ha_hist_line]    44: **** 3018617
[M::ha_hist_line]    45: *** 2543151
[M::ha_hist_line]    46: *** 2136988
[M::ha_hist_line]    47: ** 1815608
[M::ha_hist_line]    48: ** 1590298
[M::ha_hist_line]    49: ** 1377571
[M::ha_hist_line]    50: * 1224353
[M::ha_hist_line]    51: * 1086614
[M::ha_hist_line]    52: * 996807
[M::ha_hist_line]    53: * 913449
[M::ha_hist_line]    54: * 867606
[M::ha_hist_line]    55: * 801406
[M::ha_hist_line]    56: * 751187
[M::ha_hist_line]    57: * 709351
[M::ha_hist_line]    58: * 674812
[M::ha_hist_line]    59: * 639595
[M::ha_hist_line]    60: * 607773
[M::ha_hist_line]    61: * 585141
[M::ha_hist_line]    62: * 557620
[M::ha_hist_line]    63: * 536691
[M::ha_hist_line]    64: * 520219
[M::ha_hist_line]    65: * 505957
[M::ha_hist_line]    66: * 489982
[M::ha_hist_line]    67: * 469387
[M::ha_hist_line]    68: * 460654
[M::ha_hist_line]    69: * 444635
[M::ha_hist_line]    70: * 430740
[M::ha_hist_line]    71: * 415882
[M::ha_hist_line]  rest: ************************** 21369902
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_ft_gen] peak_hom: 16; peak_het: -1
[M::ha_ct_shrink::753.682*9.05] ==> counted 18503479 distinct minimizer k-mers
[M::ha_ft_gen::762.634*8.95@33.149GB] ==> filtered out 18503479 k-mers occurring 80 or more times
[M::ha_opt_update_cov] updated max_n_chain to 100
[M::yak_count] collected 677559156 minimizers
[M::yak_count] collected 555935884 minimizers
[M::ha_pt_gen::1363.596*7.88] ==> counted 148868405 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[6] = 450700
[M::ha_analyze_count] highest: count[15] = 3979651
[M::ha_hist_line]     1: ****************************************************************************************************> 75643470
[M::ha_hist_line]     2: ****************************************************************************************************> 12918904
[M::ha_hist_line]     3: ******************************************************************************************** 3664192
[M::ha_hist_line]     4: ******************************** 1264014
[M::ha_hist_line]     5: ************** 576503
[M::ha_hist_line]     6: *********** 450700
[M::ha_hist_line]     7: ************** 540662
[M::ha_hist_line]     8: ******************** 780241
[M::ha_hist_line]     9: ***************************** 1157070
[M::ha_hist_line]    10: ****************************************** 1655725
[M::ha_hist_line]    11: ******************************************************** 2221891
[M::ha_hist_line]    12: *********************************************************************** 2815634
[M::ha_hist_line]    13: ************************************************************************************ 3351710
[M::ha_hist_line]    14: ********************************************************************************************** 3757076
[M::ha_hist_line]    15: **************************************************************************************************** 3979651
[M::ha_hist_line]    16: **************************************************************************************************** 3977280
[M::ha_hist_line]    17: *********************************************************************************************** 3791414
[M::ha_hist_line]    18: *************************************************************************************** 3459817
[M::ha_hist_line]    19: **************************************************************************** 3014212
[M::ha_hist_line]    20: **************************************************************** 2529876
[M::ha_hist_line]    21: **************************************************** 2050878
[M::ha_hist_line]    22: ***************************************** 1623265
[M::ha_hist_line]    23: ******************************** 1265502
[M::ha_hist_line]    24: ************************* 1001058
[M::ha_hist_line]    25: ******************** 808625
[M::ha_hist_line]    26: ***************** 685050
[M::ha_hist_line]    27: **************** 621053
[M::ha_hist_line]    28: *************** 586303
[M::ha_hist_line]    29: ************** 571054
[M::ha_hist_line]    30: ************** 569735
[M::ha_hist_line]    31: ************** 566772
[M::ha_hist_line]    32: ************** 563020
[M::ha_hist_line]    33: ************** 547856
[M::ha_hist_line]    34: ************* 528654
[M::ha_hist_line]    35: ************* 499855
[M::ha_hist_line]    36: ************ 462742
[M::ha_hist_line]    37: *********** 422960
[M::ha_hist_line]    38: ********** 380293
[M::ha_hist_line]    39: ******** 337802
[M::ha_hist_line]    40: ******* 295864
[M::ha_hist_line]    41: ****** 256933
[M::ha_hist_line]    42: ****** 222827
[M::ha_hist_line]    43: ***** 193874
[M::ha_hist_line]    44: **** 168262
[M::ha_hist_line]    45: **** 148139
[M::ha_hist_line]    46: *** 130902
[M::ha_hist_line]    47: *** 116406
[M::ha_hist_line]    48: *** 106325
[M::ha_hist_line]    49: ** 96905
[M::ha_hist_line]    50: ** 90089
[M::ha_hist_line]    51: ** 82283
[M::ha_hist_line]    52: ** 77162
[M::ha_hist_line]    53: ** 72163
[M::ha_hist_line]    54: ** 68419
[M::ha_hist_line]    55: ** 64216
[M::ha_hist_line]    56: ** 61109
[M::ha_hist_line]    57: * 57894
[M::ha_hist_line]    58: * 54690
[M::ha_hist_line]    59: * 52587
[M::ha_hist_line]    60: * 50403
[M::ha_hist_line]    61: * 48031
[M::ha_hist_line]    62: * 45880
[M::ha_hist_line]    63: * 44005
[M::ha_hist_line]    64: * 42430
[M::ha_hist_line]    65: * 40596
[M::ha_hist_line]    66: * 39279
[M::ha_hist_line]    67: * 37509
[M::ha_hist_line]    68: * 36049
[M::ha_hist_line]    69: * 34674
[M::ha_hist_line]    70: * 33146
[M::ha_hist_line]    71: * 32123
[M::ha_hist_line]    72: * 30832
[M::ha_hist_line]    73: * 29624
[M::ha_hist_line]    74: * 28601
[M::ha_hist_line]    75: * 27551
[M::ha_hist_line]    76: * 26755
[M::ha_hist_line]    77: * 25434
[M::ha_hist_line]    78: * 23558
[M::ha_hist_line]  rest: *** 132357
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 15; peak_het: -1
[M::ha_ct_shrink::1363.820*7.89] ==> counted 73224935 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 1233495040 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::1547.559*9.21] ==> indexed 1157851570 positions, counted 73224935 distinct minimizer k-mers
[M::ha_assemble::3107.498*24.56@33.149GB] ==> corrected reads for round 1
[M::ha_assemble] # bases: 43692969185; # corrected bases: 65545497; # recorrected bases: 80209
[M::ha_assemble] size of buffer: 8.670GB
[M::yak_count] collected 1230819267 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::3253.772*24.45] ==> counted 133123573 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[6] = 429059
[M::ha_analyze_count] highest: count[16] = 3964939
[M::ha_hist_line]     1: ****************************************************************************************************> 60396761
[M::ha_hist_line]     2: ****************************************************************************************************> 12552405
[M::ha_hist_line]     3: ***************************************************************************************** 3540772
[M::ha_hist_line]     4: ******************************** 1274716
[M::ha_hist_line]     5: ************** 573163
[M::ha_hist_line]     6: *********** 429059
[M::ha_hist_line]     7: ************* 503724
[M::ha_hist_line]     8: ****************** 725951
[M::ha_hist_line]     9: *************************** 1077424
[M::ha_hist_line]    10: *************************************** 1550797
[M::ha_hist_line]    11: ***************************************************** 2099317
[M::ha_hist_line]    12: ******************************************************************** 2685167
[M::ha_hist_line]    13: ********************************************************************************** 3237599
[M::ha_hist_line]    14: ******************************************************************************************** 3656289
[M::ha_hist_line]    15: *************************************************************************************************** 3921354
[M::ha_hist_line]    16: **************************************************************************************************** 3964939
[M::ha_hist_line]    17: ************************************************************************************************ 3816470
[M::ha_hist_line]    18: ***************************************************************************************** 3520074
[M::ha_hist_line]    19: ****************************************************************************** 3102072
[M::ha_hist_line]    20: ****************************************************************** 2625821
[M::ha_hist_line]    21: ****************************************************** 2145243
[M::ha_hist_line]    22: ******************************************* 1711324
[M::ha_hist_line]    23: ********************************** 1334265
[M::ha_hist_line]    24: *************************** 1051970
[M::ha_hist_line]    25: ********************* 839397
[M::ha_hist_line]    26: ****************** 701690
[M::ha_hist_line]    27: **************** 623733
[M::ha_hist_line]    28: *************** 584555
[M::ha_hist_line]    29: ************** 564165
[M::ha_hist_line]    30: ************** 561626
[M::ha_hist_line]    31: ************** 560821
[M::ha_hist_line]    32: ************** 560933
[M::ha_hist_line]    33: ************** 548890
[M::ha_hist_line]    34: ************* 533483
[M::ha_hist_line]    35: ************* 510353
[M::ha_hist_line]    36: ************ 474912
[M::ha_hist_line]    37: *********** 437134
[M::ha_hist_line]    38: ********** 396135
[M::ha_hist_line]    39: ********* 354248
[M::ha_hist_line]    40: ******** 311997
[M::ha_hist_line]    41: ******* 273658
[M::ha_hist_line]    42: ****** 234848
[M::ha_hist_line]    43: ***** 205543
[M::ha_hist_line]    44: ***** 178592
[M::ha_hist_line]    45: **** 155778
[M::ha_hist_line]    46: *** 137147
[M::ha_hist_line]    47: *** 121622
[M::ha_hist_line]    48: *** 109906
[M::ha_hist_line]    49: *** 100445
[M::ha_hist_line]    50: ** 92901
[M::ha_hist_line]    51: ** 84955
[M::ha_hist_line]    52: ** 79603
[M::ha_hist_line]    53: ** 74244
[M::ha_hist_line]    54: ** 69889
[M::ha_hist_line]    55: ** 66040
[M::ha_hist_line]    56: ** 62674
[M::ha_hist_line]    57: * 59059
[M::ha_hist_line]    58: * 55995
[M::ha_hist_line]    59: * 53375
[M::ha_hist_line]    60: * 50919
[M::ha_hist_line]    61: * 48448
[M::ha_hist_line]    62: * 46959
[M::ha_hist_line]    63: * 44770
[M::ha_hist_line]    64: * 42602
[M::ha_hist_line]    65: * 40891
[M::ha_hist_line]    66: * 40169
[M::ha_hist_line]    67: * 38858
[M::ha_hist_line]    68: * 36954
[M::ha_hist_line]    69: * 35323
[M::ha_hist_line]    70: * 33833
[M::ha_hist_line]    71: * 32381
[M::ha_hist_line]    72: * 32219
[M::ha_hist_line]    73: * 30342
[M::ha_hist_line]    74: * 29096
[M::ha_hist_line]    75: * 27914
[M::ha_hist_line]    76: * 27076
[M::ha_hist_line]    77: * 26554
[M::ha_hist_line]    78: * 24684
[M::ha_hist_line]    79: * 22463
[M::ha_hist_line]  rest: *** 134096
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 16; peak_het: -1
[M::ha_ct_shrink::3254.032*24.45] ==> counted 72726812 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 1230819267 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::3446.544*24.10] ==> indexed 1170422506 positions, counted 72726812 distinct minimizer k-mers
[M::ha_assemble::4826.518*28.57@43.953GB] ==> corrected reads for round 2
[M::ha_assemble] # bases: 43681092725; # corrected bases: 1301356; # recorrected bases: 40015
[M::ha_assemble] size of buffer: 8.546GB
[M::yak_count] collected 1230688192 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::4964.091*28.43] ==> counted 132880522 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[6] = 429056
[M::ha_analyze_count] highest: count[16] = 3965085
[M::ha_hist_line]     1: ****************************************************************************************************> 60190455
[M::ha_hist_line]     2: ****************************************************************************************************> 12525197
[M::ha_hist_line]     3: ***************************************************************************************** 3527904
[M::ha_hist_line]     4: ******************************** 1276731
[M::ha_hist_line]     5: *************** 576822
[M::ha_hist_line]     6: *********** 429056
[M::ha_hist_line]     7: ************* 503170
[M::ha_hist_line]     8: ****************** 723936
[M::ha_hist_line]     9: *************************** 1076318
[M::ha_hist_line]    10: *************************************** 1549737
[M::ha_hist_line]    11: ***************************************************** 2098322
[M::ha_hist_line]    12: ******************************************************************** 2684667
[M::ha_hist_line]    13: ********************************************************************************** 3236625
[M::ha_hist_line]    14: ******************************************************************************************** 3654950
[M::ha_hist_line]    15: *************************************************************************************************** 3922023
[M::ha_hist_line]    16: **************************************************************************************************** 3965085
[M::ha_hist_line]    17: ************************************************************************************************ 3816073
[M::ha_hist_line]    18: ***************************************************************************************** 3520297
[M::ha_hist_line]    19: ****************************************************************************** 3102954
[M::ha_hist_line]    20: ****************************************************************** 2626468
[M::ha_hist_line]    21: ****************************************************** 2145889
[M::ha_hist_line]    22: ******************************************* 1711834
[M::ha_hist_line]    23: ********************************** 1334484
[M::ha_hist_line]    24: *************************** 1051899
[M::ha_hist_line]    25: ********************* 839824
[M::ha_hist_line]    26: ****************** 702125
[M::ha_hist_line]    27: **************** 623858
[M::ha_hist_line]    28: *************** 584099
[M::ha_hist_line]    29: ************** 563851
[M::ha_hist_line]    30: ************** 561563
[M::ha_hist_line]    31: ************** 560971
[M::ha_hist_line]    32: ************** 561031
[M::ha_hist_line]    33: ************** 548857
[M::ha_hist_line]    34: ************* 533492
[M::ha_hist_line]    35: ************* 510325
[M::ha_hist_line]    36: ************ 474940
[M::ha_hist_line]    37: *********** 437792
[M::ha_hist_line]    38: ********** 396214
[M::ha_hist_line]    39: ********* 354135
[M::ha_hist_line]    40: ******** 312202
[M::ha_hist_line]    41: ******* 273085
[M::ha_hist_line]    42: ****** 235091
[M::ha_hist_line]    43: ***** 205642
[M::ha_hist_line]    44: ***** 178672
[M::ha_hist_line]    45: **** 155796
[M::ha_hist_line]    46: *** 137349
[M::ha_hist_line]    47: *** 121523
[M::ha_hist_line]    48: *** 110049
[M::ha_hist_line]    49: *** 100163
[M::ha_hist_line]    50: ** 93144
[M::ha_hist_line]    51: ** 84854
[M::ha_hist_line]    52: ** 79791
[M::ha_hist_line]    53: ** 73976
[M::ha_hist_line]    54: ** 69885
[M::ha_hist_line]    55: ** 65763
[M::ha_hist_line]    56: ** 62835
[M::ha_hist_line]    57: * 59211
[M::ha_hist_line]    58: * 55973
[M::ha_hist_line]    59: * 53416
[M::ha_hist_line]    60: * 51093
[M::ha_hist_line]    61: * 48486
[M::ha_hist_line]    62: * 46994
[M::ha_hist_line]    63: * 44851
[M::ha_hist_line]    64: * 42845
[M::ha_hist_line]    65: * 40717
[M::ha_hist_line]    66: * 40251
[M::ha_hist_line]    67: * 38706
[M::ha_hist_line]    68: * 37103
[M::ha_hist_line]    69: * 35255
[M::ha_hist_line]    70: * 33852
[M::ha_hist_line]    71: * 32416
[M::ha_hist_line]    72: * 32188
[M::ha_hist_line]    73: * 30342
[M::ha_hist_line]    74: * 28961
[M::ha_hist_line]    75: * 27966
[M::ha_hist_line]    76: * 27312
[M::ha_hist_line]    77: * 26596
[M::ha_hist_line]    78: * 24740
[M::ha_hist_line]    79: * 22555
[M::ha_hist_line]  rest: *** 134900
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 16; peak_het: -1
[M::ha_ct_shrink::4964.318*28.43] ==> counted 72690067 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 1230688192 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::5142.206*28.12] ==> indexed 1170497737 positions, counted 72690067 distinct minimizer k-mers
[M::ha_assemble::6523.439*30.58@55.164GB] ==> corrected reads for round 3
[M::ha_assemble] # bases: 43680652600; # corrected bases: 360071; # recorrected bases: 24735
[M::ha_assemble] size of buffer: 8.520GB
[M::yak_count] collected 1230641673 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::6675.641*30.37] ==> counted 132813633 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[6] = 428599
[M::ha_analyze_count] highest: count[16] = 3964926
[M::ha_hist_line]     1: ****************************************************************************************************> 60139679
[M::ha_hist_line]     2: ****************************************************************************************************> 12515646
[M::ha_hist_line]     3: ***************************************************************************************** 3523367
[M::ha_hist_line]     4: ******************************** 1275830
[M::ha_hist_line]     5: *************** 577164
[M::ha_hist_line]     6: *********** 428599
[M::ha_hist_line]     7: ************* 502940
[M::ha_hist_line]     8: ****************** 723789
[M::ha_hist_line]     9: *************************** 1075937
[M::ha_hist_line]    10: *************************************** 1549484
[M::ha_hist_line]    11: ***************************************************** 2098016
[M::ha_hist_line]    12: ******************************************************************** 2684457
[M::ha_hist_line]    13: ********************************************************************************** 3236604
[M::ha_hist_line]    14: ******************************************************************************************** 3654547
[M::ha_hist_line]    15: *************************************************************************************************** 3921944
[M::ha_hist_line]    16: **************************************************************************************************** 3964926
[M::ha_hist_line]    17: ************************************************************************************************ 3816134
[M::ha_hist_line]    18: ***************************************************************************************** 3520327
[M::ha_hist_line]    19: ****************************************************************************** 3102970
[M::ha_hist_line]    20: ****************************************************************** 2626478
[M::ha_hist_line]    21: ****************************************************** 2145998
[M::ha_hist_line]    22: ******************************************* 1712087
[M::ha_hist_line]    23: ********************************** 1334508
[M::ha_hist_line]    24: *************************** 1051836
[M::ha_hist_line]    25: ********************* 839933
[M::ha_hist_line]    26: ****************** 702249
[M::ha_hist_line]    27: **************** 623735
[M::ha_hist_line]    28: *************** 584049
[M::ha_hist_line]    29: ************** 563778
[M::ha_hist_line]    30: ************** 561623
[M::ha_hist_line]    31: ************** 560928
[M::ha_hist_line]    32: ************** 561006
[M::ha_hist_line]    33: ************** 548882
[M::ha_hist_line]    34: ************* 533469
[M::ha_hist_line]    35: ************* 510352
[M::ha_hist_line]    36: ************ 474929
[M::ha_hist_line]    37: *********** 437847
[M::ha_hist_line]    38: ********** 396279
[M::ha_hist_line]    39: ********* 354080
[M::ha_hist_line]    40: ******** 312308
[M::ha_hist_line]    41: ******* 273088
[M::ha_hist_line]    42: ****** 235056
[M::ha_hist_line]    43: ***** 205678
[M::ha_hist_line]    44: ***** 178700
[M::ha_hist_line]    45: **** 155748
[M::ha_hist_line]    46: *** 137381
[M::ha_hist_line]    47: *** 121492
[M::ha_hist_line]    48: *** 110068
[M::ha_hist_line]    49: *** 100155
[M::ha_hist_line]    50: ** 93147
[M::ha_hist_line]    51: ** 84902
[M::ha_hist_line]    52: ** 79801
[M::ha_hist_line]    53: ** 73938
[M::ha_hist_line]    54: ** 69911
[M::ha_hist_line]    55: ** 65786
[M::ha_hist_line]    56: ** 62761
[M::ha_hist_line]    57: * 59226
[M::ha_hist_line]    58: * 56071
[M::ha_hist_line]    59: * 53420
[M::ha_hist_line]    60: * 51070
[M::ha_hist_line]    61: * 48511
[M::ha_hist_line]    62: * 47003
[M::ha_hist_line]    63: * 44710
[M::ha_hist_line]    64: * 42863
[M::ha_hist_line]    65: * 40718
[M::ha_hist_line]    66: * 40237
[M::ha_hist_line]    67: * 38731
[M::ha_hist_line]    68: * 37150
[M::ha_hist_line]    69: * 35273
[M::ha_hist_line]    70: * 33821
[M::ha_hist_line]    71: * 32442
[M::ha_hist_line]    72: * 32230
[M::ha_hist_line]    73: * 30332
[M::ha_hist_line]    74: * 28953
[M::ha_hist_line]    75: * 27963
[M::ha_hist_line]    76: * 27257
[M::ha_hist_line]    77: * 26677
[M::ha_hist_line]    78: * 24779
[M::ha_hist_line]    79: * 22595
[M::ha_hist_line]  rest: *** 135275
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 16; peak_het: -1
[M::ha_ct_shrink::6675.822*30.37] ==> counted 72673954 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 1230641673 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::6869.520*30.02] ==> indexed 1170501994 positions, counted 72673954 distinct minimizer k-mers
[M::ha_assemble::7353.247*30.57@58.178GB] ==> found overlaps for the final round
[M::ha_print_ovlp_stat] # overlaps: 151114802
[M::ha_print_ovlp_stat] # strong overlaps: 40118644
[M::ha_print_ovlp_stat] # weak overlaps: 110996158
[M::ha_print_ovlp_stat] # exact overlaps: 145937125
[M::ha_print_ovlp_stat] # inexact overlaps: 5177677
[M::ha_print_ovlp_stat] # overlaps without large indels: 150890619
[M::ha_print_ovlp_stat] # reverse overlaps: 25154652
Writing reads to disk... 
Reads has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
bin files have been written.
[M::purge_dups] homozygous read coverage threshold: 32
[M::purge_dups] purge duplication coverage threshold: 40
Writing raw unitig GFA to disk... 
Writing processed unitig GFA to disk... 
[M::purge_dups] homozygous read coverage threshold: 32
[M::purge_dups] purge duplication coverage threshold: 40
[M::mc_solve_core::0.224] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [27, infinity]
Writing primary contig GFA to disk... 
Writing alternate contig GFA to disk... 
Inconsistency threshold for low-quality regions in BED files: 70%
[M::main] Version: 0.16.1-r375
[M::main] CMD: hifiasm -o BF05.asm --primary -t 40 /work/soghigian_lab/data/pacbio/maryland1/BF05/XAGSY_20211214_S64049_PL100219968-1_B01.ccs.fastq.gz /work/soghigian_lab/data/pacbio/maryland1/BF05/XAGSY_20211230_S64018_PL100219968-1_A01.ccs.fastq.gz
[M::main] Real time: 7841.055 sec; CPU: 225599.574 sec; Peak RSS: 58.178 GB

**Comment by chhylp123** [comment]
Actually this is a good question, and I should add it to FAQs. If your sample is diploid, I guess the heterozygous coverage and the homozygous coverage should be around 16 and 32, respectively. Probably because the heterozygosity of your sample is high, hifiasm only found one coverage peak around 16, and misidentified it as homozygous coverage peak (thus `peak_het=-1` and `peak_hom=16`). The wrong peak_hom will affect the overlap calculation, as hifiasm will check up to `peak_hom*(-D)` overlaps for each read during correction. So there are two solutions: a) double the option `-D` from 5 (default) to 10; b) set correct value for `--hg-size`.

**Comment by genmor** [comment]
Just as a quick follow-up, setting -D to 10 did not resolve my peak_het=-1 issue, but specifying --hg-size did identify the peaks correctly.  Thanks again for your help!

**Comment by qdu-beep** [comment]
> Actually this is a good question (but not a big deal), and I should add it to FAQs. If your sample is diploid, I guess the heterozygous coverage and the homozygous coverage should be around 16 and 32, respectively. Probably because the heterozygosity of your sample is high, hifiasm only found one coverage peak around 16, and misidentified it as homozygous coverage peak (thus `peak_het=-1` and `peak_hom=16`). The wrong peak_hom will affect the overlap calculation, as hifiasm will check up to `peak_hom*(-D)` overlaps for each read during correction. So there are two solutions: a) double the option `-D` from 5 (default) to 10; b) set correct value for `--hg-size`.
Hello, by setting "--purge-cov" to the position of the heterozygous peak of the kmer diagram in the log file (the upper position in the diagram), can you solve the problem of hifiasm misidentifying the heterozygous peak and the homozygous peak (het_peak :-1)? I saw your answer at that time in a previous issue and I was a little confused. thanks for your help!
“You can manually set hom peak by '--purge-cov'. It is hard for hifiasm to get right peak in this case. Please note it just affects phasing and graph cleaning, so that no need to run the whole assembly workflow.”
from https://github.com/chhylp123/hifiasm/issues/78#issuecomment-822143133

**Comment by qdu-beep** [comment]
> Actually this is a good question (but not a big deal), and I should add it to FAQs. If your sample is diploid, I guess the heterozygous coverage and the homozygous coverage should be around 16 and 32, respectively. Probably because the heterozygosity of your sample is high, hifiasm only found one coverage peak around 16, and misidentified it as homozygous coverage peak (thus `peak_het=-1` and `peak_hom=16`). The wrong peak_hom will affect the overlap calculation, as hifiasm will check up to `peak_hom*(-D)` overlaps for each read during correction. So there are two solutions: a) double the option `-D` from 5 (default) to 10; b) set correct value for `--hg-size`.

Hello, by setting "--purge-cov" to the position of the heterozygous peak of the kmer diagram in the log file (the upper position in the diagram), can you solve the problem of hifiasm misidentifying the heterozygous peak and the homozygous peak (het_peak :-1)? 
I saw your answer at that time in a previous issue and I was a little confused. thanks for your help!
“You can manually set hom peak by '--purge-cov'. It is hard for hifiasm to get right peak in this case. Please note it just affects phasing and graph cleaning, so that no need to run the whole assembly workflow.”
from https://github.com/chhylp123/hifiasm/issues/78#issuecomment-822143133

**Comment by qdu-beep** [comment]
> Just as a quick follow-up, setting -D to 10 did not resolve my peak_het=-1 issue, but specifying --hg-size did identify the peaks correctly. Thanks again for your help!

Hello, how did you get the value of --hg-size (estimated haploid genome size used for inferring read coverage)? Is it obtained through genome survey analysis?

**Comment by genmor** [comment]
> > Just as a quick follow-up, setting -D to 10 did not resolve my peak_het=-1 issue, but specifying --hg-size did identify the peaks correctly. Thanks again for your help!
> 
> Hello, how did you get the value of --hg-size (estimated haploid genome size used for inferring read coverage)? Is it obtained through genome survey analysis?

Flow cytometry or using kmer based estimation. There's also a database (https://www.genomesize.com/) for animals if that's what you have.

**Comment by qdu-beep** [comment]
> > > Just as a quick follow-up, setting -D to 10 did not resolve my peak_het=-1 issue, but specifying --hg-size did identify the peaks correctly. Thanks again for your help!
> > 
> > 
> > Hello, how did you get the value of --hg-size (estimated haploid genome size used for inferring read coverage)? Is it obtained through genome survey analysis?
> 
> Flow cytometry or using kmer based estimation. There's also a database (https://www.genomesize.com/) for animals if that's what you have.

Thanks fou your reply! It helps me a lot!
