### ISSUE TITLE
How can I set stricter parameters if I think the contig is too long to contain misassembly

### ISSUE THREAD

**Issue by lizhao007** [chhylp123/hifiasm#255]
Thanks for the author's contribution. 
How can I set stricter parameters if there may be misassembled contigs with default parameters?

**Comment by lizhao007** [comment]
> What do you mean by "error contigs"?

After using hifiasm, I get the result as below, contig is less and longer.
<img width="480" alt="图片1" src="https://user-images.githubusercontent.com/36907006/156087492-01a7927b-65e2-4505-9c3c-0563809efd57.png">

ALLHiC was used for further assembly and showed many abnormal interactions as follows. 
[500K_Whole_genome.pdf](https://github.com/chhylp123/hifiasm/files/8158256/500K_Whole_genome.pdf)

After searching on the Internet, maybe errors occurred in the contig assembly.

**Comment by lh3** [comment]
I still don't know what "errors" you are referring to.

**Comment by lizhao007** [comment]
> I still don't know what "errors" you are referring to.

I'm sorry for my inappropriate word. In fact, when I get the abnormal interactions from ALLHIC and find the contig is long, I think there may be misassembly within a single contig. So I want to set stricter parameters with hifiasm to compare the results.

**Comment by chhylp123** [comment]
See FAQ here: https://hifiasm.readthedocs.io/en/latest/faq.html#how-do-i-avoid-misassemblies. But I'm not sure if your assemblies actually have misassemblies.

**Comment by lizhao007** [comment]
> See FAQ here: https://hifiasm.readthedocs.io/en/latest/faq.html#how-do-i-avoid-misassemblies. But I'm not sure if your assemblies actually have misassemblies.

Thank you for your suggestion.  In fact, I tried different parameters like --hom-cov, --purge-max and -s, but couldn't figure out which was the best. So maybe I should ask how to determine the accuracy of the assembled contigs and choose the best assembly.

**Comment by chhylp123** [comment]
Probably you could also try `-u`. It is hard to say how to determine the best parameters. But from the Hi-C plot, looks like there are not too many misassemblies (please note that some ambiguous regions in Hi-C plot might not be the real misassemblies), so that you can manually fix them.

**Comment by lizhao007** [comment]
Thanks. Do you have any suggested software for the following assembly after hifiasm?

**Comment by chhylp123** [comment]
Are you using hic phased assemblies?

**Comment by lizhao007** [comment]
Yes, the picture above is the result of hifiasm with both hifi reads and HiC reads



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 3, 2022 12:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chhylp123/hifiasm] How can I set stricter parameters if I thinkthe contig is too long to contain misassembly (Issue #255)




 
Are you using hic phased assemblies?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chhylp123** [comment]
Probably you could follow the blog here: https://github.com/baozg/phased-assembly-check. I think it is reasonable, especially for Hi-C phased assemblies.

**Comment by lizhao007** [comment]
Thanks a lot!
