### ISSUE TITLE
Clarifying the meaning of the number in the fourth column of *lowQ.bed files

### ISSUE THREAD

**Issue by 21hyin** [chhylp123/hifiasm#256]
Example of `*lowQ.bed` file with number in fourth column between asterisks:
```
ptg000001l	0	2361	*100*	m64139_220121_190216/175047009/ccs,m64139_220118_184546/119341498/ccs,m64139_220118_184546/170657730/ccs
ptg000001l	1023522	1024637	*100*	m64139_220118_184546/113707639/ccs,m64139_220121_190216/144508907/ccs
ptg000002l	0	4284	*90*	m64139_220120_021028/108135356/ccs,m64139_220118_184546/54921570/ccs,m64139_220118_184546/122618710/ccs
```
The maximum value of this fourth number in hifiasm's output that I'm getting seems to be 100. If the numbers in the second and third columns are start and end positions, is the fourth number a score? But the [BED format documentation](https://genome.ucsc.edu/FAQ/FAQformat.html#format1) says that scores have range 0-1000, so is the fourth number a percentage based on the score?

**Comment by chhylp123** [comment]
Yes, it is the percentage, indicating how reliable the corresponding region is.

**Comment by 21hyin** [comment]
Thank you--so the higher the percentage, the more reliable the region (while keeping in mind that all output in this file is still "low quality", or has more inconsistencies relative to other regions not listed in this file)?

**Comment by 21hyin** [comment]
Thanks for confirming!
