### ISSUE TITLE
ERROR-r-break ERROR-read when using Hi-C data

### ISSUE THREAD

**Issue by peterdfields** [chhylp123/hifiasm#257]
Hi,

I'm trying to assemble a fairly heterozygous plant genome. I wanted to try using Hi-C data to possibly resolve individual haplotypes more clearly but my initial results do not look so promising. I noticed the following in the log:

```
[M::load_hc_hits::] ==> Hi-C linkages have been loaded
[M::mc_solve_core::0.039] ==> Partition
ERROR-r-break
ERROR-read
[M::dedup_hits::8.484] ==> Dedup
[M::stat] # misjoined unitigs: 7 (N50: 923135); # corrected unitigs: 14 (N50: 524431)
[M::adjust_weight_kv_u_trans_advance::0.368]
[M::mb_solve_core::3.745] ==> Partition
[M::mc_solve_core::1.959] ==> Partition
[M::adjust_weight_kv_u_trans_advance::0.409]
[M::mb_solve_core::3.763] ==> Partition
[M::mc_solve_core::1.946] ==> Partition
[M::adjust_weight_kv_u_trans_advance::0.853]
[M::mb_solve_core::3.844] ==> Partition
[M::mc_solve_core::1.965] ==> Partition
[M::stat] # heterozygous bases: 1221416508; # homozygous bases: 486281909
[M::reduce_hamming_error::0.657] # inserted edges: 2, # fixed bubbles: 2
[M::adjust_utg_by_trio] primary contig coverage range: [45, infinity]
Writing hi-c.asm.hic.hap1.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [45, infinity]
Writing hi-c.asm.hic.hap2.p_ctg.gfa to disk...
Inconsistency threshold for low-quality regions in BED files: 70%
```

I also noticed in the two haplotype outputs that one of them is about 1/3 the size of the second. Could the `ERROR-r-break ERROR-read` suggest a failure of the Hi-C step?

Please let me know if any additional information would be helpful.

**Comment by chhylp123** [comment]
It is a warning, which does not matter too much. If your Hi-C phased assemblies are not such good, you can have a look at this FAQ: https://hifiasm.readthedocs.io/en/latest/faq.html#how-can-i-tweak-parameters-to-improve-hi-c-integrated-assembly.

**Comment by peterdfields** [comment]
thank you @chhylp123 I'll have a closer look at these recommendations.
