### ISSUE TITLE
when align the CCS reads to hifiasm result by using minimap2, Approximate per-base sequence divergence is very high

### ISSUE THREAD

**Issue by libenping** [chhylp123/hifiasm#26]
Hi,
     Recently I use hifiasm (0.8-r279) to assemble Redwood（data from ./ https://sra-download.ncbi.nlm.nih.gov/traces/sra34/SRR/010948/）with asm options -t 80. The result is 35G, and N50 5.4M.
     However,when I map the CCS reads to the assemble genome by using minimap2(  minimap2-2.17 (r941) ,  --secondary=no -x asm20), I find that almost evey ccs reads can align to several contigs，and dv are in the range of 0.1~0.2，similar with ONT alignment. 
    I think this phenomenon is abnormal，and actural I also  use minimap2 to map other ccs reads to there corresponding contigs(also assembled with hifiasm), the dv value are all about 0.005. So I want to know is there really something wrong happend? and can you give me some advice to avoid these phenomena ? Thank you!

**Comment by lh3** [comment]
With minimap2, you need to add option `-I60g`.

**Comment by chhylp123** [comment]
By the way, our latest version should be better than v0.8. The latest version can avoid some misassemblies. If you have v0.8 bin files, it is quite fast to rerun v0.11.

**Comment by libenping** [comment]
@lh3 I try to add the option -I60g.  Unfortunately,  now the max RAM of my cluster is 256G, and it is not enough to index the genome, so can you give me  some advices to reduce the required RAM?
@chhylp123 Thank you very much for your advice! Yeah, I have v0.8 bin files and I have tried to use the v0.11 to rerun it, however the required RAM also exceeds 256G.

**Comment by chhylp123** [comment]
256G is too small for redwood. Hifiasm needs about 700Gb RAM in this case.
