### ISSUE TITLE
Poor switch/hamming error rate on HG002

### ISSUE THREAD

**Issue by skoren** [chhylp123/hifiasm#262]
Hi,

I'm running hifiasm v0.16.1-r375 on HG002 DeepConsenus reads in trio mode. When I evaluate the assembly using merqury DBs, I get a high hamming rate (>20%). I know the parents are correct and trust the merqury DBs since they show reasonable results on other HG002 assemblies (e.g. the recent bakeoff ones). I've tried tweaking both the -c and -d parameters for hifiasm and yak trioeval. With some settings (-c 5 -d 25), yak trioeval does report a low hamming/switch error rate but the merqury evaluation never does, varying between the low to high 20% hamming error. I'd appreciate any suggestions on what I am doing wrong or what I parameters I can tweak.

Evaluation commands:
```
cat asm.dip.hap1.p_ctg.gfa |awk '{if (match($1, "^S")) { print ">"$2; print $3}}'|fold -c > trio.combined.fasta
cat asm.dip.hap2.p_ctg.gfa |awk '{if (match($1, "^S")) { print ">"$2; print $3}}'|fold -c >> trio.combined.fasta

yak trioeval -c 5 -d 25 pat.yak mat.yak trio.combined.fasta |tail -n 3
W       3466    1068979 0.003242
H       5479    1069533 0.005123
N       1012148 57498   0.053754

sh $MERQURY/trio/hap_blob.sh HG002.mat.hapmers.meryl/ HG002.pat.hapmers.meryl/ trio.combined.fasta assembly
sh $MERQURY/trio/hamming_error.sh assembly.hapmers.count trio.combined.fasta
Assembly        Hap1    Hap2    Hap1Error(%)    Hap2Error(%)    MajorHapError(%)
trio.combined   18619278        36883983        66.4537 33.5463 24.6926
```

The command:
```
#!/bin/bash

cores=32

yak count -k31 -b37 -t $cores -o pat.yak paternal/*.fastq.gz
yak count -k31 -b37 -t $cores -o mat.yak maternal/*.fastq.gz

hifiasm -o asm -t $cores -1 pat.yak -2 mat.yak ../../hifi/*.fastq.gz
```

The log:
[run.out.gz](https://github.com/chhylp123/hifiasm/files/8319066/run.out.gz)

The data I'm using:
HiFi:
https://storage.googleapis.com/brain-genomics/awcarroll/t2t/fastq/q20/m64011_190830_220126.Q20.fastq.gz
https://storage.googleapis.com/brain-genomics/awcarroll/t2t/fastq/q20/m64011_190901_095311.Q20.fastq.gz
https://storage.googleapis.com/brain-genomics/awcarroll/t2t/fastq/q20/m64012_190920_173625.Q20.fastq.gz
https://storage.googleapis.com/brain-genomics/awcarroll/t2t/fastq/q20/m64012_190921_234837.Q20.fastq.gz

Mother: https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG004_NA24143_mother/NIST_Illumina_2x250bps/reads/

Father: https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG003_NA24149_father/NIST_Illumina_2x250bps/reads/

Merqury DBs:
https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=publications/HG002_BAKEOFF_2021/HG002_Assessment/merqury/

Sorry for the long issue but I wanted to provide all data needed to reproduce. Apologies if I missed an open issue addressing this already.

**Comment by chhylp123** [comment]
I see. Let me check the data.

**Comment by skoren** [comment]
I suspected the issue was my yak DBs so I downloaded ones from here: https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=submissions/6040D518-FE32-4CEB-B55C-504A05E4D662--HG002_PARENTAL_YAKS/HG002_PARENTS_FULL/ and got good results. I noticed these are also much bigger than my yak DBs (GB vs <100mb for mine).

**Comment by chhylp123** [comment]
But the merqury is still not good enough, right?

**Comment by skoren** [comment]
No the merqury is OK, same as yak when I use the above yak DBs so the issue must be from how I had run yak.

**Comment by chhylp123** [comment]
Sorry, I previously thought you would like to let us check why the merqury and yak output different results... The yak DBs built with 30x short reads are often >20Gb. They should be more than 10Gb.  If you need any other support like separate Hi-C phasing, please let me know.

**Comment by chhylp123** [comment]
I guess the issue might be how do you feed fastq through a pipe. If you feed fastq through a pipe, you need to apply the pipe twice like:

>yak count -b37 -o count.yak <(zcat in.fastq.gz) <(zcat in.fastq.gz)

The first builds a bloom filter ('-b37'). The second pipe does the counting. If you directly feed fastq, then

> yak count -b37 -o count.yak in.fastq

**Comment by skoren** [comment]
I was passing a list of fastq.gz like this: `yak count -k31 -b37 -o mat.yak *.fastq.gz`, would that be the problem?

**Comment by lh3** [comment]
That does not work due to the way yak is implemented. You may use
```
yak count -k31 -b37 -o mat.yak <(zcat *.fastq.gz) <(zcat *.fastq.gz)
```

**Comment by skoren** [comment]
Thanks, I'll use the updated command. I'd suggest adding that info to the documentation since it's different from hifiasm's syntax and the current manual only lists how to run w/one input file.
