### ISSUE TITLE
Meaning of "-s"

### ISSUE THREAD

**Issue by shelkmike** [chhylp123/hifiasm#268]
According to the parameter reference (https://hifiasm.readthedocs.io/en/latest/parameter-reference.html), -s is the similarity threshold for duplicate haplotigs that should be purged. Could you please explain the algorithm behind the calculation of haplotig similarity?

**Comment by chhylp123** [comment]
Given a HiFi read, hifiasm could identify the cis overlaps and the trans overlaps. Cis overlaps are real overlaps from the same haplotype, while the trans overlaps are the overlaps between homologous reads. The similarity is determined by how many trans overlaps between contigs.

**Comment by shelkmike** [comment]
Thank you
