### ISSUE TITLE
Can I use canu trimmed reads as input for hifiasm?

### ISSUE THREAD

**Issue by lileiting** [chhylp123/hifiasm#27]
Hi,

**Canu** (<https://github.com/marbl/canu>) assemble a genome through three steps: **correct**, **trim** and **assemble**. The first step will generate a file called `correctedReads.fasta` and the second step will generate a file called `trimmedReads.fasta`. I am wondering, it is OK or accepatable to use the canu-generated trimmed reads as input for `hifiasm`?

I am asking this question because I want to assemble a genome using both the raw PacBio CLR reads and the PacBio HiFi reads. `Canu/HiCanu` did not work very well for this situation (a lower N50 length than two independent assemblies), so I would like to switch to `hifiasm` (the resulting assembly has a better N50 length than two independent assemblies). 

Leiting

**Comment by chhylp123** [comment]
I don't know. Maybe you can have a try. Generally integrating CLR reads, even corrected CLR reads, probably affect allele resolution and segdup resolution, losing the power of HiFi. I personally think a better solution is to assemble HiFi and CLR independently, and then use CLR assembly to fill the gap of HiFi assembly.

**Comment by lileiting** [comment]
Thanks, I will have a try.
