### ISSUE TITLE
unknown memory error

### ISSUE THREAD

**Issue by Overcraft90** [chhylp123/hifiasm#273]
Hi,

while I tried to run _**hifiasm**_ on a HPC cluster using both HiFi and Hi-C (see command below), I've been prompted with the following error:

> var/spool/slurmd/job3061503/slurm_script: line 15: 72907 Killed
> `./hifiasm -o $WORK/HG03492_proc -t 48 --h1 /g100_work/IscrC_PanSV/HG03492_proc/HiC/*_hic1.fastq.gz --h2 /g100_work/IscrC_PanSV/HG03492_proc/HiC/*_hic2.fastq.gz /g100_work/IscrC_PanSV/HG03492_proc/*.gz`
> slurmstepd: error: Detected 1 oom-kill event(s) in StepId=3061503.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

Now, it seems like something related to memory but I'm not sure. What I can say is that the HiFi reads sets are particularly big in size (e.g. ~130GB) and divided in three files. The Hi-C read sets are ~30GB but divided into 16 parts for both the R1 and the R2, which I carefully merged into single files for _hap1_ and _hap2_.

I'm launching the process on a single node (48 CPUs and 350GB of RAM) that could be the cause for this issue. However, until now all the _de novo_ assemblies of human genome have been successful, so I was wondering what might have caused this problem.

Thanks in advance.

**Comment by chhylp123** [comment]
Looks like there is not enough memory? Probably you could check it by `/usr/bin/time -v` or other similar command lines.

**Comment by Overcraft90** [comment]
Thanks a lot. 

I was wondering, based on those file sizes, how much memory would I need in order to get the process through? I mean could it be possible to launch it on multiple nodes?

**Comment by chhylp123** [comment]
No, hifiasm only supports the single-node model for now.

**Comment by Overcraft90** [comment]
Thanks again, I'll close the thread.
