### ISSUE TITLE
low coverage, unresolved haplotypes?

### ISSUE THREAD

**Issue by cistarsa** [chhylp123/hifiasm#274]
Hello and thanks for this nifty program, **big** fan! 

Anyway, I'm troubleshooting a HiFi assembly that is ~25% smaller than expected based on C-Value estimates, but similar to genomescope (have noticed issue267), and wondered if the coverage is attributed to this. The k-mer histogram from hifiasm does have two peaks, but they're not well resolved. Here're the log and fastq genomescope files, thank you!

![plot](https://user-images.githubusercontent.com/20863931/164167915-8978eb17-d504-4af6-b95b-4eae969a6932.png)
[hifi_Agr_420.log](https://github.com/chhylp123/hifiasm/files/8518996/hifi_Agr_420.log)

**Comment by chhylp123** [comment]
Thanks a lot. The coverage is a little bit low. The smaller size might also be caused by the internal purging of hifiasm. What if you disable the purging with `-l0`? But anyway get more coverage should be very helpful.

**Comment by cistarsa** [comment]
Gotcha, thank you! Do you think coverage is enough to purge_dups after, as
this stands what are the possible issues with using this assembly as the
reference?

 Frankly, the situation is that we’re comparing this result with an older
CLR assembly, with much better coverage. Some of the team are convinced the
hifi is the one to move forward with given much better qv, but I’m
reluctant given this much lower coverage and somewhat wonky buscos…yet the
sizes are actually similar enough and other metrics of quality are
comparable.

**Comment by cistarsa** [comment]
Thank you, that's really helpful!
