### ISSUE TITLE
Getting the full sequence of the alternate assembly

### ISSUE THREAD

**Issue by elcortegano** [chhylp123/hifiasm#278]
Hi,

I'd be interested into getting the full length sequence of the alternate assembly (i.e. including shared sequence with the primary contig) for variant calling (e.g. with [MUMandCo](https://github.com/SAMtoBAM/MUMandCo)). Is it possible to generate this expanded atlernate assembly?

Any other advice on calling heterozygote mutations from assemblies? I fear that if a structural variant (e.g. inversion) is resolved into the alternate assembly, using assembly-based calling methods just on the primary assembly data will miss that.

Thanks

**Comment by chhylp123** [comment]
For the diploid genome, you could have a try with `bp.hap1.gfa` and `bp.hap2.gfa`. They are the dual assemblies, both of them are as contiguous as the primary assembly. To call SV from genome assemblies, dipcall should be a choice: https://github.com/lh3/dipcall .

**Comment by elcortegano** [comment]
Thanks for the advice, I see these files are generated in a more recent version than the one I was using. Will try this way as well as dipcall.

Following this, my understanding is that if I were to build assembly graphs with minigraph to call heterozygote variants, I would also need to use `bp.hap1.gfa` as well as `bp.hap2.gfa` when creating the graph, is that right? Thanks!

**Comment by elcortegano** [comment]
I just tried to generate an assembly with hifiasm version `0.16.1-r375`. I was expecting the `bp.hap?.p_ctg.gfa` to be part of the output, but apparently, none was generated.

This is the command I run:

    hifiasm -o output -t32 -l0  files.fq  2>  output.log

These are the files generated:

```
output.bp.a_ctg.gfa
output.bp.a_ctg.lowQ.bed
output.bp.a_ctg.noseq.gfa
output.bp.p_ctg.gfa
output.bp.p_ctg.lowQ.bed
output.bp.p_ctg.noseq.gfa
output.bp.p_utg.gfa
output.bp.p_utg.lowQ.bed
output.bp.p_utg.noseq.gfa
output.bp.r_utg.gfa
output.bp.r_utg.lowQ.bed
output.bp.r_utg.noseq.gfa
output.ec.bin
output.ovlp.reverse.bin
output.ovlp.source.bin
```
Note that option `-l0` was included, but to my understanding, it should only affect the pruning. How can the `bp.hap1.gfa` and `bp.hap2.gfa` files be generated?

**Comment by chhylp123** [comment]
No, you should disable `-l0`. `bp.hap*` is generated with purging.

**Comment by elcortegano** [comment]
I see, this works perfectly, thanks again!
