### ISSUE TITLE
Duplicate GFA edges

### ISSUE THREAD

**Issue by asl** [chhylp123/hifiasm#280]
Hello

It seems there are duplicate edges in the produces GFA. What is the purpose of these?

E.g. if we'd take `sheepB.hifiasm-meta.a_ctg.gfa.gz` then we'll end with:

```
L       s0.ctg000590l   +       s0.ctg027907l   -       10632M  L1:i:29150
...
L       s0.ctg027907l   +       s0.ctg000590l   -       10637M  L1:i:14435
```

Note that overlaps are different as well which does look suspicious...

**Comment by chhylp123** [comment]
Is this the result of hifiasm-meta? If it is, probably you should open an issue here: https://github.com/xfengnefx/hifiasm-meta.
