### ISSUE TITLE
About polishing.

### ISSUE THREAD

**Issue by GRGong** [chhylp123/hifiasm#283]
In a recent study [https://doi.org/10.1093/bib/bbac146](url) ,  the authors found that the post-assembly correction process (pilon) improved hifiasm assembly quality. I wonder whether it is neccessary to use short reads to polish the result.

**Comment by chhylp123** [comment]
Probably not. The results look a little bit weird.

**Comment by GRGong** [comment]
OK, thanks for your quick reply!
