### ISSUE TITLE
Are regions present only by one haplotig homozygote?

### ISSUE THREAD

**Issue by elcortegano** [chhylp123/hifiasm#284]
After using hifiasm to generate partially-phased assemblies (the `bp.hap?.p_ctg.gfa` files), I am confused about regions where the assembly is apparently missing for one of the two assemblies.

For example, the region below shows two tracks in IGV, one for the `hap1` file and the other for `hap2`, but the track for `hap2` does not show the assembly:

![Screenshot from 2022-05-25 17-51-53](https://user-images.githubusercontent.com/57492899/170319223-87d5b5c8-4a58-4420-beec-b16ab925f80b.png)
 
Can be safely assumed that this happens because that region is homozygote? Other regions in the genome with no differences between `hap1` and `hap2` assemblies (i.e. homozygote) are shown in the two assemblies, so I am not sure how to interpret situations like the picture above.

Thanks

**Comment by chhylp123** [comment]
Could you please show the corresponding subregions in the assembly graph?

**Comment by elcortegano** [comment]
The example above is for the assembly converted into fasta format (and aligned with minimap2 against a reference). Not sure how to show subregions in the assembly graph. Could I please have some pointers to do that? thank you

**Comment by chhylp123** [comment]
The A-lines in GFA files indicate the HiFi reads that are used by contigs/unitigs. You could pick up the corresponding HiFi reads in contigs, and grep them in the `r_utg.gfa` or `p_utg.gfa`.

**Comment by elcortegano** [comment]
I have grep-ed this contig name in both `r_utg.gfa` and `p_utg.gfa`. The contig is not found in any of these files (but it is in the `bp.hap1.p_ctg.gfa` file used to generate the fasta).

**Comment by chhylp123** [comment]
No, I mean give a contig X, then you could know which HiFi reads does contig X contain by looking at A-lines (see: https://hifiasm.readthedocs.io/en/latest/interpreting-output.html). Then you could grep the HiFi read name in `r_utg.gfa` or `p_utg.gfa`. In this case, you could find which unitigs share the same HiFi reads with the contig X.

**Comment by elcortegano** [comment]
Thank you for the pointers,

I have selected five reads from that subregion. These are their entries in the `r_utg.gfa` file:

    A	utg001077l	987645	+	m64046_211224_001820/70322940/ccs	0	16400	id:i:755895	HG:A:a
    A	utg001077l	985575	-	m64046_211224_001820/175047612/ccs	0	15372	id:i:1870320	HG:A:a
    A	utg001077l	977138	-	m64046_220325_124801/80872867/ccs	0	22357	id:i:5364909	HG:A:a
    A	utg001077l	976603	-	m64046_220323_031807/169149946/ccs	0	18481	id:i:2511738	HG:A:a
    A	utg001077l	975645	-	m64046_220325_124801/119014200/ccs	0	18856	id:i:5827125	HG:A:a

And in the `p_utg_.gfa` file:

    A	utg000747l	1084405	+	m64046_211224_001820/70322940/ccs	0	16400	id:i:755895	HG:A:a
    A	utg000747l	1082335	-	m64046_211224_001820/175047612/ccs	0	15372	id:i:1870320	HG:A:a
    A	utg000747l	1073898	-	m64046_220325_124801/80872867/ccs	0	22357	id:i:5364909	HG:A:a
    A	utg000747l	1073363	-	m64046_220323_031807/169149946/ccs	0	18481	id:i:2511738	HG:A:a
    A	utg000747l	1072405	-	m64046_220325_124801/119014200/ccs	0	18856	id:i:5827125	HG:A:a

**Comment by chhylp123** [comment]
Thanks. So what does the graph look like in Bandage?

**Comment by elcortegano** [comment]
Done like this for the selected unitigs in the region? Above for `r_utg.gfa` and below for `p_utg.gfa`.

![bandage r_utg](https://user-images.githubusercontent.com/57492899/170361667-c765171c-4742-493b-950a-bf42c045c074.png)

![bandage p_utg](https://user-images.githubusercontent.com/57492899/170361684-7843f5ce-05d1-46c4-a8eb-5469224fe13e.png)

**Comment by elcortegano** [comment]
Ok, so maybe this suggests already that it is homozygote? repeated this procedure for a known heterozygote region an can clearly see two nodes in parallel connected to the same adjacent nodes.

**Comment by chhylp123** [comment]
Yes, looks like it is a homozygote.

**Comment by elcortegano** [comment]
Ok, thank you for the clarification! learned a lot from this.
