### ISSUE TITLE
Reason why haplotype assemblies are smaller than primary assembly?

### ISSUE THREAD

**Issue by pjm43** [chhylp123/hifiasm#286]
Hi,

I'm working on a plant species that does not have sex chromosomes and should be highly inbred (homozygous).  I'm curious about why the haplotype assemblies are smaller than the primary assembly.  The genome size estimate for the species is ~4.27 Gb (Genomescope v1.0) 

p_ctg.fa: sum = 4234371105, n = 1068, ave = 3964766.95, largest = 54705417, N50 = 10250742, n = 128
hap1.p_ctg.fa:  sum = 3654440006, n = 1215, ave = 3007769.55, largest = 54747671, N50 = 8412219, n = 127
hap2.p_ctg.fa:  sum = 3511920105, n = 970, ave = 3620536.19, largest = 35800774, N50 = 8138134, n = 129

I realize that since the plant is homozygous, perhaps I shouldn't need purging (phasing), is this the likely reason that the phasing is not sufficient to produce haplotype assemblies equal to that of the primary assembly?  I'm assuming the primary assembly is what I should use going forward for scaffolding (HiC)?  Correct?  The assembly was run on V16.1 with all default parameters (hifiasm -o hifiasm_v16_Ae -t 36 fastq.gz).

Any thoughts or ideas would be greatly appreciated.

Jeff

**Comment by chhylp123** [comment]
Phasing and purging have the same issue: these two models may collapse repeats. The collapsed repeats will make the assemblies smaller. If your sample is homozygous, it would be better to run hifiasm with `-l0`, which disable the purging.
