### ISSUE TITLE
Assembled contig (centromere-region) is too large than expected with hifi reads by Hifiasm

### ISSUE THREAD

**Issue by JiaoLaboratory** [chhylp123/hifiasm#289]
**Dear hifiasm developer,
I am using hifiasm to assembly the Centromere-region with hifi reads, while I get one contig much longer than expected,
I mapped the hifi reads and ONT reads to the contig to check its coverage, and HIC-reads to check the HIC contacts, It is so abnormal !

![image](https://user-images.githubusercontent.com/65637958/175886380-ca2a0fe7-6db6-492d-8e2b-76735b9fec92.png)

could you give me some advice? 

futhermore, the contig sequence is full of repeats! 
![image](https://user-images.githubusercontent.com/65637958/175886428-5696de61-5dae-4e99-a79f-af5448cd5527.png)

is the contig correctly  assembled?**

[M::ha_analyze_count] highest: count[8] = 16604
[M::ha_hist_line]     1: ******* 1088
[M::ha_hist_line]     2: *** 507
[M::ha_hist_line]     3: ******** 1351
[M::ha_hist_line]     4: ******************* 3092
[M::ha_hist_line]     5: **************************************** 6576
[M::ha_hist_line]     6: **************************************************************************** 12604
[M::ha_hist_line]     7: ************************************************************************************************* 16154
[M::ha_hist_line]     8: **************************************************************************************************** 16604
[M::ha_hist_line]     9: ************************************************************************************* 14055
[M::ha_hist_line]    10: **************************************************************************** 12630
[M::ha_hist_line]    11: ************************************************** 8331
[M::ha_hist_line]    12: **************************** 4728
[M::ha_hist_line]    13: *************** 2521
[M::ha_hist_line]    14: ***************** 2767
[M::ha_hist_line]    15: **************** 2595
[M::ha_hist_line]    16: ***************** 2784
[M::ha_hist_line]    17: *************** 2485
[M::ha_hist_line]    18: *************** 2509
[M::ha_hist_line]    19: ************** 2348
[M::ha_hist_line]    20: *********** 1846
[M::ha_hist_line]    21: *********** 1778
[M::ha_hist_line]    22: ********* 1464
[M::ha_hist_line]    23: ******* 1214
[M::ha_hist_line]    24: ******** 1290
[M::ha_hist_line]    25: ******* 1129
[M::ha_hist_line]    26: ******* 1123
[M::ha_hist_line]    27: ****** 1002
[M::ha_hist_line]    28: ******* 1146
[M::ha_hist_line]    29: ****** 965
[M::ha_hist_line]    30: ***** 901
[M::ha_hist_line]    31: **** 711
[M::ha_hist_line]    32: **** 658
[M::ha_hist_line]    33: ***** 750
[M::ha_hist_line]    34: **** 678
[M::ha_hist_line]    35: **** 584
[M::ha_hist_line]    36: *** 515
[M::ha_hist_line]    37: *** 566
[M::ha_hist_line]    38: *** 472
[M::ha_hist_line]    39: ** 363
[M::ha_hist_line]    40: ** 369
[M::ha_hist_line]    41: * 196
[M::ha_hist_line]    42: * 91
[M::ha_hist_line]  rest:  78
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: count[16] = 2784
[M::ha_pt_gen] peak_hom: 16; peak_het: 8
[M::ha_pt_gen::42.825*6.59] ==> indexed 1609869 positions
[M::ha_assemble::44.931*6.74@16.396GB] ==> found overlaps for the final round
[M::ha_print_ovlp_stat] # overlaps: 53476
[M::ha_print_ovlp_stat] # strong overlaps: 3820
[M::ha_print_ovlp_stat] # weak overlaps: 49656
[M::ha_print_ovlp_stat] # exact overlaps: 50692
[M::ha_print_ovlp_stat] # inexact overlaps: 2784
[M::ha_print_ovlp_stat] # overlaps without large indels: 53388
[M::ha_print_ovlp_stat] # reverse overlaps: 1720
Writing reads to disk...
Reads has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
bin files have been written.
[M::purge_dups] purge duplication coverage threshold: 20
Writing raw unitig GFA to disk...
Writing processed unitig GFA to disk...
[M::purge_dups] purge duplication coverage threshold: 20
[M::mc_solve:: # edges: 0]
[M::mc_solve_core::0.000] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [13, infinity]
Writing hifiasm.asm.bp.p_ctg.gfa to disk...
Writing hifiasm.asm.bp.hap1.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [13, infinity]
Writing hifiasm.asm.bp.hap2.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [13, infinity]
Inconsistency threshold for low-quality regions in BED files: 70%
[M::main] Version: 0.15.1-r334
[M::main] CMD: hifiasm -t 10 ptg000014l.hifiread.id.fa
[M::main] Real time: 46.042 sec; CPU: 304.123 sec; Peak RSS: 16.396 GB

**Comment by chhylp123** [comment]
Sorry for the late reply. Can you have a try with the latest version (v0.16-r375) and show the assembly graph? I think the graph structure will be helpful for quick checking. By the way, it seems the coverage of your dataset is a little bit low.

**Comment by JiaoLaboratory** [comment]
Dear hifiasm developer, 
 In fact, I have a plant genome with total size (250M~300M, I am not pretty sure),
 I used hifiasm ( Version: 0.16.1-r375) to assembly the genome with the hifi reads (~70x)  and get a total size of 300M, (N50=1.2M ); 
While, I'm pretty confused about my hifiasm results these days, because, I found the top largest contigs are full of repeats, I checked the reads coverage for these top contigs and found these contigs are nearly full of highly repeats in some low-coverage regions, and the HIC also looks abnormal. 

I have some question about this,
 1. Do you think, are these top largest contigs (maybe centromeric region)  are succesfully assembled by hifiasm?  if this, whether are these centromeric region too large (some up to 8M) ？
2. I wonder if hifiasm overextended repeat areas and so that,lead to these large contigs？
3. Or, if hifiasm has special optimization for the centromeric region ? （If so, I am very glad and lucky to have sucessfully assembled the centromere regions）
4. Other reasons?  reads self ?  I  do not know. 
  
 These top largest hifiasm-contigs have no collinearity with the ONT assembly. 
![image](https://user-images.githubusercontent.com/65637958/177683206-42273088-fe8c-4fff-aaa4-25175c4c162c.png)

Meanwhile, I used nextDenovo(v2.5.0) to assembly the genome with hifi reads and get similar resultes (~300M, N50=1.0M). Similarly, the top largest are also full of repeats as hifiasm. While ,when I used nextDenovo(v2.5.0) and flye (v2.9-b1778) to assembly the genome with ultralong+ONT(~100X ), and both get the total size of 250M,N50=9M. 

I have no idea about the genome size and the top largest hifiasm-contigs, could U help me? @chhylp123 @lh3 @

[Afi.hifiasm.log.txt](https://github.com/chhylp123/hifiasm/files/9060103/Afi.hifiasm.log.txt)
[The top largest hifiasm-contigs.pdf](https://github.com/chhylp123/hifiasm/files/9060104/The.top.largest.hifiasm-contigs.pdf)

**Comment by chhylp123** [comment]
It is hard to say, especially for centromeres. Looks like your genome is homozygous. If it is, I would recomend you to verify the centromere by the methods utilized in the CHM13 reference genome paper (see: https://www.science.org/doi/full/10.1126/science.abj6987). The general idea is to map all reads back to the assembly, and see if the coverage distribution is normal. If that contig has some issue, there should be coverage gaps or extremely high coverage peaks. Hifiasm does not have special treatment for centromeres.

**Comment by JiaoLaboratory** [comment]
Thank you for your advice, I will check carefully!

**Comment by JiaoLaboratory** [comment]
> **Dear hifiasm developer, I am using hifiasm to assembly the Centromere-region with hifi reads, while I get one contig much longer than expected, I mapped the hifi reads and ONT reads to the contig to check its coverage, and HIC-reads to check the HIC contacts, It is so abnormal !
> 
> ![image](https://user-images.githubusercontent.com/65637958/175886380-ca2a0fe7-6db6-492d-8e2b-76735b9fec92.png)
> 
> could you give me some advice?
> 
> futhermore, the contig sequence is full of repeats! ![image](https://user-images.githubusercontent.com/65637958/175886428-5696de61-5dae-4e99-a79f-af5448cd5527.png)
> 
> is the contig correctly assembled?**
> 
> [M::ha_analyze_count] highest: count[8] = 16604 [M::ha_hist_line] 1: ******* 1088 [M::ha_hist_line] 2: *** 507 [M::ha_hist_line] 3: ******** 1351 [M::ha_hist_line] 4: ******************* 3092 [M::ha_hist_line] 5: **************************************** 6576 [M::ha_hist_line] 6: **************************************************************************** 12604 [M::ha_hist_line] 7: ************************************************************************************************* 16154 [M::ha_hist_line] 8: **************************************************************************************************** 16604 [M::ha_hist_line] 9: ************************************************************************************* 14055 [M::ha_hist_line] 10: **************************************************************************** 12630 [M::ha_hist_line] 11: ************************************************** 8331 [M::ha_hist_line] 12: **************************** 4728 [M::ha_hist_line] 13: *************** 2521 [M::ha_hist_line] 14: ***************** 2767 [M::ha_hist_line] 15: **************** 2595 [M::ha_hist_line] 16: ***************** 2784 [M::ha_hist_line] 17: *************** 2485 [M::ha_hist_line] 18: *************** 2509 [M::ha_hist_line] 19: ************** 2348 [M::ha_hist_line] 20: *********** 1846 [M::ha_hist_line] 21: *********** 1778 [M::ha_hist_line] 22: ********* 1464 [M::ha_hist_line] 23: ******* 1214 [M::ha_hist_line] 24: ******** 1290 [M::ha_hist_line] 25: ******* 1129 [M::ha_hist_line] 26: ******* 1123 [M::ha_hist_line] 27: ****** 1002 [M::ha_hist_line] 28: ******* 1146 [M::ha_hist_line] 29: ****** 965 [M::ha_hist_line] 30: ***** 901 [M::ha_hist_line] 31: **** 711 [M::ha_hist_line] 32: **** 658 [M::ha_hist_line] 33: ***** 750 [M::ha_hist_line] 34: **** 678 [M::ha_hist_line] 35: **** 584 [M::ha_hist_line] 36: *** 515 [M::ha_hist_line] 37: *** 566 [M::ha_hist_line] 38: *** 472 [M::ha_hist_line] 39: ** 363 [M::ha_hist_line] 40: ** 369 [M::ha_hist_line] 41: * 196 [M::ha_hist_line] 42: * 91 [M::ha_hist_line] rest: 78 [M::ha_analyze_count] left: none [M::ha_analyze_count] right: count[16] = 2784 [M::ha_pt_gen] peak_hom: 16; peak_het: 8 [M::ha_pt_gen::42.825_6.59] ==> indexed 1609869 positions [M::ha_assemble::44.931_[6.74@16.396GB](mailto:6.74@16.396GB)] ==> found overlaps for the final round [M::ha_print_ovlp_stat] # overlaps: 53476 [M::ha_print_ovlp_stat] # strong overlaps: 3820 [M::ha_print_ovlp_stat] # weak overlaps: 49656 [M::ha_print_ovlp_stat] # exact overlaps: 50692 [M::ha_print_ovlp_stat] # inexact overlaps: 2784 [M::ha_print_ovlp_stat] # overlaps without large indels: 53388 [M::ha_print_ovlp_stat] # reverse overlaps: 1720 Writing reads to disk... Reads has been written. Writing ma_hit_ts to disk... ma_hit_ts has been written. Writing ma_hit_ts to disk... ma_hit_ts has been written. bin files have been written. [M::purge_dups] purge duplication coverage threshold: 20 Writing raw unitig GFA to disk... Writing processed unitig GFA to disk... [M::purge_dups] purge duplication coverage threshold: 20 [M::mc_solve:: # edges: 0] [M::mc_solve_core::0.000] ==> Partition [M::adjust_utg_by_primary] primary contig coverage range: [13, infinity] Writing hifiasm.asm.bp.p_ctg.gfa to disk... Writing hifiasm.asm.bp.hap1.p_ctg.gfa to disk... [M::adjust_utg_by_trio] primary contig coverage range: [13, infinity] Writing hifiasm.asm.bp.hap2.p_ctg.gfa to disk... [M::adjust_utg_by_trio] primary contig coverage range: [13, infinity] Inconsistency threshold for low-quality regions in BED files: 70% [M::main] Version: 0.15.1-r334 [M::main] CMD: hifiasm -t 10 ptg000014l.hifiread.id.fa [M::main] Real time: 46.042 sec; CPU: 304.123 sec; Peak RSS: 16.396 GB
