### ISSUE TITLE
Low contig N50 for a fish genome with 40x HiFi reads 

### ISSUE THREAD

**Issue by baozg** [chhylp123/hifiasm#29]
Hi, @chhylp123 

`hifiasm` works great on all my plant genome assembly, it produce more contiguous and complete genome in less resource usage. 

But I recently assembly a fish genome with `hifiasm`, it have low contig N50. 

Here is the all the information I have. Do you have any suggestions for tuning?

- genomscope estimation from the survey data: 789M, 0.517% het, repeat 49.3%
![image](https://user-images.githubusercontent.com/20680150/89854721-360cba00-dbc7-11ea-95e8-3c5829d1f4b7.png)

- HiFi data: 33.6G HiFi data from two SMRT cell, ccs N50 20,226, Q30 93.96

- Assembly stat：

The kmer histo from the HiFi seems different from the genomescope.

Stat | hifiasm(0.11) | wtdbg2(2.4) | flye(2.8)
-- | -- | -- | --
genomesize | 919821446 | 870750720 | 1.15E+09
contigNumber | 2313 | 4435 | 16179
contigN50 | 1152427 | 823296 | 324539
contigL50 | 214 | 280 | 831

```bash
hifiasm -o fish -t 28 fish.hifi.fastq.gz
```

- BUSCO stat on `fish.p_ctg.fa`: C:93.3%[S:88.6%,D:4.7%],F:2.0%,M:4.7%,n:4584

I have tried blast 50000 seqs from the HiFi reads, it mostly mapped to the fish sequences in NR database. 

Typically, fish genome have more simple repeat (~8%) than plant(<2%).

Here is the log of hifiasm
[fish.hifiasm.log](https://github.com/chhylp123/hifiasm/files/5054588/fish.hifiasm.log)

Here is the raw unitig graph (fish.p_utg.noseq.gfa)
[fish.p_utg.noseq.gfa.zip](https://github.com/chhylp123/hifiasm/files/5054593/fish.p_utg.noseq.gfa.zip)

Thanks,

Zhigui Bao

**Comment by chhylp123** [comment]
What's the size of a_ctg.gfa of hifiasm? I guess the size of hifiasm is p_ctg.gfa's, while wtdbg2 and flye are the whole size?

**Comment by baozg** [comment]
Yes. The size of hifiasm are the p_ctg size, the a_ctg size are 791975516.

By the way, I have run the HiCanu. (size: 1739194735, N50 463525, ContigNum: 9732).

But the `purge_dups` from the sanger is very strange, its first peak is less than 5x.
![PB cov](https://user-images.githubusercontent.com/20680150/90037105-5be4ac80-dcf6-11ea-9e25-4d7fc27dd8b7.png)

**Comment by chhylp123** [comment]
Well, it is hard to say...probably you can check the break points at p_ctg.gfa, and find what's their corresponding parts at r_utg.gfa look like.
