### ISSUE TITLE
Genome completeness is kind of low

### ISSUE THREAD

**Issue by liwang0307** [chhylp123/hifiasm#290]
Hi,
Hifiasm is a great tool! I enjoyed it. Thank you very much! 
I am working on a fungus genome and the genome size is expected to be 110mb. I have assembled my HiFi reads using Hicanu and Hifiasm with default parameters. The evaluation results, by BUSCO and Merqury, are as below:

Assembler   N50    SUM   completeness(%)       BUSCO
hifiasm   3.76m   89.22m         83  C:100.0%[S:100.0%,D:0.0%],F:0.0%,M:0.0%,n:100
hicanu    1.0m     158.7m        99   C:100.0%[S:16.0%,D:84.0%],F:0.0%,M:0.0%,n:100

And then I have tried the purge level -l 0 option. The completeness increase to 90%, the genome to 115.6m, and BUSCO is C:100.0%[S:67.0%,D:33.0%],F:0.0%,M:0.0%,n:100. I have tried to -s 0.95 option (similarity threshold for duplicate haplotigs). The results look better, with 122.9mb and 92.6% completeness. I also tried the homozygous read coverage option, you can check my log file here: [hifiasm_v016.txt (https://github.com/chhylp123/hifiasm/files/8994541/hifiasm_v016.txt). But the genome size is similar to the default parameters, 89m. I am not sure if I did the right thing. Do you have any suggestions for me? Appreciate your help!

**Comment by chhylp123** [comment]
Is your sample homozygous? If homozygous, I think `-l0` should be better.

**Comment by liwang0307** [comment]
Thank you so much for your reply! I don't think my fungus is homozygous because it was isolated from the field. I guess the reason is probably that it contains lots of repetitive regions. I have tried several options:
`-D` FLOAT     drop k-mers occurring >FLOAT*coverage times [5.0]
`--hg-size`    INT(k, m or g)
`--hom-cov`    homozygous read coverage [auto]
Purge-dups:
    `-l` INT       purge level. 0: no purging; 1: light; 2/3: aggressive [0 for trio; 3 for unzip]
    `-s` FLOAT     similarity threshold for duplicate haplotigs [0.75 for -l1/-l2, 0.55 for -l3]
    `-O` INT       min number of overlapped reads for duplicate haplotigs [1]

I have tried different options many times. There are the main results of my assembly:

Assembler;                   options;                    sum(Mb);                  completeness
hicanu                         `default`                  158;                               99%
flye                              `default`                 130;                                  99%
hifiasm                        `default`                 89;                                  82%
hifiasm               `--hom-cov 198 `    89;                                82%
hifiasm                        `-l0`                        115;                                90%
hifiasm                     `-s0.95`                   122;                                92%
hifiasm      `-l0; --hom-cov 198; --hg-size 110m; -s 0.85`        115;     90%
hifiasm     ` -l0; -D10; --hom-cov 198; --hg-size 110m`              115;     90%
hifiasm     `-o10; -D10; -s0.99; --hom-cov 198; --hg-size 110m`  128;   94%

The statistics of results from Hifiasm are great, except for completeness. I indeed want to use the results from Hifiasm. However, I have tried more than ten times, and the best completeness is 94%. It is still kind of low.  Do you have any recommendations for me? Appreciate your support!

You can check my log file for my last run.
[hifiasm_o10d10s99.log](https://github.com/chhylp123/hifiasm/files/9024516/hifiasm_o10d10s99.log)

**Comment by chhylp123** [comment]
By the BUSCO completeness, is this the `S+D` or `S`?

**Comment by liwang0307** [comment]
No, this is the completeness calculated by Merqury. My BUSCO scores are all 100%, so I didn't list them here. The main issue is that the genome size is much smaller than expected and the completeness is smaller, too. I have tried different parameters, and the genome size and completeness become larger and better, but still not good enough. I have no idea what should I do to increase them right now. Hope you can give me valuable advice. Appreciate your help and support!

**Comment by liwang0307** [comment]
The completeness calculated by Merqury is based on diploid data. The assemblies of Canu and Flye are mixed haplotypes, so their completeness scores are higher than Hifiasm. I figure it out now and will close this issue. Thanks!
