### ISSUE TITLE
Can order of reads affect assembly reproducibility?

### ISSUE THREAD

**Issue by proteinosome** [chhylp123/hifiasm#291]
Hi, I've recently assembled a human genome using a set of HiFi FASTQs and the results look great. However, when another group tried to reproduce the genome assembly, we noticed a very minor difference in results. Shown here is the primary contig results:

```
  Main genome scaffold total:             212
  Main genome contig total:               212
  Main genome scaffold sequence total:    3092.484 MB
  Main genome contig sequence total:      3092.484 MB     0.000% gap
  Main genome scaffold N/L50:             14/91.511 MB
  Main genome contig N/L50:               14/91.511 MB
  Main genome scaffold N/L90:             21/62.924 MB
  Main genome contig N/L90:               21/62.924 MB
  Max scaffold length:                    146.425 MB
  Max contig length:                      146.425 MB
  Number of scaffolds > 50 KB:            154
  % main genome in scaffolds > 50 KB:     99.94%
```

Another assembly's primary contig:

```
  Main genome scaffold total:             213
  Main genome contig total:               213
  Main genome scaffold sequence total:    3088.064 MB
  Main genome contig sequence total:      3088.064 MB     0.000% gap
  Main genome scaffold N/L50:             13/92.228 MB
  Main genome contig N/L50:               13/92.228 MB
  Main genome scaffold N/L90:             20/72.58 MB
  Main genome contig N/L90:               20/72.58 MB
  Max scaffold length:                    160.295 MB
  Max contig length:                      160.295 MB
  Number of scaffolds > 50 KB:            145
  % main genome in scaffolds > 50 KB:     99.93%
```

We then cross checked each other's FASTQ file by using `seqkit` to generate the read quality, length and statistics and they're *perfectly* identical, as expected. The only difference I can find is the order of the reads in the FASTQ file. We exported the FASTQ differently and in one set of FASTQ the reads are ordered by read names, but the other set is not.

May I know if the order of FASTQ file can actually affect the output, even if it's minor? Is it possible that some of the parameters in the software that for example limit the reads to a specific number can possibly result in different set of reads being used?

I've also attached the Hifiasm log file for both set of assembly.
[hifiasm_log1.err.gz](https://github.com/chhylp123/hifiasm/files/9015792/hifiasm_log1.err.gz)
[hifiasm_log2.err.gz](https://github.com/chhylp123/hifiasm/files/9015793/hifiasm_log2.err.gz)

Thank you!

**Comment by lh3** [comment]
This is expected.

**Comment by proteinosome** [comment]
Thanks Prof. Li! Can you comment a little bit more on which stages of the software are affected by this?

**Comment by chhylp123** [comment]
The order matters. If the order is exactly the same, the assembly will be also exactly the same.

**Comment by proteinosome** [comment]
@chhylp123 Thanks, yes that's what Prof. Li confirmed and I understood that. May I know why that is so? In that case, is there a way to sort the reads such that it optimizes the outcome?

**Comment by chhylp123** [comment]
There are millions of HiFi reads involved in genome assembly. In rare cases, selecting any of two or more reads for assembly is fine. In this case, hifiasm may select the reads with the smallest ID. I personally think the order does not matter too much. The difference will be very minor.

**Comment by proteinosome** [comment]
Thank you for the explanation @chhylp123 !
