### ISSUE TITLE
Confused killed without any error message or log

### ISSUE THREAD

**Issue by Lillian-21** [chhylp123/hifiasm#293]
Hi,
     I meet a similar error, hope you can give me some advise.
     The estimated haploid genome size was ~1G. I get ~40G hifi reads (ccs) with 3 times (10G+10G+10G).
     I can run hifiasm and get the result with each three separate row reads, and it is nomal with the first and second merged reads (cat 1.fa 2.fa >all.fa). But can not run with the all merged date (cat 1.fa 2.fa 3.fa >all.fa) with 16 CPU, 1000G memory. 

I also have unified the read ID like: 
>1
>2
>3
....

The code:
       hifiasm -l0 -o M.asm -t 16 --h1 read_1.fq.gz --h2 read_2.fq.gz all.fa

The error work.e:
[M::ha_analyze_count] lowest: count[5] = 3862894
[M::ha_analyze_count] highest: count[18] = 22152699
[M::ha_hist_line]     2: ***************************************************************************** 16963866
[M::ha_hist_line]     3: **************************** 6268088
[M::ha_hist_line]     4: ******************** 4321862
[M::ha_hist_line]     5: ***************** 3862894
[M::ha_hist_line]     6: ****************** 3948105
[M::ha_hist_line]     7: ******************** 4334836
[M::ha_hist_line]     8: *********************** 5144718
[M::ha_hist_line]     9: ***************************** 6328175
[M::ha_hist_line]    10: ************************************ 7954684
[M::ha_hist_line]    11: ********************************************* 10036053
[M::ha_hist_line]    12: ******************************************************** 12453254
[M::ha_hist_line]    13: ******************************************************************** 15005075
[M::ha_hist_line]    14: ******************************************************************************* 17498969
[M::ha_hist_line]    15: ***************************************************************************************** 19686578
[M::ha_hist_line]    16: ************************************************************************************************ 21290767
[M::ha_hist_line]    17: **************************************************************************************************** 22145800
[M::ha_hist_line]    18: **************************************************************************************************** 22152699
[M::ha_hist_line]    19: ************************************************************************************************ 21289731
[M::ha_hist_line]    20: ***************************************************************************************** 19767821
[M::ha_hist_line]    21: ******************************************************************************** 17799455
[M::ha_hist_line]    22: ********************************************************************** 15599388
[M::ha_hist_line]    23: ************************************************************* 13411401
[M::ha_hist_line]    24: **************************************************** 11415353
[M::ha_hist_line]    25: ******************************************** 9730460
[M::ha_hist_line]    26: ************************************** 8423890
[M::ha_hist_line]    27: ********************************** 7524446
[M::ha_hist_line]    28: ******************************** 6992179
[M::ha_hist_line]    29: ******************************* 6762082
[M::ha_hist_line]    30: ****************************** 6733623
[M::ha_hist_line]    31: ******************************* 6847274
[M::ha_hist_line]    32: ******************************** 7029507
[M::ha_hist_line]    33: ********************************* 7213455
[M::ha_hist_line]    34: ********************************* 7366063
[M::ha_hist_line]    35: ********************************** 7425009
[M::ha_hist_line]    36: ********************************* 7387370
[M::ha_hist_line]    37: ********************************* 7247514
[M::ha_hist_line]    38: ******************************** 7010619
[M::ha_hist_line]    39: ****************************** 6686517
[M::ha_hist_line]    40: **************************** 6308220
[M::ha_hist_line]    41: ************************** 5861884
[M::ha_hist_line]    42: ************************ 5396754
[M::ha_hist_line]    43: ********************** 4907367
[M::ha_hist_line]    44: ******************** 4440113
[M::ha_hist_line]    45: ****************** 3997782
[M::ha_hist_line]    46: **************** 3595480
[M::ha_hist_line]    47: *************** 3226038
[M::ha_hist_line]    48: ************* 2911589
[M::ha_hist_line]    49: ************ 2637439
[M::ha_hist_line]    50: *********** 2410819
[M::ha_hist_line]    51: ********** 2217858
[M::ha_hist_line]    52: ********* 2055196
[M::ha_hist_line]    53: ********* 1918791
[M::ha_hist_line]    54: ******** 1800450
[M::ha_hist_line]    55: ******** 1702207
[M::ha_hist_line]    56: ******* 1612009
[M::ha_hist_line]    57: ******* 1530744
[M::ha_hist_line]    58: ******* 1453134
[M::ha_hist_line]    59: ****** 1383597
[M::ha_hist_line]    60: ****** 1310710
[M::ha_hist_line]    61: ****** 1238018
[M::ha_hist_line]    62: ***** 1167077
[M::ha_hist_line]    63: ***** 1102174
[M::ha_hist_line]    64: ***** 1037311
[M::ha_hist_line]    65: **** 972451
[M::ha_hist_line]    66: **** 913931
[M::ha_hist_line]    67: **** 858981
[M::ha_hist_line]    68: **** 804071
[M::ha_hist_line]    69: *** 755737
[M::ha_hist_line]    70: *** 711878
[M::ha_hist_line]    71: *** 668243
[M::ha_hist_line]    72: *** 631403
[M::ha_hist_line]    73: *** 595644
[M::ha_hist_line]    74: *** 560632
[M::ha_hist_line]    75: ** 532053
[M::ha_hist_line]    76: ** 502614
[M::ha_hist_line]    77: ** 474795
[M::ha_hist_line]    78: ** 450443
[M::ha_hist_line]    79: ** 426968
[M::ha_hist_line]    80: ** 404615
[M::ha_hist_line]    81: ** 383633
[M::ha_hist_line]    82: ** 364210
[M::ha_hist_line]    83: ** 345499
[M::ha_hist_line]    84: * 328775
[M::ha_hist_line]    85: * 311773
[M::ha_hist_line]    86: * 295616
[M::ha_hist_line]    87: * 281603
[M::ha_hist_line]    88: * 267006
[M::ha_hist_line]    89: * 255749
[M::ha_hist_line]    90: * 243137
[M::ha_hist_line]    91: * 233598
[M::ha_hist_line]    92: * 224276
[M::ha_hist_line]    93: * 215077
[M::ha_hist_line]    94: * 207088
[M::ha_hist_line]    95: * 199773
[M::ha_hist_line]    96: * 194018
[M::ha_hist_line]    97: * 188218
[M::ha_hist_line]    98: * 184087
[M::ha_hist_line]    99: * 179008
[M::ha_hist_line]   100: * 173154
[M::ha_hist_line]   101: * 169369
[M::ha_hist_line]   102: * 165172
[M::ha_hist_line]   103: * 161195
[M::ha_hist_line]   104: * 156724
[M::ha_hist_line]   105: * 153125
[M::ha_hist_line]   106: * 149940
[M::ha_hist_line]   107: * 145154
[M::ha_hist_line]   108: * 142184
[M::ha_hist_line]   109: * 138707
[M::ha_hist_line]   110: * 136244
[M::ha_hist_line]   111: * 131965
[M::ha_hist_line]   112: * 129324
[M::ha_hist_line]   113: * 126609
[M::ha_hist_line]   114: * 123464
[M::ha_hist_line]   115: * 120935
[M::ha_hist_line]   116: * 117399
[M::ha_hist_line]   117: * 115878
[M::ha_hist_line]   118: * 113114
[M::ha_hist_line]   119: * 111792
[M::ha_hist_line]  rest: ************************************************ 10700114
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: count[35] = 7425009
[M::ha_ft_gen] peak_hom: 35; peak_het: 18
[M::ha_ct_shrink::1224.310*5.17] ==> counted 6838559 distinct minimizer k-mers
[M::ha_ft_gen::1227.458*5.16@28.517GB] ==> filtered out 6838559 k-mers occurring 175 or more times
[M::ha_opt_update_cov] updated max_n_chain to 175
[M::yak_count] collected 600527388 minimizers
[M::ha_pt_gen::1695.168*6.49] ==> counted 44450354 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[5] = 618584
[M::ha_analyze_count] highest: count[11] = 1234564
[M::ha_hist_line]     1: ****************************************************************************************************> 16725306
[M::ha_hist_line]     2: ************************************************************************************************* 1200352
[M::ha_hist_line]     3: ************************************************* 601886
[M::ha_hist_line]     4: ******************************************** 548626
[M::ha_hist_line]     5: ************************************************** 618584
[M::ha_hist_line]     6: ************************************************************ 746245
[M::ha_hist_line]     7: ************************************************************************ 890968
[M::ha_hist_line]     8: ************************************************************************************ 1034693
[M::ha_hist_line]     9: ********************************************************************************************* 1145755
[M::ha_hist_line]    10: ************************************************************************************************** 1213009
[M::ha_hist_line]    11: **************************************************************************************************** 1234564
[M::ha_hist_line]    12: *************************************************************************************************** 1217596
[M::ha_hist_line]    13: *********************************************************************************************** 1171299
[M::ha_hist_line]    14: ****************************************************************************************** 1106914
[M::ha_hist_line]    15: ************************************************************************************ 1042399
[M::ha_hist_line]    16: ******************************************************************************* 972371
[M::ha_hist_line]    17: ************************************************************************* 907367
[M::ha_hist_line]    18: ******************************************************************** 844998
[M::ha_hist_line]    19: *************************************************************** 779908
[M::ha_hist_line]    20: ********************************************************** 718851
[M::ha_hist_line]    21: ***************************************************** 657276
[M::ha_hist_line]    22: ************************************************* 600594
[M::ha_hist_line]    23: ******************************************** 545979
[M::ha_hist_line]    24: **************************************** 499242
[M::ha_hist_line]    25: ************************************* 452868
[M::ha_hist_line]    26: ********************************** 416245
[M::ha_hist_line]    27: ******************************* 384331
[M::ha_hist_line]    28: ***************************** 355160
[M::ha_hist_line]    29: *************************** 334122
[M::ha_hist_line]    30: ************************* 314109
[M::ha_hist_line]    31: ************************ 298256
[M::ha_hist_line]    32: *********************** 283015
[M::ha_hist_line]    33: ********************** 268819
[M::ha_hist_line]    34: ********************* 255413
[M::ha_hist_line]    35: ******************** 241982
[M::ha_hist_line]    36: ******************* 228757
[M::ha_hist_line]    37: ***************** 215517
[M::ha_hist_line]    38: **************** 201536
[M::ha_hist_line]    39: *************** 187323
[M::ha_hist_line]    40: ************** 173520
[M::ha_hist_line]    41: ************* 162507
[M::ha_hist_line]    42: ************ 148232
[M::ha_hist_line]    43: *********** 136404
[M::ha_hist_line]    44: ********** 125569
[M::ha_hist_line]    45: ********* 115338
[M::ha_hist_line]    46: ********* 106524
[M::ha_hist_line]    47: ******** 97559
[M::ha_hist_line]    48: ******* 90924
[M::ha_hist_line]    49: ******* 83701
[M::ha_hist_line]    50: ****** 78672
[M::ha_hist_line]    51: ****** 73426
[M::ha_hist_line]    52: ****** 69280
[M::ha_hist_line]    53: ***** 64671
[M::ha_hist_line]    54: ***** 60805
[M::ha_hist_line]    55: ***** 58126
[M::ha_hist_line]    56: **** 54742
[M::ha_hist_line]    57: **** 51765
[M::ha_hist_line]    58: **** 49497
[M::ha_hist_line]    59: **** 46782
[M::ha_hist_line]    60: **** 44074
[M::ha_hist_line]    61: *** 41916
[M::ha_hist_line]    62: *** 39693
[M::ha_hist_line]    63: *** 38421
[M::ha_hist_line]    64: *** 36380
[M::ha_hist_line]    65: *** 34046
[M::ha_hist_line]    66: *** 32763
[M::ha_hist_line]    67: *** 31271
[M::ha_hist_line]    68: ** 29540
[M::ha_hist_line]    69: ** 28284
[M::ha_hist_line]    70: ** 26915
[M::ha_hist_line]    71: ** 25846
[M::ha_hist_line]    72: ** 24711
[M::ha_hist_line]    73: ** 23563
[M::ha_hist_line]    74: ** 22500
[M::ha_hist_line]    75: ** 21872
[M::ha_hist_line]    76: ** 20832
[M::ha_hist_line]    77: ** 19837
[M::ha_hist_line]    78: ** 19094
[M::ha_hist_line]    79: * 18473
[M::ha_hist_line]    80: * 17565
[M::ha_hist_line]    81: * 17019
[M::ha_hist_line]    82: * 16268
[M::ha_hist_line]    83: * 15613
[M::ha_hist_line]    84: * 15159
[M::ha_hist_line]    85: * 14603
[M::ha_hist_line]    86: * 13981
[M::ha_hist_line]    87: * 13311
[M::ha_hist_line]    88: * 12924
[M::ha_hist_line]    89: * 12508
[M::ha_hist_line]    90: * 12210
[M::ha_hist_line]    91: * 11393
[M::ha_hist_line]    92: * 11174
[M::ha_hist_line]    93: * 10681
[M::ha_hist_line]    94: * 10282
[M::ha_hist_line]    95: * 10080
[M::ha_hist_line]    96: * 9655
[M::ha_hist_line]    97: * 9344
[M::ha_hist_line]    98: * 9122
[M::ha_hist_line]    99: * 8882
[M::ha_hist_line]   100: * 8375
[M::ha_hist_line]   101: * 8419
[M::ha_hist_line]   102: * 8113
[M::ha_hist_line]   103: * 7833
[M::ha_hist_line]   104: * 7328
[M::ha_hist_line]   105: * 7360
[M::ha_hist_line]   106: * 7122
[M::ha_hist_line]   107: * 6689
[M::ha_hist_line]   108: * 6662
[M::ha_hist_line]   109: * 6487
[M::ha_hist_line]  rest: ******************* 233882
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 11; peak_het: -1
[M::ha_ct_shrink::1695.499*6.49] ==> counted 27725048 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 600527388 minimizers
[M::ha_pt_gen::2182.672*7.18] ==> indexed 583802082 positions, counted 27725048 distinct minimizer k-mers
/opt/gridengine/default/spool/cngb-supermem-a14-4/job_scripts/6825918: line 1: 26937 Killed                  hifiasm -l0 -o M.asm -t 16 --h1 read_1.fq.gz --h2 read_2.fq.gz all.fa

**Comment by chhylp123** [comment]
If it was killed, can you ensure does hifiasm require too large memory?

**Comment by Lillian-21** [comment]
I sorry with my mistakes. I used one of row Hifi data (not ccs) causing the task killed.
