### ISSUE TITLE
Multiple HiC inputs

### ISSUE THREAD

**Issue by oushujun** [chhylp123/hifiasm#298]
Hello,

Thank you for developing hifiasm and incorporating HiC data for phasing! I have two questions when trying to specify HiC data with `--h1` and `--h2` parameters. 

[Experimental setting]
There are multiple HiC files for read1 and read2 that were generated from the same tissue but different runs. Hifiasm bin files (`.ec.bin`, `ovlp.reverse.bin`, and `ovlp.source.bin`) were reused in the following tests.

[Question 1, use of wildcards]
**Test 1**
I tried to use wildcards to specify multiple HiC input files: `--h1 ../hic_colon_read1/*fastq.gz --h2 ../hic_colon_read2/*fastq.gz`, but the program report suggest `--h1` only took the first file in read 1 and put all other read 1 files to read 2:

```
...
[M::main] Version: 0.16.1-r375
[M::main] CMD: hifiasm -o 357.hifiasm -t 48 --h1 ../hic_colon_read1/ENCFF117LIZ.fastq.gz --h2 ../hic_colon_read2/ENCFF033BJR.fastq.gz ../hic_colon_read1/ENCFF235UQI.fastq.gz ../hic_colon_read1/ENCFF332QBC.fastq.gz ../hic_colon_read1/ENCFF532RAH.fastq.gz ../hic_colon_read1/ENCFF632YLE.fastq.gz ../hic_colon_read2/ENCFF510NMI.fastq.gz ../hic_colon_read2/ENCFF544BDR.fastq.gz ../hic_colon_read2/ENCFF872EMR.fastq.gz ../hic_colon_read2/ENCFF935XVK.fastq.gz ../m54333U_220301_195452.hifi_reads.fastq.gz ../m54333U_220318_160137.hifi_reads.fastq.gz ../m54333U_220319_220029.hifi_reads.fastq.gz ../m54333U_220321_041234.hifi_reads.fastq.gz
[M::main] Real time: 8395.723 sec; CPU: 28115.909 sec; Peak RSS: 156.570 GB
```

**Test 2**
I tried to specify HiC files without wildcards (write out all file paths and names), the result was the same -`--h1` only took the first file in read 1 and put all other read 1 files to read 2.

Is this possibly a bug when using wildcard to specify HiC data?

[Question 2, order of HiC inputs]
Because hifiasm seems not taking multiple HiC files at the moment, I concatinated all HiC files into single read 1 and read 2 files. I did this in two ways. 

**Test 3**
First, I concatinated with `cat hic_colon_read1/*fastq.gz > read1.fastq.gz` and `cat hic_colon_read2/*fastq.gz > read2.fastq.gz`, and the order of read 1 files was not matching the order of read 2 files due to poor naming conventions. 

**Test 4**
Second, I concatinated by specify the matching read 1 and read 2 order. 

I phased the assembly with these two sets of HiC files and the resulting assemblies were quite different:
```
# Random concatination
test3/357.hifiasm.hic.hap1.p_ctg.fa.stats
Number of contigs        467
Total size of contigs 3066706704
test3/357.hifiasm.hic.hap2.p_ctg.fa.stats
Number of contigs        377
Total size of contigs 2911551911

# Ordered concatination
test4/357.hifiasm.hic.hap1.p_ctg.fa.stats
Number of contigs        437
Total size of contigs 2928758196
test4/357.hifiasm.hic.hap2.p_ctg.fa.stats
Number of contigs        385
Total size of contigs 3049819358
```
This give raise to the second question: What is the proper way to merge multiple HiC data for hifiasm?

I also check the possible HiC bin file generated by hifiasm, their sizes are shown below in concordance to test 1 - 4. It seems that Test 4 generated the largest bin file.
```
413M Jul 19 02:06 test1/357.hifiasm.hic.lk.bin
413M Jul 19 12:03 test2/357.hifiasm.hic.lk.bin
1.1G Jul 22 13:44 test3/357.hifiasm.hic.lk.bin
1.7G Jul 22 18:35 test4/357.hifiasm.hic.lk.bin
```

Any suggestions are welcome! Thank you.

Best,
Shujun

**Comment by chhylp123** [comment]
Consider you have `a_hic_1.fq`, `a_hic_2.fq`, `b_hic_1.fq`, `b_hic_2.fq`, `c_hic_1.fq` `c_hic_2.fq`, `*_hic_1.fq` and `*_hic2_2.fq` are paired together. To merge them by hifiasm, please utilize the following command lines:

`--h1 a_hic_1.fq,b_hic1_fq,c_hic1_fq --h2 b_hic1.fq,b_hic2.fq,c_hic2.fq`

Wildcards do not work in this case. As for the file order, see https://github.com/chhylp123/hifiasm/issues/291.
