### ISSUE TITLE
Usage question: trio options -3/-4

### ISSUE THREAD

**Issue by ptrebert** [chhylp123/hifiasm#30]
Hi,
I am using hifiasm v0.11 in trio mode and supply lists of hap1/hap2 read names via the `-3` and `-4` command line options. Do I understand correctly that the read lists should only contain names of haplotype-specific reads? In other words, those reads that are contained in the input FASTQ but that are not part of these two read name files are treated by hifiasm as not haplotype-specific and will be used in the assembly process for both haplotypes. Thanks for confirming or clarifying how to properly use the `-3 / -4` options.
Best,
Peter

**Comment by lh3** [comment]
> Do I understand correctly that the read lists should only contain names of haplotype-specific reads?

Yes

**Comment by ptrebert** [comment]
Thanks for the clarification
