### ISSUE TITLE
no output file

### ISSUE THREAD

**Issue by sxfss** [chhylp123/hifiasm#300]
Hi! I have trouble when I use the hifiasm trio bin. The program does not produce any output file. The log file also does not provide any error message. My HiFi fastq sequence has 200G.
What is the reason?
my run command：
hifiasm -o /public/home/hpc164611151/shixf/projects/haplo/hifiasm_trio_bin/assembly/HG00544.asm -t 80 -1 /public/home/hpc164611151/shixf/projects/haplo/hifiasm_trio_bin/assembly/HG00544.pat.yak -2 /public/home/hpc164611151/shixf/projects/haplo/hifiasm_trio_bin/assembly/HG00544.mat.yak /public/home/hpc164611151/shixf/projects/data/home2/HG00544/fastq/HiFi/merge/HG00544_HiFi.fastq.gz
Log:
![log](https://user-images.githubusercontent.com/87353719/181734575-5ebfdc7d-f84a-45d6-bcd7-2c75b61db395.png)

**Comment by chhylp123** [comment]
Which version are you using? Could please post the whole log file here?

**Comment by sxfss** [comment]
Thanks for your answer.I’m using the 0.16.1-r375 version. Here is the whole log file. The log file stops generating at the last part.
[hifiasm_trio.sh.log](https://github.com/chhylp123/hifiasm/files/9221337/hifiasm_trio.sh.log)

**Comment by sxfss** [comment]
The last run of hifiasm took 60 hours and finally got the output result. I find the reason might be the linux server's. Thanks for your reply.
