### ISSUE TITLE
Empty result without reasing error

### ISSUE THREAD

**Issue by Ne0tea** [chhylp123/hifiasm#307]
Hi! i am trying to assembly a genome about 4Gb, but the results of hifiasm are empty (the result files were created but empty). fisrtly, i thought it only occured with hifiasm v0.15, but when i turned to 0.16.1, i encountered with the same situation. it confused me with couple of days, so is there any advice?
this is my command:
/public/home/huangyj/software/hifiasm-0.16.1/hifiasm -o Toba_Y3.asm -t 50 /public3/labmember/sheneh/tobacco/data/tong_20220815/01.CleanData/Genome/PacBio/B/out.B.subreads.fastq.gz /public3/labmember/sheneh/tobacco/data/tong_20220815/01.CleanData/Genome/PacBio/A/out.A.subreads.fastq.gz /public3/labmember/sheneh/tobacco/data/tong_20220815/01.CleanData/Genome/PacBio/C/out.C.subreads.fastq.gz
[log_HLW_pri.log](https://github.com/chhylp123/hifiasm/files/9541727/log_HLW_pri.log)

**Comment by chhylp123** [comment]
Could you please check the disk first? It is likely that something is wrong for the disk space.

**Comment by Ne0tea** [comment]
> Could you please check the disk first? It is likely that something is wrong for the disk space.

I have assembled a 1.3 Gb genome on the same server before and it worked well, so the disk may be right
Actually, files suffixed with 'ec.bin' were generated successfully, while others are empty, just like this.
![image](https://user-images.githubusercontent.com/113273372/189514707-2e3b0b4a-a3fd-47d8-b858-08146a4bf8f9.png)

**Comment by chhylp123** [comment]
It shouldn't happen. Could you please have a try with a small subset for testing?

**Comment by Ne0tea** [comment]
I am so sorry that I have made a mistake and it is runing well now, thank you for your reply and advice. I will close this issue.

**Comment by pants08** [comment]
> ###
> [Sep 20, 2022](#issuecomment-1251861010)

Excuse me, it seems I ran into the same problem as you described, can you describe what caused your problem and how you solved it? Appreciate.

**Comment by Ne0tea** [comment]
> > [Sep 20, 2022](#issuecomment-1251861010)
> 
> Excuse me, it seems I ran into the same problem as you described, can you describe what caused your problem and how you solved it? Appreciate.

It may be appropriate to double-check your raw data. It may be caused by the low quality of sequencing data which is not HiFi

**Comment by pants08** [comment]
> > > [Sep 20, 2022](#issuecomment-1251861010)
> > 
> > 
> > Excuse me, it seems I ran into the same problem as you described, can you describe what caused your problem and how you solved it? Appreciate.
> 
> It may be appropriate to double-check your raw data. It may be caused by the low quality of sequencing data which is not HiFi

OK, thanks again!
