### ISSUE TITLE
rerun on bin files

### ISSUE THREAD

**Issue by dabitz** [chhylp123/hifiasm#31]
Hi,

How can I rerun Hifiasm with different parameters based on the generated bin files?

Thanks,
André

**Comment by chhylp123** [comment]
Just rerun with the same input reads and '-o' option:
>hifiasm -o xxx.asm input.fastq

In this example, '-o xxx.asm' and 'input.fastq' should be unchanged.

**Comment by dabitz** [comment]
Thanks!
