### ISSUE TITLE
two large genome size and two haplotypes are not balanced

### ISSUE THREAD

**Issue by dzaccook** [chhylp123/hifiasm#311]
Hello,
I have a hybrid plant genome and used Hifiasm 0.16.1-r375 to generate a assembly (CMD: hifiasm -o hongye.hifiasm.asm -t 80 --primary -f 38 hongye.hifi_reads.fasta). The genome size was estimated to be ~11Gb using genomescope2 (with 1% heterozygosity) and flow cytometer. And I got the primary assembly with ~22Gb, the log file is 
[untitled.txt](https://github.com/chhylp123/hifiasm/files/9621482/untitled.txt)

I think it identified a wrong homozygosis coverage with 22, then I re-run it with --hom-cov 42 (CMD: hifiasm -o hongye.hifiasm.asm -t 80 --hom-cov 42 -f 38 hongye.hifi_reads.fasta), and the primary assembly size is ~20.5Gb, and the hap1 and hap2 genome size is ~18Gb and ~11Gb, respectively. I also re-run hifiasm with "-hom-cov 42  -s0.45" and "-hom-cov 42  -s0.1", but the genome size of primary assembly, hap1 and hap2 still reached ~20.5Gb, ~18Gb and ~11Gb, respectively.
Can you give me some advice? Thank you!

**Comment by chhylp123** [comment]
If the het rate is extremely high, the internal purge of hifiasm may not work well. Could you please have a try with purge_dups?

**Comment by dzaccook** [comment]
Thank you! T will try purge_dups.
