### ISSUE TITLE
Hapliod genome primary assembly larger than predicted

### ISSUE THREAD

**Issue by bibionid** [chhylp123/hifiasm#316]
Hello, 

Thank you for your comprehensive work on this amazing tool!

I would appreciate some advice on the assembly of a haploid genome. I have used hifiasm-0.16.1 with default settings and `-l0` to assemble ~75x coverage of hifi reads which GenomeScope2 predicts to be around 308Mb (haploid genome size). The resulting `.bp.p_ctg.fa` is 1.13Gb. I have used 4 tools to screen for contaminants and have identified roughly 71Mb. This primary assembly represents the appropriate busco set as follows:`C:97.1%[S:96.9%,D:0.2%],F:0.6%,M:2.3`.

Following the documentation provided here, I then used the `--hom-cov` flag to manaully set the homoztgous read coverage threshold. This was initially predicted as 13, but from the kmer plot was 33. With only this change in place, the resulting `.bp.p_ctg.fa` is 1.07Gb. 

I have been using `-l0` in these assemblies. Am I correct in suggesting this is the correct approach for a haploid assembly? 

My question is regarding my next step: From the docuemtation it would seem that tuning the `-s` parameter might help in this is situation. Is this an effective measure if the `-l0` flag is in place? 

If tuning `-s` is not worthwhile in this situation, I would be most grateful of any suggestions you might have for ways to further diagnose or address this additional assembly content. 

Many thanks in advance!

**Comment by chhylp123** [comment]
`-s` only works with purging_dups + `-l1`/`-l2`/`-l3`, while `-l0` does not have the purging step. So `-s` does not matter for your case. Actually, your assembly looks pretty nice.

**Comment by bibionid** [comment]
Thank you very much for the confirmation, and for the positive feedback.
