### ISSUE TITLE
Typo in README.md?

### ISSUE THREAD

**Issue by jelber2** [chhylp123/hifiasm#32]
Shouldn't 

    awk '/^S/{print ">"$1;print $2}' test.p_ctg.gfa > test.p_ctg.fa  # get primary contigs in FASTA

be 

    awk '/^S/{print ">"$2;print $3}' test.p_ctg.gfa > test.p_ctg.fa  # get primary contigs in FASTA

?

In the README.md for commit 55f95c0?

**Comment by chhylp123** [comment]
Yes, it is a typo...Thank you so much for point that!

**Comment by jelber2** [comment]
Ok. You are welcome.
