### ISSUE TITLE
Using low-coverage data

### ISSUE THREAD

**Issue by YahGao** [chhylp123/hifiasm#320]
Hi,

I have an issue regarding using low-coverage data.
I can run successfully with the raw hifi fastq files, but when I use seqkit (zcat sample.subreads_to_ccs.bam.fastq.gz | seqkit sample -p {perce} -s22 -o sample.subreads_to_ccs.bam_{depth}x .fastq.gz) to downsample the raw data to low coverage, such as 4x, 5x, etc., some fastq files with low coverage fail to run successfully with errors. See the error message below. Seems to be a memory issue, but I have raised the threshold to 100. Do you have any suggestions for this problem?

Thanks,
Yahui

[M::ha_analyze_count] lowest: count[67] = 52809
[M::ha_analyze_count] highest: count[4095] = 53579
[M::ha_hist_line]     2: ****************************************************************************************************> 217385853
[M::ha_hist_line]     3: ****************************************************************************************************> 217877667
.......
[M::ha_hist_line]  4094:  16
[M::ha_hist_line]  4095: **************************************************************************************************** 53579
[M::ha_hist_line]  rest:  0
[M::ha_analyze_count] left: count[68] = 52849
[M::ha_analyze_count] right: none
[M::ha_ft_gen] peak_hom: 4095; peak_het: 68
[M::ha_ct_shrink::1340.898*2.82] ==> counted 53595 distinct minimizer k-mers
[M::ha_ft_gen::1343.811*2.82@48.935GB] ==> filtered out 53595 k-mers occurring 4094 or more times
[M::ha_opt_update_cov] updated max_n_chain to 20475
[M::yak_count] collected 512462134 minimizers
[M::ha_pt_gen::1596.418*3.11] ==> counted 90232794 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[54] = 5024
[M::ha_analyze_count] highest: count[55] = 5031
[M::ha_hist_line]     1: ****************************************************************************************************> 18605132
.......
[M::ha_hist_line]   743: * 44
[M::ha_hist_line]   744: * 41
[M::ha_hist_line]  rest: ****************************************************************************************************> 19710
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 55; peak_het: -1
[M::ha_ct_shrink::1597.084*3.11] ==> counted 71627662 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 512462134 minimizers
[M::ha_pt_gen::1709.270*3.52] ==> indexed 493857002 positions, counted 71627662 distinct minimizer k-mers
/var/spool/slurmd/job2351215/slurm_script: line 16:  8481 Killed                  hifiasm -o assembly-hifiasm -t 100 -r 3 -a 5 -n 5 ../sample.subreads_to_ccs.bam_${depth}x.fastq.gz
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=2351215.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by chhylp123** [comment]
Hifiasm won't work very well with too low coverage This issue might be able to be fixed in the future.

**Comment by YahGao** [comment]
Thanks for your update
