### ISSUE TITLE
 How to evaluate the results of phasing ？

### ISSUE THREAD

**Issue by Moo-cow** [chhylp123/hifiasm#325]
Hi,

Hifiasm is a great piece of software.
I get two haplotypes with HiFi reads and HiC reads. This is a wild diploid plant, so I don't have parental information.

I want to know how to evaluate errors.

As mentioned in your article.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/26018594/196133905-515855a9-db2a-4c5b-b256-0b5841eade3d.png">

Sorry to bother you.
Thanks.

**Comment by chhylp123** [comment]
This plot is evaluated by the parental data. As there is no parental data for the wild diploid plant, one possibility is to check the Hi-C heatmap. Here is a nice example: https://github.com/baozg/phased-assembly-check.

**Comment by Moo-cow** [comment]
Well, thank you very much for your help.
I will try.
Please let me know if there are other better methods in the future.
I have this plant's HiC, Illumina, PacBio HiFi and PacBio CLR data. (also have RNA-seq and Iso-seq data)

Thank you for taking the time.
