### ISSUE TITLE
Should I trim the HiC short-reads at restriction site first?

### ISSUE THREAD

**Issue by plnspineda** [chhylp123/hifiasm#339]
Hello,

I just wanted to be sure and ask if I should trim the HiC short-reads first at restriction site before running HiFiasm with HiC mode?

Cleaning/Trimming with something like this:

`homerTools trim -3 GATC -mis 0 -matchStart 20 -min 20 hicExp1_R1_fastq`?

Thank you!

**Comment by chhylp123** [comment]
Sorry for the late reply. The answer is no need to do that.

**Comment by plnspineda** [comment]
Thank you!
