### ISSUE TITLE
hifiasm output: 731.928 MB single contig

### ISSUE THREAD

**Issue by B10inform** [chhylp123/hifiasm#34]
Hi,
I am working with highly heterozygous genome. My genome size is ~400MB with 9 chromosome.
Hifiasm gives me single contig of 731.928 MB.

This is the stats:
Main genome scaffold total:         	1
Main genome contig total:           	1
Main genome scaffold sequence total:	731.928 MB
Main genome contig sequence total:  	731.927 MB  	0.000% gap
Main genome scaffold N/L50:         	1/731.928 MB
Main genome contig N/L50:           	1/731.927 MB
Main genome scaffold N/L90:         	1/731.928 MB
Main genome contig N/L90:           	1/731.927 MB
Max scaffold length:                	731.928 MB
Max contig length:                  	731.927 MB
Number of scaffolds > 50 KB:        	1
% main genome in scaffolds > 50 KB: 	100.00%

It does not look right.
Any help, would be great.

**Comment by chhylp123** [comment]
Could you please run hifiasm with '-l0' and see what the result looks like? Thanks in advance.

**Comment by lh3** [comment]
Which tool are you using? Are you sure the tool itself is correct? How did you convert GFA to FASTA?

**Comment by B10inform** [comment]
Hi chhylp123,

This is my output with -I0 :
Main genome scaffold total:         	928
Main genome contig total:           	928
Main genome scaffold sequence total:	714.223 MB
Main genome contig sequence total:  	714.223 MB  	0.000% gap
Main genome scaffold N/L50:         	11/23.151 MB
Main genome contig N/L50:           	11/23.151 MB
Main genome scaffold N/L90:         	45/1.178 MB
Main genome contig N/L90:           	45/1.178 MB
Max scaffold length:                	52.188 MB
Max contig length:                  	52.188 MB
Number of scaffolds > 50 KB:        	342
% main genome in scaffolds > 50 KB: 	97.19%

The genome size is bigger than i am expecting. My genome size is ~400MB. What would be the good way to work with this? Heterozygosity is ~3.5

Thank, happy holidays.

**Comment by chhylp123** [comment]
> Which tool are you using? Are you sure the tool itself is correct? How did you convert GFA to FASTA?

Thanks. As Heng said, which tool did you use to covert GFA to FASTA and calculate N50?

**Comment by B10inform** [comment]
awk '/^S/{print ">"$2;print $3}' PB4.asm.p_ctg.gfa > PB.asm.p_ctg.fa

**Comment by chhylp123** [comment]
Interesting. Is it possible that you can share the bin files with us? If not, could you please try Purge_dups on -l0 assembly?

**Comment by conchoecia** [comment]
Assembly problems aside, I suggest making a Hi-C heatmap against the contig to see if the assembly makes sense, or if it has concatenated several chromosomes together.
