### ISSUE TITLE
Recommended settings for PacBio program ccs for converting subreads to HiFi reads for downstream usage with hifiasm

### ISSUE THREAD

**Issue by jelber2** [chhylp123/hifiasm#35]
Hi,

Do you have recommended settings for the PacBio program `ccs` (https://github.com/PacificBiosciences/ccs) for converting raw subreads to HiFi reads for downstream usage with `hifiasm`?

Best,
Jean Elbers

**Comment by jelber2** [comment]
Excerpt from https://genome.cshlp.org/content/suppl/2020/09/02/gr.263566.120.DC1/Supplemental_Material_.pdf (supplemental material of HiCanu by paper Nurk _et al._ 2020; _Genome Research_ doi: 10.1101/gr.263566.120)

    

    Assuming a 30-hr movie (https://www.pacb.com/products-and-services/sequel-system/latest-system-release/),
    acquiring CHM13 data on four SMRTcells would require 120 hours. We obtained 3/6 NA12878 raw bam files for
    the subreads and converted them to HiFi using the CCS command v3.4.1:

    ccs --maxLength 21000 --minPasses 3 --numThreads 32 --polish   --minPredictedAccuracy 0.99 input.bam output.bam

Would these settings be something you would recommend to start with?

**Comment by lh3** [comment]
I have never run PacBio's ccs tool, so I don't know.

**Comment by HenrivdGeest** [comment]
just from another user perspective;  besides altering the maxLength de default settings are fine. We have good experience with the defaults, there is hardly anything thing to tweak on the ccs tools. With any alteration you can make the data just more noisy, for example lowering the minPredictedAccuracy, will just make the final result a tiny bit larger, but more noisy, which could hamper hifiasm.

**Comment by jelber2** [comment]
Oh thank you! Yeah, I guess as with most tools, there are pros/cons to changing certain settings, especially things such as k-mer length for de novo assembly!
