### ISSUE TITLE
Crash on HG00544 dataset in trio mode

### ISSUE THREAD

**Issue by skoren** [chhylp123/hifiasm#355]
I was running hifiasm (`0.17.4-r455`) w/ul reads on the HG00544 dataset in trio mode using the full set of HiFi DeepConsensus reads and ONT reads filtered for >100kb (using seqtk) and had the crash:
```
hifiasm: inter.cpp:9018: void worker_for_ul_rescall_alignment(void*, long int, int): Assertion `UL_INF.a[s->id+i].rlen == s->len[i]' failed.
hifiasm: inter.cpp:9018: void worker_for_ul_rescall_alignment(void*, long int, int): Assertion `UL_INF.a[s->id+i].rlen == s->len[i]' failed.
hifiasm: inter.cpp:9018: void worker_for_ul_rescall_alignment(void*, long int, int): Assertion `UL_INF.a[s->id+i].rlen == s->len[i]' failed.
/var/spool/slurm/slurmd/job53086250/slurm_script: line 18: 111338 Aborted                 /data/korens/devel/hifiasm/hifiasm -o asm -t $cores -1 pat.yak -2 mat.yak ../hifi/*.fastq.gz --ul ont_over100kb.fastq
```

**Comment by chhylp123** [comment]
HG00544 works on my side. This assertion should not fail. Could you please share the bin files and the UL reads with us? Does hifiasm work for other human samples?

**Comment by chhylp123** [comment]
If this assertion fails, it means the input UL reads have been changed.

**Comment by skoren** [comment]
I was able to run CHM13, the other diploid humans are still running (launched about 2 days ago) but haven't crashed. I updated the code to latest and re-launch just in case I was out of date.

How can I share the bins with you, they're pretty large so can't upload to GitHub.

**Comment by chhylp123** [comment]
I also have no space for the bin files. Could you please share the links for the HiFi reads/UL reads? I could rerun on my side and check if we are using the same data.

**Comment by skoren** [comment]
Strange, the UL file shouldn't have changed based on the timestamps, I'll see if the re-run with latest code works.

The links are here:
`
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/1E2DD570-3B26-418B-B50F-5417F64C5679--HIFI_DEEPCONSENSUS/HG00544/raw_data/PacBio_HiFi/DeepConsensus/m64043_210702_183246.dc0.2.Q20.fastq.gz
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/1E2DD570-3B26-418B-B50F-5417F64C5679--HIFI_DEEPCONSENSUS/HG00544/raw_data/PacBio_HiFi/DeepConsensus/m64136_210520_180433.dc0.2.Q20.fastq.gz
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/1E2DD570-3B26-418B-B50F-5417F64C5679--HIFI_DEEPCONSENSUS/HG00544/raw_data/PacBio_HiFi/DeepConsensus/m64136_210522_014758.dc0.2.Q20.fastq.gz
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/1E2DD570-3B26-418B-B50F-5417F64C5679--HIFI_DEEPCONSENSUS/HG00544/raw_data/PacBio_HiFi/DeepConsensus/m64136_210523_100337.dc0.2.Q20.fastq.gz
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/1E2DD570-3B26-418B-B50F-5417F64C5679--HIFI_DEEPCONSENSUS/HG00544/raw_data/PacBio_HiFi/DeepConsensus/m64136_210525_165246.dc0.2.Q20.fastq.gz
`
and 
```
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/90A1F283-2752-438B-917F-53AE76C9C43E--UCSC_HPRC_nanopore_Year2/HG00544/nanopore/07_13_21_R941_HG00544_1_Guppy_5.0.11_prom_sup.fastq.gz
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/90A1F283-2752-438B-917F-53AE76C9C43E--UCSC_HPRC_nanopore_Year2/HG00544/nanopore/07_13_21_R941_HG00544_2_Guppy_5.0.11_prom_sup.fastq.gz
https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/90A1F283-2752-438B-917F-53AE76C9C43E--UCSC_HPRC_nanopore_Year2/HG00544/nanopore/07_13_21_R941_HG00544_3_Guppy_5.0.11_prom_sup.fastq.gz
````
filtered via `   zcat ../ont/*.fastq.gz | seqtk seq -L 100000 - > ont_over100kb.fastq`

**Comment by chhylp123** [comment]
Thanks a lot. It seems we are using the same dataset. Let me have a try.

**Comment by chhylp123** [comment]
The new release (`0.17.6 (r460) beta`) fixed a memory issue when aligning UL reads. Since it affects all procedures of the UL-integration assembly, it would be better to rerun the UL assembly from the scratch (delete all bin files except ec.bin, ovlp.reverse.bin, and ovlp.source.bin). I'm not sure if it affects the this issue, but I guess it should work.

**Comment by skoren** [comment]
The latest version ran to completion
