### ISSUE TITLE
duo haplotyping

### ISSUE THREAD

**Issue by chklopp** [chhylp123/hifiasm#36]
We would like to assemble and haplotype a tree genome for which we only have the maternal genome available. The father could be any surrounding tree. 
How could we generate the yak paternal file using genome and maternal kmer contents?

**Comment by lh3** [comment]
An interesting use case. In theory, there should be an algorithm that can generate phased assembly with just one parent (to lower accuracy in comparison to trio binning). However, hifiasm doesn't support this use case yet and implementing it will take time. We will keep this in mind. Thanks.

**Comment by shilpagarg** [comment]
Yes, adding to Heng's comment: I think WHdenovo algorithm (https://github.com/shilpagarg/WHdenovo) in principle can generate phased assemblies for any variants of pedigrees. We have designed this tool for Illumina and long-read data types. From our experiments, we observe that this method works fine for genome sizes up to 500 Mb and repeats 10-20%. I am happy to work with you to help you solve your use case. Let me know.

**Comment by chklopp** [comment]
The genome we are assembling has 2% heterozygocity. The kmer count histogram show a nice bimodal distribution. To produce the yak paternal file for hifiasm we would need to perform three operations on the HiFi and maternal yak files. One would be to chunk the HiFi kmer file to separate the homozygous and heterozygous kmer using minimum and maximum coverage thresholds (kind of yak split), the second, to find heterozygous kmers which a not in the maternal file (kind of yak diff) and the last to join homozygous and partenal heterozygous kmer (kind of yak merge).

Yak code (https://github.com/lh3/yak) does not seem to have these functions.

Another solution would be to perform this with another tool, for example kmc, and then to format the resulting file in yak format. 
Is there a script to format a kmer count file in yak format?

**Comment by chhylp123** [comment]
I guess the second solution might be better. If you want to do it manually, I recommend you to partition to corrected reads by yourself, and then feed the partitioned lists to hifiasm by the option '-3' and '-4'.
