### ISSUE TITLE
how to assemly the genome combined with the HiFi, HiC and UL-ONT ?

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#369]
I have the HiFi， HiC, and UL-ONT data， but the HiC and Ul-ONT were used to assemble with HiFi， respectively. How do I assembly them together? Thanks~

**Comment by chhylp123** [comment]
It would be better to rerun the latest version of hifiasm with all types of data from the scratch.

**Comment by zhoudreames** [comment]
can i used this code to assembly it ?
``
hifiasm -o NA12878.asm -t32 --h1 read1.fq.gz --h2 read2.fq.gz HiFi-reads.fq.gz --ul ul.ont.fq.gz
```

**Comment by wangsb111** [comment]
Hello,  i had run the hifiasm with only the Hifi reads . and now i want to add the UL-ont reads . 
1. should i rerun  from begining to end or the hifiasm can use the *bin scourece files .  
2.  UL-ont reads had been corrected by the NextDenovo, so ,how can i set the --ul-rate[0.2] . the erro ratio of corrected UL-ont reads has much less than 0.2 。

**Comment by chhylp123** [comment]
> @chhylp123 can i used this code to assembly it ?
> 
> ```
> hifiasm -o NA12878.asm -t32 --h1 read1.fq.gz --h2 read2.fq.gz HiFi-reads.fq.gz --ul ul.ont.fq.gz
> ```

It would be better to run as follows:
>hifiasm -o NA12878.asm -t32 --ul ul.ont.fq.gz --h1 read1.fq.gz --h2 read2.fq.gz HiFi-reads.fq.gz

**Comment by wangsb111** [comment]
ok. i will try to use the raw ul-ont reads. if its necessary to filtered the short ul-ont reads like length under 20kb？



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 12, 2022 23:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chhylp123/hifiasm] how to assemly the genome combined with the HiFi, HiC and UL-ONT ? (Issue #369)




  
Hello, i had run the hifiasm with only the Hifi reads . and now i want to add the UL-ont reads .
  
should i rerun  from begining to end or the hifiasm can use the *bin scourece files . 

UL-ont reads had been corrected by the NextDenovo, so ,how can i set the --ul-rate[0.2] . the erro ratio of corrected UL-ont reads has much less than 0.2 。 
  
You can reuse the bin files, but it would be better to rerun the latest version of hifiasm with all types of data from the scratch. I would also recommend you to run hifiasm with the uncorrected UL reads. I personally do not trust the self-correction of ONT reads.

**Comment by chhylp123** [comment]
It would be better to filter short UL reads. We have only tested to hifiasm with >100kb UL reads, but you could also have a try with other cutoffs like 50kb.
