### ISSUE TITLE
Question regarding the hifiasm phasing of diploid heterozygous genomes without the use of Hi-C.

### ISSUE THREAD

**Issue by ap1438** [chhylp123/hifiasm#373]
Dear developers,

I thank you for developing this tool. It's very efficient.

I have few queries.

1.On what basis the tools separate the 2 haplotypes in a diploid genome. How does it bin the contigs to different haplotypes with only hifiasm (no use of HI-C).
2. I have a heterozygous diploid plant genome and i intended to do genome assembly and when I ran hifiasm with default parameters (I only have pacbio Hifi reads). It produced 3 files as output i.e.
-primary assembly -263 mb
-hap1 assembly/paternal (as per the doc in hifiasm) -250 mb
-hap2 assembly/maternal (as per the doc in hifiasm)-207 mb

with a huge genome size difference between hap1 and hap2. What would you suggest about this. Is it because of the heterozygosity. Should I use **-s** with less value (How to select an optimal value).
My question is which assembly I should use for further processing to get a good assembly of my genome.
And secondly how far the hap* assemblies can be trusted (like Do all the contigs belonging to hap1 are from the same halpotype). Or there might be switch errors and the hap1 assembly may contain contigs from hap2.

**Comment by chhylp123** [comment]
For the different genome sizes, please see FAQ here: https://hifiasm.readthedocs.io/en/latest/faq.html#why-one-hi-c-integrated-assembly-is-larger-than-another-one. As for the second question, HiFi-only assemblies will have haplotype switch since there is no long-range information for phasing.

**Comment by ap1438** [comment]
Thank you for the clarification.
I ran the tool with trio binning mode with illumina short reads from parents.  commands used 
yak count -k31 -b37 -t16 -o S1_TT1.pat.yak < (zcat *fastq.gz) < (zcat *fastq.gz)
yak count -k31 -b37 -t16 -o S1_TT1.mat.yak < (zcat *fastq.gz) < (zcat *fastq.gz)
hifiasm -o S1_TT1_PA.asm --primary   -t 16 hiifi_reads.fastq.gz  2> S1_TT1_PA.asm.pri.log
hifiasm -o S1_TT1.asm -t 32 -1 S1_TT1.pat.yak -2 S1_TT1.mat.yak /dev/null 2> S1_TT1.asm.trio.log

It generated these files

****225M**       S1_TT1.asm.dip.hap1.p_ctg.gfa**
112K                 S1_TT1.asm.dip.hap1.p_ctg.lowQ.bed
4.6M                 S1_TT1.asm.dip.hap1.p_ctg.noseq.gfa
****230M**       S1_TT1.asm.dip.hap2.p_ctg.gfa**
301K                S1_TT1.asm.dip.hap2.p_ctg.lowQ.bed
4.5M                S1_TT1.asm.dip.hap2.p_ctg.noseq.gfa
****466M**       S1_TT1.asm.dip.p_utg.gfa**
477K                S1_TT1.asm.dip.p_utg.lowQ.bed
9.1M                S1_TT1.asm.dip.p_utg.noseq.gfa
****482M**       S1_TT1.asm.dip.r_utg.gfa**
529K                 S1_TT1.asm.dip.r_utg.lowQ.bed
9.2M                 S1_TT1.asm.dip.r_utg.noseq.gfa
8.6G                  S1_TT1.asm.ec.bin
2.8G                 S1_TT1.asm.ovlp.reverse.bin
14G                  S1_TT1.asm.ovlp.source.bin
1.6G                S1_TT1_mat.yak
77K                  S1_TT1_PA.asm.pri.log
1.7G                 S1_TT1_pat.yak

-First the command to generate primary/alternate assembly should generate 2 files i.e. *.asm.p_ctg.gfa and ***.asm.a_ctg.gfa**, but i got *.asm.p_ctg.gfa and ***.asm.r_ctg.gfa** instead of second file being a_ctg.gfa.

So, is the filr * .asm.r_ctg.gfa similar to .asm.a_ctg.gfa mentioned in the document.

-Second the size of the primary assembly is almost the double of what is generated by trio-binning as well as when i run hifiasm with only hifi reads default mode (250mb approx.) . Why is it so is anything wrong with the command.

**Comment by chhylp123** [comment]
There should be `bp.p_ctg` and 'bp.a_ctg' with `--primary`. I guess hifiasm has not been actually run in that mode.

**Comment by ap1438** [comment]
I have observed some unusual things with the trio binning.

- The no. of contigs differ largely between the hap1 (121) and hap 2 (611) even though the difference in genome assembly size is less  hap1(230)  hap2(235).
- Increase in k-mer  results in decrease genome size in hap1 and increase in genome size of hap2

  K-mer               Hap1(contig)                  Hap1(Size)                                         Hap2(Contig)                  Hap2(Size)
  K- mer 19        180                                   232                                                        533                                   233
  K-mer 21         155                                   231                                                        580                                   234                      
  K-mer 27         127                                   230(230327507bp)                              605                                   235(235538444bp)   
  K-mer 31         121                                  230(230155226bp)                               611                                   235(235737967bp)

It seems that increase in k-mer results in decreasing the no. of contigs in hap1 and increasing in hap2.

It means that the haplotype phasing is completely dependent on k-mer.
Can you please comment on this. Is this a problem.

**Comment by chhylp123** [comment]
This is fine. It would be better to check the assembly quality like BUSCO, contiguity, and hamming error rate, rather than assembly size or contig number.
