### ISSUE TITLE
hifiasm: Correct.cpp:3506

### ISSUE THREAD

**Issue by xzhoubayer** [chhylp123/hifiasm#389]
[M::ha_pt_gen::52334.834*15.76] ==> indexed 13410120297 positions, counted 408214577 distinct minimizer k-mers
hifiasm: Correct.cpp:3506: void recalcate_window_advance(overlap_region_alloc*, All_reads*, const ul_idx_t*, UC_Read*, Correct_dumy*, UC_Read*, kvec_t_u64_warp*, int64_t, double, double): Assertion `error != (unsigned int)-1' failed.

**Comment by xzhoubayer** [comment]
hifiasm_0.18.5 was used.

**Comment by chhylp123** [comment]
It is very likely that your input fastq files of HiFi reads have non-A/C/G/T bases. Could you please check that first?

**Comment by xzhoubayer** [comment]
Thanks a lot!
Yes, one of the fasta files is bad.
