### ISSUE TITLE
inter.cpp:16098: void gen_trans_base_count_comp(ug_trans_t*, kv_u_trans_t*): Assertion `z->nw > 0' failed.

### ISSUE THREAD

**Issue by liusc1988** [chhylp123/hifiasm#390]
The same cmd failed with 0.18.5 but work on 0.18.2.
[slurm-431996.txt](https://github.com/chhylp123/hifiasm/files/10529518/slurm-431996.txt)

**Comment by chhylp123** [comment]
If possible, could you please share the bin files with us? I might be a bug and I will have a try to fix it as soon as possible.

**Comment by liusc1988** [comment]
谢谢！已收到。查看后，会尽快给您回复。祝一切安好！

**Comment by chhylp123** [comment]
We just need `*ec.bin`, `*reverse.bin`, `*source.bin`, `*ul.ovlp.bin`, `*ul.ovlp.bin` and `*uidx.ucr.bin`.

**Comment by liusc1988** [comment]
No problem.But these data are nearly 1T. How to send them to you?

**Comment by chhylp123** [comment]
By the google drive or the onenote?

**Comment by jpnm** [comment]
Same happened to me with an assembly using HiFi+Omni-C! 
And it should not be related with software versions or hardware, as everything went well for other assemblies in the same conda environment with the same type and amount of data.

**Comment by liusc1988** [comment]
谢谢！已收到。查看后，会尽快给您回复。祝一切安好！

**Comment by chhylp123** [comment]
@jpnm Could you please try the latest release (0.18.7)? This is a bug which has already been fixed by 0.18.7.

> Same happened to me with an assembly using HiFi+Omni-C! And it should not be related with software versions or hardware, as everything went well for other assemblies in the same conda environment with the same type and amount of data.

**Comment by jpnm** [comment]
Thanks! Issue solved!
