### ISSUE TITLE
hifiasm: Correct.cpp:3287: 

### ISSUE THREAD

**Issue by xzhoubayer** [chhylp123/hifiasm#391]
hifiasm: Correct.cpp:3287: void recalcate_window_advance(overlap_region_alloc*, All_reads*, const ul_idx_t*, UC_Read*, Correct_dumy*, UC_Read*, kvec_t_u64_warp*, int64_t, double, double): Assertion `error != (unsigned int)-1' failed.

Got a bit different error message after the illegal characters in sequence fasta were removed.

**Comment by chhylp123** [comment]
I guess there are still non-ACTG or Ns.

**Comment by xzhoubayer** [comment]
I'm searching for those chars. Is 'N' ok?

**Comment by chhylp123** [comment]
No, HiFi reads shouldn't have Ns

**Comment by xzhoubayer** [comment]
After bad fasta file is removed, the issue is solved.
