### ISSUE TITLE
Use of --b-cov and --m-rate to avoid missassemblies

### ISSUE THREAD

**Issue by vpymerel** [chhylp123/hifiasm#396]
Hello !

I used hifiasm to build an insect genome assembly (HiFi only),

The assembly is very good, but there is a few misassemblies that I would like to get rid of,

More precisely I am talking about "artefactual duplications" in the primary assembly. I identified those by looking at duplicated BUSCOs. The coverage of duplicated BUSCO genes (0.5*average coverage) strongly suggests that these are not "biological duplications".

For example the picture attached represents the alignment of two contigs in the primary assembly. X and Y axis show contigs coordinates. 
![tmp](https://user-images.githubusercontent.com/98694826/217838442-6462aca4-c047-4435-bc8a-0953722917c9.png)
As we can see the beginning of one of the contig align very well to a region inside the second contig (black segment - 500Kb).

I know from coverage analysis that this aligned portion correspond to a false "duplication" (i.e. half coverage in this region),

I tried several things to get rid of these duplications, including activating "-u", increasing -a to 8, increasing -r to 5 and changing -l,

The --b-cov and --m-rate parameters seem promising to me, but I am not sure to understand precisely what they are doing,

Can you try to explain me what they are doing please ? And tell me if it is actually a good idea, or if I should try something else ?

Thank you,
V

**Comment by chhylp123** [comment]
`--b-cov` is used to break contigs around the subregions with too low coverage, while `--h-cov` is used to break subregions with too high coverage. Too low or too high coverage might be the missassemblies. As for the `--m_rate`, it is used to detect subregions that most overlaps between assembly nodes are inexact, which also means it might be a potiential misassembly. 

It is hard to see if these options could work, but worth to have a try. Actually for this type of misassemblies, I guess most people will just mannually breaks them...

**Comment by vpymerel** [comment]
Thank you, I tried to set --b-cov to half-"homozygous" coverage but it did not helped much. Anyway, histogram of coverage and BUSCO score, indicate that overall "wrong duplication rate" is low in the assembly.
