### ISSUE TITLE
Assertion `error != (unsigned int)-1' failed

### ISSUE THREAD

**Issue by lvrcek** [chhylp123/hifiasm#397]
Hi,

I am trying to assemble a single chromosome from HiFi data generated with PBSIM3. I run into the following error during the error-correction phase (I left out the two histograms printed out prior to this):
```
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 30; peak_het: -1
[M::ha_ct_shrink::22.192*6.36] ==> counted 801253 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 25124796 minimizers
[M::ha_pt_gen::24.280*7.59] ==> indexed 23966422 positions, counted 801253 distinct minimizer k-mers
hifiasm: Correct.cpp:3287: void recalcate_window_advance(overlap_region_alloc*, All_reads*, const ul_idx_t*, UC_Read*, Correct_dumy*, UC_Read*, kvec_t_u64_warp*, int64_t, double, double): Assertion `error != (unsigned int)-1' failed.
Aborted (core dumped)
```

I am running the latest version of Hifiasm (0.18.5-r499) on Ubuntu 20.04.2 LTS.
I am passing to hifiasm a FASTA file which is only 856 MB in size, and the length of the chromosome is 27.5 Mbp.

After reading some other issues:
- I don't think it is a memory issue, the files are small and there is enough memory available
- I don't think the problem is in the FASTA file itself since I am able to open it and parse it with some other tools (e.g., Biopython)

Do you have any idea what happened here?

Thank you!

**Comment by chhylp123** [comment]
The reason is that the simulated data has non-ACGT bases, while real HiFi reads only have A/C/G/T (see: https://github.com/chhylp123/hifiasm/issues/374#issuecomment-1409834241).

**Comment by lvrcek** [comment]
Understood, thank you very much!
