### ISSUE TITLE
ERROR6

### ISSUE THREAD

**Issue by amvarani** [chhylp123/hifiasm#399]
Hi there

I have got an ERROR6 message, see below:
What is it ? 

[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 106; peak_het: 12
[M::ha_ct_shrink::47042.480*55.76] ==> counted 151985453 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 3256747289 minimizers
[M::yak_count] collected 0 minimizers
[M::yak_count] collected 0 minimizers
[M::yak_count] collected 0 minimizers
[M::ha_pt_gen::47319.860*55.65] ==> indexed 3218225789 positions, counted 151985453 distinct minimizer k-mers
[M::ha_assemble::51231.256*55.97@148.917GB] ==> found overlaps for the final round
[M::ha_print_ovlp_stat] # overlaps: 220872756
[M::ha_print_ovlp_stat] # strong overlaps: 155297186
[M::ha_print_ovlp_stat] # weak overlaps: 65575570
[M::ha_print_ovlp_stat] # exact overlaps: 211076123
[M::ha_print_ovlp_stat] # inexact overlaps: 9796633
[M::ha_print_ovlp_stat] # overlaps without large indels: 220178804
[M::ha_print_ovlp_stat] # reverse overlaps: 266442006
[M::ha_opt_update_cov_min] updated max_n_chain to 530
Writing reads to disk... 
Reads has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
bin files have been written.
[M::purge_dups] homozygous read coverage threshold: 105
[M::purge_dups] purge duplication coverage threshold: 132
ERROR6
Writing raw unitig GFA to disk... 
[M::ug_ext_gfa::] # tips::3978
Writing processed unitig GFA to disk... 
[M::purge_dups] homozygous read coverage threshold: 105
[M::purge_dups] purge duplication coverage threshold: 132
[M::adjust_utg_by_primary] primary contig coverage range: [89, infinity]
Writing primary contig GFA to disk... 
Writing alternate contig GFA to disk... 
Inconsistency threshold for low-quality regions in BED files: 70%
[M::main] Version: 0.18.5-r499

**Comment by chhylp123** [comment]
It's ok. It is just a warnning.
