### ISSUE TITLE
the assembled result need to be redundant?

### ISSUE THREAD

**Issue by 18616831168** [chhylp123/hifiasm#40]
Hi,

I am trying to assemble a heterotetraploid genome. Add -l0 to the assembly parameter, and combine the information of a_ctg and p_ctg files as a result. If I want to distinguish between haplotypes, do I need to de-redundate the genome?

Thanks,
Yulin Bai

**Comment by chhylp123** [comment]
By distinguish haplotypes, would you like to know which haplotype does each contig come from, or get fully phased assembly for each haplotype?

**Comment by 18616831168** [comment]
> By distinguish haplotypes, do you want to know which haplotype does each contig come from, or get fully phased assembly for each haplotype?

yes

**Comment by 18616831168** [comment]
> By distinguish haplotypes, do you want to know which haplotype does each contig come from, or get fully phased assembly for each haplotype?

Yes, as you said.

**Comment by chhylp123** [comment]
With -l0, a_ctg + p_ctg represents lossless information, so it is no need to postprocess. If you want to get fully phased assemblies or bin contigs, you may need some additional data like HiC or trio.
