### ISSUE TITLE
Explanation for "--s-base"

### ISSUE THREAD

**Issue by shelkmike** [chhylp123/hifiasm#404]
The parameter "--s-base" has recently been introduced to Hifiasm. There is a brief explanation in https://github.com/chhylp123/hifiasm/releases/tag/0.18.4 . Could you please provide a more detailed explanation? In particular, I would like to know:
1) How is this "similarity" calculated?
2) What does a value like "0.5" mean? This is probably not the usual "sequence identity" reported by programs like BLAST.
3) Does the value of this parameter affect only haplotigs, or it affects primary contigs too?

**Comment by chhylp123** [comment]
1 && 2. Actually it is the per-base similaity calcuated by the edit distance, which is similar to the "sequence identity" reported by BLAST. `--s-base` means if a pair of unitigs have >=50% similarity, they might be identified as homologous pair. 
3. Right now it only affects HiC-phased assemblies.

**Comment by shelkmike** [comment]
Thank you.

**Comment by AlcaArctica** [comment]
Just to clarify in the release it says:

> Integrated new option --s-base to enable homology detection in base-level. This might be helpful in improving the Hi-C phasing results for the samples with very high heterozygosity or centromeres.

So now if I want to assemble a high heterozygosity genome, I should set `-s 0.55` which is the same as choosing  `-l 3`? Is that right?
