### ISSUE TITLE
 Are these assembly errors?

### ISSUE THREAD

**Issue by zhangyixing3** [chhylp123/hifiasm#405]
Dear author, I am now assembling an autopolyploid . Its ploidy is about 10. I meet some trouble in scaffolding. I use utg.fa and HIC data to partition.but I faild,more than 20000 Contigs are allocated together (in fact, we want these Contigs to be allocated to different groups). Then I use SALSA to find misassemble contig, I did find some sequences that might be incorrectly assembled. SALSA has found 295 potential mistakes, and I believe its results are conservative. It is also quite difficult to adjust the misassemble contig. The polyploid is a little different from the previous situation https://github.com/baozg/phased-assembly-check . 
Here are some of these contig's HIC heatmaps.  Can I use appropriate parameters to reduce these misassemble ？
My  parameters are  **hifiasm -o my  -t 30  -D 10 -N 200 read1.fq read2.fq read3.fq**
Thank you !
![utg000126l](https://user-images.githubusercontent.com/91043462/219951731-7f3e3a13-b9d8-4555-b526-c5ff7252f9b5.jpg)
![utg001363l](https://user-images.githubusercontent.com/91043462/219951826-c20f912e-f712-46e9-9a60-2692ef831f52.jpg)

**Comment by chhylp123** [comment]
Are you using unitigs extracted from the `p_utg.gfa`? If you are using `p_utg.gfa`, there might be not too many misassemblies.

**Comment by zhangyixing3** [comment]
I used TRF to find repetitive sequences, and found that>utg000126l: 7760000-8730000 was composed of tandem sequences, while>utg001363l: 4387500-4612500 and>utg001363l: 900000-10125000 were not
