### ISSUE TITLE
How to get coverage depth information in the GFA?

### ISSUE THREAD

**Issue by jflot** [chhylp123/hifiasm#41]
Hello,
Thanks for this very useful tool. One lacking feature (or perhaps I could just not find it?) is that there is no coverage depth information available in the GFAs produced. Is there a way to access this information (or to request for it to be added in a future update of hifiasm)?

**Comment by chhylp123** [comment]
In each S-line of gfa, the "rd:i" indicates the coverage. For example, 
>S       atg000001l      *       LN:i:43560      rd:i:12

**Comment by jflot** [comment]
Thanks for your reply, it is very useful. In my current hifiasm assemblies I notice that (in the raw utg gfa) many unitigs have coverage value indicated as zero in the "rd:i" field. This makes me wonder how hifiasm calculates the coverage values: could you provide some more details about it?

**Comment by chhylp123** [comment]
Hifiasm uses the reads of A-line to calculate coverage and considers contained reads at once. "rd:i" field is reliable for long contigs but might be not such reliable for short contigs.

**Comment by xinghua1001** [comment]
Is it necessary to filter those contigs with zero coverage? I find quite a lot of them in my assembly

**Comment by chhylp123** [comment]
> Is it necessary to filter those contigs with zero coverage? I find quite a lot of them in my assembly

How long and how many reads in these contigs? Could you please give me a few examples?
