### ISSUE TITLE
Understanding Hifiasm's PAF output

### ISSUE THREAD

**Issue by cjain7** [chhylp123/hifiasm#410]
Hi Haoyu,

I and my student @MehakBindra are trying to use Hifiasm to compute all-to-all read overlaps among long-accurate reads (e.g., HiFi or ONT Duplex). What we need is all overlaps that are above a certain identity (say 95 or 97%). For diploid genomes, we seek "good" overlaps, irrespective of whether reads come from same haplotype or different. Similarly, for haploid genomes, we would like "good" overlaps even if two reads are sampled from different near-identical repetitive regions. 

Based on our understanding, hifiasm outputs PAF file with `--write-paf` option **after** haplotype-aware error correction, i.e., after Hifiasm identifies "true" haplotype-specific overlaps for each read. We did some experiments with simulated reads sampled from HG002 genome to confirm this, where we saw fewer overlaps per read than anticipated. Please confirm if our understanding is correct.

Is it possible to get a PAF file from Hifiasm (similar to minimap2 all-to-all mode) that outputs all good haplotype-**oblivious** overlaps? I'd imagine that such overlaps are computed by hifiasm before error correction begins, but I think there is no option to retrieve them.

Thanks,
Chirag

**Comment by cjain7** [comment]
This feature request may be connected to this issue raised in minimap2 GitHub page.
https://github.com/lh3/minimap2/issues/753

**Comment by chhylp123** [comment]
Do you need all good overlaps among raw HiFi reads or corrected HiFi reads? My uderstanding is that you would like to get all cis overlaps and good trans overlaps, right?

**Comment by cjain7** [comment]
>Do you need all good overlaps among raw HiFi reads or corrected HiFi reads?

For our purpose, we seek overlaps among raw reads.

> My uderstanding is that you would like to get all cis overlaps and good trans overlaps, right?

Yes

**Comment by cjain7** [comment]
Sure, thank you!

**Comment by cjain7** [comment]
Just a reminder.
We are wishing to get all good overlaps without any filtering based on cis/trans criteria, alignment length or type of overlap (dovetail/contained) -- unless the alignment has poor sequence identity.

**Comment by chhylp123** [comment]
Sorry I missed your reminder. Will update it as soon as possible.

**Comment by chhylp123** [comment]
@cjain7 Sorry for the delay as I was quite busy during the last a few weeks. I have pushed the updated version to the github HEAD (`r555`). With `--dbg-ovec`, hifiasm will output two files, `*0.ovlp.paf` and `*1.ovlp.paf`. `*0.ovlp.paf` includes cis overlaps, while `*1.ovlp.paf` includes trans overlaps.

**Comment by cjain7** [comment]
Thank you!

**Comment by junhaiqi** [comment]
Dear Dr. Cheng,

I'd like to discuss this issue further. Hifiasm is already a powerful software. Is it possible for Hifiasm to offer an option where the user inputs a PAF file and a FASTQ file (similar to Miniasm), and then Hifiasm uses the information from the provided PAF file to complete the assembly? Currently, Hifiasm can compute a separate PAF file, which can then be used for other sequence analyses. If Hifiasm could also perform assembly based on a user-provided PAF file, this would likely fully leverage Hifiasm's advantages and greatly simplify the development of assembly software.
