### ISSUE TITLE
new questions about multiple HiC inputs

### ISSUE THREAD

**Issue by SC-Duan** [chhylp123/hifiasm#412]
Hi,
I assembly a genome with HiFi reads and HiC reads, and there are 12 sequenced lines for HiC reads. So I  refer to the issue in https://github.com/chhylp123/hifiasm/issues/298, and use the similar command line: --h1 line1_hic_1.fq.gz,line2_hic1_fq.gz,..........,line12_hic1_fq.gz --h2 line1_hic2.fq.gz,line2_hic2.fq.gz,...........,line12_hic2.fq.gz. This run just takes 1 day (used the *bin files generated from HiFi-only assembly). But when I merged all HiC lines and fed to hifiasm (--h1 all_hic_1.fq.gz --h2 all_hic_2.fq.gz), it has taken ten days and just  generated some \*hic.r_utg.\*,  \*hic.p_utg.\* and \*hic.p_ctg.\* files. Do you have a suggestion for this?
Thank you!

**Comment by chhylp123** [comment]
Could you please check if you are merging HiC reads in wrong order?

**Comment by SC-Duan** [comment]
The order is OK. There are about 1Tb HiC reads, so I think the result for un-merged HiC reads may be incorrect, it just takes 1 day (I set 80 threads and the estimated genome size is about 10Gb), did it use the reads of fist line?

**Comment by chhylp123** [comment]
Could you please share the log files?

**Comment by SC-Duan** [comment]
Hi,
The log of un-merged: [log1.txt](https://github.com/chhylp123/hifiasm/files/10830155/log1.txt)
The log of merged: [log2.txt](https://github.com/chhylp123/hifiasm/files/10830157/log2.txt)
and now the memory for merged keeps increasing.

**Comment by chhylp123** [comment]
Does the assembly produced by un-merged HiC reads look ok? The log file looks fine for me.

**Comment by SC-Duan** [comment]
It looks like the result of HiFi-only assembly, one hap is larger than another one. I am surprise for the speed between un-merged and merged. How can I check that which HiC reads was used for phasing? Like reads' ID? The *hic*bin saves the results of Hi-C alignment, so maybe I should check these files. Can it be transformed to TXT?

**Comment by chhylp123** [comment]
It is hard to say. If the input HiC reads are exactly the same, hifiasm will also output the exactly same assemblies. I guess there might be something wrong for the input data.

**Comment by SC-Duan** [comment]
Thank you! I will check it furthermore.
