### ISSUE TITLE
Question about hybrid +Trio Binning + Hi-C

### ISSUE THREAD

**Issue by carolhsb** [chhylp123/hifiasm#417]
Hi all

Thank you for the great tool!

I am working with a hybrid species and have Hi-Fi, Illumina reads from parents, and Hi-C data. What would be the best strategy to use all these types of data? 

My best guess would be to run hifiasm in Trio Binnig mode, as it does better in phasing the haplotypes, and then incorporate Hi-C data to separate scaffolds into chromosomes in Juicer/3d-dna.

My main interest is to have two haploid genomes for both species.

Best,

Carol

**Comment by chhylp123** [comment]
Yes, if you have trio data, this will be the easiest solution.

**Comment by carolhsb** [comment]
Thank you!!!
