### ISSUE TITLE
Differences between hic.p_ctg.gfa and `prefix`.p_ctg.gfa without HIC data

### ISSUE THREAD

**Issue by liusc1988** [chhylp123/hifiasm#424]
The result of adding HIC data to `prefix`.hic.p_ctg.gfa is contig N50 decrease compared to `prefix`.p_ctg.gfa without HIC data. Is it necessary to add HIC data if I only want to assemble the haploid genome? Or will `prefix`.hic.p_ctg.gfad have higher confidence than `prefix`.p_ctg.gfa?

**Comment by chhylp123** [comment]
If you don't care about phasing, then no need to add HiC data. HiC is mostly used for phasing.

**Comment by liusc1988** [comment]
谢谢！已收到。查看后，会尽快给您回复。祝一切安好！

**Comment by liusc1988** [comment]
Thanks.
