### ISSUE TITLE
hifiasm Killed during first step

### ISSUE THREAD

**Issue by vlnaraujo** [chhylp123/hifiasm#428]
Hello everyone!

I am having a problem running an assembly with hifiasm.
After aprox. 15 hours running, the job is killed and no log file with any error number of information about the problem is produced.

Available RAM: 4039588kb
Estimated genome size 3.5gb

Genomescope linear plot and log follow attached.

![linear_plot1](https://user-images.githubusercontent.com/128530689/226717842-84bc842b-ecf9-441d-bfa7-4368983fe2e6.png)
[t.log](https://github.com/chhylp123/hifiasm/files/11032748/t.log)

Do you have any idea of what is going on in this situation?

Best,
Victor

**Comment by chhylp123** [comment]
The available RAM is 4039588kb = 4Gb? 4Gb is too small for hifiasm.

**Comment by vlnaraujo** [comment]
Thanks! How much would you recommend in this situation?

**Comment by chhylp123** [comment]
I hope the peak memory should be equal to the number of bases of input HiFi reads.

**Comment by funing950529** [comment]
Dear colleague

My input HiFi reads are 114Gb in total, which is smaller than the available Mem 216 Gb. However, the running was also killed. The parameters were set as: hifiasm -o Bch.asm -t 32 --h1 1.fastq.gz --h2 2.fastq.gz  hifi.fastq.gz  2> run.log. Moreover, I am the only user on the system. In this situation, what should I do?
