### ISSUE TITLE
adding HiC data

### ISSUE THREAD

**Issue by weihongqi** [chhylp123/hifiasm#43]
Dear Haoyu,

It has been a very nice experience using hifiasm. Thanks for your exercellent wrok. 

May I ask for your suggestion on how to combine HiC data with hifiasm assemblies in general, for both phasing and scaffolding? 

Many thanks in advance. 

Kind regards,

Weihong

**Comment by chhylp123** [comment]
For fully-phased assembly of diploid sample with Hi-C, an immediate solution is to follow Shilpa Garg's pipeline here: [https://www.biorxiv.org/content/10.1101/810341v2](url), but make some modification with hifiasm:
>1. get a primary assembly by hifiasm
2. partition corrected HiFi reads generated by hifiasm with HiC
3. feed the read partition lists to hifiasm with the options '-3/-4'. This step will reuse the bin files generated by step 1. So it just does graph cleaning and don't perform reassembly.

This solution might be not the optimal in the long term, but it can already get the best Hi-C phased assembly so far.

**Comment by shilpagarg** [comment]
Yes, I agree with Haoyu. An alternative approach is to directly use the Dipasm pipeline, but additionally, use sdip (https://doi.org/10.1101/2020.02.25.964445) to improve partitioning in highly identical repetitive regions in the second last step. On my experiments with HG002 data, the continuity is comparable to trio hifiasm. I am happy to help you with this if you like.
