### ISSUE TITLE
Usage of ordinary Nanopore reads

### ISSUE THREAD

**Issue by shelkmike** [chhylp123/hifiasm#432]
The manual of Hifiasm states that Hifiasm can use ultra-long Nanopore reads. Can ordinary Nanopore reads be used by Hifiasm? Since ordinary Nanopore reads are usually longer than HiFi reads, it seems that even ordinary (non-ultralong) Nanopore reads should be beneficial for assembly.

**Comment by chhylp123** [comment]
Yes, it can. But it would be better to filter out too short ONT reads.

**Comment by hrpelg** [comment]
Hi, I am interested in feeding hifiasm with hifi reads as with ordinary ONT reads, how can be that done? any specific commands?
Cheers

E

**Comment by chhylp123** [comment]
You can just treat ordinary ONT reads as UL reads.

**Comment by Huyuxi08** [comment]
> Yes, it can. But it would be better to filter out too short ONT reads.

Hi @chhylp123 ! What read length would you recommend filtering out reads below?
