### ISSUE TITLE
Unitig graph with tetraploid

### ISSUE THREAD

**Issue by Seajull** [chhylp123/hifiasm#434]
Hi, I'm trying to assemble a tetraploid with hifiasm and i'm using the unitig graph (p_utg.gfa) since this graph is lossless. 
But i can' t find what "lossless" really mean : 

- Are the size of unitig graph the expected size of the whole genome (4x size of haplotype genome size) ?
- How homozygous unitig / region are represented ? Are they collapsed into one unitig ?

Thanks !

**Comment by chhylp123** [comment]
Sorry for the late reply.
> Are the size of unitig graph the expected size of the whole genome (4x size of haplotype genome size) ?
It will be a bit larger since the unitig graph have many overlaps between nodes. These overlaps will double the size. 

>How homozygous unitig / region are represented ? Are they collapsed into one unitig ?
Yes.

**Comment by Seajull** [comment]
Thank you !
