### ISSUE TITLE
Extra purge_dups or stringnet (-s) when heterozygosity is not expected, but duplication appears in assembly?

### ISSUE THREAD

**Issue by igwill** [chhylp123/hifiasm#437]
Hello,

I've assembled a few genomes that Hifiasm (0.18.4-r496) has handled quite well so far. For one of my genomes, I am getting more BUSCO duplication (80%) and larger genome size (5x bigger) than I would have expected. However, based on an initial Genomescope check, I saw no evidence of high heterozygosity, and we would have assumed this fungal mycelium sample was in a haploid asexual phase.
Even if I could torture the assembly to fit my expectations, Hifiasm may be in fact indicating there has been large duplication events in this genome. I was hoping you could provide some insight into if Hifiasm is indeed working correctly, or needs some help with new parameters?

**Primary assembly overviews (from Quast and BUSCO), either setting -l0 or allowing default (+ a HiCanu assembly for comparison). Only Hifi reads used:**

Assembly | Mbp | Avg.Coverage | Contigs | N50 (Mbp) | largest contig | BUSCO-C | BUSCO-S | BUSCO-D | BUSCO-exons
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
-l0 set|129 | 40 | 567 | 0.65| 7.88 |98.2 | 16.8 | 81.4 | 22208
Default|**123.2** | 42 | 538 | 0.65 | 7.88 | 98.1 | 19.3 | **78.8** | 29171
Canu|129.5 | 40 | 1372 | 0.24 | 7.88 | 98.2 | 16.7 | 81.5 | 22688

Based on a lower coverage Spades+Illumina assembly previously done by others, this new Hifiasm+Pacbio assembly is much larger and more duplicated, but not much more BUSCO complete. That Spades assembly was 27.1 Mbp and BUSCO-Complete 94.5% (SC: 94%, Dup: 0.7%). I don't know every detail of SPADES under the hood, but do know that it is probably optimized to work with/produce small genomes (esp. bacterial genomes).

**This is the Genomescope that had me assuming no/low heterozygosity:**
![TZomb_genomescope_plot](https://user-images.githubusercontent.com/24592158/229891502-77317dff-b519-4eab-8c23-7fbcc24139a3.png)

(To handle the large "error" peak, I also set -min-hist-cov 10)

**This is the tailend of the Hifiasm output/log for the default-settings run, it seems to be doing a good job at identifying the homozygous peak and not finding a heterozygous one. Although, the estimate of initial 140x coverage comes way down once the assembly is done and the reads mapped back with Quast (~40x, see table at start):**
[M::ha_assemble::8244.102*15.70@17.710GB] ==> corrected reads for round 3
[M::ha_assemble] # bases: 4877046300; # corrected bases: 34764; # recorrected bases: 3100
[M::ha_assemble] size of buffer: 0.475GB
[M::yak_count] collected 135513602 minimizers
[M::ha_pt_gen::8272.108*15.69] ==> counted 3663722 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[28] = 833
[M::ha_analyze_count] highest: count[142] = 17851
[M::ha_hist_line]     1: ****************************************************************************************************> 90482
[M::ha_hist_line]     2: ****************************************************************************************************> 61200
[M::ha_hist_line]     3: ****************************************************************************************************> 113581
[M::ha_hist_line]     4: ****************************************************************************************************> 185433
[M::ha_hist_line]     5: ****************************************************************************************************> 253515
[M::ha_hist_line]     6: ****************************************************************************************************> 301674
[M::ha_hist_line]     7: ****************************************************************************************************> 326787
[M::ha_hist_line]     8: ****************************************************************************************************> 325157
[M::ha_hist_line]     9: ****************************************************************************************************> 292410
[M::ha_hist_line]    10: ****************************************************************************************************> 251281
[M::ha_hist_line]    11: ****************************************************************************************************> 200017
[M::ha_hist_line]    12: ****************************************************************************************************> 150465
[M::ha_hist_line]    13: ****************************************************************************************************> 105589
[M::ha_hist_line]    14: ****************************************************************************************************> 71734
[M::ha_hist_line]    15: ****************************************************************************************************> 46969
[M::ha_hist_line]    16: ****************************************************************************************************> 29095
[M::ha_hist_line]    17: *************************************************************************************************** 17688
[M::ha_hist_line]    18: *********************************************************** 10538
[M::ha_hist_line]    19: ************************************ 6498
[M::ha_hist_line]    20: ************************ 4361
[M::ha_hist_line]    21: ***************** 3083
[M::ha_hist_line]    22: ************* 2381
[M::ha_hist_line]    23: ********** 1737
[M::ha_hist_line]    24: ********* 1546
[M::ha_hist_line]    25: ******* 1257
[M::ha_hist_line]    26: ****** 1075
[M::ha_hist_line]    27: ***** 960
[M::ha_hist_line]    28: ***** 833
[M::ha_hist_line]    29: ***** 842
[M::ha_hist_line]    30: **** 717
[M::ha_hist_line]    31: *** 605
[M::ha_hist_line]    32: *** 552
[M::ha_hist_line]    33: *** 506
[M::ha_hist_line]    34: ** 434
[M::ha_hist_line]    35: ** 418
[M::ha_hist_line]    36: ** 381
[M::ha_hist_line]    37: ** 357
[M::ha_hist_line]    38: ** 332
[M::ha_hist_line]    39: ** 382
[M::ha_hist_line]    40: ** 331
[M::ha_hist_line]    41: ** 387
[M::ha_hist_line]    42: ** 327
[M::ha_hist_line]    43: ** 370
[M::ha_hist_line]    44: ** 373
[M::ha_hist_line]    45: ** 430
[M::ha_hist_line]    46: *** 459
[M::ha_hist_line]    47: ** 432
[M::ha_hist_line]    48: *** 479
[M::ha_hist_line]    49: ** 422
[M::ha_hist_line]    50: *** 464
[M::ha_hist_line]    51: *** 466
[M::ha_hist_line]    52: ** 360
[M::ha_hist_line]    53: ** 388
[M::ha_hist_line]    54: ** 409
[M::ha_hist_line]    55: ** 342
[M::ha_hist_line]    56: ** 325
[M::ha_hist_line]    57: ** 395
[M::ha_hist_line]    58: ** 384
[M::ha_hist_line]    59: ** 381
[M::ha_hist_line]    60: ** 440
[M::ha_hist_line]    61: ** 371
[M::ha_hist_line]    62: *** 458
[M::ha_hist_line]    63: ** 343
[M::ha_hist_line]    64: ** 281
[M::ha_hist_line]    65: ** 287
[M::ha_hist_line]    66: ** 283
[M::ha_hist_line]    67: ** 330
[M::ha_hist_line]    68: ** 282
[M::ha_hist_line]    69: ** 365
[M::ha_hist_line]    70: ** 286
[M::ha_hist_line]    71: ** 326
[M::ha_hist_line]    72: ** 304
[M::ha_hist_line]    73: ** 296
[M::ha_hist_line]    74: ** 376
[M::ha_hist_line]    75: ** 361
[M::ha_hist_line]    76: ** 352
[M::ha_hist_line]    77: ** 412
[M::ha_hist_line]    78: ** 419
[M::ha_hist_line]    79: *** 510
[M::ha_hist_line]    80: *** 564
[M::ha_hist_line]    81: *** 572
[M::ha_hist_line]    82: *** 598
[M::ha_hist_line]    83: *** 604
[M::ha_hist_line]    84: **** 669
[M::ha_hist_line]    85: **** 704
[M::ha_hist_line]    86: **** 684
[M::ha_hist_line]    87: ***** 815
[M::ha_hist_line]    88: ***** 863
[M::ha_hist_line]    89: ***** 907
[M::ha_hist_line]    90: ***** 980
[M::ha_hist_line]    91: ****** 1131
[M::ha_hist_line]    92: ******* 1186
[M::ha_hist_line]    93: ******* 1238
[M::ha_hist_line]    94: ******** 1391
[M::ha_hist_line]    95: ********* 1572
[M::ha_hist_line]    96: ********* 1591
[M::ha_hist_line]    97: ********** 1768
[M::ha_hist_line]    98: *********** 1897
[M::ha_hist_line]    99: ************ 2118
[M::ha_hist_line]   100: ************ 2164
[M::ha_hist_line]   101: ************* 2259
[M::ha_hist_line]   102: ************* 2371
[M::ha_hist_line]   103: ************** 2564
[M::ha_hist_line]   104: *************** 2726
[M::ha_hist_line]   105: **************** 2940
[M::ha_hist_line]   106: ****************** 3287
[M::ha_hist_line]   107: ******************** 3503
[M::ha_hist_line]   108: ******************** 3628
[M::ha_hist_line]   109: ********************** 3979
[M::ha_hist_line]   110: *********************** 4089
[M::ha_hist_line]   111: ************************** 4586
[M::ha_hist_line]   112: **************************** 5032
[M::ha_hist_line]   113: ******************************* 5490
[M::ha_hist_line]   114: ******************************** 5751
[M::ha_hist_line]   115: ************************************ 6392
[M::ha_hist_line]   116: ************************************** 6725
[M::ha_hist_line]   117: *************************************** 7026
[M::ha_hist_line]   118: ******************************************* 7624
[M::ha_hist_line]   119: ****************************************** 7542
[M::ha_hist_line]   120: ********************************************** 8183
[M::ha_hist_line]   121: ************************************************ 8531
[M::ha_hist_line]   122: *************************************************** 9143
[M::ha_hist_line]   123: ****************************************************** 9577
[M::ha_hist_line]   124: ******************************************************* 9852
[M::ha_hist_line]   125: ************************************************************ 10642
[M::ha_hist_line]   126: *************************************************************** 11229
[M::ha_hist_line]   127: ***************************************************************** 11586
[M::ha_hist_line]   128: ******************************************************************** 12053
[M::ha_hist_line]   129: *********************************************************************** 12736
[M::ha_hist_line]   130: *************************************************************************** 13324
[M::ha_hist_line]   131: **************************************************************************** 13632
[M::ha_hist_line]   132: ****************************************************************************** 13973
[M::ha_hist_line]   133: ******************************************************************************** 14351
[M::ha_hist_line]   134: ************************************************************************************ 15036
[M::ha_hist_line]   135: ************************************************************************************ 15075
[M::ha_hist_line]   136: **************************************************************************************** 15737
[M::ha_hist_line]   137: ****************************************************************************************** 15977
[M::ha_hist_line]   138: ********************************************************************************************* 16535
[M::ha_hist_line]   139: *********************************************************************************************** 16934
[M::ha_hist_line]   140: *********************************************************************************************** 16936
[M::ha_hist_line]   141: ************************************************************************************************** 17474
[M::ha_hist_line]   142: **************************************************************************************************** 17851
[M::ha_hist_line]   143: ************************************************************************************************** 17486
[M::ha_hist_line]   144: ************************************************************************************************* 17393
[M::ha_hist_line]   145: ************************************************************************************************ 17186
[M::ha_hist_line]   146: *********************************************************************************************** 16967
[M::ha_hist_line]   147: ********************************************************************************************** 16777
[M::ha_hist_line]   148: ******************************************************************************************* 16250
[M::ha_hist_line]   149: ****************************************************************************************** 16021
[M::ha_hist_line]   150: *************************************************************************************** 15489
[M::ha_hist_line]   151: ************************************************************************************* 15209
[M::ha_hist_line]   152: ********************************************************************************* 14527
[M::ha_hist_line]   153: ******************************************************************************* 14151
[M::ha_hist_line]   154: *************************************************************************** 13423
[M::ha_hist_line]   155: *********************************************************************** 12631
[M::ha_hist_line]   156: ******************************************************************** 12100
[M::ha_hist_line]   157: ****************************************************************** 11821
[M::ha_hist_line]   158: ************************************************************** 11054
[M::ha_hist_line]   159: ********************************************************** 10377
[M::ha_hist_line]   160: ******************************************************* 9765
[M::ha_hist_line]   161: ************************************************** 8992
[M::ha_hist_line]   162: *********************************************** 8386
[M::ha_hist_line]   163: ******************************************* 7667
[M::ha_hist_line]   164: ****************************************** 7414
[M::ha_hist_line]   165: ************************************** 6828
[M::ha_hist_line]   166: *********************************** 6245
[M::ha_hist_line]   167: ********************************* 5917
[M::ha_hist_line]   168: ****************************** 5401
[M::ha_hist_line]   169: **************************** 5082
[M::ha_hist_line]   170: ************************** 4669
[M::ha_hist_line]   171: ************************ 4208
[M::ha_hist_line]   172: *********************** 4064
[M::ha_hist_line]   173: ******************** 3628
[M::ha_hist_line]   174: ******************* 3376
[M::ha_hist_line]   175: ***************** 2989
[M::ha_hist_line]   176: *************** 2714
[M::ha_hist_line]   177: ************ 2171
[M::ha_hist_line]   178: *********** 1925
[M::ha_hist_line]   179: ********* 1610
[M::ha_hist_line]   180: ******** 1420
[M::ha_hist_line]   181: ******* 1194
[M::ha_hist_line]   182: ****** 1055
[M::ha_hist_line]   183: ***** 878
[M::ha_hist_line]   184: **** 736
[M::ha_hist_line]   185: **** 659
[M::ha_hist_line]   186: *** 554
[M::ha_hist_line]   187: *** 540
[M::ha_hist_line]   188: ** 432
[M::ha_hist_line]   189: ** 391
[M::ha_hist_line]   190: ** 310
[M::ha_hist_line]   191: * 255
[M::ha_hist_line]   192: * 221
[M::ha_hist_line]   193: * 161
[M::ha_hist_line]   194: * 141
[M::ha_hist_line]   195: * 125
[M::ha_hist_line]   196: * 101
[M::ha_hist_line]   197: * 90
[M::ha_hist_line]   198: * 90
[M::ha_hist_line]  rest: ************************************* 6681
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 142; peak_het: -1
[M::ha_ct_shrink::8272.145*15.69] ==> counted 3573240 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 135513602 minimizers
[M::ha_pt_gen::8300.476*15.68] ==> indexed 135423120 positions, counted 3573240 distinct minimizer k-mers
[M::ha_assemble::8639.341*15.69@17.710GB] ==> found overlaps for the final round
[M::ha_print_ovlp_stat] # overlaps: 207103189
[M::ha_print_ovlp_stat] # strong overlaps: 2475093
[M::ha_print_ovlp_stat] # weak overlaps: 204628096
[M::ha_print_ovlp_stat] # exact overlaps: 205950945
[M::ha_print_ovlp_stat] # inexact overlaps: 1152244
[M::ha_print_ovlp_stat] # overlaps without large indels: 207060281
[M::ha_print_ovlp_stat] # reverse overlaps: 431644
Writing reads to disk...
Reads has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
Writing ma_hit_ts to disk...
ma_hit_ts has been written.
bin files have been written.
[M::purge_dups] homozygous read coverage threshold: 141
[M::purge_dups] purge duplication coverage threshold: 177
Writing raw unitig GFA to disk...
[M::ug_ext_gfa::] # tips::255
Writing processed unitig GFA to disk...
[M::purge_dups] homozygous read coverage threshold: 141
[M::purge_dups] purge duplication coverage threshold: 177
[M::mc_solve:: # edges: 178]
[M::mc_solve_core_adv::0.026] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [119, infinity]
Writing TZomb_hifiasm.bp.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [119, infinity]
Writing TZomb_hifiasm.bp.hap1.p_ctg.gfa to disk...
[M::adjust_utg_by_trio] primary contig coverage range: [119, infinity]
Writing TZomb_hifiasm.bp.hap2.p_ctg.gfa to disk...
Inconsistency threshold for low-quality regions in BED files: 70%

So, does it look like Hifiasm needs help (e.g. external purge_dups or low -s? it seems to do fine with reading the coverage peak, so hom-cov probably doesn't need fiddled with?) or might this be one of those cases where BUSCO is imperfect and this fungus might just has some unexpected biology that the more fragmented SPADES assembly couldn't pick up on? I'm running a [-s 0.2] assembly right now, but even if it "works" - is it right will be the question.

Thank you!

**Comment by igwill** [comment]
Followup information - it seems like that error(contamination?)-peak seen in the kmer plots < 20x has made its way into the assembly. Only one contig appears to be bacterial contamination, the rest are getting fungal-only blast hits, as expected (and I think we would have detected multiple strains of fungi in our cultures...)

When mapping reads, we get this information (showing just 25 contigs):
contig | length (bp) | numreads | covbases | coverage | meandepth | meanbaseq | meanmapq
-- | -- | -- | -- | -- | -- | -- | --
ptg000001l | 155077 | 211 | 155077 | 100 | 8.57029 | 85.6 | 58.9
ptg000002l | 627181 | 886 | 627181 | 100 | 9.42511 | 86.2 | 59.7
ptg000003l | 427504 | 610 | 427500 | 99.9991 | 9.18001 | 85.9 | 59.8
ptg000004l | 543935 | 771 | 543935 | 100 | 9.25403 | 86.4 | 59.6
**ptg000005l** | 6286237 | 150483 | 6286236 | 100 | **142.819** | 85.8 | 59.5
ptg000006l | 340733 | 479 | 340733 | 100 | 8.77574 | 83.9 | 60
ptg000007l | 851151 | 1210 | 851149 | 99.9998 | 8.83869 | 84.6 | 59.9
ptg000008l | 1304923 | 1786 | 1304923 | 100 | 8.91422 | 85.8 | 59.8
ptg000009l | 4328940 | 6042 | 4328926 | 99.9997 | 9.11932 | 86 | 59.8
ptg000010l | 1404556 | 2033 | 1404549 | 99.9995 | 9.11132 | 85.3 | 60
ptg000011l | 236836 | 329 | 236836 | 100 | 8.73884 | 84.9 | 60
ptg000012l | 1936137 | 2682 | 1936135 | 99.9999 | 9.07822 | 85.4 | 59.9
**ptg000013l** | 7879388 | 186663 | 7879388 | 100 | **141.124** | 85.8 | 59.8
ptg000014l | 127145 | 170 | 127142 | 99.9976 | 8.10181 | 85.6 | 60
ptg000015l | 226648 | 346 | 226648 | 100 | 9.60808 | 84.3 | 60
ptg000016l | 821741 | 1113 | 821741 | 100 | 8.87876 | 84.9 | 59.8
**ptg000017l** | 3814683 | 88341 | 3814683 | 100 | **138.256** | 85.8 | 60
ptg000018l | 226167 | 305 | 226167 | 100 | 8.95141 | 84.4 | 60
ptg000019l | 77602 | 103 | 77602 | 100 | 7.9984 | 86.3 | 60
**ptg000020l** | 4938908 | 115553 | 4938905 | 99.9999 | **139.64** | 85.8 | 59.9
ptg000021l | 1318673 | 1849 | 1318673 | 100 | 9.20758 | 86.2 | 60
ptg000022l | 623305 | 889 | 623304 | 99.9998 | 9.18669 | 85.9 | 59.8
ptg000023l | 881505 | 1350 | 881494 | 99.9988 | 9.62369 | 85.7 | 59.8
ptg000024l | 390575 | 465 | 390560 | 99.9962 | 7.46278 | 84.3 | 60
ptg000025l | 221786 | 195 | 221784 | 99.9991 | 5.76952 | 86 | 60

You'll see that we have a few nice contigs hitting right around that predicted 142x homozygous coverage, and many contigs coming in at the ~10x we expect from the error peak. Using a rough cutoff of contigs with 70x minimum coverage, that totals about 28Mbp, matching the SPADES assembly very nicely.

Now my question is, does hifiasm have a parameter where I can help inform it to disregard some of these reads during assembly? Or, is it up to me to make a somewhat arbitrary cutoff call on contig mean coverage and remove a bunch of these after assembly?

Cheers

**Comment by chhylp123** [comment]
Sorry for the late reply. It is hard for hifiasm to utilize the assumption of coverage, since hard-to-assembled regions may have abnormal coverages. It might be better to postprocessing the additional contigs by yourself, as you can see hifiasm is able to seperate the contamination and real contigs.

**Comment by igwill** [comment]
Okay, thank you for the feedback and the not-so-late reply!

**Comment by HouYan20** [comment]
@igwill 
Hi,
I am new to genome assembly projects and I'm curious about how you obtained the statistics presented in your table as following. Could you please inform me which tool you used? Thanks a lot in advance!
![图片](https://github.com/chhylp123/hifiasm/assets/95693906/0ad58964-1271-4163-b23f-7be74ac781c1)

**Comment by igwill** [comment]
Hi, I think I was just using Samtools. Maybe Quast as well.
