### ISSUE TITLE
fixing the mis-connection

### ISSUE THREAD

**Issue by zhaotao1987** [chhylp123/hifiasm#440]
Hello,

When I performed hic scaffolding of the hifiasm contigs, as we can see from the picture, the end of the group 12a contig contains two times alletic segments (which should be cut and assign one part to group 12b) , but this is an entire contig from hifiasm.
What would you recommend to fix mis-connections like this? 

Thanks very much!

Best, Tao

![image](https://user-images.githubusercontent.com/16197676/230767562-d21a5535-ed57-48a8-bf60-a19c7fa8ab3d.png)

**Comment by chhylp123** [comment]
You could have try with `--u` to disabe the postjoining, which might be helpful. The latest release might be also helpful to avoid misjoining. However, as the misjoining is clear, it might be better to directly break the current contigs.

**Comment by zhaotao1987** [comment]
Thanks very much for your response!
