### ISSUE TITLE
output ultra long corrected reads

### ISSUE THREAD

**Issue by chklopp** [chhylp123/hifiasm#444]
Hi,

Is there a parameter to output fully corrected or almost fully corrected UL reads in fasta or fastq format?

Cheers,

**Comment by chhylp123** [comment]
Hifiasm does not do the base-level correcton for the UL reads, so it cannot output the corrected UL reads.

**Comment by chklopp** [comment]
Thank you.
Do you know at tool which would take hifi + UL and output corrected UL?

What is the impact of the --ul-rate parameter, if I leave default (0.2) for r10.4 reads will it be less efficient to use UL?

**Comment by chhylp123** [comment]
`--ul-rate 0.2` indicates the UL alignment allows at most 20% errors. If r10.4 reads have less number of errors, probably you could have a try with `--ul-rate 0.05`. This might be able to resolve more repeats or make the UL alignment steps faster. 

As for the hybrid correction, I'm not sure if @GuillaumeHolley 's tool could work (see: https://github.com/DecodeGenetics/Ratatosk).

**Comment by chklopp** [comment]
Thank you.
