### ISSUE TITLE
Process Killed after HiC integration

### ISSUE THREAD

**Issue by amvarani** [chhylp123/hifiasm#449]
Hi there!

I am assembling a 4G polyploid genome. The hifiasm performs well when using only the HiFi reads, successfully generating the assembly. However, upon introducing the HiC reads, an error appears in the log below.
The server being used has 60 cores and 512 GB of RAM.

Can you provide any insights into this issue?

Reads has been loaded.
Loading ma_hit_ts from disk... 
ma_hit_ts has been read.
Loading ma_hit_ts from disk... 
ma_hit_ts has been read.
[M::ha_assemble::228.291*0.72] ==> loaded corrected reads and overlaps from disk
[M::ha_opt_update_cov_min] updated max_n_chain to 485
[M::purge_dups] homozygous read coverage threshold: 96
[M::purge_dups] purge duplication coverage threshold: 121
ERROR6
[M::ug_ext_gfa::] # tips::3983
Writing raw unitig GFA to disk... 
[M::ug_ext_gfa::] # tips::1
Writing processed unitig GFA to disk... 
[M::purge_dups] homozygous read coverage threshold: 96
[M::purge_dups] purge duplication coverage threshold: 121
[M::adjust_utg_by_primary] primary contig coverage range: [81, infinity]
Writing genome.hic.p_ctg.gfa to disk... 
[M::ha_opt_update_cov] updated max_n_chain to 485
Killed

**Comment by chhylp123** [comment]
This is caused by no enough memory. The polyploid Hi-C assembly may require huge memory with current hifiasm, and the results are also not prefect. Probably it is not worth to have a try specificlly if you don't have enough memory.
