### ISSUE TITLE
Difference between "prefix.hap1.p_ctg.gfa" and "prefix.hap1.a_ctg.gfa" ?

### ISSUE THREAD

**Issue by 18616831168** [chhylp123/hifiasm#45]
Hi,
I want to know the difference between "prefix.hap1.p_ctg.gfa" and "prefix.hap1.a_ctg.gfa", is there any difference between them? If I do not need to distinguish haplotypes, can I consider "prefix.hap1.p_ctg.gfa" as the final result after assembly? Thanks  a lot！

**Comment by chhylp123** [comment]
Yes. "prefix.hap1.p_ctg.gfa" includes the primary contigs while "prefix.hap1.a_ctg.gfa" includes haplotigs.
