### ISSUE TITLE
UL integration sequencing depth requirement 

### ISSUE THREAD

**Issue by BitaoQiu** [chhylp123/hifiasm#451]
Dear Hifiasm authors,

We are planning to integrate PacBio Hifi and ONT UL to assembly a single individual genome. May I ask what is the sequencing depth requirement for UL? Because we can only obtain limited amount of DNA from a single individual, we wonder if 20x coverage for HiFi and 10x coverage for ONT will be enough? Or have you done downsampling to test the influence of UL depth?

Also, we wonder what is the principle for HiFi and UL integration? [Will the paper be out soon?] We notice that assembly duplication rate is negatively correlated with HiFi sequencing depth, so we hope UL integration can resolve this problem. May I ask does UL integration help reducing false duplication due to heterozygosity? 

Best regards,
Bitao

**Comment by chhylp123** [comment]
I think it depends on the sample. If the sample is easy to be assembled, the coverage requirement should be lower. For large genomes like the human genome, it seems 35x HiFi + 20x UL could produce decent assemblies. I'm not 100% sure how much it required for small genomes. But in principle, the coverage requirement should be lower. As there is no enough DNA, another solution is to get higher coverage of HiFi reads, which sometimes may produce better assemblies. Higher coverage of HiFi reads will make assemblies more compele, while the power of UL integration is to assemble through very complex regions. 

As for the duplication rate, I guess it mainly becauses the assemblies are more contiguous with higher coverage of HiFi reads, so there are significantly less number of fragmented contigs. UL is also helpful for that. Hopefully we could make the preprint out soon.

**Comment by BitaoQiu** [comment]
@chhylp123 Thank you for the reply. Hope we can see the preprint out soon!

BTW, would you recommend integrating HiFi low input and HiFi ultra-low input (from the same individual) for hifiasm? It seems to me HiFi ultra-low input can generate much more data, so there will be less number of fragmented contigs. 

However, I can imagine that because HiFi ultra-low input require PCR amplification, the genome coverage will not be even due to amplification bias. Because the step of purge duplicate in Hifiasm is based on coverage (assuming to be diploid), do you think HiFi ultra low-input will impact hifiasm performance? 

Best regards,
Bitao

**Comment by chhylp123** [comment]
I have no sense about HiFi ultra-low input. But if hifiasm could directly assemble through these regions with abnormal coverages, the uneven coverage issue won't affect the final results.

**Comment by BitaoQiu** [comment]
I see. Thank you for the input!
