### ISSUE TITLE
Multiple fastq for UL reads

### ISSUE THREAD

**Issue by Mar10L** [chhylp123/hifiasm#453]
Hi,
how can I submit multiple fastq files for ul reads without specifying every single file?
`hifiasm -ul ont_*fastq hifi.fastq` or using stdout of a subshell doesn't seem to work.

**Comment by chhylp123** [comment]
Please also note the option for UL is '--ul' instead of '-ul'.

**Comment by Mar10L** [comment]
Thanks for the answer.
Given the fact that I have about fifty distinct fastq files, I was wondering if there could be any other way to list all the files (without merging them and generating a unique fastq file).

Thanks for the `--ul` correction (it was a typing error in my comment, not in the command I ran).

**Comment by baozg** [comment]
Simple bash works. I use 
```bash
hifiasm -t 64 -l 0 --ul `ls *.pass.ul.fastq.gz|tr '\n' ','|perl -ple 'chop'` *.hifi.fastq.gz

```
