### ISSUE TITLE
Add Clarification to Readme about Yak functionality with wildcards

### ISSUE THREAD

**Issue by ahulsekemp** [chhylp123/hifiasm#458]
Please add a clarification to the Readme.md file for functionality of wildcards in use of trio binning of parental data. Suggest to add something like the following to the end of the **Trio binning** section.
_________
Wildcards cannot be used to feed in parental fastq files. Multiple files parental read files (IE off different sequencing lanes) should be combined prior to running `yak count`.

`cat paternal*.fq.gz > combined.paternal.fq.gz`

then run 

`yak count -k31 -b37 -t16 -o pat.yak combined.paternal.fq.gz`

**Comment by chhylp123** [comment]
Thanks a lot. We should make it more clear soon. Another way is to: 
> yak count -k31 -b37 -o mat.yak <(zcat *.fastq.gz) <(zcat *.fastq.gz)
