### ISSUE TITLE
restarting a failed Hifiasm run

### ISSUE THREAD

**Issue by Jokendo-collab** [chhylp123/hifiasm#460]
I have been running Hifiasm for for days then it failed due to memory. I was wondering if there is a way I can restart it from where it failed to avoid waiting for another 4 days or so.

**Comment by chhylp123** [comment]
If hifiasm has already produced bin files, then it can reuse those bin files to save the time.

**Comment by Jokendo-collab** [comment]
No the pricess stopped at "indexing" stage. There are no bin files. I will rerun it from scratch

**Comment by JohnUrban** [comment]
Does one simply restart HiFiasm if it has the bin files? Or do we need to use additional options/flags to point to the bin files?
