### ISSUE TITLE
How to choose k-mer size for trio-binning assembly

### ISSUE THREAD

**Issue by LQHHHHH** [chhylp123/hifiasm#47]
Hi,
I used the HiFiasm trio mode to phased my genome into maternal and paternal assembly. The first step is using yak to generate trio index. When I used ```yak count -b37 -t16 -k21``` and ```yak count -b37 -t16 -k19``` the genome size was **different**. -k21 will generate larger genome size than -k19 with the same parameters using hifiasm to assemble. So It's there any formula like Canu-trio can suggest the best k-mer size for user? 
Thanks!

**Comment by lh3** [comment]
What is the difference? Generally, trio binning is a noisy process with many reads mispartitioned. You can't expect to get identical results with different k-mer sizes or short read datasets. If unsure, follow the README and use the default 31-mer. 21-mer or 19-mer is too short and will hurt binning.

**Comment by LQHHHHH** [comment]
Ok, I will try 31-mer. Thank you
