### ISSUE TITLE
HiFiasm job paralization

### ISSUE THREAD

**Issue by Jokendo-collab** [chhylp123/hifiasm#474]
I am running `hifiasm` of ~1.4GB genome using both the ONT and PacBio HiFi data. The program is stuck at `[M::ha_pt_gen::21255.245*7.18] ==> indexed 5753798835 positions, counted 251767750 distinct minimizer k-mers` for over three days. How can one speed the analysis? I have sufficient computational resources though. Any suggestion(s)?

**Comment by chhylp123** [comment]
So sorry for the late reply. Did hifiasm pass this step right now?

**Comment by Jokendo-collab** [comment]
No. We have ~2000 ONT and anytime I run it it fails. I gave up lol. Shawn Burgess (my PI at NIH) suggested we concatenate the ONT data. I am not sure why it's failing even after giving ~800GB of memory.

**Comment by chhylp123** [comment]
Could you please show the command lines? It is a little bit weird. Thanks in advance.

**Comment by Jokendo-collab** [comment]
I use the following script:
`hifiasm -o fish_11_hifiasm_ul.asm -t 48 -l 0 --ul /ont_data/*.fastq.gz /hifi_data/*.fastq.gz`

**Comment by chhylp123** [comment]
The problem is that you were feeding UL reads inappropriate, so that hifiasm treated some of UL reads as HiFi reads. To do that (see: https://github.com/chhylp123/hifiasm/issues/453),
`hifiasm -o fish_11_hifiasm_ul.asm -t 48 -l 0 --ul `ls /ont_data/*.fastq.gz|tr '\n' ','|perl -ple 'chop'` /hifi_data/*.fastq.gz`

**Comment by Jokendo-collab** [comment]
Do you have an
![Screen Shot 2023-07-24 at 10 42 10 AM](https://github.com/chhylp123/hifiasm/assets/26459707/d129e5df-1b18-4949-9286-1d4854be7094)

**Comment by chhylp123** [comment]
This graph looks not bad?

**Comment by Jokendo-collab** [comment]
That

**Comment by Jokendo-collab** [comment]
This is actually from verkko. The one from Hifiasm is attached and it look disconnected. How can I improve the hifiasm assembly?
<img width="1118" alt="Screen Shot 2023-07-25 at 11 47 28 AM" src="https://github.com/chhylp123/hifiasm/assets/26459707/6a24a67b-e718-4c9a-a4ed-0219b3ce7f7d">

**Comment by chhylp123** [comment]
Which graph are you using for hifiasm? Do you have the log file for the new run?

**Comment by Jokendo-collab** [comment]
Attached please find the logfile for the above bandageNG plot. You may have a look and advise. I used the following script to run hifiasm: ```hifiasm -o fish_11_hifiasm_ul.asm -t 48 -l 0 --ul `ls *.fastq.gz | tr '\n' ',' | perl -ple 'chop'` /data/okendojo/zebrafish/data/fish11/hifi/*.fastq.gz```
[slurm-4935636.out.zip](https://github.com/chhylp123/hifiasm/files/12176439/slurm-4935636.out.zip)

**Comment by chhylp123** [comment]
Could you please show the `p_utg`?

**Comment by Jokendo-collab** [comment]
My `fish_11_hifiasm_ul.asm.bp.p_utg.gfa` plot looks as follow:

![Screen Shot 2023-07-26 at 3 48 14 PM](https://github.com/chhylp123/hifiasm/assets/26459707/20f7c31b-bfc7-4e15-bd27-bfb53ca5bcf0)

**Comment by chhylp123** [comment]
Thanks. I would say the graphs of hifiasm and verkko are different due to the visualization. For instance, hifiasm keeps small bubbles within the `p_utg` graph, but verkko tends to directly pop them from the graph. These bubbles are likely to be the somatic mutations and won't hurt the final assemblies. So how do the final contigs look like? If the final contigs of hifiasm are fine, hifiasm should be ok.

**Comment by Jokendo-collab** [comment]
The question is why are there more disconnection from the `p_ctg.gfa` because that is the graph file containing the phased blocks. The previous bangageplot is from the `p_ctg.gfa` and it is appear to be different from verkko. 
I did not get what this means `So how do the final contigs look like?`

What I chck the N50, Hifiasm give `~44MB` and verkko gives `~56MB` close to ~12mb difference. Would you mind sparing me some time on Friday after the VGP call and discuss this with us? I think Shawn will be available for a small talk. Let me know

**Comment by chhylp123** [comment]
Of course. See you Friday. Just want to double check: is the N50 of verkko's assembly the contig N50 or the scaffolding N50?

**Comment by chhylp123** [comment]
Oh I see. Please just ignore me as verkko shouldn't have scaffold when assembling the haploid genome.

**Comment by chhylp123** [comment]
Could you please show the log file of the new hifiam run?

**Comment by Jokendo-collab** [comment]
> Attached please find the logfile for the above bandageNG plot. I rendered the above bandage graph using `asm.out.bp.p_ctg.gfa`. You may have a look and advise. I used the following script to run hifiasm: `` hifiasm -o fish_11_hifiasm_ul.asm -t 48 -l 0 --ul `ls *.fastq.gz | tr '\n' ',' | perl -ple 'chop'` /data/okendojo/zebrafish/data/fish11/hifi/*.fastq.gz `` [slurm-4935636.out.zip](https://github.com/chhylp123/hifiasm/files/12176439/slurm-4935636.out.zip)

I shared the logfile here.

**Comment by chhylp123** [comment]
Could you please share the bin files with us? With the bin files, we should be able to improve the assembly of hifiasm. Thanks a lot.

**Comment by Jokendo-collab** [comment]
Thanks @chhylp123 , Which files do you need from the list below:
```bash
├── 5-untip
│   ├── compressed.fasta
│   ├── f11TrimmedONTHiFi.bp.r_utg.fasta
│   ├── fish_11_hifiasm_ul.asm.bp.p_utg.gfa
│   └── mashmap.out
├── assembly.fasta
├── assembly.homopolymer-compressed.chr.csv
├── chrmassign.sh
├── compressed.mashmap.out -> 5-untip/mashmap.out
├── fish_11_hifiasm_ul.asm.bp.a_ctg.gfa
├── fish_11_hifiasm_ul.asm.bp.a_ctg.lowQ.bed
├── fish_11_hifiasm_ul.asm.bp.a_ctg.noseq.gfa
├── fish_11_hifiasm_ul.asm.bp.p_ctg.gfa
├── fish_11_hifiasm_ul.asm.bp.p_ctg.lowQ.bed
├── fish_11_hifiasm_ul.asm.bp.p_ctg.noseq.gfa
├── fish_11_hifiasm_ul.asm.bp.p_utg.gfa
├── fish_11_hifiasm_ul.asm.bp.p_utg.lowQ.bed
├── fish_11_hifiasm_ul.asm.bp.p_utg.noseq.gfa
├── fish_11_hifiasm_ul.asm.bp.r_utg.gfa
├── fish_11_hifiasm_ul.asm.bp.r_utg.lowQ.bed
├── fish_11_hifiasm_ul.asm.bp.r_utg.noseq.gfa
├── fish_11_hifiasm_ul.asm.ec.bin
├── fish_11_hifiasm_ul.asm.ovlp.reverse.bin
├── fish_11_hifiasm_ul.asm.ovlp.source.bin
├── fish_11_hifiasm_ul.asm.re.uidx.bin
├── fish_11_hifiasm_ul.asm.re.uidx.ucr.bin
├── fish_11_hifiasm_ul.asm.re.ul.msk.bin
├── fish_11_hifiasm_ul.asm.re.ul.ovlp.bin
├── fish_11_hifiasm_ul.asm.uidx.bin
├── fish_11_hifiasm_ul.asm.ul.ovlp.bin
├── GRCz11.fasta -> ../f11vkcleanedata/GRCz11.fasta
├── mashmap.out
├── t2t.txt
├── tmp4
└── tmp.gfa

1 directory, 34 files
[oken
```
Let me know and I will zip and share them with you

**Comment by chhylp123** [comment]
Could you please share `*bin` with us? Thanks in advance.

**Comment by Jokendo-collab** [comment]
You can download the bin file from here: `https://hpc.nih.gov/~okendojo/hifiasm_bin.tar.gz` , let me know once you downloaded. How do you also to chromosomal assignment using `hifiasm` results? I would like to append the chromosome names in the bandage plots. Do you have a specific script you are using for this?

**Comment by chhylp123** [comment]
Thanks for the bin files. Actually we don't have the script to chromosomal assignment yet, but we are working for that right now.

**Comment by Jokendo-collab** [comment]
I can now delete that file from our server? I hope you downloaded it?

**Comment by chhylp123** [comment]
Yes, thanks a lot!

**Comment by Jokendo-collab** [comment]
@chhylp123 how can I speak with you directly?

**Comment by chhylp123** [comment]
My email is: hcheng@ds.dfci.harvard.edu. Thanks.

**Comment by Jokendo-collab** [comment]
@chhylp123 do you have any update(s) ?
