### ISSUE TITLE
Assertion error in running hifiasm-0.19.5

### ISSUE THREAD

**Issue by wzboy1984** [chhylp123/hifiasm#476]
Dear author,

I encountered the following error when I tried running hifiasm-0.19.5 on a hifi+ONT dataset.
my command line is: hifiasm-0.19.5/hifiasm -o xxx -t 32 hifi.fasta.gz --ul ont.fasta.gz

> ...
> [M::update_sg_uo::] ==> # gfa reads:1244886, # covered gfa reads:1241365
> [M::ul_realignment::] ==> starting UL
> [M::ha_opt_update_cov] updated max_n_chain to 250
> [M::gen_cov_track::] # bases: 7670394310
> [M::ha_ct_shrink::228287.929*23.37] ==> counted 38262074 distinct minimizer k-mers
> [M::ha_ft_ul_gen::228300.628*23.37@192.603GB] ==> filtered out 38262074 k-mers occurring 32 or more times
> [M::yak_count] collected 763729387 minimizers
> [M::ha_pt_ul_gen::228544.310*23.36] ==> counted 106893469 distinct minimizer k-mers
> [M::ha_ct_shrink::228544.758*23.36] ==> counted 106893469 distinct minimizer k-mers
> [M::yak_count] collected 763729387 minimizers
> [M::ha_pt_ul_gen::228851.317*23.34] ==> indexed 763729387 positions
> [M::uidx_l_build] Index has been built.
> [M::uidx_write] Index has been written.
> [M::ha_opt_update_cov] updated max_n_chain to 250
> [M::cal_graph_ovlp_binning::994.689] ==> Qualification
> [M::write_emask_t] Index has been written.
> [M::rescall_ul_pipeline::52273.014] ==> Qualification
> [M::rescall_ul_pipeline::] ==> # reads: 564404, # bases: 0, # fully corrected reads: 539820
> [M::write_all_ul_t] Index has been written.
> hifiasm: inter.cpp:17944: void filter_short_ulalignments(void*, long int, int): Assertion `a[p->aidx].pidx == (uint32_t)k' failed.

I also tried running the lastest master version with same parameters, keeping the previous generated middle files. And I got the same error message.
What should I do to avoid this error? 
Looking forward to your reply.
Best wishes,

**Comment by chhylp123** [comment]
Sorry for the late reply. Would any of you share the bin files with me? I guess it should be a small bug. Thanks in advance.

**Comment by wzboy1984** [comment]
This assertion error could be avoid by changing the aidx, pidx, etc back to -1.

**Comment by chhylp123** [comment]
Hi @ptrebert, could you please share the bin files with me? Thanks again.

**Comment by chhylp123** [comment]
> This assertion error could be avoid by changing the aidx, pidx, etc back to -1.

Sorry could you please let me knhow what are the aidx and pidx? That would be very helpful.

**Comment by ptrebert** [comment]
@chhylp123 I prepared a Globus share, can you remind me of your globus id?

**Comment by chhylp123** [comment]
@ptrebert I was using: hcheng@jimmy.harvard.edu. Thanks a lot.

**Comment by chhylp123** [comment]
@wzboy1984 @ptrebert Could you please have a try with current github HEAD (`0.19.5-r593`) using the bin files? Thanks in advance.

**Comment by alex-kozik** [comment]
Confirmed. The same error:

$ /share/rwmwork/akozik/2023_HiFi_Assy/bin/hifiasm_0.19.5 -v
0.19.5-r587

[M::rescall_ul_pipeline::] ==> # reads: 1572170, # bases: 0, # fully corrected reads: 1482668
[M::write_all_ul_t] Index has been written.
hifiasm_0.19.5: inter.cpp:17944: void filter_short_ulalignments(void*, long int, int): Assertion `a[p->aidx].pidx == (uint32_t)k' failed.

I will check 0.19.5-r593 as you (chhylp123) suggested.

**Comment by chhylp123** [comment]
Thanks. Hope the r593 works.

**Comment by alex-kozik** [comment]
@chhylp123 Thank you. 
0.19.5-r593 worked without issues on the same dataset which caused job termination with 0.19.5-r587

**Comment by chhylp123** [comment]
Got it. Thanks for sharing the results!
