### ISSUE TITLE
Un-balanced paternal/maternal haplotigs from trio binning (Revio HG002 HiFi child + NGS parental)

### ISSUE THREAD

**Issue by liu-xingliang** [chhylp123/hifiasm#485]
Dear @chhylp123, 

### Input data
child: recent Revio HiFi for HG002-rep1 (29X given genome size 3.2Gb) 
https://downloads.pacbcloud.com/public/revio/2022Q4/HG002-rep1/m84011_220902_175841_s1.hifi_reads.bam
parental: short reads from hifiasm demo dataset
https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG003_NA24149_father/NIST_HiSeq_HG003_Homogeneity-12389378/HG003Run01-13262252/HG003Run01_S1.bam
https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG004_NA24143_mother/NIST_HiSeq_HG004_Homogeneity-14572558/HG004Run01-15133132/HG004Run01_S1.bam

### Command line
```bash
yak=~/yak/yak
$yak count -k31 -b37 -t16 -o pat.yak /home/UNIXHOME/xliu/datasets/hifiasm_HG002trio/HG003Run01_S1.bam
$yak count -k31 -b37 -t16 -o mat.yak /home/UNIXHOME/xliu/datasets/hifiasm_HG002trio/HG004Run01_S1.bam

coverage="29X"
hifiasm=~/hifiasm/hifiasm
bam2fastq=~/bin/bam2fastq
$bam2fastq HG002-rep1.$coverage.bam -o HG002-rep1.$coverage -u -j 32
$hifiasm -o HG002.$coverage.asm/HG002.$coverage.asm -t 32 HG002-rep1.$coverage.fastq 2> HG002.$coverage.asm.pri.log
$hifiasm -o HG002.$coverage.asm/HG002.$coverage.asm -t 32 -1 pat.yak -2 mat.yak /dev/null 2> HG002.$coverage.asm.trio.log
```

### Results

![Picture1](https://github.com/chhylp123/hifiasm/assets/42717675/d6b49b96-2c61-4ec1-8202-3a6a1bacd59f)

Thank you very much for your help!

**Comment by chhylp123** [comment]
I guess the main reason is that yak cannot handle bam, so it would be better to covert bam to fastq first.

**Comment by liu-xingliang** [comment]
Hi @chhylp123 

Thank you for your help. The unbalanced haplotigs after trio-binning got fixed after switching yak input to fastq format. Yak completed nicely without complaining about the input format, I overlooked it actually did not do the job with bam files. 

![image](https://github.com/chhylp123/hifiasm/assets/42717675/c081c833-7b89-4055-8586-194a595f0c02)

Now the figures make sense to me, trio-binning improved the phasing generating longer maternal haplotigs. The collapsed primary consensus contigs is almost equal size (or slightly longer) as trio-binning phased haplotigs.

Close the case. Feel free to re-open if you have any comments @chhylp123 

Best regards,
Xingliang
