### ISSUE TITLE
Segmentation fault at trio mode

### ISSUE THREAD

**Issue by LHG-GG** [chhylp123/hifiasm#494]
Hifiasm Version -- 0.19.5-r593

I am working with non public dataset: child ~99x >10kb hifi reads; 80x >100kb ulont reads and ~60x parental hifi reads. I have generated  parental yak count as discussed https://github.com/chhylp123/hifiasm/issues/491. 

here is the log file. 
[hifiasm_trio_seg_err.txt](https://github.com/chhylp123/hifiasm/files/12272397/hifiasm_trio_seg_err.txt)

**Comment by chhylp123** [comment]
Could you please show the size of yak index?

**Comment by chhylp123** [comment]
Hifiasm has done the HiFi correction but was killed when writting the bin files to the disk. Could you please have a look if there is anything abnormal for the disk?

**Comment by LHG-GG** [comment]
yak files size is 25G each. yak files were written to the same disk but hifiasm is failing at same step (as in log file) even with earlier versions. As you mentioned it looks like not a bug. Thank you
