### ISSUE TITLE
Assembly fail with small regions (« ERROR: failed to read the graph »)

### ISSUE THREAD

**Issue by scauet** [chhylp123/hifiasm#496]
Hello !
I am trying to assemble small genomic regions (~100-300kb) with last version of Hifiasm. Historically I used hifiasm-0.12 version with 50-100X of PacBio data and everything worked correctly.
Now, I have tried on the same sample hifiasm 0.12, 0.15 and 0.19.5. With hifiasm 0.12 I get my assembly without problem.  But with hifiasm 0.15 and hifiasm-0.19.5 I get an error after graph generation : « ERROR: failed to read the graph ».

Here is the log for hifiasm-0.19.5 assembly:

> …
> [M::ha_print_ovlp_stat] # overlaps: 66525
> [M::ha_print_ovlp_stat] # strong overlaps: 701
> [M::ha_print_ovlp_stat] # weak overlaps: 65824
> [M::ha_print_ovlp_stat] # exact overlaps: 65875
> [M::ha_print_ovlp_stat] # inexact overlaps: 650
> [M::ha_print_ovlp_stat] # overlaps without large indels: 66388
> [M::ha_print_ovlp_stat] # reverse overlaps: 53
> [M::ha_opt_update_cov_min] updated max_n_chain to 440
> Writing reads to disk... 
> Reads has been written.
> Writing ma_hit_ts to disk... 
> ma_hit_ts has been written.
> Writing ma_hit_ts to disk... 
> ma_hit_ts has been written.
> bin files have been written.
> [M::purge_dups] homozygous read coverage threshold: 81
> [M::purge_dups] purge duplication coverage threshold: 102
> Writing raw unitig GFA to disk... 
> Writing processed unitig GFA to disk... 
> [M::adjust_utg_by_primary] primary contig coverage range: [68, infinity]
> Writing primary contig GFA to disk... 
> Writing alternate contig GFA to disk... 
> Inconsistency threshold for low-quality regions in BED files: 70%
> [M::main] Version: 0.19.5-r587
> [M::main] CMD: hifiasm -l0 -o bc2071 filtered_bc2071.fasta
> [M::main] Real time: 120.763 sec; CPU: 120.671 sec; Peak RSS: 16.098 GB
> ERROR: failed to read the graph
> 

I can send you full log or other files if needed.

Do you have an idea why it works with 0.12 and not others ?
Can I tweak some parameters in order to work with small regions with lastest version of hifiasm ?

Many thanks for your help !

**Comment by chhylp123** [comment]
Did hifiasm produce any gfa outputs?

**Comment by scauet** [comment]
Yes 3 gfa files (bc2071.bp.r_utg.gfa, bc2071.bp.p_utg.gfa, bc2071.bp.p_ctg.gfa) have been produced. Only the bc2071.bp.a_ctg.gfa file is still empty.

**Comment by chhylp123** [comment]
Sorry for the late reply. If you would like to get `a_ctg.gfa`, please add '--primary'.

**Comment by scauet** [comment]
I have done some new tests with the last version of hifiasm and --primary option and everything is fine.
Thanks for your help !
