### ISSUE TITLE
Assertion `a[p->aidx].pidx == (uint32_t)k' failed for only one sample

### ISSUE THREAD

**Issue by smkumaill** [chhylp123/hifiasm#497]
Hello

I am trying to produce assemblies for a few of our samples. It's been running perfectly for all of the samples except one, when it gives the following error:

`Assertion 'a[p->aidx].pidx == (uint32_t)k' failed`

I am using the version 0.19.5-r587. I have tried running it on multiple machines with no success.  

Please find the entire log attached.

[gp007.g100.log](https://github.com/chhylp123/hifiasm/files/12309110/gp007.g100.log)

**Comment by chhylp123** [comment]
Could you please have a try with the current HEAD (r593)? It was a bug which should be fixed with r593.

**Comment by smkumaill** [comment]
Ah my bad, I was using the Hifiasm from bioconda. Thought that was the latest version as it was the same as the latest release on Github.  

It worked!

Thank you
