### ISSUE TITLE
Assertion error != (unsigned int)-1

### ISSUE THREAD

**Issue by fbattke** [chhylp123/hifiasm#498]
I'm trying to assemble a human genome from long reads, running into this assertion:

[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 29; peak_het: -1
[M::ha_ct_shrink::3918.325*5.90] ==> counted 86700785 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 2346022044 minimizers
[M::ha_pt_gen::4227.318*7.21] ==> indexed 2320687455 positions, counted 86700785 distinct minimizer k-mers
hifiasm: Correct.cpp:3511: void recalcate_window_advance(overlap_region_alloc*, All_reads*, const ul_idx_t*, UC_Read*, Correct_dumy*, UC_Read*, kvec_t_u64_warp*, int64_t, double, double): Assertion `error != (unsigned int)-1' failed.

Note that these long reads are not produced by a PacBio instrument but rather I'm using the new Illumina "Complete Long Reads" (ICLR) as input to hifiasm. ICLR are, like PB reads, presented as fastq files, so I'm assuming the error is not related to the source of the reads but rather something more generic?

**Comment by chhylp123** [comment]
Yes, I guess so. Is it possible that you can share the bin files with me? I guess it shoud be a bug and I could fix it soon. Thanks in advance.

**Comment by fbattke** [comment]
Thanks for the quick reply. Unfortunately, no bin files were written. 

This error occurred with three separate input files. I'm attaching all three log files, hoping they might help.

[hifiasm.log](https://github.com/chhylp123/hifiasm/files/12314693/hifiasm.log)
[hifiasm.log](https://github.com/chhylp123/hifiasm/files/12314694/hifiasm.log)
[hifiasm.log](https://github.com/chhylp123/hifiasm/files/12314696/hifiasm.log)

I used no specific settings, only -o $OUTDIR -t $THREADS

**Comment by chhylp123** [comment]
Could you please share the raw reads?

**Comment by fbattke** [comment]
Sure! Could you drop me a line at florian.battke@cegat.de, then I'll reply with download details.

Thank you for looking into this!

**Comment by chhylp123** [comment]
Hi @fbattke, the problem is that your input reads contain non-A/C/G/T bases (see: https://github.com/chhylp123/hifiasm/issues/374).

**Comment by fbattke** [comment]
I had no idea, thank you very much!
