### ISSUE TITLE
Generating HiFi reads from a "butterfly"?

### ISSUE THREAD

**Issue by jelber2** [chhylp123/hifiasm#5]
Pardon the ignorance, but how did you generate HiFi reads from a butterfly? We were told by our PacBio provider that we need 15 ug DNA (and we are working with Dipteran fly, so that was not possible from a single individual and thus we could only use the low-input DNA protocol with continuous long reads). We were also told that we couldn't use the PacBio Sequel I and could only generate HiFi reads from the PacBio Sequel II, but that doesn't seem to be the case according to PacBio's website.

Edit...so it does seem possible to use the low DNA input workflow for HiFi read generation
https://youtu.be/PJXDhusSexY

**Comment by chhylp123** [comment]
HiFi reads were not generated by ourselves. The butterfly is sequenced by Richard Durbin in Wellcome Sanger Institute. So maybe you can ask him : )

**Comment by jelber2** [comment]
@richarddurbin can you comment on this?
