### ISSUE TITLE
Can Hifiasm distinguish duplicated chromosomes with different coverage in the genome assembly?

### ISSUE THREAD

**Issue by JChenGatersleben** [chhylp123/hifiasm#500]
Hi, currently we are working on B chromosome, which is a chromosome have many copies in a genome.

We generate PacBio HiFi reads of a plant (~16 Gb) carrying 6 B chromosome (580 Mb/chromosome), and as I know, the Hifiasm will calcualte the sequence coverage of the reads, but here,  we have two difference coverage (standard chromosome: 8x, B chromosome: 30 x). 

The output report gave us the final coverage is 8x, are there any methods could help us to find out the contigs with 30x coverage?

Greetings

**Comment by chhylp123** [comment]
By finding out the contigs with 30x coverage, would you like to find the contigs coming from B chromosome?

**Comment by JChenGatersleben** [comment]
Yes, we want to find the contigs coming from B chromosome (30x coverage), as I know, purge_dups can calculate the coverage, or is there any other suggestions?

**Comment by chhylp123** [comment]
In GFA file, rd:i: indicates the coverage of current contigs (see: https://hifiasm.readthedocs.io/en/latest/interpreting-output.html).

**Comment by JChenGatersleben** [comment]
Thank you so much for your reply! I overlooked this information! Cool! Problem solved!
