### ISSUE TITLE
error: update_rovlp_chain_qse

### ISSUE THREAD

**Issue by fergsc** [chhylp123/hifiasm#518]
Hi,
I am trying to assemble a plant genome using HiFi + ONT data. We have been sucessful using HiFiAsm on th HiFi reads alone, but when the ONT data is included we get the following error.

Input data:
  hifi = 30.28 Gbp = 54.05x
  ONT = 32.67 Gbp = 58.35x

Genome size: 560 Mbp

command
```
hifiasm                    \
    -t 48                     \
    --ul ONT.fastq.gz \
    hifi.fastq.gz
```

```
hifiasm: inter.cpp:15304: void update_rovlp_chain_qse(ma_ug_t*, int64_t, int64_t, mg_lchain_t*, int64_t, int64_t): Assertion `a[i].qs >= 0 && a[i].qs <= qlen' failed.
```
[hifiasm.log](https://github.com/chhylp123/hifiasm/files/12581504/hifiasm.log)

Thanks.

**Comment by chhylp123** [comment]
Which version are you using? Is it possible that you can share the bin files and UL reads with me? I could do a very quick check. Thanks.

**Comment by fergsc** [comment]
I have emailed you a link to the ONT UL and bin files.
I am using HiFiAsm version 0.19.6-r595

Thanks for looking in to this.

**Comment by chhylp123** [comment]
Thanks. I just had a try with your bin files and UL reads using the github HEAD (`0.19.6-r597`). Hifiasm could produce final contigs without issues. Could you please have a try with current HEAD? Thanks so much!

**Comment by fergsc** [comment]
Success.
I also ran it with additional UL and with Hi-C data and it ran till completion.

Thanks for the help.

**Comment by chhylp123** [comment]
Great. Thanks for the updates.
