### ISSUE TITLE
Hifiasm increases scaffold size for --high-het (or default) compared to -l0

### ISSUE THREAD

**Issue by jelber2** [chhylp123/hifiasm#52]
Just checking to make sure this makes sense, but hifiasm has a bigger N50 for `--high-het` (or default purge_dups settings [identical output with --high-het or defaults]) than using `-l0` for the p_ctgs that are produced by either `--high-het` or `-l0`. This seems like it should be the opposite? All other settings are defaults `hifiasm -p prefix --high-het or -l0 hifi.reads.fasta.gz` with hifiasm 0.13-r307.

**Comment by chhylp123** [comment]
If `-l0` is not specified, `hifiasm -p prefix --high-het` will enable `-l2`.  Hifiasm with `-l2` perform purge_dup step so it should have bigger 50.

**Comment by jelber2** [comment]
Well, hifiasm ends up merging several scaffolds so that none are originally over 25 Mbp such that I think 4 or so are over 25 Mbp. I can provide the assembly stats tomorrow.

**Comment by jelber2** [comment]
Okay, so I changed the title of the post as I realized that I incorrectly described the problem in the title and the initial post.


    /genetics/elbers/bin/hifiasm/hifiasm -o wm.asm -t75 -l0 ../HiFi-reads-rm-icecream.fasta.gz
    awk '/^S/{print ">"$2"\n"$3}' wm.asm.p_ctg.gfa | fold > wm.asm.p_ctg.l0.fa

    # note that N50 is a number and not a length with bbstats.sh
    # note that L50 is a length and not a number with bbstats.sh

    /opt/bbmap/bbstats.sh wm.asm.p_ctg.l0.fa
    A	C	G	T	N	IUPAC	Other	GC	GC_stdev
    0.3364	0.1635	0.1636	0.3365	0.0000	0.0000	0.0000	0.3271	0.0378

    Main genome scaffold total:         	1926
    Main genome contig total:           	1926
    Main genome scaffold sequence total:	1089.879 MB
    Main genome contig sequence total:  	1089.879 MB  	0.000% gap
    Main genome scaffold N/L50:         	89/3.043 MB
    Main genome contig N/L50:           	89/3.043 MB
    Main genome scaffold N/L90:         	570/287.908 KB
    Main genome contig N/L90:           	570/287.908 KB
    Max scaffold length:                	23.994 MB
    Max contig length:                  	23.994 MB
    Number of scaffolds > 50 KB:        	1235
    % main genome in scaffolds > 50 KB: 	98.07%


    Minimum 	Number        	Number        	Total         	Total         	Scaffold
    Scaffold	of            	of            	Scaffold      	Contig        	Contig  
    Length  	Scaffolds     	Contigs       	Length        	Length        	Coverage
    --------	--------------	--------------	--------------	--------------	--------
        All 	         1,926	         1,926	 1,089,878,911	 1,089,878,911	 100.00%
     2.5 KB 	         1,926	         1,926	 1,089,878,911	 1,089,878,911	 100.00%
       5 KB 	         1,924	         1,924	 1,089,869,399	 1,089,869,399	 100.00%
      10 KB 	         1,924	         1,924	 1,089,869,399	 1,089,869,399	 100.00%
      25 KB 	         1,734	         1,734	 1,085,989,968	 1,085,989,968	 100.00%
      50 KB 	         1,235	         1,235	 1,068,806,588	 1,068,806,588	 100.00%
     100 KB 	           964	           964	 1,049,179,798	 1,049,179,798	 100.00%
     250 KB 	           610	           610	   991,796,034	   991,796,034	 100.00%
     500 KB 	           384	           384	   910,161,360	   910,161,360	 100.00%
       1 MB 	           237	           237	   803,609,777	   803,609,777	 100.00%
     2.5 MB 	           114	           114	   616,698,085	   616,698,085	 100.00%
       5 MB 	            41	            41	   360,473,780	   360,473,780	 100.00%
      10 MB 	            11	            11	   158,615,155	   158,615,155	 100.00%


    /genetics/elbers/bin/hifiasm/hifiasm -o wm.asm -t75 --high-het ../HiFi-reads-rm-icecream.fasta.gz
    awk '/^S/{print ">"$2"\n"$3}' wm.asm.p_ctg.gfa | fold > wm.asm.p_ctg.high-het.fa

    /opt/bbmap/bbstats.sh wm.asm.p_ctg.high-het.fa 
    A	C	G	T	N	IUPAC	Other	GC	GC_stdev
    0.3361	0.1637	0.1639	0.3363	0.0000	0.0000	0.0000	0.3276	0.0448

    Main genome scaffold total:         	825
    Main genome contig total:           	825
    Main genome scaffold sequence total:	784.534 MB
    Main genome contig sequence total:  	784.534 MB  	0.000% gap
    Main genome scaffold N/L50:         	19/11.155 MB
    Main genome contig N/L50:           	19/11.155 MB
    Main genome scaffold N/L90:         	134/552.325 KB
    Main genome contig N/L90:           	134/552.325 KB
    Max scaffold length:                	47.052 MB
    Max contig length:                  	47.052 MB
    Number of scaffolds > 50 KB:        	518
    % main genome in scaffolds > 50 KB: 	98.84%


    Minimum 	Number        	Number        	Total         	Total         	Scaffold
    Scaffold	of            	of            	Scaffold      	Contig        	Contig  
    Length  	Scaffolds     	Contigs       	Length        	Length        	Coverage
    --------	--------------	--------------	--------------	--------------	--------
        All 	           825	           825	   784,534,196	   784,534,196	 100.00%
     2.5 KB 	           825	           825	   784,534,196	   784,534,196	 100.00%
       5 KB 	           823	           823	   784,524,684	   784,524,684	 100.00%
      10 KB 	           823	           823	   784,524,684	   784,524,684	 100.00%
      25 KB 	           730	           730	   782,625,060	   782,625,060	 100.00%
      50 KB 	           518	           518	   775,437,403	   775,437,403	 100.00%
     100 KB 	           379	           379	   765,444,834	   765,444,834	 100.00%
     250 KB 	           229	           229	   741,486,833	   741,486,833	 100.00%
     500 KB 	           140	           140	   709,699,869	   709,699,869	 100.00%
       1 MB 	            93	            93	   677,986,980	   677,986,980	 100.00%
     2.5 MB 	            61	            61	   623,843,181	   623,843,181	 100.00%
       5 MB 	            36	            36	   533,469,808	   533,469,808	 100.00%
      10 MB 	            21	            21	   420,184,726	   420,184,726	 100.00%
      25 MB 	             5	             5	   174,385,273	   174,385,273	 100.00%

So it appears that hifiasm with `--high-het` or without `-l0` is merging scaffolds?

Unless there is something wrong with the gfa file during the conversion with `awk '/^S/{print ">"$2"\n"$3}' wm.asm.p_ctg.gfa | fold > wm.asm.p_ctg.high-het.fa`

**Comment by HenrivdGeest** [comment]
My 2 cents; To see this clear, you are saying that its not just the n50 that increased. Increased n50 makes sense with purging the assembly. (if you would take an NG50, it should stay the same, right?)
However, your problem is that you reach ~616Mb with 140 contigs with your "default -l0" assembly, and  you reach ~623Mb with 61 contigs for your "high-het -l2" assembly. 
I don't think persee the high-het option is 'merging' contigs, although I don't know the algorithm, it can also be that because of different alignment parameters (which we can't see, or are not exposed) it just makes the assembler making bigger contigs. 
Maybe the unitig joining step is different, maybe the unitigs themselves are already different?
Since the high-het option is experimental, I think it would help chhylp123 if you could check somehow if these bigger contigs are actually right, or that there are contain more errors. 
Do you agree that It would make life easier if you would run 2 assemblies, with just enabling/disabling the --high-het option (leaving -l identical)?

**Comment by lh3** [comment]
What is the input data? Haplotig duplicate purging at the -l2 level joins haplotigs from different haplotypes which is disallowed at -l0. For heterozygous samples, -l2 is highly recommended. This is why tools like purge_dups exist.

**Comment by jelber2** [comment]
It is a Dipteran fly with an estimated 1.5% heterozygosity (based on using genomescope on the HiFi reads - Illumina reads from 5 other individuals suggest similar heterozygosity levels) with ~30x HiFi read coverage.

**Comment by lh3** [comment]
GenomeScope seems to overestimate heterozygosity at our hand. The real heterozygosity is probably closer to 1%. At this level, definitely use -l2. As I remember, you need even higher heterozygosity for --high-het to kick in.

**Comment by jelber2** [comment]
Ok. If I run purge_dups manually on the p_ctg from -l0 output, I don’t end up with larger scaffolds, so l am a little confused.

**Comment by lh3** [comment]
> Haplotig duplicate purging at the -l2 level joins haplotigs from different haplotypes

Standalone purge_dups doesn't do this.

**Comment by jelber2** [comment]
Ok thank you so much!
