### ISSUE TITLE
Question regarding dataset used in Hifiasm (UL) manuscript 

### ISSUE THREAD

**Issue by cjain7** [chhylp123/hifiasm#524]
Dear Haoyu,

I have a follow-up question from Supplementary Table 3 of your manuscript ["Scalable telomere-to-telomere assembly for diploid and polyploid genomes with double graph"](https://arxiv.org/abs/2306.03399). Here HG002 is listed in "HPRC Year 2" category, but it is not listed among the year-2 samples on the [HPRC page](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=submissions/90A1F283-2752-438B-917F-53AE76C9C43E--UCSC_HPRC_nanopore_Year2/). I was able to locate 100kb+ reads (~15x coverage) through HPRC [HG002_Data_Freeze_v1.0](https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=NHGRI_UCSC_panel/HG002/hpp_HG002_NA24385_son_v1/nanopore/downsampled/greater_than_100kb/) but your table says that you are using UL 100kbp+ data with 31x coverage. Can you please point me to the 31x UL dataset?

Thanks,
Chirag

**Comment by chhylp123** [comment]
The HPRC team ran the Y2 test for both verkko and hifiasm. Let me double check with them.

**Comment by cjain7** [comment]
Thank you. Please do let me know when you hear back.

**Comment by cjain7** [comment]
A gentle reminder. Would it be possible to get access to the data?

**Comment by chhylp123** [comment]
Sorry for the late reply. They are at: 

``
s3://human-pangenomics/NHGRI_UCSC_panel/HG002/nanopore/ultra-long/03_08_22_R941_HG002_1_Guppy_6.1.2_5mc_cg_prom_sup.bam 
s3://human-pangenomics/NHGRI_UCSC_panel/HG002/nanopore/ultra-long/03_08_22_R941_HG002_2_Guppy_6.1.2_5mc_cg_prom_sup.bam 
s3://human-pangenomics/NHGRI_UCSC_panel/HG002/nanopore/ultra-long/03_08_22_R941_HG002_3_Guppy_6.1.2_5mc_cg_prom_sup.bam

**Comment by cjain7** [comment]
Great, thank you!
Closing the issue now.
