### ISSUE TITLE
generate the corrected fastq reads

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [chhylp123/hifiasm#53]
Hello,
I wonder if there is a way to generate the corrected Hifi fastq reads into .fq format. Right now they are in binary format, right? 
thanks,
Zhenzhen

**Comment by lh3** [comment]
Use --write-ec to output fasta. No fastq output. See README or the manpage.

**Comment by chhylp123** [comment]
> Use --write-ec to output fasta. No fastq output. See README or the manpage.

Just give a little bit more details: once you specify '--write-ec', the corrected fasta will be outputted to 'prefix.ec.fa', where 'prefix' is specified by '-o'.

**Comment by zhenzhenyang-psu** [comment]
excellent, thanks!
