### ISSUE TITLE
Much larger assembled genome than flow cytometry estimate

### ISSUE THREAD

**Issue by jiangqiuqiuu** [chhylp123/hifiasm#531]
Hi there,

I am trying to assemble a plant genome estimately of 90Mb (estimated with flow cytometry) with HiFi reads, however, the primary contig I assembled is around 270Mb to the largest, when I tried to turn -s down to 0.25/0.35, the assembled primary contig size decreased to 190Mb. Also I did one assembly with --hom-cov turned on, the resulting primary genome size turned out to be around 190Mb which is still much larger than the estimated haploid genome size. I am not completely sure what's causing the big genome size of the assemblies, probably due to high level of heterozygosity? What's more, the kmer plot looks kind of weird, here I attach the kmer plot. I would really appreciate it if you could provide some insights on the assembly. 

Thanks!

[M::ha_analyze_count] lowest: count[5] = 3999993
[M::ha_analyze_count] highest: count[7] = 4943470
[M::ha_hist_line]     2: ****************************************************************************************************> 18587580
[M::ha_hist_line]     3: ****************************************************************************************************> 6022135
[M::ha_hist_line]     4: ****************************************************************************** 3839183
[M::ha_hist_line]     5: ********************************************************************************* 3999993
[M::ha_hist_line]     6: ********************************************************************************************* 4592481
[M::ha_hist_line]     7: **************************************************************************************************** 4943470
[M::ha_hist_line]     8: *************************************************************************************************** 4898621
[M::ha_hist_line]     9: ****************************************************************************************** 4445154
[M::ha_hist_line]    10: *************************************************************************** 3705059
[M::ha_hist_line]    11: *********************************************************** 2925054
[M::ha_hist_line]    12: ******************************************** 2199642
[M::ha_hist_line]    13: ************************************ 1777191
[M::ha_hist_line]    14: ********************************* 1623285
[M::ha_hist_line]    15: ********************************* 1636173
[M::ha_hist_line]    16: ************************************ 1756067
[M::ha_hist_line]    17: ***************************************** 2016293
[M::ha_hist_line]    18: *********************************************** 2306958
[M::ha_hist_line]    19: **************************************************** 2550947
[M::ha_hist_line]    20: ******************************************************** 2786505
[M::ha_hist_line]    21: ************************************************************ 2950365
[M::ha_hist_line]    22: ************************************************************** 3080028
[M::ha_hist_line]    23: **************************************************************** 3170546
[M::ha_hist_line]    24: *************************************************************** 3120641
[M::ha_hist_line]    25: ************************************************************ 2972134
[M::ha_hist_line]    26: ******************************************************** 2784117
[M::ha_hist_line]    27: ***************************************************** 2640009
[M::ha_hist_line]    28: ************************************************** 2480493
[M::ha_hist_line]    29: ********************************************* 2246187
[M::ha_hist_line]    30: ***************************************** 2006581
[M::ha_hist_line]    31: ************************************* 1807922
[M::ha_hist_line]    32: ********************************* 1619725
[M::ha_hist_line]    33: ****************************** 1500224
[M::ha_hist_line]    34: **************************** 1406230
[M::ha_hist_line]    35: *************************** 1336426
[M::ha_hist_line]    36: ************************* 1243061
[M::ha_hist_line]    37: *********************** 1132472
[M::ha_hist_line]    38: ********************* 1050678
[M::ha_hist_line]    39: ******************** 993076
[M::ha_hist_line]    40: ******************* 932109
[M::ha_hist_line]    41: ****************** 887180
[M::ha_hist_line]    42: ***************** 848523
[M::ha_hist_line]    43: ***************** 816969
[M::ha_hist_line]    44: **************** 796322
[M::ha_hist_line]    45: **************** 782102
[M::ha_hist_line]    46: *************** 753819
[M::ha_hist_line]    47: *************** 747369
[M::ha_hist_line]    48: *************** 762220
[M::ha_hist_line]    49: **************** 769056
[M::ha_hist_line]    50: **************** 790170
[M::ha_hist_line]    51: **************** 789946
[M::ha_hist_line]    52: **************** 814181
[M::ha_hist_line]    53: ***************** 833005
[M::ha_hist_line]    54: ****************** 870949
[M::ha_hist_line]    55: ******************* 934604
[M::ha_hist_line]    56: ******************** 969343
[M::ha_hist_line]    57: ********************* 1015342
[M::ha_hist_line]    58: ********************* 1048329
[M::ha_hist_line]    59: ********************** 1065532
[M::ha_hist_line]    60: ********************** 1073527
[M::ha_hist_line]    61: ********************* 1061548
[M::ha_hist_line]    62: ********************** 1073159
[M::ha_hist_line]    63: ********************* 1054704
[M::ha_hist_line]    64: ********************* 1022432
[M::ha_hist_line]    65: ******************** 985716
[M::ha_hist_line]    66: ******************* 931696
[M::ha_hist_line]    67: ****************** 870184
[M::ha_hist_line]    68: **************** 810064
[M::ha_hist_line]    69: *************** 749599
[M::ha_hist_line]    70: ************** 693346
[M::ha_hist_line]    71: ************* 626914
[M::ha_hist_line]    72: *********** 556104
[M::ha_hist_line]    73: ********** 489368
[M::ha_hist_line]    74: ********* 426572
[M::ha_hist_line]    75: ******** 374662
[M::ha_hist_line]    76: ****** 320184
[M::ha_hist_line]    77: ****** 277752
[M::ha_hist_line]    78: ***** 238757
[M::ha_hist_line]    79: **** 204139
[M::ha_hist_line]    80: **** 173573
[M::ha_hist_line]    81: *** 152109
[M::ha_hist_line]    82: *** 130012
[M::ha_hist_line]    83: ** 107985
[M::ha_hist_line]    84: ** 90485
[M::ha_hist_line]    85: * 73397
[M::ha_hist_line]    86: * 65795
[M::ha_hist_line]    87: * 62025
[M::ha_hist_line]    88: * 57286
[M::ha_hist_line]    89: * 52667
[M::ha_hist_line]    90: * 46239
[M::ha_hist_line]    91: * 44434
[M::ha_hist_line]    92: * 41897
[M::ha_hist_line]    93: * 39446
[M::ha_hist_line]    94: * 37199
[M::ha_hist_line]    95: * 36498
[M::ha_hist_line]    96: * 36420
[M::ha_hist_line]    97: * 33471
[M::ha_hist_line]    98: * 33659
[M::ha_hist_line]    99: * 32266
[M::ha_hist_line]   100: * 30387
[M::ha_hist_line]   101: * 29375
[M::ha_hist_line]   102: * 29437
[M::ha_hist_line]   103: * 29002
[M::ha_hist_line]   104: * 27426
[M::ha_hist_line]   105: * 27221
[M::ha_hist_line]   106: * 26501
[M::ha_hist_line]   107: * 26319
[M::ha_hist_line]   108: * 25201
[M::ha_hist_line]   109: * 24976
[M::ha_hist_line]  rest: ******************************* 1516424
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_ft_gen] peak_hom: 7; peak_het: -1
[M::ha_ct_shrink::290.850*2.70] ==> counted 39962342 distinct minimizer k-mers
[M::ha_ft_gen::302.399*2.62@18.788GB] ==> filtered out 39962342 k-mers occurring 35 or more times
[M::ha_opt_update_cov] updated max_n_chain to 100
[M::yak_count] collected 148671843 minimizers
[M::ha_pt_gen::538.135*3.08] ==> counted 25073269 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[5] = 289530
[M::ha_analyze_count] highest: count[8] = 378423
[M::ha_hist_line]     1: ****************************************************************************************************> 16580367
[M::ha_hist_line]     2: ****************************************************************************************************> 932903
[M::ha_hist_line]     3: ******************************************************************************************* 344432
[M::ha_hist_line]     4: ******************************************************************** 258703
[M::ha_hist_line]     5: ***************************************************************************** 289530
[M::ha_hist_line]     6: ***************************************************************************************** 336987
[M::ha_hist_line]     7: *************************************************************************************************** 372916
[M::ha_hist_line]     8: **************************************************************************************************** 378423
[M::ha_hist_line]     9: ******************************************************************************************** 348989
[M::ha_hist_line]    10: ******************************************************************************* 297996
[M::ha_hist_line]    11: **************************************************************** 242609
[M::ha_hist_line]    12: *************************************************** 191383
[M::ha_hist_line]    13: ****************************************** 159287
[M::ha_hist_line]    14: *************************************** 146960
[M::ha_hist_line]    15: *************************************** 147578
[M::ha_hist_line]    16: ****************************************** 159477
[M::ha_hist_line]    17: ************************************************ 179927
[M::ha_hist_line]    18: ***************************************************** 201359
[M::ha_hist_line]    19: ********************************************************** 220349
[M::ha_hist_line]    20: *************************************************************** 238856
[M::ha_hist_line]    21: ******************************************************************* 253006
[M::ha_hist_line]    22: ********************************************************************* 262388
[M::ha_hist_line]    23: *********************************************************************** 267791
[M::ha_hist_line]    24: ********************************************************************* 262569
[M::ha_hist_line]    25: ******************************************************************* 254789
[M::ha_hist_line]    26: **************************************************************** 241449
[M::ha_hist_line]    27: ************************************************************* 230309
[M::ha_hist_line]    28: ********************************************************** 217759
[M::ha_hist_line]    29: **************************************************** 198390
[M::ha_hist_line]    30: *********************************************** 177648
[M::ha_hist_line]    31: ******************************************* 162838
[M::ha_hist_line]    32: *************************************** 147225
[M::ha_hist_line]    33: ************************************* 139153
[M::ha_hist_line]    34: ************************************* 138911
[M::ha_hist_line]    35: **** 13808
[M::ha_hist_line]    36: *** 9560
[M::ha_hist_line]    37: ** 7998
[M::ha_hist_line]    38: ** 6896
[M::ha_hist_line]    39: ** 5825
[M::ha_hist_line]    40: * 5039
[M::ha_hist_line]    41: * 4318
[M::ha_hist_line]    42: * 3856
[M::ha_hist_line]    43: * 3342
[M::ha_hist_line]    44: * 2923
[M::ha_hist_line]    45: * 2620
[M::ha_hist_line]    46: * 2363
[M::ha_hist_line]    47: * 2174
[M::ha_hist_line]    48: * 1910
[M::ha_hist_line]  rest: ***** 17381
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 8; peak_het: -1
[M::ha_ct_shrink::538.413*3.08] ==> counted 8492902 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 148671843 minimizers
[M::ha_pt_gen::659.387*3.73] ==> indexed 132091476 positions, counted 8492902 distinct minimizer k-mers
[M::ha_assemble::3612.920*7.13@18.788GB] ==> corrected reads for round 1
[M::ha_assemble] # bases: 6835687852; # corrected bases: 12009534; # recorrected bases: 8629
[M::ha_assemble] size of buffer: 4.471GB
[M::yak_count] collected 144801571 minimizers
[M::ha_pt_gen::3736.913*7.10] ==> counted 19199943 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[5] = 263732
[M::ha_analyze_count] highest: count[8] = 371432
[M::ha_hist_line]     1: ****************************************************************************************************> 11051600
[M::ha_hist_line]     2: ****************************************************************************************************> 719937
[M::ha_hist_line]     3: ************************************************************************* 272941
[M::ha_hist_line]     4: ************************************************************ 222741
[M::ha_hist_line]     5: *********************************************************************** 263732
[M::ha_hist_line]     6: ************************************************************************************** 318487
[M::ha_hist_line]     7: ************************************************************************************************* 361461
[M::ha_hist_line]     8: **************************************************************************************************** 371432
[M::ha_hist_line]     9: ********************************************************************************************** 349127
[M::ha_hist_line]    10: ********************************************************************************* 301732
[M::ha_hist_line]    11: ****************************************************************** 245444
[M::ha_hist_line]    12: **************************************************** 192870
[M::ha_hist_line]    13: ******************************************* 158775
[M::ha_hist_line]    14: ************************************** 142397
[M::ha_hist_line]    15: ************************************** 140462
[M::ha_hist_line]    16: **************************************** 148275
[M::ha_hist_line]    17: ********************************************* 167946
[M::ha_hist_line]    18: *************************************************** 188903
[M::ha_hist_line]    19: ******************************************************** 208295
[M::ha_hist_line]    20: ************************************************************** 228926
[M::ha_hist_line]    21: ***************************************************************** 242196
[M::ha_hist_line]    22: ******************************************************************** 254145
[M::ha_hist_line]    23: *********************************************************************** 263340
[M::ha_hist_line]    24: *********************************************************************** 263597
[M::ha_hist_line]    25: ********************************************************************* 255454
[M::ha_hist_line]    26: ***************************************************************** 243068
[M::ha_hist_line]    27: *************************************************************** 232832
[M::ha_hist_line]    28: ************************************************************ 221182
[M::ha_hist_line]    29: ******************************************************* 205682
[M::ha_hist_line]    30: ************************************************** 184658
[M::ha_hist_line]    31: ********************************************* 168757
[M::ha_hist_line]    32: ***************************************** 151829
[M::ha_hist_line]    33: ************************************* 138252
[M::ha_hist_line]    34: *********************************** 131855
[M::ha_hist_line]    35: ******************** 74102
[M::ha_hist_line]    36: ******** 29184
[M::ha_hist_line]    37: **** 13170
[M::ha_hist_line]    38: ** 8976
[M::ha_hist_line]    39: ** 7188
[M::ha_hist_line]    40: ** 6255
[M::ha_hist_line]    41: * 5269
[M::ha_hist_line]    42: * 4477
[M::ha_hist_line]    43: * 3888
[M::ha_hist_line]    44: * 3563
[M::ha_hist_line]    45: * 3172
[M::ha_hist_line]    46: * 2710
[M::ha_hist_line]    47: * 2446
[M::ha_hist_line]    48: * 2254
[M::ha_hist_line]    49: * 2063
[M::ha_hist_line]  rest: ***** 18896
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 8; peak_het: -1
[M::ha_ct_shrink::3737.129*7.10] ==> counted 8148343 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 144801571 minimizers
[M::ha_pt_gen::3863.889*7.08] ==> indexed 133749971 positions, counted 8148343 distinct minimizer k-mers
[M::ha_assemble::6542.441*7.43@18.788GB] ==> corrected reads for round 2
[M::ha_assemble] # bases: 6834389132; # corrected bases: 358394; # recorrected bases: 4494
[M::ha_assemble] size of buffer: 4.128GB
[M::yak_count] collected 144649696 minimizers
[M::ha_pt_gen::6667.454*7.41] ==> counted 19026189 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[5] = 263294
[M::ha_analyze_count] highest: count[8] = 372143
[M::ha_hist_line]     1: ****************************************************************************************************> 10897707
[M::ha_hist_line]     2: ****************************************************************************************************> 708611
[M::ha_hist_line]     3: ************************************************************************ 267501
[M::ha_hist_line]     4: *********************************************************** 221072
[M::ha_hist_line]     5: *********************************************************************** 263294
[M::ha_hist_line]     6: ************************************************************************************* 317771
[M::ha_hist_line]     7: ************************************************************************************************* 360518
[M::ha_hist_line]     8: **************************************************************************************************** 372143
[M::ha_hist_line]     9: ********************************************************************************************** 349320
[M::ha_hist_line]    10: ********************************************************************************* 301423
[M::ha_hist_line]    11: ****************************************************************** 245782
[M::ha_hist_line]    12: **************************************************** 193545
[M::ha_hist_line]    13: ******************************************* 158290
[M::ha_hist_line]    14: ************************************** 141696
[M::ha_hist_line]    15: ************************************** 140518
[M::ha_hist_line]    16: **************************************** 148099
[M::ha_hist_line]    17: ********************************************* 167677
[M::ha_hist_line]    18: *************************************************** 188720
[M::ha_hist_line]    19: ******************************************************** 207735
[M::ha_hist_line]    20: ************************************************************** 228893
[M::ha_hist_line]    21: ***************************************************************** 241919
[M::ha_hist_line]    22: ******************************************************************** 254287
[M::ha_hist_line]    23: *********************************************************************** 263475
[M::ha_hist_line]    24: *********************************************************************** 263478
[M::ha_hist_line]    25: ********************************************************************* 255385
[M::ha_hist_line]    26: ***************************************************************** 243323
[M::ha_hist_line]    27: *************************************************************** 233370
[M::ha_hist_line]    28: *********************************************************** 220717
[M::ha_hist_line]    29: ******************************************************* 205660
[M::ha_hist_line]    30: ************************************************** 184622
[M::ha_hist_line]    31: ********************************************* 168997
[M::ha_hist_line]    32: ***************************************** 151673
[M::ha_hist_line]    33: ************************************* 138267
[M::ha_hist_line]    34: *********************************** 131849
[M::ha_hist_line]    35: ******************** 74607
[M::ha_hist_line]    36: ******** 29712
[M::ha_hist_line]    37: **** 13337
[M::ha_hist_line]    38: ** 9075
[M::ha_hist_line]    39: ** 7110
[M::ha_hist_line]    40: ** 6231
[M::ha_hist_line]    41: * 5200
[M::ha_hist_line]    42: * 4585
[M::ha_hist_line]    43: * 3962
[M::ha_hist_line]    44: * 3609
[M::ha_hist_line]    45: * 3140
[M::ha_hist_line]    46: * 2648
[M::ha_hist_line]    47: * 2468
[M::ha_hist_line]    48: * 2275
[M::ha_hist_line]    49: * 2056
[M::ha_hist_line]  rest: ***** 18837
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 8; peak_het: -1
[M::ha_ct_shrink::6667.633*7.41] ==> counted 8128482 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 144649696 minimizers
[M::ha_pt_gen::6793.913*7.39] ==> indexed 133751989 positions, counted 8128482 distinct minimizer k-mers
[M::ha_assemble::9282.473*7.70@18.788GB] ==> corrected reads for round 3
[M::ha_assemble] # bases: 6834288217; # corrected bases: 61949; # recorrected bases: 3778
[M::ha_assemble] size of buffer: 4.087GB
[M::yak_count] collected 144630508 minimizers
[M::ha_pt_gen::9370.663*7.72] ==> counted 19006749 distinct minimizer k-mers
[M::ha_pt_gen] count[4095] = 0 (for sanity check)
[M::ha_analyze_count] lowest: count[5] = 263297
[M::ha_analyze_count] highest: count[8] = 372124
[M::ha_hist_line]     1: ****************************************************************************************************> 10881890
[M::ha_hist_line]     2: ****************************************************************************************************> 706551
[M::ha_hist_line]     3: ************************************************************************ 266599
[M::ha_hist_line]     4: *********************************************************** 220554
[M::ha_hist_line]     5: *********************************************************************** 263297
[M::ha_hist_line]     6: ************************************************************************************* 317686
[M::ha_hist_line]     7: ************************************************************************************************* 360661
[M::ha_hist_line]     8: **************************************************************************************************** 372124
[M::ha_hist_line]     9: ********************************************************************************************** 349334
[M::ha_hist_line]    10: ********************************************************************************* 301371
[M::ha_hist_line]    11: ****************************************************************** 245761
[M::ha_hist_line]    12: **************************************************** 193649
[M::ha_hist_line]    13: ******************************************* 158214
[M::ha_hist_line]    14: ************************************** 141663
[M::ha_hist_line]    15: ************************************** 140436
[M::ha_hist_line]    16: **************************************** 148129
[M::ha_hist_line]    17: ********************************************* 167639
[M::ha_hist_line]    18: *************************************************** 188757
[M::ha_hist_line]    19: ******************************************************** 207736
[M::ha_hist_line]    20: ************************************************************* 228807
[M::ha_hist_line]    21: ***************************************************************** 241890
[M::ha_hist_line]    22: ******************************************************************** 254327
[M::ha_hist_line]    23: *********************************************************************** 263463
[M::ha_hist_line]    24: *********************************************************************** 263494
[M::ha_hist_line]    25: ********************************************************************* 255270
[M::ha_hist_line]    26: ***************************************************************** 243309
[M::ha_hist_line]    27: *************************************************************** 233419
[M::ha_hist_line]    28: *********************************************************** 220688
[M::ha_hist_line]    29: ******************************************************* 205734
[M::ha_hist_line]    30: ************************************************** 184497
[M::ha_hist_line]    31: ********************************************* 169072
[M::ha_hist_line]    32: ***************************************** 151684
[M::ha_hist_line]    33: ************************************* 138254
[M::ha_hist_line]    34: *********************************** 131873
[M::ha_hist_line]    35: ******************** 74597
[M::ha_hist_line]    36: ******** 29770
[M::ha_hist_line]    37: **** 13326
[M::ha_hist_line]    38: ** 9074
[M::ha_hist_line]    39: ** 7120
[M::ha_hist_line]    40: ** 6236
[M::ha_hist_line]    41: * 5201
[M::ha_hist_line]    42: * 4593
[M::ha_hist_line]    43: * 3951
[M::ha_hist_line]    44: * 3604
[M::ha_hist_line]    45: * 3143
[M::ha_hist_line]    46: * 2650
[M::ha_hist_line]    47: * 2461
[M::ha_hist_line]    48: * 2292
[M::ha_hist_line]    49: * 2057
[M::ha_hist_line]  rest: ***** 18842
[M::ha_analyze_count] left: none
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 8; peak_het: -1
[M::ha_ct_shrink::9370.692*7.72] ==> counted 8124859 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 144630508 minimizers
[M::ha_pt_gen::9407.475*7.77] ==> indexed 133748618 positions, counted 8124859 distinct minimizer k-mers
[M::ha_assemble::9498.060*7.91@18.788GB] ==> found overlaps for the final round
[M::ha_print_ovlp_stat] # overlaps: 20272165
[M::ha_print_ovlp_stat] # strong overlaps: 11887714
[M::ha_print_ovlp_stat] # weak overlaps: 8384451
[M::ha_print_ovlp_stat] # exact overlaps: 19321794
[M::ha_print_ovlp_stat] # inexact overlaps: 950371
[M::ha_print_ovlp_stat] # overlaps without large indels: 20121450
[M::ha_print_ovlp_stat] # reverse overlaps: 9963860
Writing reads to disk... 
Reads has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
Writing ma_hit_ts to disk... 
ma_hit_ts has been written.
bin files have been written.
[M::purge_dups] homozygous read coverage threshold: 21
[M::purge_dups] purge duplication coverage threshold: 27
Writing raw unitig GFA to disk... 
Writing processed unitig GFA to disk... 
[M::purge_dups] homozygous read coverage threshold: 21
[M::purge_dups] purge duplication coverage threshold: 27
[M::mc_solve_core::0.160] ==> Partition
[M::adjust_utg_by_primary] primary contig coverage range: [17, infinity]
Writing selaginellasorg_hifiasm_assembly_s035.asm.bp.p_ctg.gfa to disk... 
[M::adjust_utg_by_trio] primary contig coverage range: [17, infinity]
Writing selaginellasorg_hifiasm_assembly_s035.asm.bp.hap1.p_ctg.gfa to disk... 
[M::adjust_utg_by_trio] primary contig coverage range: [17, infinity]
Writing selaginellasorg_hifiasm_assembly_s035.asm.bp.hap2.p_ctg.gfa to disk... 
Inconsistency threshold for low-quality regions in BED files: 70%
[M::main] Version: 0.16.1-r375
[M::main] CMD: hifiasm -s 0.35 -o *_s035.asm -t 32 m64041_230527_063349.bc2047--bc2047.hifi_reads.fastq.gz
[M::main] Real time: 9585.436 sec; CPU: 75260.297 sec; Peak RSS: 18.788 GB

**Comment by chhylp123** [comment]
Is your sample diploid?

**Comment by jiangqiuqiuu** [comment]
> Is your sample diploid?

Yes. It is supposed to be a homoploid hybrid species (hybrid without polyploidization). After some analysis I am also thinking about the possibility that this is not a diploid as lots of results from my analysis do not make sense.

**Comment by jiangqiuqiuu** [comment]
I figured it out. The sequenced sample is of multiple pooled individuals. Thank you!
