### ISSUE TITLE
change -k parameter

### ISSUE THREAD

**Issue by zskey-zn** [chhylp123/hifiasm#533]
Hello. I use hifiasm to assembly a high Heterozygous plant，I got this log，it's weird k-mer plots
![image](https://github.com/chhylp123/hifiasm/assets/55039417/f1ed7261-19f9-4820-a7a9-91002f40d661)

but when I use k=17 to cut mer, k-mer plots  look fine
![image](https://github.com/chhylp123/hifiasm/assets/55039417/66caef40-f800-4ae9-894e-37603c000c42)

can I change k parameter`(k:51->21 or 51->31)` to assembly?

**Comment by chhylp123** [comment]
No, the k-mer plot is still not correct when k = 7 (see: https://hifiasm.readthedocs.io/en/latest/faq.html#why-does-hifiasm-stuck-or-crash).
