### ISSUE TITLE
combine hifi data and nanopore data in hifiasm

### ISSUE THREAD

**Issue by tianjio** [chhylp123/hifiasm#534]
When I worked with hifi data and nanopore data for assembly, I tried to work with different nanopore datasets, including shallow incomplete datasets, complete datasets, and corrected datasets. But the result is that the output results of the three data sets after hifiasm assembly are exactly the same. I don't know how to check these problems. Could you please provide some suggestions?
I used the following parameters: hifiasm-o hifiasm --n-hap 4 -l 0 --ul correct.fa -t 20 sort.fastq 2> hifiasm.log

**Comment by chhylp123** [comment]
Could you please show the log file? Thanks so much.

**Comment by tianjio** [comment]
Thank you for your reply. 
Here is my log files. The first log file is uncorrect ,the second is correct. It seems that there is no difference between  two documents. And hifiasm version is 0.16.1.
[uncorrect_not_complete_l0_ont_hap4.hifiasm.log](https://github.com/chhylp123/hifiasm/files/12866379/uncorrect_not_complete_l0_ont_hap4.hifiasm.log)
[correct_2_l0_ont_hap4.hifiasm.log](https://github.com/chhylp123/hifiasm/files/12866380/correct_2_l0_ont_hap4.hifiasm.log)

And I have two other questions.
The first question is whether the --ul parameter should be followed by a fasta file or a fastq file, or both.
The second question is, does hifiasm software have specific parameters that can output the mapping file from unitig to contig?
Looking forward to your reply again

**Comment by chhylp123** [comment]
Oh, you need to run the latest version of hifiasm since 0.16.1 does not support the UL integration. As for your questions, hifiasm supports both fasta and fastq, but it cannot outpuut alignment files right now. We are considering to do that.

**Comment by tianjio** [comment]
Thanks for your help！\^o^/
