### ISSUE TITLE
Misjoins in the assembly

### ISSUE THREAD

**Issue by tbrown91** [chhylp123/hifiasm#54]
Hi,

I have used hifiasm to try assemble a few mammals and fish and have run into problems with mis-joins in the assembly. These issues are not detected until we map hic data and attempt to scaffold the contigs and often results in us having to make manual cuts in the contigs. Below is an example hic map of 3 contigs scaffolded into one chromosome. I have highlighted the beginning and end of the middle contig with blue arrows, which appears to have an issue at the start.

![scaffold_8_misassembly](https://user-images.githubusercontent.com/11500978/100599097-e0882480-32ff-11eb-90f2-1cab311201a5.png)

It is also quite easy to see which scaffold this contig belongs to by looking at the hic interactions with another scaffold:

![scaffold_8_1_misassembly](https://user-images.githubusercontent.com/11500978/100599189-fb5a9900-32ff-11eb-96f2-4b880e9822c6.png)

I have highlighted the contig of interest here in the p_ctg gfa, which is around 16Mb in length and this foreign region makes up the last ~600kb.

![hifiasm13_pctg_gfa](https://user-images.githubusercontent.com/11500978/100599350-34930900-3300-11eb-87be-3d2022b773cf.png)

For completenesss, here is the p_utg gfa, however I am not sure how to trace back to our contig of interest as the graph is very difficult to interpret.

![hifiasm13_putg_gfa](https://user-images.githubusercontent.com/11500978/100599420-4d032380-3300-11eb-8676-bd9cb8035800.png)

I mapped our ccs reads back to the assembly and found our break point, which shows a drop in coverage and a potential separation of the reads into the two haplotypes, although this may also be an issue with the underlying sequence in this region and the mapping.

![ccs_coverageBreakPoint](https://user-images.githubusercontent.com/11500978/100600335-73758e80-3301-11eb-8ef8-e0e933d52f92.png)

I ran hifiasm v0.13 without any additional arguments and perfomed mapping of the  CCS using pbmm2 with the CCS preset. We had around 36X coverage of this genome.

It would be great to hear if you have detected any similar issues and if we can tune the parameters to avoid such issues?

Many thanks,

Tom

**Comment by chhylp123** [comment]
Thanks for point out this problem. The first priority is to check if these mis-joins are caused by assembly step or purge_dups. You can have a try with '-l0' (disable purge_dups), '-l1' (no mis-joins) and '-l2' (default, may introduce mis-joins). I worry most of them are caused by '-l2'. With '-l2', increasing '-s' and '-O' should be helpful. '--pri-range' might be useful in some rare cases. If the mis-joins are not caused by '-l2', '-u' might be helpful. All these options reuse bin files so it should be fast to test them. 

I'm curious are there too many mis-joins? If there are just a few, probably it is fine to manually cut them by HiC... It is not hard to provide an option in hifiasm to cut potential mis-joins by coverage. The reason we haven't done that up to now is that it seems usually there are only a little mis-joins and can be easily solved by HiC. 

For now to cut mis-joins manually, usually you should find the reads at problematic regions in p_ctg (A-lines), and then grep them at r_utg, which is useless.

**Comment by tbrown91** [comment]
Thanks for the response. It varies between species, but currently I am having to make between 5 and 10 cuts per genome, which takes a fair amount of time and would be great to avoid. I have restarted the runs with l0 and l1 and will look at the mapping relative to the first assembly. Hopefully I will be able to give you an answer tomorrow.

Could you give a brief explanation of the -u argument? It seems a little counter-intuitive to remove mis-joins and increase N50 as is in the documentation.

**Comment by lh3** [comment]
It would be good to see the local unitig graph in .r_utg.gfa. If the misassembly is already present in the unitig graph. Haoyu's solutions above won't work.

**Comment by chhylp123** [comment]
I see. Some other groups prefer to have higher contiguity and they think a few misassemblies are fine, especially these misassemblies can be easily fixed by HiC. But misassemblies definitely make things harder. We should add an option to let users decide. 

As for '-u', hifiasm has a rescue mode in default, which rescues some overlaps to improve N50.  But it may introduce mis-joins in rare case. '-u' is used to disable it.

**Comment by lh3** [comment]
If the data is public and you can give us a list of read names around the misassembly, we can also investigate on our end. Thanks!

**Comment by tbrown91** [comment]
Unfortunately I'm not able to share the data, but I will now try to find the local unitig graph now

**Comment by tbrown91** [comment]
Hi, I've found my node of interest and have tried to highlight it at various zoom levels

![image](https://user-images.githubusercontent.com/11500978/100640559-d9303d80-3336-11eb-85ec-215c92963416.png)

![image](https://user-images.githubusercontent.com/11500978/100640521-cc134e80-3336-11eb-81e8-81e607a98b10.png)

![image](https://user-images.githubusercontent.com/11500978/100640882-2dd3b880-3337-11eb-987f-a6c114896772.png)

**Comment by chhylp123** [comment]
How long of this node? Is it much smaller than 16Mb?

**Comment by tbrown91** [comment]
yes, this node is pretty short at 44kb

**Comment by chhylp123** [comment]
So I guess this mis-join is caused by '-l2'

**Comment by tbrown91** [comment]
Ok, great. I will re-run the HiC mapping to check how this works

**Comment by tbrown91** [comment]
Hello again,

I reran the HiC mapping for assemblies using -l0 and -l1. Unfortunately I still have the same misjoins cropping up. I was able to count 5 errrors in the l0 assembly. The hic map for the contig I showed you for the -l1 assembly is here:

![image](https://user-images.githubusercontent.com/11500978/100744091-8cec0880-33dd-11eb-9990-83654b479634.png)

And for the -l0 assembly is here:

![image](https://user-images.githubusercontent.com/11500978/100743933-4a2a3080-33dd-11eb-88ca-14977902334a.png)

I will now try again using -l0 and -u, but again this will take some time to run. 

Any further guidance would be much appreciated.

Thanks,

Tom

**Comment by chhylp123** [comment]
Thanks a lot. Does the 44kb short unitig still introduce misassembly with '-l0'?

**Comment by tbrown91** [comment]
This  short contig doesn't seem to be involved. I know found the sequence in this 'gap' in the following two nodes, which are around 260kb and 500kb in length:

![image](https://user-images.githubusercontent.com/11500978/100751590-cfb2de00-33e7-11eb-8f5e-3de3514e81f2.png)

![image](https://user-images.githubusercontent.com/11500978/100751635-de00fa00-33e7-11eb-837e-1f869503b2cc.png)

![image](https://user-images.githubusercontent.com/11500978/100751681-eb1de900-33e7-11eb-9891-a90c63f8835c.png)

Is there a way to avoid joining together such regions of the graph and cut at these positions?

**Comment by tbrown91** [comment]
I missed this first time, but it looks like there is some sort of tandem in the middle of this region:

AATGTGGGCCCCACATGGGCCACAAGTGGGCAAGATGGGTACTGACTGGGCATGGGCTTGTCCAGGGCAAATTTTGAGGGGCCCAGAAAGGTTTGCTAATGTGGGCCCCATGTGTGATGCCCACATGGGCTGTGATCTGGGCCCCATATGGGTCTGTTGTTGGTTAAATGGGCATGGGATAAAACTGGGCAAAAATTAATGGGCCCATATAGTTTAACATACATGGGGCCCAGGTGTAAAGCCCATGTGGGTTGGCTAAATGGGACCTTTATGGGTTCTAAGTGGGCAAACTGGGCATGGGCTAAGGCTGGGATGCCCTATGTAGGGCCCATATAGTTTAACCTGAATTGGCCCCACATGGGCAACCCACGTGGGCTAACTATATGGGGCCCATTTAAAATTCAAGTGGGCTAAACTGACATGGGCTAAGGCTGGGATGCCCTATGTAGGGCCCATATAGTTTAACCTGAATTGGCCCCACATGGGCAACCCACGTGGGCTAACTATATGGGGCCCATTTAAAATTCAAGTGGGCTAAACTGACATGGGCTAAGGCTGGGATGCCCTATGTAGGGCCCATATAGTTTAAACTGAATTGGCCCCACATGGGCAACCCACGTGGGCTAACTATATGGGGCCCATTTAAAGTTCGAGTGGGCT

**Comment by tbrown91** [comment]
And the -l0 -u assembly still gives a contig that maps front-to-end with this contig, both about 20Mb in length, so the -u option did not break the contig at this misjoin.

**Comment by chhylp123** [comment]
I see. I will update a new version soon that can provide an option to break these low coverage regions.

**Comment by chhylp123** [comment]
@tbrown91 Sorry for the delay. We just released v0.14, which includes three new options '--b-cov', '--h-cov' and '--m-rate'. Hope it is helpful to break contigs at potential misassemblies.

**Comment by tbrown91** [comment]
Thank you for the new version. Do you have any hints as to how to set these values? Have you been able to play with it at all with any datasets? I'm particularly interested in the --m-rate parameter - would you recommend changing this much from the default 0.75?

**Comment by chhylp123** [comment]
It's hard to say...For homozygous samples, '--m-rate' works ok, but for heterozygous samples, sometimes '--m-rate' decreases N50 a lot.

**Comment by tbrown91** [comment]
Is there any chance you could write a short explanation of what the m-rate is doing and which coverage this corresponds to? Is the break rate FLOAT*(haploid coverage)? Or does this coverage somehow relate to the b-cov and h-cov?

**Comment by chhylp123** [comment]
@tbrown91 Sorry I missed this comment due to email misconfiguration... Yes, it depends on b-cov and h-cov. For example, if hifiasm is run with "--h-cov=62 --m-rate=0.75", which means:

>hifiasm breaks subregions with X-fold (X>=62) coverages and it has <=(0.75*X) exact overlaps. The coverage is the coverage of subregion instead of haploid coverage.

**Comment by tbrown91** [comment]
Just a short update. I've noticed since v15 that these mis-assemblies are no longer appearing in the hifiasm assemblies. Since then I haven't had to cut any contigs during the HiC scaffolding phase.

I will close the issue as things look pretty good on this front now

**Comment by chhylp123** [comment]
Good to know, thanks a lot.
