### ISSUE TITLE
Can i need to polish raw genome that generated by HiFi and ultra-long ONT reads

### ISSUE THREAD

**Issue by shehongbing** [chhylp123/hifiasm#550]
Hi,
   I wonder if further polishing is needed based on the genome assembled by HiFi and ONT.

THX

Hongbing

**Comment by chhylp123** [comment]
In most cases, assembly without polishing should be fine. But you may consider to utilize emerging very accurate polish tools like DeepPolish.

**Comment by shehongbing** [comment]
Thanks for your suggestions. I'll try this.

**Comment by GRGong** [comment]
@chhylp123 Could you please provide me with the URL for DeepPolish? I've been searching for it, but I can only find a repository called 'deeppolisher'(https://github.com/google/deeppolisher), which is empty. Thank you for your assistance!

**Comment by chhylp123** [comment]
Sorry for the late reply as I was quite busy last month. I only know they have the beta version that could be used. So could you please email the google team about the deeppolisher?

**Comment by GRGong** [comment]
Thanks a lot!
