### ISSUE TITLE
Assembly issue for ONT and HIFI

### ISSUE THREAD

**Issue by duzeyu1995** [chhylp123/hifiasm#551]
Hello，@chhylp123
This is a very important piece of software. Now I'm having some problems. 
The program runs fine with only using the HiFi reads（50X，~1.2GB genome）. I am running hifiasm using both the ONT （100X，N50=100kb）and PacBio HiFi data. It stalls after the indexing step and has been running for ~20 days since index creation.
Should I stop or keep running？How can one speed the analysis? Any suggestion(s)?

My script was shown：
hifiasm -o onthifiasm.asm -t 40 --ul /work/home/duzeyu/ONT_data/FASTQ/ont.fastq.gz /work/home/duzeyu/HiFi_data/data/FPAC230163622-1A/HIFI_14--1.hifi_reads.fasta /work/home/duzeyu/HiFi_data/data/FPAC230163622-2A/HIFI_14--2.hifi_reads.fasta 

 log：
[M::ul_refine_alignment::] ==> UL refinement...
[M::ha_opt_update_cov] updated max_n_chain to 330
[M::gen_cov_track::] # bases: 3641819464
[M::work_ul_gchains::] # try:57651, # done:5668
[M::update_sg_uo::] ==> # gfa reads:621244, # covered gfa reads:606620
[M::ha_opt_update_cov] updated max_n_chain to 330
[M::work_ul_gchains_consensus::] # try:14665, # done:387
[M::clean_contain_g0::] # discard cread::6
[M::update_sg_uo::] ==> # gfa reads:621238, # covered gfa reads:606610
[M::ha_opt_update_cov] updated max_n_chain to 330
[M::work_ul_gchains_consensus::] # try:14263, # done:0
[M::clean_contain_g0::] # discard cread::1
[M::update_sg_uo::] ==> # gfa reads:621229, # covered gfa reads:606601
[M::purge_dups] homozygous read coverage threshold: 133
[M::purge_dups] purge duplication coverage threshold: 167
[M::ug_ext_gfa::] # tips::1012
Writing raw unitig GFA to disk... 
[M::update_sg_uo::] ==> # gfa reads:599684, # covered gfa reads:592256
[M::ul_realignment::] ==> starting UL
[M::ha_opt_update_cov] updated max_n_chain to 330
[M::gen_cov_track::] # bases: 2674019972
[M::ha_ct_shrink::129905.367*35.85] ==> counted 4228643 distinct minimizer k-mers
[M::ha_ft_ul_gen::129906.841*35.85@209.026GB] ==> filtered out 4228643 k-mers occurring 32 or more times
[M::yak_count] collected 241067818 minimizers
[M::ha_pt_ul_gen::129945.609*35.84] ==> counted 64964497 distinct minimizer k-mers
[M::ha_ct_shrink::129945.734*35.84] ==> counted 64964497 distinct minimizer k-mers
[M::yak_count] collected 241067818 minimizers
[M::ha_pt_ul_gen::129988.224*35.84] ==> indexed 241067818 positions
[M::uidx_l_build] Index has been built.
[M::uidx_write] Index has been written.
[M::ha_opt_update_cov] updated max_n_chain to 330
[M::cal_graph_ovlp_binning::387.281] ==> Qualification
[M::write_emask_t] Index has been written.
[M::rescall_ul_pipeline::16869.497] ==> Qualification
[M::rescall_ul_pipeline::] ==> # reads: 806854, # bases: 0, # fully corrected reads: 688287
[M::write_all_ul_t] Index has been written.
[M::print_integert_ovlp_stat::] # UL reads::200557, # UL ovlps::55097060
[M::print_integert_ovlp_stat::] # UL reads::49852, # UL ovlps::5248150

**Comment by chhylp123** [comment]
@duzeyu1995 Is hifiasm still running with multiple CPUs? I feel like something might be wrong with hifiasm. Could you please show me the bin file hifiasm has been generated?

**Comment by duzeyu1995** [comment]
Yes，I have run the test data and the results are fine. I've always thought that maybe the ONT coverage is too large and the operation is slow. But now I think this time is not normal, so I need your help.
Is this the right bin file？ 
[hifiasm_bin.zip](https://github.com/chhylp123/hifiasm/files/13258569/hifiasm_bin.zip)

In fact, I'm trying to work with different combinations of data.However, after the ONT data is added, the operation becomes slow：alone HIFI(24h);HIFI+HIC(24h);HIFI+ONT(~20 days since index creation);HIFI+HIC+ONT(~11 days since index creation).

**Comment by chhylp123** [comment]
Hifiasm has already done the most  time-consuming part for the UL-assembly. Could you please list all bin files it generates? I was wondering if it is the issue of not enough memory or disk space for your server.

**Comment by duzeyu1995** [comment]
The server has 1.4TB of free space.
These are the files generated by the two tasks: onthifiasm (using ONT reads and HIFI) and T2Thifiasm (ONT+HIFI+HIC).
Thanks.

![image](https://github.com/chhylp123/hifiasm/assets/144589880/514501fc-5f6e-4fce-97f1-fd7cef2b3157)

![image](https://github.com/chhylp123/hifiasm/assets/144589880/e835721c-90d9-41c7-8210-1b8fc4343814)

**Comment by chhylp123** [comment]
Could you please give me a screenshot when using `top`?

**Comment by duzeyu1995** [comment]
Of course, but now I terminate the program and filter out the ONT data below 100kb and resubmit the task. I was worried that the coverage was too large and the operation was slow, and only ONT data under 20kb was cleared.
This is the current screenshot when using top.
![image](https://github.com/chhylp123/hifiasm/assets/144589880/f39d584e-1dd1-4faf-a407-a6ead2c44e26)
I use a Cloud Virtual Machine with 256GB of memory. On the 9th day of operation, I asked the backend staff about CPU Utility, and it seems to be OK.
![fe7adb3d054de394c82a57cd44a76b6](https://github.com/chhylp123/hifiasm/assets/144589880/fcb38eb9-dbe8-4d89-8c74-e0f871be0200)

**Comment by chhylp123** [comment]
Thanks so much and looking forward for your results. By the way, hifiasm could internal filter out short UL reads by using `--ul-cut`.

**Comment by duzeyu1995** [comment]
Thank you very much. I will try internal filter out short UL reads by using --ul-cut at the same time. Look forward to successful assembly.

**Comment by kevfengler227** [comment]
I have been troubleshooting the same issue. The UL integration step after indexing gets held up for very long given slightly larger UL  datasets. For example, 22x HiFi + 17x ONT (min 30k) finishes in a few hours but 22x + 27x (min 30k) took 10 days.

**Comment by chhylp123** [comment]
@kevfengler227 How large is your genome? Is it possible that you can share the 22x HiFi + 27x ONT with us? Taking 10 days might be wrong on hifiasm.

**Comment by kevfengler227** [comment]
it's only a 2.3 Gb maize genome. unfortunately, I cannot share the data but willingly to help troubleshoot in any way I can.

**Comment by chhylp123** [comment]
Could you please share me the log files for both the 27x ONT and the 17x ONT rounds? By looking at the log files, probably I can figure out some issues. Thanks so much.

**Comment by kevfengler227** [comment]
maize has a lot of long simple sequence repeats so I am wondering if the ONT reads containing those are problematic, perhaps at some threshold given higher higher coverage

**Comment by chhylp123** [comment]
@kevfengler227 What if we have a try to give hifiasm 17x twice and see how long it will take? Then the coverage will be 34x. But it would still be very helpful if you could give me the log files first.

**Comment by kevfengler227** [comment]
correction. my last test that took 10 days to complete had 33x HiFi and 48x ONT (min 30 kb) for 2.3 Gb genome. I gave up on previous tests with less ONT after a few days. this one I let run until it finished. I'll send you the log.

**Comment by chhylp123** [comment]
Thanks so much. I am just worrying whether the much longer running time is the issue of higher coverage or the data quality of the additional ONT reads.

**Comment by kevfengler227** [comment]
The accuracy of the ONT reads based on alignment to the assembly is 98.3%, but I guess unaligned reads could be problematic

I have another test that finished in 5 days with the same 48x ONT, but only 22x HiFi, so the HiFi is involved too. I'll send you that log.

**Comment by kevfengler227** [comment]
I'll try the 17x versus 17x(x2) test that you suggest.

**Comment by chhylp123** [comment]
@kevfengler227 Thanks so much for your log files. Actually hifiasm does two rounds of UL-to-HiFi alignment. The first round is to align UL reads to HiFi reads (roughly), while the second round is to align UL reads to HiFi assembly graph. It seems >90% of time was taken for the first of round of UL alignment. I worry that very few of ONT reads are very hard to be assembled, so that they took most of the time. If that is true, 17x(x2) test will be supper fast as well. I may consider to set a threshold to directly discard these very bad ONT reads. But I'm looking for your test first. Thanks again for your great help.

**Comment by kevfengler227** [comment]
do you think that reads with long SSRs would be classified as "bad" ONT reads? As I said, maize has more of these then other plant genomes. All of the assemblies I have done with soybean, which do not have these, were much faster.

of course these are the exact regions I am trying to resolve and close to achieve T2T!

**Comment by chhylp123** [comment]
@kevfengler227 Actually I am worrying it more likely a bug. As you mentioned, 17x is much fast while 27x takes 10 days. So if reads with long SSRs matters, taking 17x ONT reads will also extremely slow. I feel like some reads are bad in weird ways.

**Comment by baozg** [comment]
Could `hifiasm` count UL reads mapping to inform people how the alignment going? Like 10000 reads per line, if some parts took too many times, then you have a chance to find "bad" reads? @kevfengler227 Have you tried to use published Mo17 T2T to reproduce this issue? If it happened with this public dataset, then you can share it, right? I do think some long TAG repeats would hurt UL alignment.

**Comment by kevfengler227** [comment]
I could do that, but that Mo17 ONT data would be quite dated now, so may not be informative for current ONT data . The ONT data here is with the latest chemistry and plant optimized basecaller. Let's see how the test goes. I like the idea of more info during alignment to help with troubleshooting.

**Comment by baozg** [comment]
Did you mean sequencing with R10.4 with Kit14? But that's only normal simplex reads, right? It's not an ultra-long library since ONT only supports it with R9.

**Comment by duzeyu1995** [comment]
I tested a hybrid assembly of ONT (100 x, min 100 KB), HIFI (50 x), and HIC (100 x) using hifiasm. ContigN50 has been doubled, it looks fine. Compared to unfiltered ONT running a 20days card on the index step, this took only 1day14hours. It does seem to be due to high ONT data coverage. The genome of my species is also rich in repeats. When I used --ul-cut, it was also fast (18h), but produced the same result as hifi+hic assembly, seemingly cutting the entire ONT data.

**Comment by chhylp123** [comment]
@duzeyu1995 Could you please show me the log file and command line you were using with `--ul-cut`?

**Comment by duzeyu1995** [comment]
Of course，command line：
`hifiasm -o /work/home/duzeyu/hifiasm/cut/t2thifiasm.asm -t 64 --h1 /work/home/duzeyu/HIC_data/hic_1.fq.gz --h2 /work/home/duzeyu/HIC_data/hic_2.fq.gz --ul-cut /work/home/duzeyu/ONT_data/FASTQ/ont.fastq.gz /work/home/duzeyu/HiFi_data/data/FPAC230163622-1A/HIFI_14--1.hifi_reads.fasta /work/home/duzeyu/HiFi_data/data/FPAC230163622-2A/HIFI_14--2.hifi_reads.fasta `

the log file：
[t2thifiasm_1.log](https://github.com/chhylp123/hifiasm/files/13316578/t2thifiasm_1.log)

**Comment by chhylp123** [comment]
@duzeyu1995 Probably you need to set a value for `--ul-cut`. Could you please have a try with:
> hifiasm -o /work/home/duzeyu/hifiasm/cut/t2thifiasm.asm -t 64 --h1 /work/home/duzeyu/HIC_data/hic_1.fq.gz --h2 /work/home/duzeyu/HIC_data/hic_2.fq.gz --ul-cut 100000 /work/home/duzeyu/ONT_data/FASTQ/ont.fastq.gz /work/home/duzeyu/HiFi_data/data/FPAC230163622-1A/HIFI_14--1.hifi_reads.fasta /work/home/duzeyu/HiFi_data/data/FPAC230163622-2A/HIFI_14--2.hifi_reads.fasta

**Comment by duzeyu1995** [comment]
Thank you very much. Of course, I will try and communicate with you.

**Comment by duzeyu1995** [comment]
Hello, this command runs successfully (-1d13h).

**Comment by chhylp123** [comment]
@duzeyu1995 Could you please share me the HiFi bin files (*.ecc.bin, *.ovlp.source.bin, and, *ovlp.reverse.bin) and the 100x UL reads with me? It would be very helpful if you could share these bin files with me, then I can have a try to fix the issue that hifiasm is extremly slow when working with very high coverage UL reads. To save the space, you can share the fasta of UL reads with me. Thanks in advance.

**Comment by zhangyixing3** [comment]
Hello, this issue has been resolved? @chhylp123 
I encountered a similar issue. The version of hifiasm is 0.24.0-r702.
I found that when I use `--ont` to assemble R10 ONT data at 24X coverage, it is very fast—taking only two day to complete. However, when I use `--ul all.pass.ul.fq.gz` (24X， reads with quality >= Q10), the process becomes extremely slow. It has been six days already, only four files have been generated:
xz.ec.bin, xz.ovlp.reverse.bin, xz.ovlp.source.bin, and xz.uidx.bin.

Perhaps I also need to filter the reads based on length？

**Comment by zhangyixing3** [comment]
Yes, hifiasm may only require about 400G of memory, and I have 2T, which should be sufficient. I'm working on an autotetraploid sugarcane, Its genome is particularly complex，so maybe I just need to wait  longer time ?

**Comment by HaxyMoly** [comment]
> Yes, hifiasm may only require about 400G of memory, and I have 2T, which should be sufficient. I'm working on an 2n=8X= 80 sugarcane, Its genome is particularly complex，so maybe I just need to wait longer time ?

Hi, have you completed the assembly? How long did it take? I'm currently attempting to use 140x hifi + 140x ultra long + 50x trio data for hybrid assembly, but hifiasm takes too much memory (over 1T), and it's still stuck at

```
[M::ha_analyze_count] left: count[76] = 671614
[M::ha_analyze_count] right: none
[M::ha_pt_gen] peak_hom: 156; peak_het: 76
[M::ha_ct_shrink::8908.953*12.35] ==> counted 82460931 distinct minimizer k-mers
[M::ha_pt_gen::] counting in normal mode
[M::yak_count] collected 9493742630 minimizers
[M::ha_pt_gen::9695.003*14.80] ==> indexed 9404094762 positions, counted 82460931 distinct minimizer k-mers
```

for at least 72 hours without creating any files. But it's just a simple mammal genome (approximately 2.6g)

**Comment by chhylp123** [comment]
140x HiFi reads are huge amount of data. In this case, it will take longer. You may consider to downsample it a little bit if time is a constrain.
