### ISSUE TITLE
Usage assembly without hifi reads

### ISSUE THREAD

**Issue by yeah-zin** [chhylp123/hifiasm#554]
Hello, I was amazed by the impressive performance of hifiasm. While the manual mainly focuses on using hifi reads, is it possible to perform assembly without hifi reads, only with ordinary ONT reads?

**Comment by chhylp123** [comment]
We may have a try to make hifiasm work for ONT reads later, but it does not work right now.

**Comment by yeah-zin** [comment]
@chhylp123  Thank you for reply.
