### ISSUE TITLE
HiFi and ultra-Long ONT  reads generates many short contigs in length

### ISSUE THREAD

**Issue by shehongbing** [chhylp123/hifiasm#556]
Hi,
    Thanks for your powerful tool. I used hifiasm to assemble a inbred line material (2n=12) based on HiFi (80x) and ultra-long ONT reads (65x) with default parameters. Total of 931 contigs were obtained and N50 length of 164 Mb. There are 6 contigs almost reached the chromosome-level, and remaining 925 contigs averaged 61 kb in length  (occupied 57 Mb, 5.9% of the assembly, min length: 1,190; max length: 2,938,020). 

Do you any suggestions to reduce the number of short length contigs.

Best,
Hongbing

**Comment by Hanjiangna** [comment]
So could it be mitochondria
