### ISSUE TITLE
Hi.  'hifiasm.0.19.8-r603' and Your pre-printed articles

### ISSUE THREAD

**Issue by kuangzhuoran** [chhylp123/hifiasm#557]
I noticed your article on arxiv: 'Scalable telomere-to-telomere assembly for diploid and polyploid genomes with double graph'

Does it correspond to the version 'hifiasm.0.19.8-r603'?

**Comment by chhylp123** [comment]
The version corresponds to our manuscript is `0.19.5-r587`. But it would be always better to use the latest one.

**Comment by kuangzhuoran** [comment]
Thanks
