### ISSUE TITLE
check resulting assembly from haplotype binning is better than without

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [chhylp123/hifiasm#56]
Hello there,
Thanks for developing such wonderful tool. There is an idea that I want to test. 
I would like to know if the resulting haplotype-specific assembly from hifiasm using '-3 -4' is better than a diploid hifiasm assembly.  For instance, for a region of interest, I have already information (say from Hi-C) that allows me to separate the HiFi reads into two haplotypes. 
so I ran hifiasm using the following command:
hifiasm -o haplotype_binning_-3-4out -t 8 -3 haplotype1_read_list -4 haplotype2_read_list comb.fa

I wanted to know if this assembly is better than an assembly from default hifiasm, so I ran hifiasm with the following command:
hifiasm -o comb.hifiasm -t8 comb.fa

It produces the output files as shown in the attachment.
I wonder what are the files that I should look at for a direct comparison, say check N50? 
I am very curious to know essentially what hifiasm did, specifically, how differently the '-3 -4' mode behave differently from the default diploid assembly. 
<img width="563" alt="Screen Shot 2020-12-03 at 12 42 30 AM" src="https://user-images.githubusercontent.com/9053403/100903358-c79a9180-3500-11eb-8a6e-4ef962edef28.png">
<img width="576" alt="Screen Shot 2020-12-03 at 12 42 17 AM" src="https://user-images.githubusercontent.com/9053403/100903378-cbc6af00-3500-11eb-85c5-1796205f10e3.png">
Hope my questions are clear :-).
thanks,
zhenzhen

**Comment by zhenzhenyang-psu** [comment]
I compared the N50 of the fast from the following three files:
comb.hifiasm.p_ctg.fa
haplotype_binning_-3-4out.hap1.p_ctg.fa
haplotype_binning_-3-4out.hap2.p_ctg.fa

The N50 is not much different:
combined primary contain N50:
		"totalContigLength": "1419992",
		"numberOfContigs": "3",
		"contigN50": "492778",
		"longestContig": "657757",
		"totalScaffoldLength": "1419992",
		"numberOfScaffolds": "3",
		"scaffoldN50": "492778",
		"longestScaffold": "657757",

haplotype1 primary contain N50:
		"totalContigLength": "1419063",
		"numberOfContigs": "3",
		"contigN50": "491528",
		"longestContig": "658078",
		"totalScaffoldLength": "1419063",
		"numberOfScaffolds": "3",
		"scaffoldN50": "491528",
		"longestScaffold": "658078",

haplotype2 primary contig N50:
		"totalContigLength": "1416418",
		"numberOfContigs": "3",
		"contigN50": "492613",
		"longestContig": "655973",
		"totalScaffoldLength": "1416418",
		"numberOfScaffolds": "3",
		"scaffoldN50": "492613",
		"longestScaffold": "655973",

They are not much different. I guess this means that the haplotype binning information I provided is not better than what hifiasm can do inherently.

so presumably if the HIFI reads that I provide span a much longer haplotype block than what HIFI reads can phase, it should be better. 

Anyways, sorry for bothering. 

I was wondering the difference of primary unitigs (p_utg.gfa)/the alternate unitigs (r_utigs.gfa) from primary contigs. 
is there a way to visualize the .gfa for these different files for illustration. 

Finally, there is a question of how to use the overlap information 
(comb.hifiasm.ovlp.source.bin/comb.hifiasm.ovlp.reverse.bin) to identify any HiFi reads that overlap with HiFI reads of interest (among the input HiFi reads)?
thanks a lot,
zhenzhen

**Comment by chhylp123** [comment]
The assemblies with/without -3 and -4 are totally different:

>1. If you run hifiasm in default, it will output a primary assembly including haplotype switch between two haplotypes. So the primary assembly is not a fully phased assembly, it is a mixture of two haplotypes. 
>2. If you run hifiasm with -3 and -4, it will try to output two fully phased assemblies, one for each haplotypes (see Figure 1 and Figure 2 in https://arxiv.org/pdf/2008.01237.pdf).

If the N50s of hap1, hap2 and the primary assembly are similar, I guess the reason might be that your sample is too simple. You can have a try with large and complex samples.

As for the overlaps, hifiasm can output all overlaps with the option `--write-ec`.

**Comment by zhenzhenyang-psu** [comment]
thanks, Haoyu! 
When you say large and complex samples, do you mean input file containing HiFi reads across a bigger region from the genome?

**Comment by lh3** [comment]
Option -1/-2 or -3/-4 is intended for whole-genome phasing.

**Comment by zhenzhenyang-psu** [comment]
I see. Thanks!
I wonder when using -3/-4, if the ability to designate reads from two separate haplotypes is limited - i.e. only a portion of the reads are indicated to be haplotype-specific and provided via -3/-4, how does hifiasm handle the remaining reads? Does it consider all the remaining reads as homozygous and add to each of the two haplotypes?

**Comment by chhylp123** [comment]
No, in this case, it can still check which read is heterozygous, and then assign heterozygous reads to one haplotype randomly.

**Comment by zhenzhenyang-psu** [comment]
> No, in this case, it can still check which read is heterozygous, and then assign heterozygous reads to one haplotype randomly.

that's wonderful! thank you!
