### ISSUE TITLE
High BUSCO missing rate

### ISSUE THREAD

**Issue by shehongbing** [chhylp123/hifiasm#574]
Hi, 
I have both HiFi and ONT long-reads. First, I de novo a assembly with N50 164 Mb based on  both HiFi and ONT long-reads, and the BUSCO value is follows:
C:92.6%[S:90.7%,D:1.9%],F:1.8%,M:5.6%,n:1375

Then, I assembled the other genome with N50 75 Mb based on only HiFi reads. And the BUSCO value is follows:
C:93.6%[S:91.7%,D:1.9%],F:1.5%,M:4.9%,n:1375

Last, I assembled with ONT data only using NextDenovo and got 100 Mb of N50 of the genome, but his BUSCO value is still very low, see follows:
C:93.0%[S:90.4%,D:2.6%],F:1.5%,M:5.5%,n:1375

Can you give me some advice on why there is such a low BUSCO value?
Thanks 

Hongbing

**Comment by chhylp123** [comment]
Sorry for the late reply as I was quite busy last month. In general, BUSCO gives a sense about how good the assembly is.  But I feel like for some specific samples, the busco values should be around 90%? It would be better to use other metrics such as k-mer completeness to double check the assembly.
