### ISSUE TITLE
Not clear about haplotig purging (-l0)

### ISSUE THREAD

**Issue by ptranvan** [chhylp123/hifiasm#58]
Hi,

I used the option `-l0` but I still have `*a_ctg.gfa` in addition of `p_ctg.gfa` so I am not sure to understand what is the option `-l0` usage for haplotig purging, because I would have expected primary contigs only

**Comment by lh3** [comment]
Real samples are heterogeneous unless you sequence a single cell with a haploid genome.

**Comment by chhylp123** [comment]
You can merge a_ctg back to p_ctg if there are only a small number of contigs in a_ctg. As Heng said, there are always some heterozygous contigs in real samples.
