### ISSUE TITLE
Hifiasm with Pacbio Ultra-low DNA input sequencing data out put assembly with High duplication level of BUSCO score in Hi-C mode

### ISSUE THREAD

**Issue by Neo-xbx-00** [chhylp123/hifiasm#584]
Hi,
Thanks a lot for this nice tool. However, my assemblies generated by hifiasm were not ideal. The species I focus on is hard for DNA extraction, so we made use of the Pacbio ultar-low DNA input sequencing methods and generated HiFi reads (~26X depth compared with the estimated genome size).
![linear_plot](https://github.com/chhylp123/hifiasm/assets/72716707/774ae33f-16cd-4100-973e-322d3b1f7da8)

Until now, I have tested for three times with Hifiasm v0.19.8 using different parameters in Hi-C mode:
~/App/hifiasm-0.19.8/hifiasm -o XX_hifiasm_default -t 24 --h1 hic_R1.fq.gz --h2 hic_R2.fq.gz XX.hifi1-2.fastq.gz
~/App/hifiasm-0.19.8/hifiasm -o XX_hifiasm_v2 -t 24 --hom-cov 8 -s 0.4 --h1 hic_R1.fq.gz --h2 hic_R2.fq.gz XX.hifi1-2.fastq.gz
~/App/hifiasm-0.19.8/hifiasm -o XX_hifiasm_v3 -t 24 --hg-size 700m -s 0.4 --min-hist-cnt 2 --h1 hic_R1.fq.gz --h2 hic_R2.fq.gz XX.hifi1-2.fastq.gz
I used BUSCO5 for evaluating the quality of these draft contig-level assemblies from HiFiasm. However, I found the contig N50 is short (I undersood what caused this problem from a previous issue) and the duplication levels from BUSCO score is really high (more than 20%).
I attached my log files for the above three Hifiasm runs as well as the busco results for the assemblies generated.
I hope you can give me some advice for parameters I should use, many thanks !
[error2.log](https://github.com/chhylp123/hifiasm/files/13792192/error2.log)
[error3.log](https://github.com/chhylp123/hifiasm/files/13792193/error3.log)
[error.log](https://github.com/chhylp123/hifiasm/files/13792194/error.log)
[stat_buscos_for_3_runs.txt](https://github.com/chhylp123/hifiasm/files/13792195/stat_buscos_for_3_runs.txt)

**Comment by chhylp123** [comment]
What’s the coverage of your dataset? By looking at the log file, it seems that the coverage is only 6, which is too low for hifiasm.

**Comment by Neo-xbx-00** [comment]
Thanks for your reply. The coverage of my dataset is around 26X.
Untils now, I have solve this problem using HiCanu + Purge_dups. Maybe the cutoffs set manually is more convenient for my dataset :)
