### ISSUE TITLE
Which of the two haplotypes is from the parent and which is from the mother? Do the two haplotypes need to remove haplotypic duplication?

### ISSUE THREAD

**Issue by aijigekoukou-shen** [chhylp123/hifiasm#585]
Hi,

I used hifisam to assemble two haplotype genomes in trio-binning mode based on ont, hifi, and Illumina DNA reads from parents. The following are my commands. I have two questions.

1) Which of the two haplotypes is from the parent and which is from the mother? Is hap1 from paternal and hap2 maternal?
2) Do the two haplotypes need to remove haplotypic duplication? For example, use purge_dups.

Thanks

Tengfei Shen
```
nohup hifiasm -o out.asm -t60 -1 pat.yak -2 mat.yak --ul ont.160k.fq ccs.10k.fq &
awk '/^S/{print ">"$2;print $3}' out.asm.dip.hap1.p_ctg.gfa > hifi_ont_hifiasm.hap1_assembly.fa
awk '/^S/{print ">"$2;print $3}' out.asm.dip.hap2.p_ctg.gfa > hifi_ont_hifiasm.hap2_assembly.fa

**Comment by chhylp123** [comment]
If `pat.yak` and `mat.yak` come from father and mother respectively, hap1 would be the  paternal assembly and hap2 would be the maternal assembly. If everything is right, no need to run purge_dups for the phased assembly.

**Comment by aijigekoukou-shen** [comment]
I see, thank you very much for your reply.
