### ISSUE TITLE
hifiasm trio-bin produced smaller N50 compared to standard hifiasm ?

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [chhylp123/hifiasm#59]
<img width="665" alt="Screen Shot 2020-12-14 at 10 40 38 AM" src="https://user-images.githubusercontent.com/9053403/102034481-0bdb3b00-3df9-11eb-8538-7d9567e77a01.png">
Hello Haoyu,
I was trying to evaluate if the hifiasm using trio-bin is better than hifiasm without trio-bin.
So I compared the N50 of the assembled fasta using hifiasm trio-bin with that from hifiasm only.
To my surprise, the N50 from the former is smaller than the latter. 
I used the HG001 dataset (30x HiFi), the resulting N50 of the p_ctg.gfa is 34MB, yet the haplotype-specific assembly is only 26.5MB. 

I also found from the hifiasm benchmarked result with HG002, the hifiasm trio bin-derived N50 is smaller than the standard hifiasm (see attached). I was under the impression that a haplotype specific assembly with more information from the trio should result in a much more contiguous assembly, is this not true?

I did find that the number of contigs from standard hifiasm is about twice as big as that from the trio-bin hifiasm. 
In my case of testing with HG001 (30x HiFi), the number of contains is 4293, yet the trio-binned version is 2286 and 2038. This would make the average contig length around twice bigger though.
I was wondering your thoughts on this.

thanks very much,
Zhenzhen

**Comment by zhenzhenyang-psu** [comment]
oops, here is the link to the attachment:
https://s3.wasabisys.com/aiden-zhenzhen/public/temp/temp/hifiasm_trio-bin_vs_hifiasm_N50.png

**Comment by lh3** [comment]
Trio binning assembly is almost always preferred. N50 is not a good metric by itself.

**Comment by zhenzhenyang-psu** [comment]
Hi Heng, thanks for your reply.  could you suggests some directions?
thanks
zhenzhen

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by chhylp123** [comment]
The outputs of trio-hifiasm and hifiasm are different. Trio-hifiasm outputs two assemblies, one for each haplotype. In contrast, standard hifiasm outputs a primary assembly, which mixes two haplotypes. If one haplotype is broken while another is contiguous, the primary assembly will select the contiguous one so that it does not affect N50. However, the trio-binning assemblies will be broken here. For fully phased assembly, the switch error rate/hamming error rate is important. Trio-binning assembly has much lower switch error rate/hamming error rate than primary assembly.

**Comment by zhenzhenyang-psu** [comment]
thanks for the comments. However, I am still puzzled why the primary assembly has higher contiguity than the haplotype-specific assembly, should it be similar at most?
<img width="603" alt="Screen Shot 2020-12-16 at 10 11 13 AM" src="https://user-images.githubusercontent.com/9053403/102295813-1d524d80-3f87-11eb-8e88-3941d11d5259.png">

**Comment by zhenzhenyang-psu** [comment]
Hello there,
I mapped the contigs (using minimap2) from the hifiasm trio-bin assembly of my HG001 dataset to the hg38 genome ( in which homozygous SVs were replaced according to the HG001 vcf). To my surprise, in certain regions, a lot of contigs map to the same region, suggesting they are redundant. This could perhaps explain why N50 is not a good metric to evaluate the quality of the assembly. 

Here just shows one of the examples of redundant contigs mapping to same region.
https://s3.wasabisys.com/aiden-zhenzhen/public/temp/temp/redundant_contigs_map2same_region.png

This brings me another question, why there is so much complexity in these regions? Do you think this is due to polymorphism or due to some difficulty in resolving assembly in this region?

thanks,
Zhenzhen

**Comment by chhylp123** [comment]
Consider there are two broken bubbles. The primary assembly has no broken points, while both haplotype 1 in blue and haplotype 2 in red have a broken point. This is why primary assembly has higher N50.  

![bubble](https://user-images.githubusercontent.com/11708053/102439297-fd08aa00-3feb-11eb-8597-dbc56365b78e.png)


> thanks for the comments. However, I am still puzzled why the primary assembly has higher contiguity than the haplotype-specific assembly, should it be similar at most?
> <img alt="Screen Shot 2020-12-16 at 10 11 13 AM" width="603" src="https://user-images.githubusercontent.com/9053403/102295813-1d524d80-3f87-11eb-8e88-3941d11d5259.png">

**Comment by chhylp123** [comment]
Based on my experiences, HiFi assembly is more likely to to be right while read alignment might be wrong. So I recommend you to make sure if it is the alignment problem or the assembly problem. The region in your example is around centromere, which is very complex. 

> could it be that this region is highly repetitive and these contigs could come from repetitive regions in elsewhere?

**Comment by zhenzhenyang-psu** [comment]
> Consider there are two broken bubbles. The primary assembly has no broken points, while both haplotype 1 in blue and haplotype 2 in red have a broken point. This is why primary assembly has higher N50.
> 
> ![bubble](https://user-images.githubusercontent.com/11708053/102439297-fd08aa00-3feb-11eb-8597-dbc56365b78e.png)
> 
> > thanks for the comments. However, I am still puzzled why the primary assembly has higher contiguity than the haplotype-specific assembly, should it be similar at most?
> > <img alt="Screen Shot 2020-12-16 at 10 11 13 AM" width="603" src="https://user-images.githubusercontent.com/9053403/102295813-1d524d80-3f87-11eb-8e88-3941d11d5259.png">

this is a very interesting bubble! Does the break point in one Haplotype result from divergence among the two haplotypes in this region?

**Comment by zhenzhenyang-psu** [comment]
> Based on my experiences, HiFi assembly is more likely to to be right while contig alignment might be wrong. So I recommend you to make sure if it is the alignment problem or the assembly problem. The region in your example is around centromere, which is very complex.
> 
> > could it be that this region is highly repetitive and these contigs could come from repetitive regions in elsewhere?

I agree, I think it could be a mapping issue!

**Comment by zhenzhenyang-psu** [comment]
hello there,
I was wondering if there is way to extract the phased string graph information that hifiasm generated. 
Basically, i have partitioned two piles of haplotype-specific HiFi reads based on external information for a given chromosome (right now I just want to build a haplotype-specific assembly for this chromosome). However, I am certain that I have missed some some heterozygous regions - the reads I obtained do not represent all the regions of the chromosome. For instance, I have only captured the heterozgyous regions 1, 2, 5, and I missed regions 3, and 4. Moreover, I don't know what the homozygous reads are. 

I remember in the hifiasm paper, it mentioned that it will build a phased string graph by using the overlap between any corrected HiFi reads. Specifically, for me to build an assembly for my interested molecule, i need to extract homozygous reads that overlap with my heterozygous HIFI reads. Is it possible to extract the string graph information from hifiasm output?
<img width="923" alt="Screen Shot 2020-12-17 at 5 16 28 PM" src="https://user-images.githubusercontent.com/9053403/102468601-b1f2a380-408c-11eb-97e1-d0c50fd934ad.png">

thanks very much!
zhenzhen

**Comment by chhylp123** [comment]
For phased assembly, the best solution should be utilizing the option '-3/-4' of hifiasm, which automatically performs such phased assembly. The 'dip.r_utg.gfa' outputted in this mode is the phased string graph.

**Comment by zhenzhenyang-psu** [comment]
great, any software for visualization of such data?

**Comment by chhylp123** [comment]
Bandage might be the most popular one.

**Comment by zhenzhenyang-psu** [comment]
thanks! I compared the haplotype-specific assembly from hifiasm trio-bin vs. standard hifiasm. Attached shows a region with 2 broken contigs in the haplotype specific assembly (upper panel), yet being a contiguous one (lower panel) in the standard assembly.
However, my quesiton is the layout in the haplotype-specific assembly shows that ends of the two contigs are the same, which suggests that the two ends should be merged (around 332kbp). I wonder why they are broken? 

thanks,
<img width="1143" alt="Screen Shot 2020-12-21 at 5 08 26 PM" src="https://user-images.githubusercontent.com/9053403/102759701-710dce00-43af-11eb-85eb-e3f66239732e.png">

**Comment by chhylp123** [comment]
Sorry for the late reply. I guess there are some long reads covering the het sites, so it cannot be linked together.

**Comment by duhuipeng** [comment]
For fully phased assembly, the switch error rate/hamming error rate is important. Trio-binning assembly has much lower switch error rate/hamming error rate than primary assembly
dear author
Are there any complementary relationships between these two indicators?(switch error,hamming error) Why can't use an indicator alone to evaluate the quality of the phase?

Another question is, are they both for SNV, How to define these two indicators?
Phasing Hamming error rate: percentage of SNPs wrongly phased in comparison to true phases. 
Phasing switch error rate: percentage of adjacent SNP pairs wrongly phased.
I understand that the molecules of both indicators should be the same  for wrong SNV, but why are they different?
for example,
![image](https://user-images.githubusercontent.com/58722433/111031585-3dd55b00-8443-11eb-88b9-ffcc5167a78c.png)
All the same molecules are wrong SNV number, why are the two molecules different in size, one is 6, the other is 4?
I feel like I've misunderstood these two concepts,Could you help me understand these two indicators

**Comment by lh3** [comment]
![image](https://user-images.githubusercontent.com/480346/111036189-07b8bc80-83ec-11eb-9270-1590f4ecc3c3.png)

**Comment by duhuipeng** [comment]
thanks ,I got it
