### ISSUE TITLE
crushed k-mer graph

### ISSUE THREAD

**Issue by yurunxian** [chhylp123/hifiasm#590]
Hi, 

I'm working on a ~1.6Gb plant genome with ~ 62Gb HiFi reads (generated by PacBio Revio system) and ~100Gb ONT long reads. Although the assembled genome size is close to our pre-estimation and the N50 is satisfying (> 2Mb), the kmer graph in hifiasm log file is quite weird. The log file is attached.

Any suggestions would be greatly appreciated!

Best,
Runxian

[hifiasm.txt](https://github.com/chhylp123/hifiasm/files/13839906/hifiasm.txt)

**Comment by yurunxian** [comment]
Ah...I found out what happened. The data in my fastq file was somehow self-doubled. For each read, there are always two 100% identity copies, and so does each k-mer. That's why the number of odd-counting kmer is so few.

**Comment by chhylp123** [comment]
Sorry for the late reply. Thanks for the input and good to know it works finally.
