### ISSUE TITLE
Benchmark of long reads mapper using A-lines

### ISSUE THREAD

**Issue by Wenfei-Xian** [chhylp123/hifiasm#591]
In GFA files,  hifiasm outputs the read IDs and their coordinates if they are used in building assemblies (see A-lines at: https://hifiasm.readthedocs.io/en/latest/interpreting-output.html#interpreting-output).

_Originally posted by @chhylp123 in https://github.com/chhylp123/hifiasm/issues/527#issuecomment-1732436001_
            
I am curious can A-lines be used as the ground true in the benchmark of long reads mappers ? 
Should I used the error corrected reads generated by hifiasm ?

**Comment by chhylp123** [comment]
Sorry for the late reply. Yes, it might be better to use A-lines. However, hifiasm itself probably has mistakes in both the error correction step and the following assembly step. It is tricky to utilize the corrected reads or not.

**Comment by Wenfei-Xian** [comment]
thanks !
