### ISSUE TITLE
The REVIO data by hifiasm！

### ISSUE THREAD

**Issue by zhangwenda0518** [chhylp123/hifiasm#594]
Hello, teacher！
    I have a question about the hifi sequencing quality. Since last year, Pacbio has launched the sequencing service of REVIO, which can generate more sequencing data.  So ，I used REVIO to sequence a concerned medicinal plant.
   Today，I checked my off-line sequencing report and found that the value of Q30 is less than 50%. What impact will this have on assembly?  Can I use the default parameters of hifiasm for assembly? Do I need to do something extra with it? 
    Thanks for your reply! 
    Best wishes!

**HiFi Read Quality Summary**
![image](https://github.com/chhylp123/hifiasm/assets/77140740/d5496389-3bad-4744-8eee-ed47abc9cc27)
**Read Quality Distribution**
![image](https://github.com/chhylp123/hifiasm/assets/77140740/83fb3a91-55f4-4132-a734-6ca4fc15d827)

**Comment by chhylp123** [comment]
It should be fine. You could also double check with the k-mer plot. As long as the k-mer plot is fine, hifiasm should work well.
