### ISSUE TITLE
Separate haplotype-recolved untig in GFA

### ISSUE THREAD

**Issue by baozg** [chhylp123/hifiasm#6]
Hi, chhylp123

> For species with high heterozygous rate (i.e., Butterfly), different haplotypes can be fully separated. It is important to remove small bubbles from the haplotype-resolved unitig graph. The reason is that some small bubbles are caused by somatic mutations or noise in data, which are not the real haplotype information. In this case, haplotype-resolved processed unitig graph without small bubbles should be better.

Haplotype-resolved untig fasta(490M) seems exactly twice of my GenomeScope estimated haploid size (260M, 1.8% het), but the result just the untig number, how can I get parental and maternal haplotype? Or  the hifiasm just output the haplotype-resolved untig, but need other information (such as HiC or Trio) to separate two haplotype for diploid.

Zhigui Bao

**Comment by chhylp123** [comment]
Hi Zhigui,

Have you ever looked at the unitig graph (_r_utg.gfa_/_p_utg.gfa_) at Bandage? I guess for species with 1.8% het, most haplotypes have already been fully separated. The graph should like Figure 1 in this blog [https://medium.com/pacbio/hifi-assembler-series-part-1-hifiasm-a-fast-haplotype-resolved-genome-assembler-bd2f30dab571](url). If you just want to get all phased assemblies, _r_utg.gfa_/_p_utg.gfa_ consists of all information. 

However, although most chromosomes have been separated, we don't know which one is parental/maternal. So you still need trio information. We plan to release a new version with trio in the next 1 or 2 weeks, which can tell you the exact parental/maternal information of each unitig.

BTW, right now the _p_ctg.gfa_  consists of one mixed primary assembly. But I guess it might be not useful for you. And to visualize graph by Bandage, I recommend you to utilize _*noseq.gfa_. These gfa files don't have sequences, while still keep the graph structure.
