### ISSUE TITLE
Small-scale misassemblies in human HG002

### ISSUE THREAD

**Issue by amwenger** [chhylp123/hifiasm#60]
@williamrowell, @zeeev, and I have noticed some deletions relative to the GRCh38 in `hifiasm` human assemblies that do not seem supported by reads.

A few examples from [your primary assembly](ftp://ftp.dfci.harvard.edu/pub/hli/hifiasm/submission/hifiasm-0.12/human-HG002.pri.fa.gz).

h1. 53 bp deletion at chr10:15,055,521-15,055,574 in ptg000004l
![image](https://user-images.githubusercontent.com/7155109/102180781-4c20d480-3e5e-11eb-8bd6-c836601aaf43.png)

h1. 55 bp deletion at chr10:97,137,410-93,137,465 in ptg000004l
Compensatory 55 bp insertion nearby
![image](https://user-images.githubusercontent.com/7155109/102181022-b20d5c00-3e5e-11eb-8b61-78ad618427eb.png)

h1. 74 bp deletion at chr11:86,725,080-86,725,154 in ptg000008l
![image](https://user-images.githubusercontent.com/7155109/102181275-1e885b00-3e5f-11eb-8d67-6ddf88f520e6.png)

h1. 93 bp deletion at chr2:150,537,682-150,537,775 in ptg000031l
Compensatory 93 bp insertion nearby
![image](https://user-images.githubusercontent.com/7155109/102182398-0ca7b780-3e61-11eb-9385-378ce644cdd4.png)

**Comment by chhylp123** [comment]
Which version are you using? This is the issue of consensus errors (see https://github.com/chhylp123/hifiasm/issues/42). I hope v0.13 can fix most of them.

**Comment by williamrowell** [comment]
On the internal assemblies for which @zeeev first noticed these gaps, we're using v0.9 (installed from bioconda).  For the examples above, @amwenger used the HG002 assembly from your publication.  We can try a couple assemblies using v0.13 to see if our internal examples have corrected gaps.

**Comment by chhylp123** [comment]
0.13 should be definitely better and it also can output low quality regions in BED format. For example, the QV of CHM13 is:
>v0.12: 54.159
>v0.13: 54.726
