### ISSUE TITLE
Why more contigs always present in haplotype 1 than haplotype 2?

### ISSUE THREAD

**Issue by Chenglin20170390** [chhylp123/hifiasm#623]
Hi, I found that the contig number of haplotype 1 from hifiasm are always large contig number of haplotype 2.
<img width="269" alt="image" src="https://github.com/chhylp123/hifiasm/assets/33062118/8cc95a8c-9cdf-4c66-aa7f-aa736f0c0d56">

What causes this? Is there any explanation in the article （https://www.nature.com/articles/s41587-022-01261-x）?

**Comment by chhylp123** [comment]
Sorry for the late reply. I feel like in most cases, hifiasm may put unphased contigs to hap1, making hap1 has more small contigs.

**Comment by Chenglin20170390** [comment]
Thanks  for your explanations!
