### ISSUE TITLE
Add Options for Pore-C Data

### ISSUE THREAD

**Issue by GLking123** [chhylp123/hifiasm#626]
Dear author,
Could it be possible to add an option specifically for Pore-C data? This could potentially allow for more accurate haplotyping of chromosomes.

**Comment by chhylp123** [comment]
Sorry for the late reply. Will support it as soon as possible.

**Comment by sh0rt2l0ng** [comment]
Hi @chhylp123 May I ask here whether Pore-C option is still considered here? This will be a key enablement for ONT-only solution.
