### ISSUE TITLE
About Running asmgene

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#64]
in your section about Running asmgene,this code blow :
minimap2 -cxsplice:hq -t <nThreads> <contigs.fa> <cDNAs.fa> > <aln.paf>
what the type of cDNAS.fa ? which is Iso-seq data or RNA-seq ?

**Comment by lh3** [comment]
Annotated genes. Iso-seq could work but less ideal.

**Comment by zhoudreames** [comment]
> Annotated genes. Iso-seq could work but less ideal.

in your article,you use ensemble V99 for human and mouse.if the v99 means all animals cDNA or other？I study pig，What cDNA data should I download ?

**Comment by zhoudreames** [comment]
@chhylp123 @lh3

**Comment by lh3** [comment]
To evaluate mouse, you only use mouse genes. You need to look for pig gene annotations.

**Comment by zhoudreames** [comment]
> To evaluate mouse, you only use mouse genes. You need to look for pig gene annotations.
thank you so mush! I got the result by using your method.  my code is "k8-0.2.4/k8-Linux paftools.js asmgene -i.99 Sscrofa11.1.cdna.paf BMX.cdna.paf"
the  Sscrofa11.1.cdna represents reference genome ;the other BMX.cdna represents Assembly . how to caculate  the Gene completeness ?
H	Metric	Sscrofa11.1.cdna	BMX.cdna
X	full_sgl	17765	                16345
X	full_dup	0	                        186
X	frag	0	31
X	part50+	0	                        214
X	part10+	0	                        16
X	part10-	0	                        973

in addtion,I got the results in blow when I evaluated the gene duplication rate,how to caculate the gene duplication rate?
H	Metric	Sscrofa11.1.cdna	BMX.cdna
X	full_sgl	18036	                13580
X	full_dup	0	                         73
X	frag	        0	                        11
X	part50+	0	                        121
X	part10+	0	                        16
X	part10-	0	                       4235

**Comment by zhoudreames** [comment]
thank you so mush! I got the result by using your method. my code is "k8-0.2.4/k8-Linux paftools.js asmgene -i.99 Sscrofa11.1.cdna.paf BMX.cdna.paf"
the Sscrofa11.1.cdna represents reference genome ;the other BMX.cdna represents Assembly . how to caculate the Gene completeness ?
H Metric Sscrofa11.1.cdna BMX.cdna
X full_sgl 17765 16345
X full_dup 0 186
X frag 0 31
X part50+ 0 214
X part10+ 0 16
X part10- 0 973

in addtion,I got the results in blow when I evaluated the gene duplication rate,how to caculate the gene duplication rate?
H Metric Sscrofa11.1.cdna BMX.cdna
X full_sgl 18036 13580
X full_dup 0 73
X frag 0 11
X part50+ 0 121
X part10+ 0 16
X part10- 0 4235

**Comment by zhoudreames** [comment]
@lh3

**Comment by zhoudreames** [comment]
@lh3 @chhylp123 hello could you help me solve this problem？thank you so much

**Comment by chhylp123** [comment]
@zhoudreames Here is an example of CHM13 assembly and T2T v1.0 reference:
> paftools.js asmgene t2t.paf hifiasm.paf
>H       Metric        t2t          hifiasm
>X       full_sgl        36,458   36,424        
>X       full_dup      0            16
>X       frag            0             4
>X       part50+      0             5
>X       part10+      0             0
>X       part10-       0             9
>X       dup_cnt      1,343      1,339
>X       dup_sum    4,120      4,091

For Gene completeness,
>Complete and single-copy: (full_sgl of hifiasm)/(full_sgl of t2t) = 36,424/36,458 = 99.91%
>Complete and duplicated: (full_dup of hifiasm)/(full_sgl of t2t) = 16/36,458 = 0.04%
>Multiple-copy gene retained: (dup_cnt of hifiasm)/(dup_cnt of t2t) = 1,339/1,343 = 99.70%

Please note that if the quality of reference and cDna is not such good, the asmgene results might be not useful.
