### ISSUE TITLE
Basic Question About HiFi Input

### ISSUE THREAD

**Issue by foreignsand** [chhylp123/hifiasm#646]
I've scanned the Docs and the Issues and can't see anything about which reads are used from PacBio HiFi sequencing output. Should the total ccs reads located in the 'reads' directory be used? Or the quality filtered reads? I have Q20, Q30, Q40, and Q50 ccs reads I could use.

Another question I have is, if the total ccs reads are used, can the quality filtered reads serve any purpose? Is it possible to do multiple passes with hifiasm initially using the total reads and then using Q30 reads for polishing?

Many thanks!

Cheers,
Emily

**Comment by chhylp123** [comment]
Hi @foreignsand, sorry for the late reply. In general, if the HiFi reads were produced recently, hifiasm should work without any filtering. You can have a try to polish hifiasm assemblies. However, I am not 100% sure if there is any tool that could work very accurately for the haplotype-resolved assemblies.

**Comment by foreignsand** [comment]
no worries about the delay! thanks for responding!

the results are from a couple of months ago so the total ccs reads should work. great!

i'm not entirely sure what you mean about a tool working for haplotype-resolved assemblies, but perhaps that will become clearer as i work my way through the pipeline.

thanks again!

cheers,
emily

**Comment by foreignsand** [comment]
okay i see what haplotype-resolved assemblies are. i'm providing paired hi-c illumina reads along with the pacbio reads, so hifiasm can resolve parental haplotypes. so in the output, i have the following files:

the assembly with the extension `hic.p_ctg.gfa`
one parental haplotype-resolved assembly with the extension `hic.hap1.p_ctg.gfa`
an additional parental haplotype-resolved assembly with the extension `hic.hap2.p_ctg.gfa`

so you're saying polishing may work with the `hic.p_ctg.gfa` assembly, but not with either of the haplotype-resolved assemblies?

many thanks!

cheers,
emily
