### ISSUE TITLE
GFA contains overlaps that are longer than the node involved in Link 

### ISSUE THREAD

**Issue by rlorigro** [chhylp123/hifiasm#65]
Hi, I am trying to use some HiFiasm diploid GFAs from this public location:
https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=submissions/fc721e22-1ce2-4d38-bf88-72cf231bcb90--UCSC_2020AUG_assembly/2020AUG26_upload/

And I am finding that there are overlaps that are longer than the sequence they involve. Here are some examples (showing the noseq lines for brevity).

In HG002 there are 2 cases like this:
```
S	utg043315l	*	LN:i:18373	rd:i:0
L	utg019238l	+	utg043315l	-	18380M	L1:i:21350
...
S	utg030401l	*	LN:i:20033	rd:i:5
L	utg030867l	-	utg030401l	-	20035M	L1:i:22251
```

In HG005 there is just one:
```
S	utg046740l	*	LN:i:16949	rd:i:0
L	utg011008l	+	utg046740l	-	16956M	L1:i:343949
```

These are making it difficult to parse the GFA and remove overlaps in preparation for further processing of the GFA.

Also, as a side issue, would it be possible to just omit the overlaps and trim the sequences, since they appear to be 100% Match operations? The fact that they are so long make it difficult to use conventional methods for "bluntifying" the GFA (e.g. aligning the overlaps).

**Comment by chhylp123** [comment]
The assemblies of HPRC were generated by hifiasm v0.11, which has a minor bug for overlap length in GFA. Hifiasm v0.13 has already fixed it.  I guess for long unitigs, trim overlaps doesn't matter too much.

**Comment by rlorigro** [comment]
The issue still exists in v0.13. I spent some time verifying this and discussing with others, but I want to bring the result of that discussion back here for the sake of continuity.
