### ISSUE TITLE
When to upgrade？

### ISSUE THREAD

**Issue by fantasticair** [chhylp123/hifiasm#67]
Hello,
      Thanks for writing the excellent assembly software. Recently, I have used your software to assembly my genome, but I find the `hifisam`  lead into the wrong assembly, the error is very similar as #50, #21 and #54, some both ends of the chromosome get mistake assembly tandem repeat，the size is about several Mb or dozens of Mb.

Best wishes ~

**Comment by lh3** [comment]
#50 and #21 are similar problems. #54 is quite different and is worse. What is exactly happening?

**Comment by fantasticair** [comment]
Thank you for your quick reply!
       My question is the same as [https://github.com/chhylp123/hifiasm/issues/50](url) , there are some tandem repeat in my assembly genome used the `hifisam` software, the tandem repeat is distributed at the end of the chromosome, the size is about several Mb or dozens of Mb in some chromosome, and the genome size is  300M more than the reference genome(about 2.8G).

Best wishes~

**Comment by lh3** [comment]
Do you have a coverage plot?

> the tandem repeat is distributed at the end of the chromosome

Telomeres are often repeat rich.

> the genome size is 300M more than the reference genome(about 2.8G).

This is not necessarily a problem, either.

**Comment by chhylp123** [comment]
It would be good to have a look with coverage plot. #54 is the problem of hifasm, but #50 and #21 might be not. We plan to make new release this weekend or next week, which includes many new features.

**Comment by fantasticair** [comment]
Thanks for your advice! The size of these sequences (300M) is shorter than 1Mb,  I have used the `Ragoo` to anchor the contig to the scaffold, these sequences were anchored at the end of the chromosome. In fact, these Sequences have aligned to the reference's some position, these sequences should belong to the tandem repeat in my assembly genome, could you give me some advice to remove it in the assembly process by `hifiasm`?

Best withes ~

**Comment by chhylp123** [comment]
Just make sure, do you mean these repeat-rich sequences should be at the ends of chromosome, but they are in the middle of hifiasm assembly like misassemblies? And what's the coverage of these regions?

**Comment by fantasticair** [comment]
I'm not sure that the repeat-rich sequence at the end of the chromosome in my assembly genome, but in my assembly genome (used the `hifiasm`) have the characteristic that these sequences always align to the reference same position as follows:
![align](https://user-images.githubusercontent.com/35028002/106252217-fb6c0c00-6250-11eb-89f3-0988fefc6591.png)


In addition, I stat the coverage,

- For wide genome
``` 
mean coverageData = 20.9054X 
std coverageData = 7.9102X
```
- For the coverage of these sequences always align to the reference same position 
```
mean coverageData =14.84X 
std coverageData = 8.529X
```
 For the coverage, it seems like normal, I doubt that the `hifiasm` does not remove from the assembly error.

Best wishes ~

**Comment by lh3** [comment]
I wouldn't trust reference-based analysis. The reference may have lower quality or is diverged from your sample. To assert assembly errors, you have to use Hi-C or read coverage as those have done in previous issues.

**Comment by chhylp123** [comment]
@fantasticair The new version of hifiasm (v0.14) has three new options: `--b-cov`, `--h-cov` and `--m-rate`, which might be helpful to reduce some potential misassemblies.

**Comment by fantasticair** [comment]
Thank you for your update.
