### ISSUE TITLE
Core dump related to usage -5 parameter

### ISSUE THREAD

**Issue by rfinkers** [chhylp123/hifiasm#684]
I'm running into a core dump, while using the -5 parameter

> Writing raw unitig GFA to disk...
> Writing processed unitig GFA to disk...
> [M::ha_polybin_list::109204.209*1.02] created the hash table for read names
> /var/lib/slurm-llnl/slurmd/job71768/slurm_script: line 65: 2222208 Segmentation fault      (core dumped) hifiasm

Could you comment on how to best start debugging this issue?

**Comment by rfinkers** [comment]
Am I correct that this has to do with the naming convention of the groups? They cannot be random, but need to follow the LG1_1, LG2_1 naming convention? Feedback on what expected here would be nice. Tnx!

**Comment by baozg** [comment]
LG is not neccessary, but the haplotype group should be consistence with `_1`,`_2`,`_3` and `_4`

**Comment by rfinkers** [comment]
Tnx @baozg. Suggestion is to add this to your C88 related GitHub doc? Two related questions, assume there is no limit, as we would require ```_5``` and ```_6``` as well. Furthermore, is using segregating markers sufficient (mostly one homologous chromosome specific in our case), or is there added value also to indicate the reads from which we know from the marker data that they are completely homozygous?

**Comment by baozg** [comment]
Thanks, I added this to my documentation. In theory, more than 4 haplotypes should work, but we never tried higher ploidy level. It's hard to tell, only using haplotype-speficic marker doesn't work in C88. This should be case by case.

**Comment by rfinkers** [comment]
@baozg follow-up question. So the name before the ```_``` is not relevant, it only processes to integer after the ```_``` for assignment of the groups. So in theory I could use ```group_1``` for all haplotype 1 markers for all chromosomes instead of ```LG1_1 LG2_1 etc.```.

**Comment by baozg** [comment]
yes, I think hifiasm didn't use linkage group information. This is just one intermediate file for our potato genome.

**Comment by rfinkers** [comment]
So, this stays a tricky option to use, and does not always perform as expected. It might require some fine-tuning, and probably could utilise in general the info about the know variant (at kmer level rather than documenting at read level?) better, especially in more complex species. Still interested to see this progressing.
