### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Mrbland** [chhylp123/hifiasm#69]
Hello,

Thank you for making great new tools for hifi reads. I am running hifiasm on an r5a.12xlarge AWS instance (48cpu, 384GB RAM), trying to assemble ~450Mb genome. My hifi fasta is ~24GB, 3.2 million reads with average read length ~10Kb. Hifiasm keeps crashing after the 3 read correction steps during `Writing reads to disk` with `Segmentation fault`. 

Do I need to use an instance with more RAM or is there something else happening? 

Thanks!

**Comment by chhylp123** [comment]
Could you please share the log file? 384GB RAM should be enough for such small genome.

**Comment by Mrbland** [comment]
I had been using `-l0` and `-l1` which caused the failure. I repeated with default purging and the assembly was successful (and looks quite good). I can try and replicate the light/no purging and share the logs in case it helps with future releases/issues.

**Comment by chhylp123** [comment]
Thanks a lot. It would be very helpful to get the log file.

**Comment by chhylp123** [comment]
@Mrbland The new version of hifiasm (v0.14) fixed a small bugs of purge_dups. Hope it can fix the your problems when using `-l0` and `-l1`.

**Comment by Mrbland** [comment]
Great, I am trying it out right now and will let you know how it runs. Sorry, I haven't revisited this issue since I first posted.

**Comment by Mrbland** [comment]
@chhylp123 v0.14 works! I only tried `-l0` and there was no seg fault. Thanks!

**Comment by chhylp123** [comment]
Great! Thanks for having a try.

**Comment by wannder-mine** [comment]
Hi@chhylp123,
Thank you for making great new tools for hifi reads.but I'm currently experiencing something similar to the above, I'm on a 53~22.04.1-Ubuntu system (256cpu,1.0TB RAM) and trying to assemble the genome. My hifi fastq.gz is ~145GB.Hifiasm keeps crashing after the 5 read correction steps during Writing reads to disk with Segmentation fault.Here is my log file
[hifiasm.log.txt](https://github.com/user-attachments/files/19830950/hifiasm.log.txt)
