### ISSUE TITLE
run pstools problem

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#71]
when I run the pstools haplotype_scaffold -t64 scaff_connections.txt pred_haplotypes.fa ./ , Igot the erro blow,could you help me  ? thanks!
*** Error in `/home/Mpzhang/Mzhou/Biosoft/pstools': free(): invalid pointer: 0x00007fffd2670198 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81489)[0x2b1b805b5489]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x4ce02a]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x4c5238]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x4adf57]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x4878a2]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x4abe7c]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x48544d]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x46cd97]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x44262d]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x44db61]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x450a5d]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b1b805563d5]
/home/Mpzhang/Mzhou/Biosoft/pstools[0x405286]
======= Memory map: ========
00400000-00595000 r-xp 00000000 4f9:2c566 144115844081791740             /home/Mpzhang/Mzhou/Biosoft/pstools
00794000-00795000 r--p 00194000 4f9:2c566 144115844081791740             /home/Mpzhang/Mzhou/Biosoft/pstools
00795000-00797000 rw-p 00195000 4f9:2c566 144115844081791740             /home/Mpzhang/Mzhou/Biosoft/pstools
00797000-00798000 rw-p 00000000 00:00 0
01c87000-b5300000 rw-p 00000000 00:00 0                                  [heap]
2b1b7f62d000-2b1b7f64f000 r-xp 00000000 08:03 3939712                    /usr/lib64/ld-2.17.so
2b1b7f64f000-2b1b7f652000 rw-p 00000000 00:00 0
2b1b7f689000-2b1b7f68f000 rw-p 00000000 00:00 0
2b1b7f84e000-2b1b7f84f000 r--p 00021000 08:03 3939712                    /usr/lib64/ld-2.17.so
2b1b7f84f000-2b1b7f850000 rw-p 00022000 08:03 3939712                    /usr/lib64/ld-2.17.so
2b1b7f850000-2b1b7f851000 rw-p 00000000 00:00 0
2b1b7f851000-2b1b7f866000 r-xp 00000000 08:03 3939778                    /usr/lib64/libz.so.1.2.7
2b1b7f866000-2b1b7fa65000 ---p 00015000 08:03 3939778                    /usr/lib64/libz.so.1.2.7
2b1b7fa65000-2b1b7fa66000 r--p 00014000 08:03 3939778                    /usr/lib64/libz.so.1.2.7
2b1b7fa66000-2b1b7fa67000 rw-p 00015000 08:03 3939778                    /usr/lib64/libz.so.1.2.7
2b1b7fa67000-2b1b7fa7e000 r-xp 00000000 08:03 3939745                    /usr/lib64/libpthread-2.17.so
2b1b7fa7e000-2b1b7fc7d000 ---p 00017000 08:03 3939745                    /usr/lib64/libpthread-2.17.so
2b1b7fc7d000-2b1b7fc7e000 r--p 00016000 08:03 3939745                    /usr/lib64/libpthread-2.17.so
2b1b7fc7e000-2b1b7fc7f000 rw-p 00017000 08:03 3939745                    /usr/lib64/libpthread-2.17.so
2b1b7fc7f000-2b1b7fc83000 rw-p 00000000 00:00 0
2b1b7fc83000-2b1b7fe0b000 r-xp 00000000 4f9:2c566 144115408645927908     /home/aihsh/2.bin/gcc-8.3.0/lib64/libstdc++.so.6
2b1b7fe0b000-2b1b8000a000 ---p 00188000 4f9:2c566 144115408645927908     /home/aihsh/2.bin/gcc-8.3.0/lib64/libstdc++.so.6
2b1b8000a000-2b1b80015000 r--p 00187000 4f9:2c566 144115408645927908     /home/aihsh/2.bin/gcc-8.3.0/lib64/libstdc++.so.6
2b1b80015000-2b1b80017000 rw-p 00192000 4f9:2c566 144115408645927908     /home/aihsh/2.bin/gcc-8.3.0/lib64/libstdc++.so.6
2b1b80017000-2b1b8001b000 rw-p 00000000 00:00 0
2b1b8001b000-2b1b8011c000 r-xp 00000000 08:03 3939727                    /usr/lib64/libm-2.17.so
2b1b8011c000-2b1b8031b000 ---p 00101000 08:03 3939727                    /usr/lib64/libm-2.17.so
2b1b8031b000-2b1b8031c000 r--p 00100000 08:03 3939727                    /usr/lib64/libm-2.17.so
2b1b8031c000-2b1b8031d000 rw-p 00101000 08:03 3939727                    /usr/lib64/libm-2.17.so
2b1b8031d000-2b1b80334000 r-xp 00000000 4f9:2c566 144115408645927920     /home/aihsh/2.bin/gcc-8.3.0/lib64/libgcc_s.so.1
2b1b80334000-2b1b80533000 ---p 00017000 4f9:2c566 144115408645927920     /home/aihsh/2.bin/gcc-8.3.0/lib64/libgcc_s.so.1
2b1b80533000-2b1b80534000 rw-p 00016000 4f9:2c566 144115408645927920     /home/aihsh/2.bin/gcc-8.3.0/lib64/libgcc_s.so.1
2b1b80534000-2b1b806f6000 r-xp 00000000 08:03 3939719                    /usr/lib64/libc-2.17.so
2b1b806f6000-2b1b808f6000 ---p 001c2000 08:03 3939719                    /usr/lib64/libc-2.17.so
2b1b808f6000-2b1b808fa000 r--p 001c2000 08:03 3939719                    /usr/lib64/libc-2.17.so

**Comment by lh3** [comment]
Please create an issue at pstools.

**Comment by zhoudreames** [comment]
> Please create an issue at pstools.

do you know pstools github website or any information? i dont search those .thanks~

**Comment by chhylp123** [comment]
It's here: https://github.com/shilpagarg/pstools
