### ISSUE TITLE
Understanding the complex topologies of unitigs

### ISSUE THREAD

**Issue by OceanLyu** [chhylp123/hifiasm#717]
Hi, 
Thanks for developing hifiasm!

I`m working on a diploid genome using only ccs reads by default hifiasm parameters. I got an assembly with contig N50 ~15 M and the longest primary unitigs is like this:

![image](https://github.com/user-attachments/assets/2cefb7f3-1c4e-47a6-8dea-8eef4e288d08)
![image](https://github.com/user-attachments/assets/55abfdd5-c19c-4e60-9130-00d71c04a88f)

As you can see there are bizarre structures like tips and 'multi-layer bubbles' in those bubbles, **which I suspect arisied from repeated sequences because the genome is diploid**. I do not know if I am correct.

Meanwhile, there is a significant number of short contigs in the primary assembly (shown by contig quast plot below). 
![image](https://github.com/user-attachments/assets/ec56e683-937a-4a3e-bb0a-3e6a69f179b0)

And as you mentioned in the paper, during bubble poping and generation of the primary assembly, tips not coming from the different haplotypes would be preserved.  I used repeatmodeler and repeatmasker to predict repeat sequences in the primary assembly and observed dispeared repeat sequences covering the entire short contigs. 

Thus I wonder **if those short contigs from cut tips that come from repeated sequences can be removed (e.g. filtered by length) when doing scaffolding for instance**.

The final question is **whether the contig N50 is long enough?**  with estimated ~2.6 G genome length. 

The ploidy was predicted by Smudgeplot (shown below) and preliminary karyotype experiments.
![image](https://github.com/user-attachments/assets/867ce1d8-ca85-416b-9192-5956df70bc7e)

And the ccs reads kmer distribution by Genomescope2 is shown below.
![image](https://github.com/user-attachments/assets/7dfc2235-76fa-4f6b-b74d-a194494e9b67)

Thanks in advance for your help!

**Comment by chhylp123** [comment]
It is hard to say. Some genomes are easy to assemble, while some others are not. In addition, the read coverage will also affect the final assembly. All of these will affect the N50.

These small tips might be repeats, or local polypoid regions. If they are too short, probably nothing hifiasm can do currently.

**Comment by OceanLyu** [comment]
Thanks very much to your reply!
