### ISSUE TITLE
Parameters for amplicon assembly

### ISSUE THREAD

**Issue by RNieuwenhuis** [chhylp123/hifiasm#72]
Hi,

I tried assembling some amplicons from HiFi reads, but so far without success. 

My initial try with ~1000x coverage failed and I guessed the coverage might have been problematic, because the peaks detected in the k-mer histogram seemed off. Subsampling to ~60x and setting `k 21` and `w 21` seemed to help and the whole read correction seems to work. But the .gfa files are all empty. 
I am aware hifiasm was not designed for amplicon assembly, but would love to hear your suggestions for settings to succeed.

```
hifiasm --version
0.13-r307
```

`hifiasm -i -k 21 -w 21 -t 8 -l 0 -o Test_amplicon Test.fastq`

Log: 
[Test_amplicon.log](https://github.com/chhylp123/hifiasm/files/5937719/Test_amplicon.log)

**Comment by jelber2** [comment]
Maybe this might help?
https://github.com/PacificBiosciences/pbAA

**Comment by RNieuwenhuis** [comment]
Thanks for the suggestion @jelber2 . It does seem to rely on a good quality reference though. In my use case I would really like to see an assembly to establish the wildtype reference.

**Comment by lh3** [comment]
Amplicon assembly is distinct from WGS assembly and violates many assumptions hifiasm makes about the data. I don't see hifiasm will support amplicon assembly.
