### ISSUE TITLE
`prefix`.bp.p_ctg.gfa vs `prefix`.p_ctg.gfa

### ISSUE THREAD

**Issue by hasindu2008** [chhylp123/hifiasm#736]
Hello Hifiasm authors,

I am slightly confused regarding the primary assembly. I tried to go through the documentation and some past GitHub issues, but could not find the exact answer.

The [Hifiasm output documentation](https://hifiasm.readthedocs.io/en/latest/interpreting-output.html#interpreting-output) states the following.

Hifiasm generates the following assembly graphs only with HiFi reads in default:
- `prefix`.bp.p_ctg.gfa: assembly graph of primary contigs.
- `prefix`.bp.hap1.p_ctg.gfa: partially phased contig graph of haplotype1.
- `prefix`.bp.hap2.p_ctg.gfa: partially phased contig graph of haplotype2.

If the option --primary or -l0 is specified, hifiasm outputs:
- `prefix`.p_ctg.gfa: assembly graph of primary contigs.
- `prefix`.a_ctg.gfa: assembly graph of alternate contigs.

My question is, if we are doing hifi only assembly, what is the difference between the `prefix`.bp.p_ctg.gfa created by default vs the `prefix`.p_ctg.gfa created when `--primary` option is provided?

**Comment by chhylp123** [comment]
There is no difference. They are exactly the same.

**Comment by hasindu2008** [comment]
Thanks :)
