### ISSUE TITLE
using CCS reads <QV20 and single-pass reads

### ISSUE THREAD

**Issue by dcopetti** [chhylp123/hifiasm#77]
Hello,
I just got some CCS data from the sequencing center, and when plotting read length and mean QV I see that I have a considerable fraction of reads with QV between 15 and 20:
<img width="443" alt="CCS_reads" src="https://user-images.githubusercontent.com/13842014/108384231-da248d00-720a-11eb-9bc4-10c5601493a8.PNG">
I wonder if I can use some of that data in a hifiasm assembly, and until which QV value it still makes sense to include reads in the input data. That would increase coverage and fraction of longer reads, likely improving the contiguity - I expect.

Always from the same data, I see that there is a fraction of reads at QV~12 that are also very long (the flat line). To me these could be single-pass reads, or templates where the adapters where not recognized. I am thinking to extract them (maybe the ones larger than 30 kb and with QV <15) and align them to the assembly (made with >Q20 reads). If they do align as a single pass (not chimeras or multiple passes), they could be good candidates for being error corrected (with the QV>20), and maybe fed into the assembly.
Do you think this could be a strategy to try to improve the assembly? Would this type of data (input reads of 100s of kb, QV 18-20) work with hifiasm?
Thanks,
Dario

**Comment by chhylp123** [comment]
I don't have experience about how to use reads with low QV. How about directly fed these reads to hifiasm? If it doesn't work, I agree align and correct should be a reasonable solution.
