### ISSUE TITLE
heterozygous reads from Hifiasm assembly graph

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [chhylp123/hifiasm#79]
Hi Haoyu,
I was wondering if there is a way to extract the heterozygous reads from the assembly graph of hifiasm. 
thanks,
zhenzhen

**Comment by chhylp123** [comment]
Hifiasm doesn't not clearly keep this information, the only way is to estimate from r_utg.gfa.

**Comment by zhenzhenyang-psu** [comment]
Hi Haoyu,
thanks for your reply! Could you elaborate on how to identify reads from each side of the bubble in the string graph?
<img width="586" alt="Screen Shot 2021-03-09 at 5 50 39 PM" src="https://user-images.githubusercontent.com/9053403/110452767-7225e000-8100-11eb-926e-e0d67f144a8b.png">
Fromt the attached figure (fig. S1) of your nature methods paper, there is way to determine whether the bubbles represent alleles or perhaps paralogs by assessing whether T comes from the different haplotype from G. I wonder how Hifiasm determines this? 
thanks,
zhenzhen

**Comment by chhylp123** [comment]
For each read, hifiasm knows which reads are potential homologous. But this result is not reliable.
