### ISSUE TITLE
The C in the BUSCO result is only 59%

### ISSUE THREAD

**Issue by Ahahaha3** [chhylp123/hifiasm#80]
hi, @lh3 , i've assembled a genome by hifiasm. The genome size about 6G and N50=6.1M, but the result of BUSCO, it's C=59%. I can't understand why.
Looking forward to your reply.

**Comment by lh3** [comment]
BUSCO coverage is poor for some species (e.g. California redwood).

**Comment by chhylp123** [comment]
What's the estimated genome size and het rate of your sample? Have you applied '-l2' when assembling?

**Comment by Ahahaha3** [comment]
No, i only run 'hifiasm -o sample.asm -t90 ./sample.fastq' and i'm trying add '-l2'.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chhylp123/hifiasm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 上午7:09
收件人:&nbsp;"chhylp123/hifiasm"<hifiasm@noreply.github.com&gt;;
抄送:&nbsp;"韩明政"<872718491@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chhylp123/hifiasm] The C in the BUSCO result is only 59% (#80)





 
What's the estimated genome size and het rate of your sample? Have you applied '-l2' when assembling?

**Comment by chhylp123** [comment]
Please ignore my reply =.=. I took 'C' as 'D' for mistake.

**Comment by Ahahaha3** [comment]
my busco:&nbsp;C:59.8%[S:12.0%,D:47.8%],F:0.2%,M:40.0%,n:1614.
Do I need to rerun hifiasm -l2 in this case?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chhylp123/hifiasm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 晚上9:24
收件人:&nbsp;"chhylp123/hifiasm"<hifiasm@noreply.github.com&gt;;
抄送:&nbsp;"韩明政"<872718491@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chhylp123/hifiasm] The C in the BUSCO result is only 59% (#80)





 
Please ignore my reply =.=. I took 'C' as 'D' for mistake.

**Comment by chhylp123** [comment]
Hifiasm enables -l2 in default, so no need to do that.

**Comment by Ahahaha3** [comment]
Thanks for your reply.



发自我的iPhone


------------------ Original ------------------
