### ISSUE TITLE
purge in hifiasm

### ISSUE THREAD

**Issue by elissaralam** [chhylp123/hifiasm#84]
Hello, 

I am assembling a heterozygous genome (_Fragaria_ x _ananassa_) using hifiasm with trio binning. In the usage section of the hifiasm documentation you state that "In the binning mode, hifiasm does not purge haplotig duplications by default." 

Does that mean that when i run the code: hifiasm -o NA12878.asm -t 32 -1 pat.yak -2 mat.yak NA12878.fq.gz , with modifications, that purging is not applied? If that is the case, what should i do/ add to the code to apply the purging step to the primary and alt assemblies?

I might have misunderstood the statement so i would really appreciate your help.
Thanks a lot,
Elissar

**Comment by lh3** [comment]
The trio mode doesn't need dup purging.
