### ISSUE TITLE
why havent alternative contig in heterozygous genome region?

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#86]
I find those  heterozygous region no have alternative contig,and the same region is so mush in my genome, that's why ? the result show you in blow :

**Comment by zhoudreames** [comment]
![Uploading image.png…]()

**Comment by zhoudreames** [comment]
![image](https://user-images.githubusercontent.com/54714639/111243534-33ca7c80-863c-11eb-8449-45ee80f64830.png)

**Comment by zhoudreames** [comment]
@molecules @lh3 @chhylp123 could you help me? thanks!

**Comment by zhoudreames** [comment]
my Genome Assembly Result:primary contig total size is 2.6Gb;alternative contig is 1.5Gb

**Comment by chhylp123** [comment]
What's the coverage of this region? Does it have right coverage for heterozygous regions? From the IGV it is hard to to say those indels are heterozygous variants or homopolymer errors.
