### ISSUE TITLE
HiC mode  result files can gain the hap1/hap2 reads 

### ISSUE THREAD

**Issue by zhoudreames** [chhylp123/hifiasm#89]
i want to gain the hap1 and hap2 own reads ，if the hic mode save split reads information？

**Comment by zhoudreames** [comment]
@lh3 @chhylp123 @molecules

**Comment by chhylp123** [comment]
You can check tag 'HG:A:' in r_utg.gfa which indicates the haplotype information of each read.

**Comment by zhoudreames** [comment]
> You can check tag 'HG:A:' in r_utg.gfa which indicates the haplotype information of each read.

thanks for your reply!   in this r_utg.gfa file ,only contain a part of the whole hifi data,can I gain whole haplotyp-resolved hifi reads  ?

**Comment by chhylp123** [comment]
It is hard, some of reads have already been filtered out as contained reads.
