### ISSUE TITLE
Targeted sequencing data assembly

### ISSUE THREAD

**Issue by skyungyong** [chhylp123/hifiasm#90]
Hi!

I have some unique datasets I generated a few years ago with a targeted-sequencing approach. From the organism's genome (~1G; diploid), I only sequenced certain genomic regions that encode a gene family of interest (~4Mb) with PacBio RS ll. The CCS data is not contiguous (2 - 5kb in size) and has uneven coverages (different capture efficiency over different regions). The gene family has undergone many duplication events (~300 genes and some of them are recent) and is typically found around active transposons, which all complicate the assembly.

A several years ago, I used Canu v1.5 - v1.6 to assemble these, which worked quite well for homozygous species. But there are heterozygous species Canu, Falcon and any other tools could not handle. For these species, the contigs were highly fragmented and duplicated. With Hifiasm v0.14 and the l3 option, I found purging is working at some extent with some variability. For instance, from 990 contigs (Canu v1.5) to 598 contigs (Hifiasm), and 820 contigs to 604 contigs. In some cases, purging is less aggressive (e.g. from 982 -> 975; 972 -> 764). Most of the homozygous species ended up with < 400 contigs, so this would be the most ideal output. I wonder whether you could provide suggestions on which parameters I may tune to try improving the outputs.

Thank you!

**Comment by chhylp123** [comment]
The assumption of purging is that the dataset should have even coverages. If you want to get more contiguous assembly, probably you can increase "--purge-cov", which would make contigs with high coverages more contiguous. However, increasing "--purge-cov" may introduce misassemblies. In addition, "-s" also affects contiguity, while it may also introduce misassemblies.
