### ISSUE TITLE
What is an A line in gfa?

### ISSUE THREAD

**Issue by sebschmi** [chhylp123/hifiasm#91]
Hi, thank you very much for creating hifiasm.

I am trying to read its output graph, and I stumbled upon lines starting with `A`. These are neither documented in GFA version 1, not GFA version 2 (at least following the link in the README).

Here is an example from a r_utg.gfa file:
```
A       utg000002l      55180   -       495     0       9921    id:i:495        HG:A:a
```

I assume that this represents an alignment of a read to the unitig `utg000002l`, where the alignment starts at `55180` on the unitig. The read is aligned backwards (`-`). Then I have no idea what `495` and `0` means. `9921` is the length of the read and `id:i:495` is the id of the read. `HG:A:a` seems to always be there.

Can you help me complete my understanding of this line?

**Comment by chhylp123** [comment]
0 is the start position of the read, which should always be 0. 495 should be the read name.

**Comment by sebschmi** [comment]
Ah thanks, makes sense.
