### ISSUE TITLE
Hi-C and genome scaffolding

### ISSUE THREAD

**Issue by StevenBai97** [chhylp123/hifiasm#97]
Hi, I used hifisam to assemble the genome and got a great result (N50: 5.4Mb, BUSCO: 98.6%). However, I have some confusion about the Hi-C scaffolding result after running 3d-dna and juicebox. As shown in the picture, chr10 has some fragments. I don't know the reason. Could you please give me some suggestions? Thanks for a lot.
![image](https://user-images.githubusercontent.com/80459240/114808465-e4ae6d80-9dda-11eb-96f0-9fdaef65fcef.png)
![image2](https://user-images.githubusercontent.com/80459240/114808678-4ff83f80-9ddb-11eb-9ec2-5330412946e1.png)

**Comment by lh3** [comment]
This question is about 3D-DNA? You should ask its developers.
