### ISSUE TITLE
Run - Aborted (core dumped)

### ISSUE THREAD

**Issue by sinha-shruti** [chhylp123/hifiasm#99]
Hi,

I am running HiFiasm on a 71Gb fastq file (human data) and ending with error below (copying the last few lines).
I ran it with default commands with -t 24. I am running it on a Linux cluster of 256GB RAM and CPU: 10C/20T Xeon gold (x2)

[M::ha_hist_line]  rest: ****************************************************************************************************> 44391
[M::ha_analyze_count] left: count[62] = 7936
[M::ha_analyze_count] right: none
[M::ha_ft_gen] peak_hom: 86; peak_het: 62
[M::ha_ft_gen::192.504*5.55@49.862GB] ==> filtered out 72042 k-mers occurring 430 or more times
[M::ha_opt_update_cov] updated max_n_chain to 430
hifiasm: sketch.cpp:51: void ha_sketch(const char*, int, int, int, uint32_t, int, ha_mz1_v*, const void*): Assertion `len > 0 && len < 1<<27 && rid < 1<<28 && (w > 0 && w < 256) && (k > 0 && k <= 63)' failed.

**Comment by lh3** [comment]
Check if your input has zero-length sequences.

**Comment by sinha-shruti** [comment]
Thanks for the help!
Looks like there was problem with file.
Successfully finished the run..
